---
permalink: a1k/install-hardware.html 
sidebar: sidebar 
keywords: aff a1k, install hardware, telco rack 
summary: Installez le système de stockage dans une armoire ou un rack de télécommunications. 
---
= Installer le matériel de fixation - AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir préparé l'installation du système de stockage AFF A1K, installez le matériel du système. Commencez par installer les kits de rails. Installez ensuite et fixez votre plate-forme dans une armoire ou un rack de télécommunications.

Ignorez cette étape si votre armoire est pré-remplie.

.Avant de commencer
* Assurez-vous de disposer des instructions fournies avec le kit de rails.
* Soyez conscient des problèmes de sécurité associés au poids du système de stockage et de l'étagère de stockage.
* Assurez-vous que le flux d'air qui traverse le système de stockage pénètre par l'avant où le cadre ou les embouts sont installés et sort par l'arrière où se trouvent les ports.


.Étapes
. Installez les kits de rails pour votre système de stockage et les étagères de stockage, selon les besoins, en suivant les instructions fournies avec les kits.
. Installez et sécurisez votre système de stockage dans l'armoire ou le rack de télécommunications :
+
.. Positionnez le système de stockage sur les rails au milieu de l'armoire ou du rack de télécommunications, puis soutenez le système de stockage par le bas et faites-le glisser pour le mettre en place.
.. Fixez le système de stockage à l'armoire ou au rack de télécommunications à l'aide des vis de montage fournies.


. Installez le tiroir de stockage :
+
.. Placez l'arrière de la tablette de stockage sur les rails, puis soutenez la tablette par le bas et faites-la glisser dans l'armoire ou le rack de télécommunications.
+
Si vous installez plusieurs tiroirs de stockage, placez le premier tiroir de stockage directement au-dessus des contrôleurs. Placez le second tiroir de stockage directement sous les contrôleurs. Répétez cette procédure pour toutes les étagères de stockage supplémentaires.

.. Fixez l'étagère de stockage à l'armoire ou au rack de télécommunications à l'aide des vis de montage fournies.


. Connectez les périphériques de gestion des câbles à l'arrière du système de stockage.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[Installez le périphérique de gestion des câbles]

. Fixez le panneau à l'avant du système de stockage.


.Et la suite ?
Après avoir installé le matériel de votre système AFF A1K, vous link:install-cable.html["Branchez les câbles du matériel du système de stockage AFF A1K"].
