---
permalink: a1k/maintain-overview.html 
sidebar: sidebar 
keywords: aff a1k maintenance, maintenance, repairing a1k, repairing aff a1k, replace aff a1k components, replace aff a1k components 
summary: Maintenance du matériel AFF A1K 
---
= Maintenance du matériel AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour le système de stockage AFF A1K, vous pouvez effectuer des procédures de maintenance sur les composants suivants.



== Support de démarrage

Le support de démarrage stocke un ensemble principal et secondaire de fichiers image ONTAP que le système utilise lors du démarrage.



== Contrôleur

Un contrôleur se compose d'une carte, d'un micrologiciel et d'un logiciel. Il contrôle les lecteurs et exécute le logiciel du système d'exploitation ONTAP.



== DIMM

Un module de mémoire en ligne double (DIMM) est un type de mémoire d'ordinateur. Ils sont installés pour ajouter de la mémoire système à une carte mère du contrôleur.



== Ventilateur

Un ventilateur refroidit le contrôleur.



== NVRAM

La mémoire NVRAM (mémoire vive non volatile) est un module qui permet au contrôleur de protéger et d'enregistrer les données à la volée en cas de coupure de courant du système. L'ID système réside dans le module NVRAM. Lorsqu'il est remplacé, le contrôleur utilise le nouvel ID système du module NVRAM de remplacement.



== Batterie NV

La batterie NVRAM est chargée d'alimenter le module NVRAM alors que les données à la volée sont déchargées vers la mémoire Flash après une coupure de courant.



== Module d'E/S.

Le module d'E/S (module d'entrée/sortie) est un composant matériel qui sert d'intermédiaire entre le contrôleur et divers dispositifs ou systèmes qui doivent échanger des données avec le contrôleur.



== Alimentation électrique

Une alimentation fournit une source d'alimentation redondante dans un contrôleur.



== Pile de l'horloge en temps réel

Une batterie d'horloge en temps réel conserve les informations relatives à la date et à l'heure du système si l'alimentation est coupée.



== Module de gestion du système

Le module de gestion du système fournit l'interface entre le contrôleur et une console ou un ordinateur portable à des fins de maintenance du contrôleur ou du système. Le module de gestion du système contient le support de démarrage et stocke le numéro de série du système (SSN).
