---
permalink: a70-key-specifications.html 
sidebar: sidebar 
keywords: AFF A70 specifications, AFF A70 specs, NetApp AFF A70, AFF A70 hardware 
summary: Spécifications clés du système de stockage AFF A70 
---
= Spécifications clés de AFF A70
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour l' AFF A70.  Visite https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) pour une liste complète des spécifications AFF A70 .  Cette page reflète une seule paire à haute disponibilité.



=== Spécifications clés de AFF A70

Configuration de la plateforme : paire de châssis simple HA AFF A70

Capacité brute maximale : 6,6096 Po

Mémoire : 256.0000 Go

Facteur de forme : châssis 4U avec 2 contrôleurs HA et 48 emplacements pour disques

Version ONTAP : b_startONTAP : 9.16.1P2b_end

Emplacements d'extension PCIe : 18

Version minimale ONTAP : ONTAP 9.15.1RC2



=== Maximums de mise à l'échelle

* NAS : 12 paires HA, capacité brute de 79,3 Po / 70,4 PiB, mémoire maximale de 3 072 Go
* SAN : 6 paires HA, capacité brute de 39,7 Po / 35,2 PiB, mémoire maximale de 1 536 Go
* Paire HA : capacité brute de 6,6 Po / 5,9 PiB, mémoire maximale de 256 0000 Go




=== IO



==== E/S embarquées

Aucune donnée IO embarquée.



==== E/S totales

* Ethernet 200 Gbit/s : 24 ports
* Ethernet 100 Gbit/s : 36 ports
* Ethernet 25 Gbit/s : 56 ports
* Ethernet 10 Gbit/s : 56 ports
* FC 64 Gbit/s : 56 ports
* NVMe/FC 64 Gbit/s : 56 ports
* SAS 12 Gbit/s : 56 ports




==== Ports de gestion

* Ethernet 1 Gbit/s : 2 ports
* RS-232 115 Kbps : 4 ports
* USB 600 Mbps : 2 ports




=== Réseau de stockage pris en charge

CIFS ; FC ; iSCSI ; NFS v3 ; NFS v4.0 ; NFS v4.1 ; NFS v4.2 ; NFSv3/RDMA ; NFSv4/RDMA ; NVMe/FC ; NVMe/TCP ; S3 ; S3 avec NAS ; SMB 2.0 ; SMB 2.1 ; SMB 2.x ; SMB 3.0 ; SMB 3.1 ; SMB 3.1.1 ;



=== Spécifications de l'environnement système

* Puissance typique : 6938 BTU/h
* Consommation d'énergie dans le pire des cas : 9 089 BTU/h
* Poids : 118,0 lb/53,5 kg
* Hauteur : 4U
* Largeur : 19 pouces conforme à la norme IEC (17,6 pouces 44,7 cm)
* Profondeur : 34,5 po (36,6 po avec support de gestion des câbles)
* Température/altitude/humidité de fonctionnement : 10 °C à 35 °C (50 °F à 95 °F) à une altitude de 3 048 m (10 000 pi) ; 8 % à 80 % (humidité relative, sans condensation)
* Température/humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu'à 12 192 m (40 000 pi)<br/>10 % à 95 % d'humidité relative, sans condensation, dans l'emballage d'origine
* Bruit acoustique : Puissance acoustique déclarée (LwAd) : 8,6 ; br/Pression acoustique (LpAm) (positions d'observation) : 71,6 dB




=== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




=== Haute disponibilité

Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP ; Contrôleurs redondants remplaçables à chaud ; Alimentations redondantes remplaçables à chaud ; Gestion SAS en bande via des connexions SAS pour étagères externes ;
