---
permalink: a70-90/bootmedia-encryption-preshutdown-checks.html 
sidebar: sidebar 
keywords: aff a70, aff a90, pre-shutdown checks for onboard encryption keys 
summary: 'Avant d"arrêter le contrôleur douteux et de vérifier le statut des clés de cryptage intégrées, vous devez vérifier le statut de ce contrôleur, désactiver le giveback automatique et vérifier quelle version de ONTAP le système fonctionne.' 
---
= Vérifiez les clés de chiffrement intégrées : AFF A70 et AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'arrêter le contrôleur douteux et de vérifier le statut des clés de cryptage intégrées, vous devez vérifier le statut de ce contrôleur, désactiver le giveback automatique et vérifier la version de ONTAP en cours d'exécution.

Si vous avez un cluster avec plus de deux nœuds, il doit être dans le quorum. Si le cluster n'est pas au quorum ou si un contrôleur en bonne santé affiche la valeur false pour l'éligibilité et la santé, vous devez corriger le problème avant de désactiver le contrôleur défaillant ; voir link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchroniser un nœud avec le cluster"^].



== Vérifiez NVE ou NSE sur les systèmes

Avant d'arrêter le contrôleur défaillant, vous devez vérifier que le gestionnaire de clés de sécurité est activé ou que les disques chiffrés sont bien activés sur le système.



== Vérifiez la configuration du gestionnaire de clés de sécurité

.Étapes
. Déterminez si le gestionnaire de clés est actif à l'aide de la commande _Security Key-Manager keystore show_. Pour plus d'informations, reportez-vous à la section https://docs.netapp.com/us-en/ontap-cli/security-key-manager-keystore-show.html["Page de MANUEL d'affichage du gestionnaire de clés de sécurité"^]
+

NOTE: Vous pouvez avoir d'autres types de gestionnaire de clés. Les types sont `KMIP`, , `AKV`et `GCP`. Le processus de confirmation de ces types est le même que celui de confirmation `external` ou de `onboard` gestionnaire de clés.

+
** Si aucune sortie n'est affichée, passer à link:bootmedia-shutdown.html["arrêtez le contrôleur défectueux"] pour arrêter le nœud défectueux.
** Si la commande affiche les valeurs de sortie, le système est `security key-manager` actif et vous devez afficher le type et l' `Key Manager` état.


. Afficher les informations pour active à l'aide de la `Key Manager` commande _Security Key-Manager key query_.
+
** Si le `Key Manager` type s'affiche `external` et que la `Restored` colonne affiche `true`, vous pouvez arrêter le contrôleur défectueux en toute sécurité.
** Si le `Key Manager` type s'affiche `onboard` et que la `Restored` colonne s'affiche `true`, vous devez effectuer quelques étapes supplémentaires.
** Si le `Key Manager` type s'affiche `external` et que la `Restored` colonne affiche autre chose que `true`, vous devez effectuer certaines étapes supplémentaires.
** Si le `Key Manager` type s'affiche `onboard` et que la `Restored` colonne affiche autre chose que `true`, vous devez effectuer certaines étapes supplémentaires.


. Si le `Key Manager` type s'affiche `onboard` et que la `Restored` colonne affiche `true`, sauvegardez manuellement les informations sur OKM :
+
.. Entrez `y` lorsque vous êtes invité à continuer : `set -priv advanced`
.. Entrez la commande pour afficher les informations de gestion des clés : _Security Key-Manager Onboard show-backup_
.. Copiez le contenu des informations de sauvegarde dans un fichier distinct ou dans votre fichier journal. Dans les scénarios d'incident, vous devrez peut-être restaurer manuellement le gestionnaire de clés intégré OKM.
.. Vous pouvez arrêter le contrôleur défectueux en toute sécurité.


. Si le `Key Manager` type s'affiche `onboard` et que la `Restored` colonne affiche autre chose que `true`:
+
.. Entrez la commande de synchronisation du gestionnaire de clés de sécurité intégré : _Security Key-Manager Onboard sync_
+

NOTE: Saisissez la phrase de passe alphanumérique de gestion des clés intégrée de 32 caractères à l'invite. Si la phrase de passe ne peut pas être fournie, contactez le support NetApp. http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. Vérifiez que la `Restored` colonne s'affiche `true` pour toutes les clés d'authentification : `security key-manager key query`
.. Vérifiez que le `Key Manager` type s'affiche `onboard`, puis sauvegardez manuellement les informations sur OKM.
.. Entrez la commande pour afficher les informations de sauvegarde de la gestion des clés : _Security Key-Manager Onboard show-backup_
.. Copiez le contenu des informations de sauvegarde dans un fichier distinct ou dans votre fichier journal. Dans les scénarios d'incident, vous devrez peut-être restaurer manuellement le gestionnaire de clés intégré OKM.
.. Vous pouvez arrêter le contrôleur en toute sécurité.


. Si le `Key Manager` type s'affiche `external` et que la `Restored` colonne affiche autre chose que `true`:
+
.. Restaurer les clés d'authentification externe de gestion des clés sur tous les nœuds du cluster : `security key-manager external restore`
+
Si la commande échoue, contactez le support NetApp à l'adresse http://mysupport.netapp.com/["mysupport.netapp.com"^].

.. Vérifiez que la `Restored` colonne s'affiche `true` pour toutes les clés d'authentification : _Security Key-Manager key query_
.. Vous pouvez arrêter le contrôleur défectueux en toute sécurité.



