---
permalink: a70-90/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the boot media 
summary: Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur. 
---
= Présentation du remplacement du support de démarrage - AFF A70, AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le support de démarrage stocke un ensemble principal et secondaire de fichiers système (image de démarrage) que le système utilise lors du démarrage. Selon votre configuration réseau, vous pouvez effectuer un remplacement sans interruption ou sans interruption.

Vous devez disposer d'une clé USB, formatée en FAT32, avec la quantité de stockage appropriée pour maintenir le `image_xxx.tgz`.

Vous devez également copier le `image_xxx.tgz` Fichier sur le lecteur flash USB pour une utilisation ultérieure dans cette procédure.

* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.
* Il est important d'appliquer les commandes au cours de la procédure suivante sur le contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le contrôleur _Healthy_ est le partenaire HA du contrôleur déficient.



