---
permalink: a70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the boot media 
summary: Veuillez consulter les exigences avant de remplacer le support de démarrage de votre système de stockage AFF A70 ou AFF A90 . 
---
= Conditions requises pour la récupération automatique du support de démarrage - AFF A70 et AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Examinez les exigences avant de remplacer le support de démarrage de votre système de stockage AFF A70 ou AFF A90 , notamment la fonctionnalité du port de cluster, la configuration du gestionnaire de clés et la compatibilité de la version ONTAP .

Le processus de récupération automatisée du support de démarrage nécessite ONTAP 9.17.1 ou une version ultérieure.  Si votre système de stockage exécute une version antérieure d' ONTAP, utilisez lelink:bootmedia-replace-workflow.html["procédure de récupération de démarrage manuel"] .

Passez en revue les exigences suivantes.

* Vous devez remplacer le support de démarrage défectueux par un support de démarrage de remplacement que vous avez reçu de NetApp.
* Les ports du cluster permettent la communication entre les deux contrôleurs lors du processus de récupération automatique au démarrage. Assurez-vous que les ports du cluster du contrôleur défaillant fonctionnent correctement.
* Pour OKM, vous avez besoin de la phrase secrète à l'échelle du cluster ainsi que des données de sauvegarde.
* Pour EKM, vous avez besoin de copies des fichiers suivants à partir du nœud partenaire :
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/client.key
** /cfcard/kmip/certs/CA.pem


* Comprendre la terminologie du contrôleur utilisée dans cette procédure :
+
** Le _contrôleur défaillant_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le _contrôleur sain_ est le partenaire HA du contrôleur altéré.




.Et la suite
Après avoir examiné la configuration requise pour le support de démarrage, vous link:bootmedia-shutdown-bmr.html["arrêter le contrôleur"].
