---
permalink: a70-90/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff a70, a90, replace the boot media 
summary: 'Avant de remplacer le support de démarrage de votre système AFF A70 ou AFF A90, assurez-vous de répondre aux exigences requises pour un remplacement réussi. Cela inclut la vérification que vous disposez du périphérique d"amorçage de remplacement approprié, l"accès au micrologiciel du système et au logiciel ONTAP, ainsi qu"une sauvegarde des données de configuration essentielles.' 
---
= Configuration requise pour remplacer le support de démarrage - AFF A70 et AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système AFF A70 ou AFF A90, assurez-vous de répondre aux exigences requises pour un remplacement réussi. Cela inclut la vérification que vous disposez du périphérique d'amorçage de remplacement approprié, l'accès au micrologiciel du système et au logiciel ONTAP, ainsi qu'une sauvegarde des données de configuration essentielles.

Passez en revue les exigences suivantes.

* Vous devez disposer d'une clé USB, formatée en FAT32, avec la quantité de stockage appropriée pour maintenir le `image_xxx.tgz` fichier.
* Vous devez copier le `image_xxx.tgz` fichier sur la clé USB pour pouvoir l'utiliser ultérieurement dans cette procédure.
* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.
* Il est important d'appliquer les commandes au cours de la procédure suivante sur le contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le contrôleur _Healthy_ est le partenaire HA du contrôleur déficient.




.Et la suite ?
Après avoir examiné la configuration requise pour remplacer le support de démarrage, vous devez link:bootmedia-encryption-preshutdown-checks.html["vérifiez la prise en charge et l'état de la clé de cryptage sur le support de démarrage"].
