---
permalink: a70-90/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: aff a70, aff a90, how to recable the system, teboot the system 
summary: Vous devez pouvoir réamorcer le contrôleur avec le stockage. 
---
= Recâblage et retour du contrôleur - AFF A70, AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Recouvrez les connexions réseau et de stockage, puis remettez le contrôleur en place.



== Étape 1 : recâblage du système

Recâblage des connexions réseau et de stockage du module de contrôleur.

.Étapes
. Recâblage du module de contrôleur vers les connexions de stockage et de réseau.
. Vérifiez que le câblage est correct à l'aide de https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].
+
.. Téléchargez et installez Config Advisor.
.. Entrez les informations du système cible, puis cliquez sur collecter les données.
.. Cliquez sur l'onglet câblage, puis examinez la sortie. Vérifiez que tous les tiroirs disques sont affichés et que tous les disques apparaissent dans le résultat, en corrigeant les problèmes de câblage que vous rencontrez.
.. Pour vérifier les autres câbles, cliquez sur l'onglet approprié, puis examinez les résultats de Config Advisor.






== Étape 2 : remettez le contrôleur en place

. Si le chiffrement est configuré sur votre système de stockage, vous devez restaurer la fonctionnalité de chiffrement de volume ou de stockage en procédant comme suit pour redémarrer le système :
+
.. Démarrez le menu et exécutez l'option 10
.. Saisissez la phrase de passe et sauvegardez les données, puis effectuez un démarrage normal. Voir https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Restore_onboard_key_management_encryption_keys["Restaurez les clés de chiffrement intégrées de gestion des clés"].
.. Effectuer un rétablissement CFO uniquement
.. Effectuez la synchronisation intégrée et vérifiez que le SVM-KEK est défini sur « true », voir https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Onboard_keymanager_sync_fails_after_motherboard_replacement["Échec de la remise en service après le remplacement du module MB - l'opération a été mise en veto par keymanager"]
.. SFO Giveback, (aucune force)


. Si le chiffrement n'est pas configuré sur votre système, procédez comme suit pour redémarrer le système :
+
.. Démarrez le menu et exécutez l'option 1.
.. Remettre le contrôleur :
.. Depuis le contrôleur sain, remettre le stockage du contrôleur remplacé : `storage failover giveback -ofnode _replacement_node_name_`
+
Le contrôleur _remplacement_ reprend son stockage et termine son démarrage.

+

NOTE: Si le retour est vetoté, vous pouvez envisager d'ignorer les vetoes.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Recherchez le contenu Configuration haute disponibilité de votre version de ONTAP 9"]

.. Une fois le retour arrière terminé, vérifiez que la paire HA est saine et que le basculement est possible : `storage failover show`


. Si le système se trouve dans une configuration MetroCluster, surveillez l'état du contrôleur : `metrocluster node show`
+
La configuration MetroCluster prend quelques minutes après le remplacement pour revenir à un état normal. À ce moment, chaque contrôleur affiche un état configuré, avec la mise en miroir reprise sur incident activée et un mode de fonctionnement normal. Le `metrocluster node show -fields node-systemid` Le résultat de la commande affiche l'ancien ID système jusqu'à ce que la configuration MetroCluster revienne à un état normal.

. Si le contrôleur est dans une configuration MetroCluster, en fonction de l'état de la MetroCluster, vérifiez que le champ ID de domicile de la reprise après incident affiche le propriétaire d'origine du disque si le propriétaire d'origine est un contrôleur sur le site de secours.
+
Ceci est requis si les deux conditions suivantes sont vraies :

+
** La configuration MetroCluster est en état de basculement.
** Le contrôleur _remplacement_ est le propriétaire actuel des disques sur le site de secours.
+
https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["Modification de la propriété des disques lors du basculement haute disponibilité et du basculement du MetroCluster dans une configuration MetroCluster à quatre nœuds"]



. Si votre système se trouve dans une configuration MetroCluster, vérifiez que chaque contrôleur est configuré : `metrocluster node show - fields configuration-state`
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Vérifier que les volumes attendus sont présents pour chaque contrôleur : `vol show -node node-name`
. Si vous avez désactivé le basculement automatique au redémarrage, activez-le à partir du contrôleur sain : `storage failover modify -node replacement-node-name -onreboot true`

