---
permalink: a70-90/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff a70, aff a90, prerequisite, replace the controller module 
summary: 'Avant de remplacer le contrôleur de votre système AFF A70 ou AFF A90, assurez-vous de répondre aux exigences requises pour un remplacement réussi. Cela inclut la vérification du bon fonctionnement de tous les autres composants du système, la vérification du bon contrôleur de remplacement et l"enregistrement de la sortie de la console du contrôleur dans un fichier journal texte.' 
---
= Conditions requises pour remplacer le contrôleur - AFF A70 et AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le contrôleur de votre système AFF A70 ou AFF A90, assurez-vous de répondre aux exigences requises pour un remplacement réussi. Cela inclut la vérification du bon fonctionnement de tous les autres composants du système, la vérification du bon contrôleur de remplacement et l'enregistrement de la sortie de la console du contrôleur dans un fichier journal texte.

Passez en revue la configuration requise pour le remplacement du module de contrôleur.

* Tous les tiroirs disques doivent fonctionner correctement.
* Le contrôleur sain doit pouvoir prendre le relais du contrôleur remplacé (appelé dans cette procédure contrôleur défectueux).
* N’utilisez pas cette procédure pour les mises à niveau de contrôleur.  Se référer à https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Choisissez la procédure de mise à niveau matérielle de votre contrôleur"] pour vous guider.
* Si votre système est configuré en MetroCluster , veuillez consulter https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Choix de la procédure de récupération correcte"] pour déterminer s'il convient d'utiliser cette procédure.
* Remplacez le composant défectueux par l'unité remplaçable sur site (FRU) que vous avez reçue de NetApp.
* Remplacez le module de commande par un module de commande du même type.  Vous ne pouvez pas mettre à niveau votre système en remplaçant le module de contrôle.
* Vous ne pouvez pas changer de disques durs ni de baies de disques durs dans le cadre de cette procédure.
* Le périphérique de démarrage se trouve sur le module de gestion du système installé à l'arrière du système.  Il n'est pas nécessaire de déplacer le périphérique de démarrage lors du remplacement d'un module de contrôleur.
* Comprendre la terminologie du contrôleur utilisée dans cette procédure :
+
** Le contrôleur _défaillant_ est le contrôleur en cours de remplacement.
** Le contrôleur de remplacement est le nouveau contrôleur qui remplace le contrôleur défectueux.
** Le contrôleur _Healthy_ est le contrôleur survivant.


* Capturez les données de la console du contrôleur dans un fichier journal texte.
+
Ce document consigne la procédure de dépannage en cas de problème survenu lors du processus de remplacement.



.Et la suite ?
Après avoir pris connaissance des exigences relatives au remplacement de votre contrôleur AFF A70 ou AFF A90 , vous devez :link:controller-replace-shutdown.html["arrêtez le contrôleur défectueux"] .
