---
permalink: a70-90/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: aff a70, aff a90, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Vérifiez que les interfaces logiques dépendent de leur port de home, effectuez une vérification de l"état du cluster, puis renvoyez la pièce défectueuse à NetApp pour terminer l"étape finale de la procédure de remplacement du contrôleur AFF A70 and AFF A90.' 
---
= Remplacement complet du contrôleur - AFF A70 et AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour terminer le remplacement du contrôleur de votre système AFF A70 ou AFF A90, restaurez d'abord la configuration du chiffrement du stockage NetApp (si nécessaire). Ensuite, vérifiez que les interfaces logiques (LIF) signalent leurs ports de repos et effectuez une vérification de l'état du cluster. Enfin, retournez la pièce défectueuse à NetApp.



== Étape 1 : vérifier la LIF et la santé du cluster

Avant de renvoyer le nœud de remplacement à la maintenance, vérifiez que les interfaces logiques se trouvent sur leurs ports home, vérifiez l'état du cluster et réinitialisez le rétablissement automatique.

.Étapes
. Vérifiez que les interfaces logiques communiquent avec leur serveur d'origine et leurs ports :
+
`network interface show -is-home false`

+
Si des interfaces logiques sont indiquées comme étant fausses, rétablissez-les à leurs ports d'origine :

+
`network interface revert -vserver * -lif *`

. Vérifiez l'état de santé de votre cluster.  Voir le https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Procédure de vérification de l'état du cluster à l'aide d'un script dans ONTAP"^] Article de la base de connaissances.
. Si le retour automatique a été désactivé, réactivez-le :
+
`storage failover modify -node local -auto-giveback true`





== Étape 2 : renvoyer la pièce défectueuse à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièces et remplacements"] page pour plus d'informations.
