---
permalink: a70-90/install-hardware.html 
sidebar: sidebar 
keywords: aff a70, a90, install hardware, telco rack 
summary: Installez le système de stockage dans une armoire ou un rack de télécommunications. 
---
= Installer le matériel de fixation - AFF A70, AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les instructions suivantes décrivent l'installation du matériel dans une armoire vide ou un rack de télécommunications. Ignorez cette étape si votre armoire est pré-remplie.

.Avant de commencer
* Vous devez lire ce https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Avis de sécurité"] document et comprendre les précautions à prendre pour déplacer et installer le matériel.
* Vous devez avoir les instructions fournies avec le kit de rails.
* Vous devez être conscient des problèmes de sécurité associés au poids de la plate-forme et de l'étagère.


.Étapes
. Installez les kits de rails pour la plate-forme et les étagères, si nécessaire, en suivant les instructions fournies avec les kits.
. Installez et fixez votre plate-forme dans l'armoire ou le rack de télécommunications :
+
.. Positionner la plate-forme sur les rails au milieu de l'armoire ou du rack de télécommunications, puis soutenir la plate-forme par le bas et la faire glisser en place.
.. Fixez la plate-forme à l'armoire ou au rack de télécommunications à l'aide des vis de montage fournies.


. Installez le ou les tiroirs :
+
.. Placez l'arrière de la tablette sur les rails, puis soutenez la tablette par le bas et faites-la glisser dans l'armoire ou le rack de télécommunications.
+
Si vous installez plusieurs tiroirs, placez le premier tiroir directement au-dessus des contrôleurs. Placez le second shelf directement sous les contrôleurs. Répétez cette procédure pour tous les tiroirs disques supplémentaires.

.. Fixez l'étagère à l'armoire ou au rack de télécommunications à l'aide des vis de montage fournies.


. Reliez les deux périphériques de gestion des câbles à l'arrière des contrôleurs.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[Installez le périphérique de gestion des câbles]

. Fixez le panneau à l'avant de la plate-forme.

