---
sidebar: sidebar 
permalink: a70-90/install-requirements.html 
keywords: a1a70-90k, install, setup, cautions 
summary: 'Passez en revue l"équipement nécessaire et les précautions de levage pour votre plate-forme et vos étagères.' 
---
= Conditions requises pour l'installation - AFF A70 et AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vérifiez l'équipement nécessaire et les précautions de levage pour votre système de stockage AFF A70 ou AFF A90 et vos tiroirs de stockage.



== Équipement nécessaire pour l'installation

Pour installer votre système de stockage AFF A70 ou AFF A90, vous avez besoin des équipements et outils suivants.

* Accès à un navigateur Web pour configurer votre système de stockage
* Sangle de décharge électrostatique (ESD)
* Lampe de poche
* Ordinateur portable ou console avec connexion USB/série
* Trombone ou stylo à pointe sphérique à pointe étroite pour le réglage des ID de tablette de stockage NS224
* Tournevis Phillips n°2




== Précautions de levage

Les systèmes de stockage AFF A70 et AFF A90, ainsi que les tiroirs de stockage NS224 sont très lourds. Faites preuve de prudence lorsque vous soulevez et déplacez ces éléments.



=== Systèmes de stockage AFF A70 et AFF A90

Un système de stockage AFF A70 ou un système de stockage AFF A90 peut peser jusqu'à 68.8 kg (151.68 lb). Pour lever le système, faire appel à quatre personnes ou à un relevage hydraulique.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90]



=== Tiroir NS224

Une étagère de stockage NS224 peut peser jusqu'à 30.29 kg (66.78 lb). Pour soulever la tablette de rangement, faites appel à deux personnes ou à un dispositif de levage hydraulique. Conservez tous les composants dans la tablette de stockage (avant et arrière) pour éviter de débalourer le poids de la tablette.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[Avertissement de levage NS224]

.Informations associées
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informations de sécurité et avis réglementaires"^]


.Et la suite ?
Après avoir examiné la configuration matérielle requise, vous link:install-prepare.html["Préparez l'installation de votre système de stockage AFF A70 ou AFF A90"].
