---
permalink: a70-90/io-module-overview.html 
sidebar: sidebar 
keywords: AFF A90, AFF A70, replace io module 
summary: 'Vous pouvez remplacer un module d"E/S défaillant de votre système de stockage AFF A70 ou AFF A90 par un module d"E/S du même type ou par un autre type de module d"E/S. Vous pouvez également ajouter un module d"E/S dans un système doté de logements vides.' 
---
= Présentation de l'ajout et du remplacement d'un module d'E/S - AFF A70 et AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes AFF A70 et AFF A90 permettent d'étendre ou de remplacer des modules d'E/S de manière flexible afin d'améliorer la connectivité et les performances du réseau. L'ajout ou le remplacement d'un module d'E/S est essentiel lors de la mise à niveau des capacités réseau ou de l'adressage d'un module défaillant.

Vous pouvez remplacer un module d'E/S défaillant de votre système de stockage AFF A70 ou AFF A90 par un module d'E/S du même type ou par un autre type de module d'E/S. Vous pouvez également ajouter un module d'E/S dans un système doté de logements vides.

* link:io-module-add.html["Ajoutez un module d'E/S."]
+
L'ajout de modules supplémentaires peut améliorer la redondance, ce qui permet de garantir que le système reste opérationnel même en cas de défaillance d'un module.

* link:io-module-hotswap.html["Remplacer à chaud un module d'E/S"]
+
Vous pouvez remplacer à chaud certains modules d'E/S par un module d'E/S équivalent afin de rétablir le système de stockage à son état de fonctionnement optimal. Le remplacement à chaud s'effectue sans avoir à effectuer une reprise manuelle.



Pour utiliser cette procédure, votre système de stockage doit exécuter ONTAP 9.18.1 ou une version ultérieure.

* link:io-module-replace.html["Remplacez un module d'E/S."]
+
Le remplacement d'un module d'E/S défaillant permet de restaurer l'état de fonctionnement optimal du système.



.Numérotation des connecteurs d'E/S.
Les connecteurs d'E/S des contrôleurs AFF A70 et AFF A90 sont numérotés de 1 à 11, comme illustré ci-dessous.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numérotation des connecteurs sur les contrôleurs AFF A70 et AFF A90]
