---
permalink: a70-90/io-module-overview.html 
sidebar: sidebar 
keywords: AFF A90, AFF A70, replace io module 
summary: 'Vous pouvez remplacer un module d"E/S défaillant de votre système de stockage AFF A70 ou AFF A90 par un module d"E/S du même type ou par un autre type de module d"E/S. Vous pouvez également ajouter un module d"E/S dans un système doté de logements vides.' 
---
= Présentation de l'ajout et du remplacement du module d'E/S - AFF A70 et AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes AFF A70 et AFF A90 permettent d'étendre ou de remplacer des modules d'E/S de manière flexible afin d'améliorer la connectivité et les performances du réseau. L'ajout ou le remplacement d'un module d'E/S est essentiel lors de la mise à niveau des capacités réseau ou de l'adressage d'un module défaillant.

Vous pouvez remplacer un module d'E/S défaillant de votre système de stockage AFF A70 ou AFF A90 par un module d'E/S du même type ou par un autre type de module d'E/S. Vous pouvez également ajouter un module d'E/S dans un système doté de logements vides.

* link:io-module-add.html["Ajoutez un module d'E/S."]
+
L'ajout de modules supplémentaires peut améliorer la redondance, ce qui permet de garantir que le système reste opérationnel même en cas de défaillance d'un module.

* link:io-module-replace.html["Remplacez un module d'E/S."]
+
Le remplacement d'un module d'E/S défaillant permet de restaurer l'état de fonctionnement optimal du système.


