---
permalink: afx-2k/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: afx 2k, shut down the controller 
summary: Éteignez le contrôleur défectueux de votre système de stockage afx 2k pour éviter toute perte de données et garantir la stabilité du système lors du remplacement du support de démarrage. 
---
= Éteignez le contrôleur pour remplacer le support de démarrage - AFX 2K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Éteignez le contrôleur défectueux de votre système de stockage AFX 2K pour éviter toute perte de données et garantir la stabilité du système lors du remplacement du support de démarrage.

Prenez le contrôle et arrêtez le contrôleur défaillant afin que le contrôleur fonctionnel continue de fournir les données provenant du stockage du contrôleur défaillant. Pour ce faire, vous supprimez la création automatique de cas dans AutoSupport, désactivez la restitution automatique et amenez le contrôleur défaillant à l'invite LOADER. L'invite LOADER correspond à l'état d'arrêt sécurisé à partir duquel vous pouvez remplacer la FRU.

.Description de la tâche
* Si vous avez un cluster avec plus de quatre nœuds, il doit être en quorum.  Pour afficher les informations de cluster sur vos nœuds, utilisez le `cluster show` commande.  Pour plus d'informations sur le `cluster show` commande, voirlink:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["Afficher les détails au niveau du nœud dans un cluster ONTAP"^] .
* Si le cluster n'est pas en quorum ou si l'état ou l'éligibilité d'un contrôleur (autre que le contrôleur altéré) s'affiche comme faux, vous devez corriger le problème avant d'arrêter le contrôleur altéré. Voir link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchroniser un nœud avec le cluster"^] .


.Étapes
. Si AutoSupport est activé, supprimez la création automatique de dossier en invoquant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
Le message AutoSupport suivant supprime la création automatique de dossiers pendant deux heures :

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Désactiver le retour automatique depuis la console du contrôleur défaillant :
+
`storage failover modify -node impaired-node -auto-giveback-of false`

+

NOTE: Lorsque vous voyez _Voulez-vous désactiver la restitution automatique ?_, entrez `y` .

. Faites passer le contrôleur douteux à l'invite DU CHARGEUR :
+
[cols="1,2"]
|===
| Si le contrôleur en état de fonctionnement s'affiche... | Alors... 


 a| 
Invite DU CHARGEUR
 a| 
Passez à l'étape suivante.



 a| 
Invite système ou invite de mot de passe
 a| 
Prendre le relais ou arrêter le contrôleur altéré à partir du contrôleur sain :
`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

Le paramètre _-halt true_ amène le nœud altéré à l'invite LOADER.

|===


.Et la suite ?
Après avoir arrêté le contrôleur,link:bootmedia-replace.html["changer le support de démarrage"] .
