---
permalink: afx-2k/controller-replace-requirements.html 
sidebar: sidebar 
keywords: afx 2k, prerequisite, replace the controller module 
summary: 'Avant de remplacer le contrôleur de votre système de stockage afx 2k, assurez-vous de respecter les conditions requises pour un remplacement réussi. Cela inclut de disposer du contrôleur de remplacement adéquat, d"une sauvegarde de la configuration de votre système et d"un accès aux outils et micrologiciels nécessaires.' 
---
= Exigences pour remplacer le contrôleur - AFX 2K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le contrôleur de votre système de stockage AFX 2K, assurez-vous de respecter les conditions requises pour un remplacement réussi. Cela inclut de vérifier que tous les autres composants du système fonctionnent correctement, de vous assurer que vous disposez du contrôleur de remplacement adéquat et d'enregistrer la sortie de la console du contrôleur dans un fichier journal texte.

Vérifiez les conditions requises pour le remplacement du contrôleur.

[NOTE]
====
NetApp recommande fortement d'activer la journalisation de la console sur les appareils que vous utilisez et de prendre les mesures suivantes lors de cette procédure :

* Laissez AutoSupport activé pendant votre maintenance. Cela permet au support NetApp de recevoir des informations de diagnostic en cas de problème.
* Activez la journalisation des sessions pour toutes les sessions CLI. Cela crée un enregistrement complet de toutes les commandes et des sorties système pendant l'opération de maintenance. Pour savoir comment activer la journalisation des sessions, consultez  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Comment configurer PuTTY pour une connectivité optimale aux systèmes ONTAP"^].


====
* Il est important d'appliquer les commandes au cours des étapes suivantes sur les systèmes appropriés :
+
** Le contrôleur _trouble_ est le contrôleur qui est en cours de remplacement.
** Le contrôleur _remplacement_ est le nouveau contrôleur qui remplace le contrôleur défaillant.
** Le contrôleur _Healthy_ est le contrôleur survivant.


* Tous les tiroirs disques doivent fonctionner correctement.
* Le contrôleur sain doit pouvoir reprendre le contrôleur qui est remplacé (appelé « contrôleur défectueux » dans cette procédure).
* Vous devez remplacer le composant défectueux par l'unité remplaçable sur site (FRU) que vous avez reçue de NetApp.
* Vous devez remplacer un module de contrôleur par un module de contrôleur du même type de modèle. Vous ne pouvez pas mettre à niveau votre système en remplaçant simplement le module de contrôleur.
* Vous ne pouvez pas modifier de disques ou de tiroirs disques dans le cadre de cette procédure.


.Et la suite ?
Après avoir examiné les exigences pour remplacer votre contrôleur AFX 2K,link:controller-replace-shutdown.html["éteindre les contrôleurs"].
