---
permalink: a900/chassis_replace_shutdown.html 
sidebar: sidebar 
keywords: aff a900, shutdown the controllers 
summary: Pour remplacer le châssis, vous devez arrêter les contrôleurs. 
---
= Arrêter le contrôleur douteux - AFF A900
:allow-uri-read: 


[role="lead"]
Vous devez arrêter le contrôleur ou le contrôleur du châssis avant de les déplacer vers le nouveau châssis.

.Description de la tâche
* Si un cluster possède plus de deux contrôleurs, il doit se trouver au quorum. Si le cluster n'est pas dans le quorum ou si un contrôleur sain s'affiche `false` pour l'admissibilité et la santé, vous devez corriger le problème avant d'arrêter le contrôleur déficient ; consultez le link:https://docs.netapp.com/us-en/ontap/system-admin/index.html["Présentation de l'administration avec l'interface de ligne de commande"^].
* Si AutoSupport est activé, supprimez la création automatique de dossier en invoquant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
Le message AutoSupport suivant supprime la création automatique de dossiers pendant deux heures : `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`



.Étapes
. Si votre système dispose de deux modules de contrôleur, désactivez la paire haute disponibilité.
+
[cols="1,2"]
|===
| Si votre système exécute clustered ONTAP avec... | Alors... 


 a| 
Deux contrôleurs dans le cluster
 a| 
`cluster ha modify -configured false` `storage failover modify -node node0 -enabled false`



 a| 
Plus de deux contrôleurs dans le cluster
 a| 
`storage failover modify -node node0 -enabled false`

|===
. Arrêter le contrôleur, en appuyant sur `y` lorsque vous êtes invité à confirmer l'arrêt : `system node halt -node _node_name_`
+
Le message de confirmation se présente comme suit :

+
[listing]
----
Warning: This operation will cause controller "node-name" to be marked as unhealthy. Unhealthy nodes do not participate in quorum voting. If the controller goes out of service and one more controller goes out of service there will be a data serving failure for the entire cluster. This will cause a client disruption. Use "cluster show" to verify cluster state. If possible bring other nodes online to improve the resiliency of this cluster.

Do you want to continue? {y|n}:
----
+

NOTE: Vous devez effectuer un arrêt correct du système avant de remplacer le châssis pour éviter de perdre des données non écrites dans la mémoire non volatile (NVMEM/NVRAM). Selon votre système, si le voyant NVMEM/NVRAM clignote, il y a du contenu dans la NVMEM/NVRAM qui n'a pas été enregistré sur le disque. Vous devez redémarrer le contrôleur et démarrer depuis le début de cette procédure. Si des tentatives répétées d'arrêt anormal du contrôleur tombent en panne, sachez que vous risquez de perdre des données qui n'ont pas été enregistrées sur le disque.

. Le cas échéant, arrêtez le second contrôleur pour éviter un message d'erreur de quorum dans une configuration de paire haute disponibilité : `system node halt -node _second_node_name_ -ignore-quorum-warnings true -skip-lif-migration-before-shutdown true`
+
Réponse `y` lorsque vous y êtes invité.


