---
permalink: a900/chassis_replace_overview.html 
sidebar: sidebar 
keywords:  
summary: 'Tous les autres composants du système doivent fonctionner correctement ; si ce n"est pas le cas, vous devez contacter le support technique.' 
---
= Remplacez le châssis - AFF A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


.Description de la tâche
[role="lead"]
Pour remplacer le châssis, vous devez retirer les blocs d'alimentation, les ventilateurs, les modules de contrôleur, les modules d'E/S, les modules DCPM, Et le module LED USB du châssis défaillant, retirez le châssis douteux du rack de l'équipement ou de l'armoire système, installez le châssis de remplacement à sa place, puis installez les composants dans le châssis de remplacement.

Tous les autres composants du système doivent fonctionner correctement ; si ce n'est pas le cas, vous devez contacter le support technique.

* Cette procédure peut être utilisée avec toutes les versions de ONTAP prises en charge par votre système.
* Cette procédure est perturbatrice. Dans le cas d'un cluster à deux nœuds, la panne totale du service et une panne partielle dans un cluster multinœud sont associés.

