---
permalink: a900/maintain-overview.html 
sidebar: sidebar 
keywords: aff A900 maintenance, maintenance, repairing aff A900, repairing aff A900, replace aff A900 components, replace aff A900 components 
summary: Entretenir le matériel AFF A900 
---
= Maintenance du matériel AFF A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Entretenez le matériel de votre système de stockage AFF A900 pour garantir une fiabilité à long terme et des performances optimales. Effectuez régulièrement des tâches de maintenance, comme le remplacement des composants défectueux, afin d'éviter les temps d'arrêt et les pertes de données.

Les procédures de maintenance supposent que le système de stockage AFF A900 a déjà été déployé en tant que nœud de stockage dans l'environnement ONTAP .



== Composants du système

Pour le système de stockage AFF A900, vous pouvez effectuer des procédures de maintenance sur les composants suivants.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Support de démarrage - récupération automatique"]
 a| 
Le support de démarrage stocke un ensemble principal et secondaire de fichiers image ONTAP que le système de stockage utilise pour démarrer. Lors de la récupération automatisée, le système de stockage récupère l'image de démarrage à partir du nœud partenaire et exécute automatiquement l'option de menu de démarrage appropriée pour installer l'image sur votre support de démarrage de remplacement. La récupération automatique du support de démarrage est prise en charge uniquement dans ONTAP 9.17.1 et versions ultérieures. Si votre système de stockage exécute une version antérieure d' ONTAP, utilisez l'option link:bootmedia-replace-workflow.html["procédure de récupération de démarrage manuel"] .



 a| 
link:bootmedia-replace-workflow.html["Support de démarrage - récupération manuelle"]
 a| 
Le support de démarrage stocke un ensemble principal et secondaire de fichiers image ONTAP que le système de stockage utilise pour démarrer. Lors de la récupération manuelle, vous démarrez le système de stockage à partir d'une clé USB et restaurez manuellement l'image et la configuration du système de fichiers.  Si votre système de stockage exécute ONTAP 9.17.1 et versions ultérieures, utilisez lelink:bootmedia-replace-workflow-bmr.html["procédure de récupération de démarrage automatisée"] .



 a| 
link:chassis_replace_overview.html["Châssis"]
 a| 
Le châssis correspond au boîtier physique qui contient tous les composants du contrôleur, tels que le contrôleur/l'unité centrale, l'alimentation et les E/S.



 a| 
link:controller_replace_overview.html["Contrôleur"]
 a| 
Un contrôleur se compose d'une carte, d'un micrologiciel et d'un logiciel. Il contrôle les entraînements et met en œuvre les fonctions ONTAP.



 a| 
link:dimm_replace.html["DIMM"]
 a| 
Vous devez remplacer un module DIMM (module de mémoire double en ligne) en cas de non-concordance de mémoire, ou si vous avez un module DIMM défectueux.



 a| 
link:dcpm-nvram11-battery-replace.html["DCPM"]
 a| 
Le DCPM (module d'alimentation du contrôleur de déchargement) contient la batterie NVRAM11.



 a| 
link:fan_swap_out.html["Ventilateur"]
 a| 
Le ventilateur refroidit le contrôleur.



 a| 
link:pci_cards_and_risers_replace.html["Module d'E/S."]
 a| 
Le module d'E/S (module d'entrée/sortie) est un composant matériel qui sert d'intermédiaire entre le contrôleur et divers dispositifs ou systèmes qui doivent échanger des données avec le contrôleur.



 a| 
link:led_module_replace.html["VOYANT USB"]
 a| 
Le module USB à LED fournit la connectivité aux ports de console et à l'état du système.



 a| 
link:nvram_module_or_nvram_dimm_replacement.html["NVRAM"]
 a| 
Le module NVRAM (mémoire vive non volatile) permet au contrôleur de conserver les données lors des cycles d'alimentation ou des redémarrages du système, tandis que le module NVRAM DIMM conserve les paramètres NVRAM .



 a| 
link:power_supply_swap_out.html["Alimentation électrique"]
 a| 
Une alimentation fournit une source d'alimentation redondante dans un contrôleur.



 a| 
link:rtc_battery_replace.html["Pile de l'horloge en temps réel"]
 a| 
Une batterie d'horloge en temps réel conserve les informations relatives à la date et à l'heure du système si l'alimentation est coupée.

|===