---
permalink: asa800/install-videos.html 
sidebar: sidebar 
keywords: asa a800, hardware installation and cabling video, perform end-to-end software configuration video 
summary: 'Deux vidéos sont disponibles. L"une montre comment installer et connecter le système, l"autre montrant un exemple d"utilisation de la configuration assistée par System Manager pour effectuer la configuration initiale du système.' 
---
= Vidéos - ASA A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Deux vidéos sont disponibles : l'une montrant comment installer et connecter le système, l'autre montrant un exemple d'utilisation de la configuration assistée par System Manager pour effectuer la configuration initiale du système.



== Vidéo l'une des deux : installation du matériel et câblage

La vidéo suivante montre comment installer et raccorder votre nouveau système.

.« Animation - installation et configuration d'un AFF A800
video::2a61ed74-a0ce-46c3-86d2-ab4b013c0030[panopto]

NOTE: La procédure d'installation du système ASA A800 est la même que celle du système AFF A800.



== Vidéo deux sur deux : effectuez une configuration logicielle de bout en bout

La vidéo suivante présente une configuration logicielle de bout en bout pour les systèmes exécutant ONTAP 9.2 et versions ultérieures.

video::WAE0afWhj1c?[youtube]