---
permalink: asa800/overview.html 
sidebar: sidebar 
keywords: ASA A800 specifications, ASA A800 specs, NetApp ASA A800, ASA A800 hardware 
summary: Spécifications clés du système de stockage ASA A800 
---
= Spécifications clés de ASA A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour l' ASA A800.  Visite https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) pour une liste complète des spécifications ASA A800 .  Cette page reflète une seule paire à haute disponibilité.



=== Spécifications clés de ASA A800

Configuration de la plateforme : paire HA à châssis unique ASA A800

Capacité brute maximale : 6,6096 Po

Mémoire : 1280.0000 Go

Facteur de forme : châssis 4U avec 2 contrôleurs HA et 48 emplacements pour disques

Version ONTAP : b_startONTAP : 9.16.1P2b_end

Emplacements d'extension PCIe : 10

Version minimale ONTAP : ONTAP 9.13.1



=== Maximums de mise à l'échelle

|===


| Type | Paires HA | Capacité brute | Mémoire maximale 


| NAS |  |  |  


| SAN | 6 | 39,7 Po / 35,2 PiB | 7680 Go 


| Paire haute disponibilité |  | 6,6 Po / 5,9 PiB | 1280,0000 
|===


=== IO



==== E/S embarquées

|===


| Protocole | Ports 


| Ethernet 100 Gbit/s | 4 
|===


==== E/S totales

|===


| Protocole | Ports 


| Ethernet 100 Gbit/s | 20 


| Ethernet 25 Gbit/s | 16 


| Ethernet 10 Gbit/s | 32 


| FC 32 Gbit/s | 32 


| NVMe/FC 32 Gbit/s | 32 


|  | 0 


|  | 0 


| SAS 12 Gbit/s | 32 
|===


==== Ports de gestion

|===


| Protocole | Ports 


| Ethernet 1 Gbit/s | 4 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== Réseau de stockage pris en charge

FC ; iSCSI ; NVMe/FC ; NVMe/TCP ;



=== Spécifications de l'environnement système

Aucune donnée environnementale disponible.



=== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




=== Haute disponibilité

Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP ; Contrôleurs redondants remplaçables à chaud ; Alimentations redondantes remplaçables à chaud ; Gestion SAS en bande via des connexions SAS pour étagères externes ;
