---
permalink: a200/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: aff a200, shut down the controller 
summary: Une fois les tâches NVE ou NSE terminées, vous devez arrêter le contrôleur pour cause de dysfonctionnement. 
---
= Arrêter le contrôleur défaillant - AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois les tâches NVE ou NSE terminées, vous devez arrêter le contrôleur pour cause de dysfonctionnement.

.Étapes
. Faites passer le contrôleur douteux à l'invite DU CHARGEUR :
+
[cols="1,2"]
|===
| Si le contrôleur en état de fonctionnement s'affiche... | Alors... 


 a| 
Invite DU CHARGEUR
 a| 
Passez à la section retrait du module de contrôleur.



 a| 
`Waiting for giveback...`
 a| 
Appuyez sur Ctrl-C, puis répondez `y` lorsque vous y êtes invité.



 a| 
Invite système ou invite de mot de passe (entrer le mot de passe système)
 a| 
Prendre le contrôle défectueux ou l'arrêter à partir du contrôleur en bon état : `storage failover takeover -ofnode impaired_node_name`

Lorsque le contrôleur douteux s'affiche en attente de rétablissement..., appuyez sur Ctrl-C et répondez `y`.

|===
. Dans l'invite DU CHARGEUR, entrez : `printenv` pour capturer toutes les variables environnementales de démarrage. Enregistrez le résultat dans votre fichier journal.
+

NOTE: Cette commande peut ne pas fonctionner si le périphérique d'amorçage est corrompu ou non fonctionnel.


