---
permalink: a200/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a200, nondisruptive, disruptive, replace the boot media, manual, manual boot recovery 
summary: 'Le support de démarrage stocke un ensemble principal et secondaire de fichiers système \(image de démarrage\) que le système utilise lors de son démarrage. Selon votre configuration réseau, vous pouvez effectuer un remplacement sans interruption ou sans interruption.' 
---
= Présentation du remplacement du support de démarrage : AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le support de démarrage stocke un ensemble principal et un ensemble secondaire de fichiers système (image de démarrage) que le système utilise lors de son démarrage. Selon la configuration de votre réseau, vous pouvez effectuer un remplacement non perturbateur ou perturbateur. Le système AFF A200 ne prend en charge que les procédures de récupération manuelles du support de démarrage. La récupération automatique du support de démarrage n'est pas prise en charge.

.Ce dont vous avez besoin
Vous devez disposer d'une clé USB, formatée en FAT32, avec la quantité de stockage appropriée pour maintenir le `image_xxx.tgz` fichier.

.Avant de commencer
* Les méthodes de remplacement d'un support de démarrage sans interruption et entraînant des perturbations nécessitent toutes deux la restauration du système de fichiers var :
+
** Pour un remplacement sans interruption, la paire HA doit être connectée à un réseau afin de restaurer le système de fichiers var.
** Pour le remplacement perturbateur, vous n'avez pas besoin d'une connexion réseau pour restaurer le système de fichiers var, mais le processus nécessite deux redémarrages.


* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.
* Il est important d'appliquer les commandes au cours de la procédure suivante sur le contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le contrôleur _Healthy_ est le partenaire HA du contrôleur déficient.



