---
permalink: a200/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a200, replace the chassis 
summary: Vous remplacez un châssis endommagé le nouveau châssis du même modèle que le châssis endommagé. 
---
= Présentation du remplacement de châssis : AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour remplacer le châssis, déplacez les blocs d'alimentation, les disques durs et les modules de contrôleur du châssis endommagé vers le nouveau châssis, puis remplacez le châssis endommagé par le rack d'équipement ou l'armoire système par le nouveau châssis du même modèle que le châssis endommagé.

Tous les autres composants du système doivent fonctionner correctement ; si ce n'est pas le cas, contactez le support technique.

.Description de la tâche
* Cette procédure peut être utilisée avec toutes les versions de ONTAP prises en charge par votre système.
* Cette procédure est rédigée en supposant que vous déplacez tous les disques et modules de contrôleur vers le nouveau châssis, et que le châssis est un nouveau composant de NetApp.
* Cette procédure est perturbatrice. Dans le cas d'un cluster à deux nœuds, la panne totale du service et une panne partielle dans un cluster multinœud sont associés.

