---
permalink: a200/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: aff a200, how to recable the system, how to reassign disks 
summary: Vous devez recomm le stockage et confirmer la réaffectation des disques. 
---
= Recâblage du système et réaffectation de disques - AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Poursuivre la procédure de remplacement en recâblage du stockage et en confirmant la réaffectation des disques.



== Étape 1 : recâbler le système

Après l'exécution des diagnostics, vous devez recâter les connexions réseau et stockage du module de contrôleur.

.Étapes
. Recâblage du système.
. Vérifiez que le câblage est correct à l'aide de https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].
+
.. Téléchargez et installez Config Advisor.
.. Entrez les informations du système cible, puis cliquez sur collecter les données.
.. Cliquez sur l'onglet câblage, puis examinez la sortie. Vérifiez que tous les tiroirs disques sont affichés et que tous les disques apparaissent dans le résultat, en corrigeant les problèmes de câblage que vous rencontrez.
.. Pour vérifier les autres câbles, cliquez sur l'onglet approprié, puis examinez les résultats de Config Advisor.






== Étape 2 : réaffectation de disques

Si le système de stockage est dans une paire HA, l'ID système du nouveau module de contrôleur est automatiquement attribué aux disques lors du rétablissement après la procédure. Dans un système autonome, vous devez réattribuer manuellement l'ID aux disques. Vous devez suivre la procédure correcte pour votre configuration.



=== Option 1 : vérifiez la modification de l'ID système sur un système HA

Vous devez confirmer la modification de l'ID système au démarrage du contrôleur _replace_, puis vérifier que la modification a été implémentée.

Cette procédure s'applique uniquement aux systèmes qui exécutent ONTAP dans une paire HA.

.Étapes
. Si le _remplacement_ contrôleur est en mode Maintenance (affiche le `*>` Invite, quittez le mode maintenance et accédez à l'invite DU CHARGEUR : `halt`
. À partir de l'invite DU CHARGEUR sur le contrôleur _replace_, démarrez le contrôleur, puis entrez `y` Si vous êtes invité à remplacer l'ID système en raison d'une discordance d'ID système.``boot_ontap``
. Attendre jusqu'à `Waiting for giveback...` Le message s'affiche sur la console du contrôleur _replace_, puis, à partir du contrôleur sain, vérifiez que le nouvel ID système partenaire a été automatiquement attribué : `storage failover show`
+
Dans le résultat de la commande, un message indiquant l'ID système modifié sur le contrôleur associé est affiché, indiquant l'ancien et le nouveau ID corrects. Dans l'exemple suivant, le node2 a fait l'objet d'un remplacement et a un nouvel ID système de 151759706.

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. Depuis le contrôleur sain, vérifier que les « coredumps » sont enregistrés :
+
.. Changement au niveau de privilège avancé : `set -privilege advanced`
+
Vous pouvez répondre `Y` lorsque vous êtes invité à passer en mode avancé. L'invite du mode avancé s'affiche (*>).

.. Enregistrez les « coredumps » : `system node run -node _local-node-name_ partner savecore`
.. Attendez que la commande `savecore'se termine avant d'émettre le retour.
+
Vous pouvez saisir la commande suivante pour surveiller la progression de la commande savecore : `system node run -node _local-node-name_ partner savecore -s`

.. Retour au niveau de privilège admin : `set -privilege admin`


. Si le chiffrement du volume ou du stockage est configuré sur votre système de stockage, vous devez restaurer la fonctionnalité de chiffrement du stockage ou du volume en suivant l'une des procédures suivantes, selon que vous utilisez la gestion des clés intégrée ou externe :
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["Restaurez les clés de chiffrement intégrées de gestion des clés"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["Restaurez les clés de chiffrement externes pour la gestion des clés"^]


. Remettre le contrôleur :
+
.. Depuis le contrôleur sain, remettre le stockage du contrôleur remplacé : `storage failover giveback -ofnode _replacement_node_name_`
+
Le contrôleur _remplacement_ reprend son stockage et termine son démarrage.

+
Si vous êtes invité à remplacer l'ID système en raison d'une discordance d'ID système, vous devez entrer `y`.

+

NOTE: Si le retour est vetoté, vous pouvez envisager d'ignorer les vetoes.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Recherchez le contenu Configuration haute disponibilité de votre version de ONTAP 9"]

.. Une fois le retour arrière terminé, vérifiez que la paire HA est saine et que le basculement est possible : `storage failover show`
+
La sortie du `storage failover show` La commande ne doit pas inclure l'ID système modifié dans le message partenaire.



. Vérifier que les disques ont été correctement affectés : `storage disk show -ownership`
+
Les disques appartenant au _replace_ Controller doivent afficher le nouvel ID système. Dans l'exemple suivant, les disques appartenant au nœud1 affichent alors le nouvel ID système, 1873775277 :

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----
. Vérifier que les volumes attendus sont présents pour chaque contrôleur : `vol show -node node-name`
. Si vous avez désactivé le basculement automatique au redémarrage, activez-le à partir du contrôleur sain : `storage failover modify -node _replacement-node-name_ -onreboot true`




=== Option 2 : réaffectez manuellement l'ID système sur un système autonome dans ONTAP

Dans un système autonome, vous devez réaffecter manuellement les disques à l'ID système du nouveau contrôleur avant de rétablir le fonctionnement normal du système.

.Description de la tâche

NOTE: Cette procédure ne s'applique qu'aux systèmes dans une configuration autonome.

.Étapes
. Si ce n'est déjà fait, redémarrez le _replace_ node, interrompez le processus de démarrage en appuyant sur Ctrl-C, puis sélectionnez l'option permettant de démarrer en mode maintenance dans le menu affiché.
. Vous devez entrer `Y` Lorsque vous êtes invité à remplacer l'ID système en raison d'une discordance d'ID système.
. Afficher les ID système : `disk show -a`
. Notez l'ancien ID système, qui s'affiche dans la colonne propriétaire du disque.
+
L'exemple suivant montre l'ancien ID système de 118073209 :

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK      OWNER                  POOL   SERIAL NUMBER  HOME
--------    -------------          -----  -------------  -------------
disk_name    system-1  (118073209)  Pool0  J8XJE9LC       system-1  (118073209)
disk_name    system-1  (118073209)  Pool0  J8Y478RC       system-1  (118073209)
.
.
.

----
. Réallouer la propriété du disque à l'aide des informations d'ID système obtenues via la commande disk show : `disk reassign -s old system ID disk reassign -s 118073209`
. Vérifier que les disques ont été correctement affectés : `disk show -a`
+
Les disques appartenant au nœud de remplacement doivent afficher le nouvel ID système. L'exemple suivant montre maintenant les disques qui appartiennent à system-1 le nouvel ID système, 118065481 :

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK      OWNER                  POOL   SERIAL NUMBER  HOME
--------    -------------          -----  -------------  -------------
disk_name    system-1  (118065481)  Pool0  J8Y0TDZC       system-1  (118065481)
disk_name    system-1  (118065481)  Pool0  J8Y0TDZC       system-1  (118065481)
.
.
.

----
. Si le chiffrement du volume ou du stockage est configuré sur votre système de stockage, vous devez restaurer la fonctionnalité de chiffrement du stockage ou du volume en suivant l'une des procédures suivantes, selon que vous utilisez la gestion des clés intégrée ou externe :
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["Restaurez les clés de chiffrement intégrées de gestion des clés"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["Restaurez les clés de chiffrement externes pour la gestion des clés"^]


. Démarrez le nœud : `boot_ontap`

