---
permalink: a220/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff a220, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Pour remplacer le châssis, vous devez arrêter les contrôleurs. 
---
= Arrêtez les contrôleurs - AFF A220
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arrêtez ou prenez le contrôleur défaillant en suivant la procédure appropriée pour votre configuration.



== Option 1 : plupart des configurations

Arrêtez les contrôleurs afin d'effectuer des opérations de maintenance sur le châssis.

Cette procédure concerne les systèmes ayant des configurations à deux nœuds. Si votre système comporte plus de deux nœuds, reportez-vous à la section https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_perform_a_graceful_shutdown_and_power_up_of_one_HA_pair_in_a_4__node_cluster["Comment effectuer un arrêt normal et mettre sous tension une paire haute disponibilité dans un cluster à quatre nœuds"^].

.Avant de commencer
* Empêchez tous les clients/hôtes d'accéder aux données sur le système NetApp.
* Suspendre les tâches de sauvegarde externes.
* Vérifiez que vous disposez des autorisations et des informations d'identification nécessaires :
+
** Informations d'identification de l'administrateur local pour ONTAP.
** Phrase secrète pour la gestion des clés intégrée NetApp à l'échelle du cluster en cas d'utilisation du chiffrement du stockage ou de NVE/NAE.
** Accès BMC pour chaque contrôleur.


* Assurez-vous de disposer des outils et de l'équipement nécessaires pour le remplacement.
* Avant de procéder à l'arrêt, vous devez :
+
** Effectuer des opérations supplémentaires https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["vérifications de l'état du système"].
** Mettez à niveau ONTAP vers une version recommandée pour le système.
** Résoudre tout https://activeiq.netapp.com/["Alertes et risques liés au bien-être Active IQ"]. Notez toutes les anomalies présentes sur le système, telles que les voyants des composants du système.




.Étapes
. Connectez-vous au cluster via SSH ou connectez-vous à un nœud du cluster à l'aide d'un câble de console local et d'un ordinateur portable/d'une console.
. Désactivez AutoSupport et indiquez la durée de mise hors ligne du système :
+
`system node autosupport invoke -node * -type all -message "MAINT=8h Power Maintenance"`

. Identifiez l'adresse SP/BMC de tous les nœuds :
+
`system service-processor show -node * -fields address`

. Quitter le cluster shell : `exit`
. Connectez-vous au processeur de service/contrôleur BMC via SSH en utilisant l'adresse IP de l'un des nœuds répertoriés dans le résultat de l'étape précédente.
+
Si vous utilisez une console ou un ordinateur portable, connectez-vous au contrôleur à l'aide des mêmes informations d'identification d'administrateur de cluster.

+

NOTE: Ouvrez une session SSH sur chaque connexion SP/BMC afin de pouvoir surveiller la progression.

. Arrêtez les deux nœuds situés dans le châssis défectueux :
+
`system node halt -node <node>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Pour les clusters qui utilisent SnapMirror en mode synchrone : `system node halt -node <node>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Entrez *y* pour chaque contrôleur du cluster lorsque vous voyez `_Warning: Are you sure you want to halt node "cluster <node-name> number"?
{y|n}:_`
. Attendez que chaque contrôleur s'arrête et affichez l'invite DU CHARGEUR.




== Option 2 : le contrôleur est en configuration MetroCluster


NOTE: N'utilisez pas cette procédure si votre système se trouve dans une configuration MetroCluster à deux nœuds.

Pour arrêter le contrôleur défaillant, vous devez déterminer l'état du contrôleur et, si nécessaire, prendre le contrôle de façon à ce que le contrôleur en bonne santé continue de transmettre des données provenant du stockage défaillant du contrôleur.

* Si vous avez un cluster avec plus de deux nœuds, il doit être dans le quorum. Si le cluster n'est pas au quorum ou si un contrôleur en bonne santé affiche la valeur false pour l'éligibilité et la santé, vous devez corriger le problème avant de désactiver le contrôleur défaillant ; voir link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchroniser un nœud avec le cluster"^].
* Si vous disposez d'une configuration MetroCluster, vous devez avoir confirmé que l'état de configuration MetroCluster est configuré et que les nœuds sont dans un état activé et normal (`metrocluster node show`).


.Étapes
. Si AutoSupport est activé, supprimez la création automatique de dossier en invoquant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
Le message AutoSupport suivant supprime la création automatique de dossiers pendant deux heures : `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Désactiver le rétablissement automatique depuis la console du contrôleur sain : `storage failover modify –node local -auto-giveback false`
. Faites passer le contrôleur douteux à l'invite DU CHARGEUR :
+
[cols="1,2"]
|===
| Si le contrôleur en état de fonctionnement s'affiche... | Alors... 


 a| 
Invite DU CHARGEUR
 a| 
Passez à l'étape suivante.



 a| 
Attente du retour...
 a| 
Appuyez sur Ctrl-C, puis répondez `y` lorsque vous y êtes invité.



 a| 
Invite système ou invite de mot de passe (entrer le mot de passe système)
 a| 
Prendre le contrôle défectueux ou l'arrêter à partir du contrôleur en bon état : `storage failover takeover -ofnode _impaired_node_name_`

Lorsque le contrôleur douteux s'affiche en attente de rétablissement..., appuyez sur Ctrl-C et répondez `y`.

|===

