---
settings:
  search: ontap-systems
  name: Install and maintain
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation sur les systèmes AFF et FAS
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/rel-notes.html"
  - title: Commencez
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Mise en service
      url: "/get-up-and-run.html"
  - title: Systèmes AFF A-Series
    url: "/aff-aseries/index.html"
    entries:
    - section: a150
    - section: a200
    - section: a250
    - section: a400
    - section: a700
    - section: a800
    - section: a900
  - title: Systèmes AFF C-Series
    url: "/aff-cseries/index.html"
    entries:
    - section: c190
    - section: c250
    - section: c400
    - section: c800
  - title: Systèmes ASA A-Series
    url: "/allsan-a-series/index.html"
    entries:
    - section: asa150
    - section: asa250
    - section: asa400
    - section: asa800
    - section: asa900
  - title: Systèmes FAS
    url: "/fas/index.html"
    entries:
    - section: fas500f
    - section: fas2700
    - section: fas2800
    - section: fas8300
    - section: fas9000
    - section: fas9500
  - title: Systèmes en fin de disponibilité
    url: "/endofavail/index.html"
    entries:
    - section: a220
    - section: a300
    - section: a320
    - section: a700s
    - section: fas2600
    - section: fas8200
  - title: Tiroirs disques
    url: "/drive-shelves/index.html"
    entries:
    - section: ns224
    - section: sas3
  - title: Kits d'armoires et de rails
    entries:
    - title: Kit SuperRail
      url: "/platform-supplemental/superrail-install.html"
    - title: Kit de rails à deux montants AFF A700/FAS9000
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: Armoire système 42U 1280 mm
      entries:
      - title: Préparez l'installation de l'armoire
        entries:
        - title: Caractéristiques de l'armoire
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: Outils/équipement requis
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: Espace requis et dimensions de l'armoire
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: Types et spécifications de PDU pris en charge
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: Déballez l'armoire système
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: Installez l'armoire
        entries:
        - title: Présentation
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: Installez le kit d'interconnexion de l'armoire
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: Poser le kit de boulon
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: Poser les rails de support
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: Installer l'équipement
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: Mettez l'armoire sous tension
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: Remplacer les PDU
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: Porte avant de l'armoire de marche arrière
        entries:
        - title: Ce dont vous avez besoin
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: Retirer le badge éclairé
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: Retirez la porte de l'armoire
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: Déplacez l'alimentation et le câblage du badge
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: Charnière de porte arrière et loquet de verrouillage
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: Réinstallez la porte et le badge éclairé
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - section: other
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: AFF and FAS Systems
  repo: ontap-systems-family
