---
sidebar: sidebar 
permalink: supported-platforms.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: Découvrez la version prise en charge de ONTAP pour votre plateforme ou votre tiroir. 
---
= Compatibilité matérielle et logicielle de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Les systèmes de stockage ONTAP sont compatibles avec plusieurs versions du logiciel ONTAP. Découvrez les versions de ONTAP prises en charge par vos systèmes de stockage et vos tiroirs disques.

La prise en charge complète de la configuration et les limitations pour les systèmes matériels ONTAP sont disponibles dans  https://hwu.netapp.com["NetApp Hardware Universe"]. Des détails sur les problèmes connus, les limitations et les mises en garde de mise à niveau dans le logiciel ONTAP 9 sont disponibles dans le https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de version de ONTAP 9"].

[role="tabbed-block"]
====
.Systèmes AFF
--
Les systèmes AFF A-Series et AFF C-Series offrent une architecture robuste en mode scale-out adaptée aux environnements virtualisés. Elles peuvent être déployées en tant que systèmes autonomes ou en tant que tiers de performance dans les configurations NetApp ONTAP. link:https://www.netapp.com/data-storage/all-flash-san-storage-array["En savoir plus sur les systèmes AFF"].

Les systèmes AFF A-Series et AFF C-Series sont pris en charge à partir des versions ONTAP suivantes.

ONTAP 9.16.1::
+
--
* AFF A20
* AFF A30
* AFF A50
* AFF C30
* AFF C60
* AFF C80


--
ONTAP 9.15.1::
+
--
* AFF A1K
* AFF A70
* AFF A90


--
ONTAP 9.12.1P1::
+
--
* AFF A150
* AFF C250
* AFF C400
* AFF C800


--
ONTAP 9.10.1::
+
--
* AFF A900


--
ONTAP 9.8::
+
--
* AFF A250


--
ONTAP 9.7::
+
--
* AFF A400
* AFF A800


--


--
.Systèmes ASA r2
--
Les systèmes ASA r2 apportent une solution matérielle et logicielle unifiée qui simplifie l'expérience et répond parfaitement aux besoins des clients SAN. link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["En savoir plus sur les systèmes ASA r2"].

Les systèmes ASA r2 sont pris en charge à partir des versions ONTAP suivantes.

ONTAP 9.16.0::
+
--
* ASA A1K
* ASA A70
* ASA A90


--


--
.Systèmes ASA
--
Les systèmes ASA A-Series et ASA C-Series offrent une expérience SAN simplifiée et dédiée qui procure une disponibilité continue des données pour les bases de données d'entreprise stratégiques et autres workloads SAN utilisant le protocole FCP ou iSCSI. link:https://www.netapp.com/data-storage/all-flash-san-storage-array["En savoir plus sur les systèmes ASA"].

Les systèmes ASA sont pris en charge à partir de ces versions d'ONTAP.

ONTAP 9.13.1P1::
+
--
* ASA C250
* ASA C400
* ASA C800


--
ONTAP 9.13.1::
+
--
* ASA A150
* ASA A250
* ASA A400
* ASA A900


--
ONTAP 9.8::
+
--
* ASA AFF A250
* ASA AFF A800


--
ONTAP 9.7::
+
--
* ASA AFF A400


--


--
.Systèmes FAS
--
Les systèmes FAS fournissent un stockage secondaire efficace et sécurisé, qui est la solution idéale pour le Tiering, la sauvegarde et la reprise d'activité. link:https://www.netapp.com/data-storage/fas/["En savoir plus sur les systèmes FAS"].

Les systèmes FAS sont pris en charge à partir de ces versions d'ONTAP.

ONTAP 9.15.1::
+
--
* FAS70
* FAS90


--
ONTAP 9.13.1::
+
--
* FAS2820


--
ONTAP 9.11.1::
+
--
* FAS9500


--
ONTAP 9.10.1P3::
+
--
* FAS9500


--
ONTAP 9.7::
+
--
* FAS2750
* FAS8300
* FAS8700


--


--
.Tiroirs disques
--
Les tiroirs disques sont spécialement conçus pour les systèmes NetApp AFF, ASA et FAS. Ils vous aident à obtenir les performances, la résilience et la flexibilité dont vous avez besoin pour votre transformation digitale.

Les tiroirs disques sont disponibles à partir des versions ONTAP suivantes.

ONTAP 9.16.1:: NS224 avec modules NSM100B
ONTAP 9.6:: Tiroir NS224 avec modules NSM100


--
====