---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: Découvrez les nouvelles plateformes pour les systèmes matériels ONTAP. 
---
= Nouveautés des systèmes matériels ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés des systèmes matériels ONTAP.



== Décembre 2024



=== AFF A20, AFF A30 et AFF A50

Les nouveaux systèmes matériels AFF A20, A30 et A50 étendent des fonctionnalités de gestion des données hautes performances, intelligentes et complètes à un plus grand nombre de clients et de charges de travail.

Ces systèmes offrent une détection DES ransomwares basée sur le MACHINE LEARNING en temps réel, une intégration cloud transparente et des performances inégalées pour les workloads stratégiques, notamment l'IA, VMware, les bases de données et l'analytique, ainsi que la prise en charge du stockage bloc, fichier et objet.

link:https://www.netapp.com/data-storage/aff-a-series/["En savoir plus sur les systèmes AFF A-Series"].



=== AFF C30, AFF C60 et AFF C80

Les nouveaux systèmes matériels AFF C30, AFF C60 et AFF C80 permettent aux entreprises d'accéder plus facilement aux performances et à l'efficacité de la technologie Flash en fournissant une capacité de stockage de 1,5 po dans les déploiements à deux racks.

Elle offre une densité exceptionnelle avec des disques de 60 To, des performances supérieures et une meilleure flexibilité des E/S.

link:https://www.netapp.com/data-storage/aff-c-series/["En savoir plus sur les systèmes AFF C-Series"].



=== Tiroir disque NS224 avec modules de tiroir NSM100B

Améliorez les fonctionnalités de votre data Center avec le NS224 et le nouveau module d'extension du stockage NVMe NSM100B. Conçu pour remplacer directement le module NSM100, le nouveau module de tiroir NSM100B s'intègre en toute transparence à votre configuration existante. Il prend en charge les configurations à connexion directe et à connexion par commutateur des tiroirs NS224, offrant ainsi une flexibilité exceptionnelle pour optimiser l'efficacité et l'évolutivité de votre système de stockage.



== Septembre 2024



=== Systèmes ASA r2

Les nouveaux systèmes matériels ASA r2 (ASA A1K, ASA A70 et ASA A90) offrent une solution matérielle et logicielle unifiée qui simplifie l'expérience en fonction des besoins des clients qui utilisent uniquement un réseau SAN.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["En savoir plus sur les systèmes ASA r2"].



=== FAS70 et FAS90

Les nouveaux systèmes matériels FAS70 et FAS90 offrent un stockage de sauvegarde économique mais haute performance, permettant un archivage sécurisé et sécurisé contre les attaques par ransomware.

link:https://www.netapp.com/data-storage/fas/["En savoir plus sur les systèmes FAS"].
