---
permalink: asa400/install-videos.html 
sidebar: sidebar 
keywords: asa a400, asa, a400, video, rack, cable, system, manager, guide, setup, initial, configuration, hardware, installation, cabling, perform, end-to-end, software, configuration, hardware installation and cabling, perform end-to-end software configuration 
summary: 'Deux vidéos sont disponibles. L"une montre comment installer et connecter le système, l"autre montrant un exemple d"utilisation de la configuration assistée par System Manager pour effectuer la configuration initiale du système.' 
---
= Vidéos - ASA A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Deux vidéos sont disponibles. L'une montre comment installer et connecter le système, l'autre montrant un exemple d'utilisation de la configuration assistée par System Manager pour effectuer la configuration initiale du système.



== Vidéo l'une des deux : installation du matériel et câblage

La vidéo suivante montre comment installer et raccorder votre nouveau système.

.Animation : instructions d'installation et de configuration du système AFF A400
video::6cbbcb96-fe92-4040-a004-ab2001624dd7[panopto]

NOTE: Le système ASA A400 utilise la même procédure d'installation que le système AFF A400.



== Vidéo deux sur deux : effectuez une configuration logicielle de bout en bout

La vidéo suivante présente une configuration logicielle de bout en bout pour les systèmes exécutant ONTAP 9.2 et versions ultérieures.

video::WAE0afWhj1c?[youtube]