---
permalink: c80/overview.html 
sidebar: sidebar 
keywords: AFF C80 specifications, AFF C80 specs, NetApp AFF C80, AFF C80 hardware 
summary: Spécifications clés du système de stockage AFF C80 
---
= Spécifications clés de AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour l' AFF C80.  Visite https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) pour une liste complète des spécifications AFF C80.  Cette page reflète une seule paire à haute disponibilité.



=== Spécifications clés de AFF C80

Configuration de la plateforme : paire de châssis simple HA AFF C80

Capacité brute maximale : 14,7360 Po

Mémoire : 512.0000 Go

Facteur de forme : châssis 4U avec 2 contrôleurs HA et 48 emplacements pour disques

Version ONTAP : b_startONTAP : 9.16.1P2b_end

Emplacements d'extension PCIe : 18

Version minimale ONTAP : ONTAP 9.16.1RC1



=== Maximums de mise à l'échelle

|===


| Type | Paires HA | Capacité brute | Mémoire maximale 


| NAS | 12 | 176,8 Po / 157,0 PiB | 6144 Go 


| SAN | 6 | 88,4 Po / 78,5 PiB | 3072 Go 


| Paire haute disponibilité |  | 14,7 Po / 13,1 PiB | 512,0000 
|===


=== IO



==== E/S embarquées

Aucune donnée IO embarquée.



==== E/S totales

|===


| Protocole | Ports 


| Ethernet 200 Gbit/s | 24 


| Ethernet 100 Gbit/s | 36 


| Ethernet 25 Gbit/s | 56 


| Ethernet 10 Gbit/s | 56 


| FC 64 Gbit/s | 56 


| NVMe/FC 64 Gbit/s | 56 


|  | 0 
|===


==== Ports de gestion

|===


| Protocole | Ports 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2 
|===


=== Réseau de stockage pris en charge

CIFS ; FC ; iSCSI ; NFS v3 ; NFS v4.0 ; NFS v4.1 ; NFS v4.2 ; NFSv3/RDMA ; NFSv4/RDMA ; NVMe/FC ; NVMe/TCP ; S3 ; S3 avec NAS ; SMB 2.0 ; SMB 2.1 ; SMB 2.x ; SMB 3.0 ; SMB 3.1 ; SMB 3.1.1 ;



=== Spécifications de l'environnement système

Aucune donnée environnementale disponible.



=== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




=== Haute disponibilité

Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP ; Contrôleurs redondants remplaçables à chaud ; Alimentations redondantes remplaçables à chaud ;
