---
permalink: c80/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff c80, replace the boot media 
summary: 'Avant de remplacer le support de démarrage de votre système AFF C80, assurez-vous que vous disposez du périphérique de démarrage de remplacement approprié, de l"accès au micrologiciel système et au logiciel ONTAP, ainsi que d"une sauvegarde des données de configuration essentielles.' 
---
= Configuration requise pour le remplacement des supports de démarrage - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système AFF C80, assurez-vous que vous disposez du périphérique de démarrage de remplacement approprié, de l'accès au micrologiciel système et au logiciel ONTAP, ainsi que d'une sauvegarde des données de configuration essentielles.

Passez en revue les exigences suivantes.

* Vous devez disposer d'une clé USB, formatée en FAT32, avec la quantité de stockage appropriée pour maintenir le `image_xxx.tgz` fichier.
* Vous devez copier le `image_xxx.tgz` fichier sur la clé USB pour pouvoir l'utiliser ultérieurement dans cette procédure.
* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.
* Il est important d'appliquer les commandes au cours de la procédure suivante sur le contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le contrôleur _Healthy_ est le partenaire HA du contrôleur déficient.



