---
permalink: c80/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff c80, replace the boot media 
summary: 'Avant de remplacer le support de démarrage de votre système AFF C80, assurez-vous de répondre aux exigences requises pour un remplacement réussi. Cela inclut la vérification de la présence d"une clé USB contenant la quantité de stockage appropriée et la vérification de la bonne mise en place du périphérique de démarrage de remplacement.' 
---
= Conditions requises pour la récupération manuelle du support de démarrage - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système AFF C80, assurez-vous de répondre aux exigences requises pour un remplacement réussi. Cela inclut la vérification de la présence d'une clé USB contenant la quantité de stockage appropriée et la vérification de la bonne mise en place du périphérique de démarrage de remplacement.

.clé USB
* Assurez-vous d’avoir une clé USB formatée en FAT32.
* La clé USB doit avoir une capacité de stockage suffisante pour contenir le  `image_xxx.tgz` déposer.


.Préparation du dossier
Copiez le  `image_xxx.tgz` sur la clé USB. Ce fichier sera utilisé lors du transfert de l'image ONTAP via la clé USB.

.Remplacement des composants
Remplacez le composant défectueux par le composant de remplacement fourni par NetApp.

.Identification du contrôleur
Il est essentiel d'appliquer les commandes au contrôleur approprié lorsque vous remplacez le support de démarrage défectueux :

* Le _contrôleur défaillant_ est le contrôleur sur lequel vous effectuez la maintenance.
* Le _contrôleur sain_ est le partenaire HA du contrôleur altéré.


.Et la suite ?
Après avoir examiné la configuration requise pour remplacer le support de démarrage, vous devez link:bootmedia-encryption-preshutdown-checks.html["vérifiez la prise en charge et l'état de la clé de cryptage sur le support de démarrage"].
