---
permalink: c80/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: c80, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Vérifiez que les interfaces logiques relèvent de leur port de base, effectuez un contrôle de l"état du cluster et renvoyez la pièce défectueuse à NetApp pour terminer l"étape finale de la procédure de remplacement du contrôleur AFF C80.' 
---
= Remplacement complet du contrôleur - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour remplacer le contrôleur de votre système AFF C80, restaurez d'abord la configuration du chiffrement du stockage NetApp (si nécessaire) et installez les licences requises sur le nouveau contrôleur. Ensuite, vérifiez que les interfaces logiques (LIF) signalent leurs ports de repos et effectuez une vérification de l'état du cluster. Enfin, enregistrez le nouveau numéro de série du contrôleur, puis renvoyez la pièce défectueuse à NetApp.



== Étape 1 : installer les licences pour le contrôleur de remplacement dans ONTAP

Vous devez installer de nouvelles licences pour le _remplacement_ node si le nœud douteux utilisait des fonctions ONTAP qui requièrent une licence standard (nœud verrouillé). Pour les fonctionnalités avec licences standard, chaque nœud du cluster doit avoir sa propre clé pour cette fonctionnalité.

.Avant de commencer
Si votre système exécutait initialement ONTAP 9.10.1 ou une version ultérieure, suivez la procédure décrite dans  https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Post_Motherboard_Replacement_Process_to_update_Licensing_on_a_AFF_FAS_system#Internal_Notes^["Procédure de post-remplacement de la carte mère pour mettre à jour les licences sur les plates-formes ONTAP"]. Si vous n'êtes pas sûr de la version ONTAP initiale de votre système, reportez-vous à la section link:https://hwu.netapp.com["NetApp Hardware Universe"^] pour plus d'informations.

.Description de la tâche
* Jusqu'à ce que vous installiez les clés de licence, les fonctions nécessitant des licences standard restent disponibles pour le _remplacement_ node. Cependant, si le nœud douteux était le seul nœud du cluster avec une licence pour la fonction, aucune modification de configuration de la fonction n'est autorisée.
+
En outre, l'utilisation de fonctions sans licence sur le nœud peut vous mettre hors conformité avec votre contrat de licence. Vous devez donc installer la ou les clés de licence de remplacement sur le _remplacement_ noeud dès que possible.

* Les clés de licence doivent être au format à 28 caractères.
* Vous disposez d'une période de grâce de 90 jours pour installer les clés de licence. Après la période de grâce, toutes les anciennes licences sont invalidés. Après l'installation d'une clé de licence valide, vous disposez de 24 heures pour installer toutes les clés avant la fin du délai de grâce.
* Si le nœud se trouve dans une configuration MetroCluster et que tous les nœuds d'un site ont été remplacés, des clés de licence doivent être installées sur le ou les nœuds _remplacement_ avant le rétablissement.


.Étapes
. Si vous avez besoin de nouvelles clés de licence, vous pouvez obtenir ces clés sur le https://mysupport.netapp.com/site/global/dashboard["Site de support NetApp"] Dans la section My support (mon support), sous licences logicielles.
+

NOTE: Les nouvelles clés de licence dont vous avez besoin sont générées automatiquement et envoyées à l'adresse électronique du fichier. Si vous ne recevez pas l'e-mail contenant les clés de licence dans les 30 jours, contactez l'assistance technique.

. Installer chaque clé de licence : `+system license add -license-code license-key, license-key...+`
. Supprimez les anciennes licences, si nécessaire :
+
.. Vérifier si les licences ne sont pas utilisées : `license clean-up -unused -simulate`
.. Si la liste semble correcte, supprimez les licences inutilisées : `license clean-up -unused`






== Étape 2 : vérifier la LIF, enregistrer le numéro de série et vérifier l'état du cluster

Avant de renvoyer le _replace_ node au service, vérifiez que les LIF se trouvent sur leurs ports de rattachement, puis enregistrez le numéro de série du _replace_ node si AutoSupport est activé et réinitialisez le rétablissement automatique.

.Étapes
. Vérifiez que les interfaces logiques sont bien placées sur leur serveur domestique et leurs ports : `network interface show -is-home false`
+
Si des LIFs sont répertoriées comme faux, restaurez-les sur leurs ports de home port : `network interface revert -vserver * -lif *`

. Enregistrez le numéro de série du système auprès du support NetApp.
+
** Si AutoSupport est activé, envoyez un message AutoSupport pour enregistrer le numéro de série.
** Si AutoSupport n'est pas activé, appeler https://mysupport.netapp.com["Support NetApp"] pour enregistrer le numéro de série.


. Vérifiez l'état de santé de votre cluster. Consultez https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Procédure de vérification de l'état du cluster à l'aide d'un script dans ONTAP"^] l'article de la base de connaissances pour plus d'informations.
. Si une fenêtre de maintenance AutoSupport a été déclenchée, mettez-la fin à l'aide du `system node autosupport invoke -node * -type all -message MAINT=END` commande.
. Si le retour automatique a été désactivé, réactivez-le : `storage failover modify -node local -auto-giveback true`




== Étape 3 : renvoyer la pièce défaillante à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièces et remplacements"] page pour plus d'informations.
