---
permalink: c80/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: c80, how to recable the system, teboot the system 
summary: Replacez le contrôle des ressources de stockage sur le contrôleur de remplacement afin que votre système AFF C80 puisse reprendre son fonctionnement normal. 
---
= Remettre le contrôleur - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Replacez le contrôle des ressources de stockage sur le contrôleur de remplacement afin que votre système AFF C80 puisse reprendre son fonctionnement normal. La procédure de restitution varie en fonction du type de cryptage utilisé par votre système : aucun cryptage ou cryptage Onboard Key Manager (OKM).

[role="tabbed-block"]
====
.Pas de cryptage
--
Remettez le contrôleur défectueux en mode de fonctionnement normal en laissant son espace de stockage.

.Étapes
. Dans l'invite Loader, entrez `boot_ontap`.
. Appuyez sur <enter> lorsque les messages de la console s'arrêtent.
+
** Si vous voyez l'invite _login_, passez à l'étape suivante à la fin de cette section.
** Si vous voyez _waiting for giveback_, appuyez sur la clé <enter>, connectez-vous au nœud partenaire, puis passez à l'étape suivante à la fin de cette section.


. Remettre le contrôleur défectueux en fonctionnement normal en réutilisant son espace de stockage : `storage failover giveback -ofnode _impaired_node_name_`
. Si le rétablissement automatique a été désactivé, le réactiver : `storage failover modify -node local -auto-giveback _true_`
. Si AutoSupport est activé, restaurer/annuler la suppression de la création automatique de cas : `system node autosupport invoke -node * -type all -message MAINT=END`


--
.Chiffrement intégré (OKM)
--
Réinitialise le chiffrement intégré et rétablit le fonctionnement normal du contrôleur.

.Étapes
. Dans l'invite Loader, entrez `boot_ontap maint`.
. Démarrez à partir du menu ONTAP à partir de l'invite Loader `boot_ontap menu` et sélectionnez l'option 10.
. Saisissez la phrase de passe OKM.
+

NOTE: Vous êtes invité à saisir deux fois la phrase de passe.

. Entrez les données de la clé de sauvegarde lorsque vous y êtes invité.
. Dans le menu de démarrage, entrez option `1` pour le démarrage normal.
. Appuyez sur <enter> lorsque _waiting for giveback_ s'affiche.
. Déplacez le câble de la console vers le nœud partenaire et connectez-vous en tant que `admin`.
. Ne donner que les agrégats CFO (l'agrégat racine) : `storage failover giveback -fromnode local -only-cfo-aggregates _true_`
+
** Si vous rencontrez des erreurs, contactez https://support.netapp.com["Support NetApp"].


. Attendez 5 minutes après la fin du rapport de rétablissement et vérifiez l'état du basculement et du rétablissement : `storage failover show` et `storage failover show-giveback`.
. Synchroniser et vérifier l'état des clés :
+
.. Replacer le câble de la console sur le contrôleur de remplacement.
.. Synchroniser les clés manquantes : `security key-manager onboard sync`
+

NOTE: Vous êtes invité à saisir la phrase de passe OKM au niveau du cluster.

.. Vérifier l'état des clés : `security key-manager key query -restored _false_`
+
La sortie ne doit pas afficher de résultats lorsqu'elle est correctement synchronisée.

+
Si le résultat affiche des résultats (les ID de clé des clés qui ne sont pas présents dans la table de clés internes du système), contactez https://support.netapp.com["Support NetApp"].



. Remettre le contrôleur défectueux en fonctionnement normal en réutilisant son espace de stockage : `storage failover giveback -ofnode _impaired_node_name_`
. Si le rétablissement automatique a été désactivé, le réactiver : `storage failover modify -node local -auto-giveback _true_`
. Si AutoSupport est activé, restaurer/annuler la suppression de la création automatique de cas : `system node autosupport invoke -node * -type all -message MAINT=END`


--
====
.Et la suite ?
Après le transfert de la propriété des ressources de stockage vers le contrôleur de remplacement, vous devez link:controller-replace-restore-system-rma.html["terminez le remplacement du contrôleur"]procéder comme suit.
