---
permalink: c80/io-module-overview.html 
sidebar: sidebar 
keywords: AFF C80, replace io module 
summary: 'Vous pouvez remplacer un module d"E/S défectueux dans votre système de stockage AFF C80 par le même type de module d"E/S ou par un autre type de module d"E/S. Vous pouvez également ajouter un module d"E/S dans un système doté de logements vides.' 
---
= Présentation de l'ajout et du remplacement du module d'E/S - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système AFF C80 offre une grande flexibilité d'extension ou de remplacement des modules d'E/S pour améliorer la connectivité et les performances du réseau. L'ajout ou le remplacement d'un module d'E/S est essentiel lors de la mise à niveau des capacités réseau ou de l'adressage d'un module défaillant.

Vous pouvez remplacer un module d'E/S défectueux dans votre système de stockage AFF C80 par le même type de module d'E/S ou par un autre type de module d'E/S. Vous pouvez également ajouter un module d'E/S dans un système doté de logements vides.

* link:io-module-add.html["Ajoutez un module d'E/S."]
+
L'ajout de modules supplémentaires peut améliorer la redondance, ce qui permet de garantir que le système reste opérationnel même en cas de défaillance d'un module.

* link:io-module-replace.html["Remplacez un module d'E/S."]
+
Le remplacement d'un module d'E/S défaillant permet de restaurer l'état de fonctionnement optimal du système.



.Numérotation des connecteurs d'E/S.
Les connecteurs d'E/S des contrôleurs AFF C80 sont numérotés de 1 à 11, comme illustré ci-dessous.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numérotation des logements sur un contrôleur AFF C80]
