---
permalink: c80/maintain-overview.html 
sidebar: sidebar 
keywords: c80 maintenance, maintenance, repairing aff c80, repairing c80, replace c80 components 
summary: 'Assurez la maintenance du matériel de votre système de stockage AFF C80 afin de garantir une fiabilité à long terme et des performances optimales. Effectuez régulièrement des tâches de maintenance, telles que le remplacement de composants défectueux, afin d"éviter les temps d"indisponibilité et les pertes de données.' 
---
= Présentation des procédures de maintenance - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Assurez la maintenance du matériel de votre système de stockage AFF C80 afin de garantir une fiabilité à long terme et des performances optimales. Effectuez régulièrement des tâches de maintenance, telles que le remplacement de composants défectueux, afin d'éviter les temps d'indisponibilité et les pertes de données.

Les procédures de maintenance supposent que le système AFF C80 a déjà été déployé en tant que nœud de stockage dans l'environnement ONTAP.



== Composants du système

Pour le système de stockage AFF C80, vous pouvez effectuer des procédures de maintenance sur les composants suivants.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Support de démarrage - récupération automatique"]
 a| 
Le support de démarrage stocke un ensemble principal et secondaire de fichiers image ONTAP que le système de stockage utilise pour démarrer.  Lors de la récupération automatisée, le système récupère l'image de démarrage à partir du nœud partenaire et exécute automatiquement l'option de menu de démarrage appropriée pour installer l'image sur votre support de démarrage de remplacement. La récupération automatique du support de démarrage est prise en charge uniquement dans ONTAP 9.17.1 et versions ultérieures. Si votre système de stockage exécute une version antérieure d' ONTAP, utilisez l'option link:bootmedia-replace-workflow.html["procédure de récupération de démarrage manuel"] .



 a| 
link:bootmedia-replace-workflow.html["Support de démarrage - récupération manuelle"]
 a| 
Le support de démarrage stocke un ensemble principal et secondaire de fichiers image ONTAP que le système de stockage utilise pour démarrer. Lors de la récupération manuelle, vous démarrez le système de stockage à partir d'une clé USB et restaurez manuellement l'image et la configuration du système de fichiers.  Si votre système de stockage exécute ONTAP 9.17.1 et versions ultérieures, utilisez lelink:bootmedia-replace-workflow-bmr.html["procédure de récupération de démarrage automatisée"] .



 a| 
link:chassis-replace-workflow.html["Châssis"]
 a| 
Le châssis correspond au boîtier physique qui contient tous les composants du contrôleur, tels que le contrôleur/l'unité centrale, l'alimentation et les E/S.



 a| 
link:controller-replace-workflow.html["Contrôleur"]
 a| 
Un contrôleur se compose d'une carte, d'un micrologiciel et d'un logiciel. Il contrôle les lecteurs et exécute le logiciel du système d'exploitation ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Un module de mémoire en ligne double (DIMM) est un type de mémoire d'ordinateur. Ils sont installés pour ajouter de la mémoire système à une carte mère du contrôleur.



 a| 
link:drive-replace.html["Lecteur"]
 a| 
Un lecteur est un périphérique qui fournit le stockage physique nécessaire aux données.



 a| 
link:fan-swap-out.html["Ventilateur"]
 a| 
Un ventilateur refroidit le contrôleur.



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
La mémoire NVRAM (mémoire vive non volatile) est un module qui permet au contrôleur de protéger et d'enregistrer les données à la volée en cas de coupure de courant du système. L'ID système réside dans le module NVRAM. Lorsqu'il est remplacé, le contrôleur utilise le nouvel ID système du module NVRAM de remplacement.



 a| 
link:nvdimm-battery-replace.html["Batterie NV"]
 a| 
La batterie NV est chargée d'alimenter le module NVRAM alors que les données en cours de transfert vers la mémoire Flash après une coupure de courant.



 a| 
link:io-module-overview.html["Module d'E/S."]
 a| 
Le module d'E/S (module d'entrée/sortie) est un composant matériel qui sert d'intermédiaire entre le contrôleur et divers dispositifs ou systèmes qui doivent échanger des données avec le contrôleur.



 a| 
link:power-supply-replace.html["Alimentation électrique"]
 a| 
Une alimentation fournit une source d'alimentation redondante dans un contrôleur.



 a| 
link:rtc-battery-replace.html["Pile de l'horloge en temps réel"]
 a| 
Une batterie d'horloge en temps réel conserve les informations relatives à la date et à l'heure du système si l'appareil est éteint.



 a| 
link:system-management-replace.html["Module de gestion du système"]
 a| 
Le module de gestion du système fournit l'interface entre le contrôleur et une console ou un ordinateur portable à des fins de maintenance du contrôleur ou du système.  Le module de gestion du système contient le support de démarrage et stocke le numéro de série du système (SSN).

|===