---
permalink: c80/overview.html 
sidebar: sidebar 
summary: Spécifications clés du groupe de plateformes C80 
---
= Spécifications clés de AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour le système de stockage AFF C80 dans une seule paire haute disponibilité.  Visitez NetApp Hardware Universe (HWU) pour obtenir les spécifications complètes de ce système de stockage.



== Spécifications clés de AFF C80

* Configuration de la plateforme : paire de châssis simple HA AFF C80
* Capacité brute maximale : 14,7360 Po
* Mémoire : 512.0000 Go
* Facteur de forme : châssis 4U avec 2 contrôleurs HA et 48 emplacements pour disques
* Version ONTAP : ONTAP: 9.16.1P2
* Emplacements d'extension PCIe : 18
* Version minimale ONTAP : ONTAP 9.16.1RC1 == Maximums de mise à l'échelle
* Type : NAS ; Paires HA : 12 ; Capacité brute : 176,8 Po / 157,0 PiB ; Mémoire maximale : 6 144 Go
* Type : SAN ; paires HA : 6 ; capacité brute : 88,4 Po / 78,5 PiB ; mémoire maximale : 3 072 Go
* Type : Paire HA ; Capacité brute : 14,7 Po / 13,1 PiB ; Mémoire maximale : 512 0000




== E/S



=== E/S embarquées

Aucune donnée d'E/S intégrée.



=== E/S totales

* Protocole : Ethernet 200 Gbps ; Ports : 24
* Protocole : Ethernet 100 Gbps ; Ports : 36
* Protocole : Ethernet 25 Gbit/s ; Ports : 56
* Protocole : Ethernet 10 Gbit/s ; Ports : 56
* Protocole : FC 64 Gbps ; Ports : 56
* Protocole : NVMe/FC 64 Gbit/s ; Ports : 56
* Ports : 0




=== Ports de gestion

* Protocole : Ethernet 1 Gbps ; Ports : 2
* Protocole : RS-232 115 Kbps ; Ports : 4
* Protocole : USB 600 Mbps ; Ports : 2




== Prise en charge du réseau de stockage

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NFSv3/RDMA
* NFSv4/RDMA
* NVMe/FC
* NVMe/TCP
* S3
* S3 avec NAS
* PME 2.0
* PME 2.1
* SMB 2.x
* PME 3.0
* PME 3.1
* SMB 3.1.1 == Spécifications de l'environnement système Aucune donnée d'environnement disponible.




== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




== Haute disponibilité

* Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP
* Contrôleurs redondants remplaçables à chaud
* Alimentations redondantes remplaçables à chaud

