---
permalink: fas2700/maintain-overview.html 
sidebar: sidebar 
keywords: fas2700 maintenance, maintenance, repairing, repairing fas2700, replace fas2700 components, replace fas2700 components 
summary: Maintenance du matériel ASA C800 
---
= Maintenance du matériel FAS2700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes de stockage FAS2700 peuvent réaliser les procédures de maintenance sur les composants suivants.



== Support de démarrage

Le support de démarrage stocke un ensemble principal et secondaire de fichiers d'image de démarrage que le système utilise lorsqu'il démarre.



== Module de cache

Vous devez remplacer le module de cache du contrôleur lorsque votre système enregistre un seul message AutoSupport (ASUP) indiquant que le module est hors ligne.



== Châssis

Le châssis correspond au boîtier physique qui contient tous les composants du contrôleur, tels que le contrôleur/l'unité centrale, l'alimentation et les E/S.



== Contrôleur

Un contrôleur se compose d'une carte, d'un micrologiciel et d'un logiciel. Il contrôle les entraînements et met en œuvre les fonctions ONTAP.



== DIMM

Vous devez remplacer un module DIMM (module de mémoire double en ligne) en cas de non-concordance de mémoire, ou si vous avez un module DIMM défectueux.



== Lecteur

Un lecteur est un périphérique qui fournit le support de stockage physique pour les données.



== Batterie NVMEM

Une batterie est fournie avec le contrôleur et conserve les données en cache en cas de panne de courant alternatif.



== Alimentation électrique

Une alimentation électrique fournit une source d'alimentation redondante dans un tiroir contrôleur.



== Pile de l'horloge en temps réel

Une batterie d'horloge en temps réel conserve les informations relatives à la date et à l'heure du système si l'alimentation est coupée.
