---
permalink: fas2700/overview.html 
sidebar: sidebar 
summary: Spécifications clés du groupe de plateformes FAS2700 
---
= Spécifications clés du FAS2750
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour le système de stockage FAS2750 dans une seule paire haute disponibilité.  Visitez NetApp Hardware Universe (HWU) pour obtenir les spécifications complètes de ce système de stockage.



== Spécifications clés du FAS2750

* Configuration de la plateforme : FAS2750 UTA2, châssis simple, paire HA
* Capacité brute maximale : 2,6832 Po
* Mémoire : 64.0000 Go
* Facteur de forme : châssis 2U avec 2 contrôleurs HA et 24 emplacements pour disques
* Version ONTAP : ONTAP: 9.16.1P2
* Emplacements d'extension PCIe : 2
* Version minimale ONTAP : ONTAP 9.4RC1 == Maximums de mise à l'échelle
* Type : NAS ; Paires HA : 12 ; Capacité brute : 32,2 Po / 28,6 PiB ; Mémoire maximale : 768 Go
* Type : SAN ; paires HA : 6 ; capacité brute : 16,1 Po / 14,3 PiB ; mémoire maximale : 384 Go
* Type : Paire HA ; Capacité brute : 2,7 Po / 2,4 PiB ; Mémoire maximale : 64 0000




== E/S



=== E/S embarquées

* Protocole : Ethernet 10 Gbps ; Ports : 12
* Protocole : FC 16 Gbps ; Ports : 8
* Protocole : SAS 12 Gbit/s ; Ports : 4




=== E/S totales

* Protocole : Ethernet 10 Gbps ; Ports : 12
* Protocole : FC 16 Gbps ; Ports : 8
* Protocole : SAS 12 Gbit/s ; Ports : 4




=== Ports de gestion

* Protocole : Ethernet 1 Gbps ; Ports : 2
* Protocole : RS-232 115 Kbps ; Ports : 4
* Protocole : USB 12 Mbps ; Ports : 2




== Prise en charge du réseau de stockage

* CIFS
* FC
* FCoE
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NVMe/TCP
* S3
* S3 avec NAS
* PME 2.0
* PME 2.1
* SMB 2.x
* PME 3.0
* PME 3.1
* SMB 3.1.1 == Spécifications de l'environnement système
* Puissance typique : 1209 BTU/h
* Consommation d'énergie dans le pire des cas : 1 676 BTU/h
* Poids : 60,8 lb 27,6 kg
* Hauteur : 2U
* Largeur : 19 pouces conforme à la norme IEC (17,6 pouces 44,7 cm)
* Profondeur : 19,0 po (24,1 po avec support de gestion des câbles)
* Température/altitude/humidité de fonctionnement : 5 °C à 45 °C (41 °F à 113 °F) à une altitude <= 3 048 m <= 10 000 ft ; humidité relative de 8 % à 90 %, sans condensation
* Température/humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu'à 12 192 m (40 000 pi) 10 % à 95 % d'humidité relative, sans condensation, dans l'emballage d'origine
* Bruit acoustique : Puissance acoustique déclarée (LwAd) : 6,9 Pression acoustique (LpAm) (positions d'observation) : 51,0 dB




== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




== Haute disponibilité

* Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP
* Contrôleurs redondants remplaçables à chaud
* Alimentations redondantes remplaçables à chaud
* Gestion SAS en bande via des connexions SAS pour les étagères externes

