---
sidebar: sidebar 
permalink: fru-reference/io-module-fru-links.html 
keywords: I/O module, field replaceable units, FRU, I/O module replacement 
summary: 'Recherchez les procédures de remplacement des modules d"E/S pour votre système de stockage NetApp organisées par famille de plates-formes.  Cette référence fournit des liens directs vers des flux de travail de remplacement de modules d"E/S étape par étape pour les systèmes AFF, ASA et FAS pour vous aider à localiser rapidement la procédure appropriée pour votre modèle spécifique.' 
---
= Procédures de remplacement des modules d'E/S par famille de plates-formes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Recherchez les procédures de remplacement des modules d'E/S pour votre système de stockage NetApp organisées par famille de plates-formes.  Cette référence fournit des liens directs vers des flux de travail de remplacement de modules d'E/S étape par étape pour les systèmes AFF, ASA et FAS pour vous aider à localiser rapidement la procédure appropriée pour votre modèle spécifique.

[role="tabbed-block"]
====
.Systèmes AFF
--
* link:../a1k/io-module-replace.html["AFF A1K"]
* link:../a20-30-50/io-module-replace.html["AFF A20/30/50"]
* link:../a70-90/io-module-replace.html["AFF A70/90"]
* link:../c30-60/io-module-replace.html["AFF C30/60"]
* link:../c80/io-module-replace.html["AFF C80"]


--
.Systèmes AFX
--
* link:../afx-1k/io-module-replace.html["AFX A1K"]


--
.Systèmes ASA
--
* link:../asa-r2-a1k/io-module-replace.html["ASA A1K"]
* link:../asa-r2-a20-30-50/io-module-replace.html["ASA A20/30/50"]
* link:../asa-r2-70-90/io-module-replace.html["ASA 70/90"]
* link:../asa-r2-c30/io-module-replace.html["ASA C30"]


--
.Systèmes FAS
--
* link:../fas50/io-module-replace.html["FAS50"]
* link:../fas-70-90/io-module-replace.html["FAS70/90"]


--
.Systèmes d'étagères
--
* link:../ns224/service-replace-io-module.html["NS224"]
* link:../nx224/service-replace-io-module.html["NX224"]


--
====