---
sidebar: sidebar 
permalink: fru-reference/nvdimm-fru-links.html 
keywords: NVDIMM, field replaceable units, FRU, NVDIMM replacement 
summary: Recherchez les procédures de remplacement NVDIMM pour votre système de stockage NetApp organisées par famille de plates-formes.  Cette référence fournit des liens directs vers des flux de travail de remplacement NVDIMM étape par étape pour les systèmes AFF, ASA et FAS pour vous aider à localiser rapidement la procédure appropriée pour votre modèle spécifique. 
---
= Procédures de remplacement des NVDIMM par famille de plateformes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Recherchez les procédures de remplacement NVDIMM pour votre système de stockage NetApp organisées par famille de plates-formes.  Cette référence fournit des liens directs vers des flux de travail de remplacement NVDIMM étape par étape pour les systèmes AFF, ASA et FAS pour vous aider à localiser rapidement la procédure appropriée pour votre modèle spécifique.

[role="tabbed-block"]
====
.Systèmes AFF
--
* link:../a320/nvdimm-replace.html["AFF A320"]
* link:../a400/nvdimm-replace.html["AFF A400"]
* link:../a800/nvdimm-replace.html["AFF A800"]
* link:../c400/nvdimm-replace.html["AFF C400"]
* link:../c800/nvdimm-replace.html["AFF C800"]


--
.Systèmes AFX
--
* link:../afx-1k/nvdimm-battery-replace.html["AFX A1K"]


--
.Systèmes ASA
--
* link:../asa400/nvdimm-replace.html["ASA A400"]
* link:../asa800/nvdimm-replace.html["ASA A800"]
* link:../asa-c400/nvdimm-replace.html["ASA C400"]
* link:../asa-c800/nvdimm-replace.html["ASA C800"]


--
.Systèmes FAS
--
* link:../fas8300/nvdimm-replace.html["FAS8300"]


--
====