---
sidebar: sidebar 
permalink: fru-reference/nvram-module-fru-links.html 
keywords: NVRAM module, field replaceable units, FRU, NVRAM module replacement 
summary: Recherchez les procédures de remplacement des modules NVRAM pour votre système de stockage NetApp organisées par famille de plates-formes.  Cette référence fournit des liens directs vers des flux de travail de remplacement de module NVRAM étape par étape pour les systèmes AFF, ASA et FAS pour vous aider à localiser rapidement la procédure appropriée pour votre modèle spécifique. 
---
= Procédures de remplacement des modules NVRAM par famille de plateformes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Recherchez les procédures de remplacement des modules NVRAM pour votre système de stockage NetApp organisées par famille de plates-formes.  Cette référence fournit des liens directs vers des flux de travail de remplacement de module NVRAM étape par étape pour les systèmes AFF, ASA et FAS pour vous aider à localiser rapidement la procédure appropriée pour votre modèle spécifique.

[role="tabbed-block"]
====
.Systèmes AFF
--
* link:../a1k/nvram-replace.html["AFF A1K"]
* link:../a70-90/nvram-replace.html["AFF A70/90"]
* link:../a700/nvram-module-or-nvram-dimm-replacement.html["AFF A700"]
* link:../a700s/nvram-or-nvram-dimm-replacement.html["AFF A700s"]
* link:../a900/nvram_module_or_nvram_dimm_replacement.html["AFF A900"]
* link:../c80/nvram-replace.html["AFF C80"]


--
.Systèmes ASA
--
* link:../asa900/nvram_module_or_nvram_dimm_replacement.html["ASA A900"]
* link:../asa-r2-a1k/nvram-replace.html["ASA A1K"]
* link:../asa-r2-70-90/nvram-replace.html["ASA 70/90"]


--
.Systèmes FAS
--
* link:../fas-70-90/nvram-replace.html["FAS70/90"]
* link:../fas9000/nvram-module-or-nvram-dimm-replacement.html["FAS9000"]
* link:../fas9500/nvram_module_or_nvram_dimm_replacement.html["FAS9500"]


--
====