---
sidebar: sidebar 
permalink: fru-reference/pci-cards-fru-links.html 
keywords: PCI cards, risers, field replaceable units, FRU, PCI replacement 
summary: Recherchez les procédures de remplacement des cartes PCI et des risers pour votre système de stockage NetApp organisées par famille de plates-formes.  Cette référence fournit des liens directs vers des flux de travail de remplacement étape par étape des cartes PCI et des risers pour les systèmes AFF, ASA et FAS pour vous aider à localiser rapidement la procédure appropriée pour votre modèle spécifique. 
---
= Procédures de remplacement des cartes et risers PCI par famille de plateformes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Recherchez les procédures de remplacement des cartes PCI et des risers pour votre système de stockage NetApp organisées par famille de plates-formes.  Cette référence fournit des liens directs vers des flux de travail de remplacement étape par étape des cartes PCI et des risers pour les systèmes AFF, ASA et FAS pour vous aider à localiser rapidement la procédure appropriée pour votre modèle spécifique.

[role="tabbed-block"]
====
.Systèmes AFF
--
* link:../a300/pci-cards-and-risers-replace.html["AFF A300"]
* link:../a320/pci-cards-and-risers-replace.html["AFF A320"]
* link:../a400/pci-cards-and-risers-replace.html["AFF A400"]
* link:../a700/pci-cards-and-risers-replace.html["AFF A700"]
* link:../a700s/pci-cards-and-risers-replace.html["AFF A700s"]
* link:../a800/pci-cards-and-risers-replace.html["AFF A800"]
* link:../c400/pci-cards-and-risers-replace.html["AFF C400"]
* link:../c800/pci-cards-and-risers-replace.html["AFF C800"]


--
.Systèmes ASA
--
* link:../asa400/pci-cards-and-risers-replace.html["ASA A400"]
* link:../asa800/pci-cards-and-risers-replace.html["ASA A800"]
* link:../asa-c400/pci-cards-and-risers-replace.html["ASA C400"]
* link:../asa-c800/pci-cards-and-risers-replace.html["ASA C800"]


--
.Systèmes FAS
--
* link:../fas2800/pci-cards-and-risers-replace.html["FAS2800"]
* link:../fas8200/pci-cards-and-risers-replace.html["FAS8200"]
* link:../fas8300/pci-cards-and-risers-replace.html["FAS8300"]
* link:../fas9000/pci-cards-and-risers-replace.html["FAS9000"]


--
====