---
sidebar: sidebar 
permalink: fru-reference/system-management-fru-links.html 
keywords: system management module, field replaceable units, FRU, system management replacement 
summary: Recherchez les procédures de remplacement des modules de gestion système pour votre système de stockage NetApp organisées par famille de plates-formes.  Cette référence fournit des liens directs vers des flux de travail de remplacement de modules de gestion système étape par étape pour les systèmes AFF, ASA et FAS pour vous aider à localiser rapidement la procédure appropriée pour votre modèle spécifique. 
---
= Procédures de remplacement des modules de gestion du système par famille de plates-formes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Recherchez les procédures de remplacement des modules de gestion système pour votre système de stockage NetApp organisées par famille de plates-formes.  Cette référence fournit des liens directs vers des flux de travail de remplacement de modules de gestion système étape par étape pour les systèmes AFF, ASA et FAS pour vous aider à localiser rapidement la procédure appropriée pour votre modèle spécifique.

[role="tabbed-block"]
====
.Systèmes AFF
--
* link:../a1k/system-management-replace.html["AFF A1K"]
* link:../a70-90/system-management-replace.html["AFF A70/90"]
* link:../c80/system-management-replace.html["AFF C80"]


--
.Systèmes ASA
--
* link:../asa-r2-a1k/system-management-replace.html["ASA A1K"]
* link:../asa-r2-70-90/system-management-replace.html["ASA 70/90"]


--
.Systèmes FAS
--
* link:../fas-70-90/system-management-replace.html["FAS70/90"]


--
====