---
permalink: platform-supplemental/42u-1280mm-remove-door.html 
sidebar: sidebar 
keywords: remove, system, cabinet, door, side, panel, illuminate, badge, component, reverse, door, remove the system cabinet door 
summary: 'Vous devez retirer la porte et les panneaux latéraux de l"armoire du système pour déplacer le badge et les composants éclairés, et pour inverser la porte.' 
---
= Retirez la porte de l'armoire système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez retirer la porte et les panneaux latéraux de l'armoire du système pour déplacer le badge et les composants éclairés, et pour inverser la porte.

. Ouvrez la porte de l'armoire système si elle n'est pas déjà ouverte.
. Effectuez l'action appropriée selon que vos armoires sont connectées ou non au kit d'interconnexion.
+
[cols="1,2"]
|===
| Si votre armoire système est... | Alors... 


 a| 
Non connecté à une autre armoire système
 a| 
Passez à l'étape suivante.



 a| 
Connecté à une autre armoire système à l'aide d'un kit d'interconnexion
 a| 
Retirez les quatre supports du kit d'interconnexion et posez les supports et les vis en lieu sûr.

|===
. Déverrouillez les deux panneaux latéraux, débranchez les fils de mise à la terre des panneaux latéraux, puis retirez-les et mettez-les de côté.
. Débranchez le fil de mise à la terre de la cosse de mise à la terre située en haut de la porte.
. Dévissez la cosse de mise à la terre et le câble du châssis de l'armoire du système et mettez-le de côté.
. Dévissez l'ensemble de cosses de mise à la terre de la porte de l'armoire du système et mettez-le de côté.
. Soulevez l'axe de charnière supérieur jusqu'à ce qu'il se dégage du fond de la charnière.
. Inclinez doucement le haut de la porte pour l'éloigner du cadre de l'armoire système, puis libérez la goupille de charnière.
. Soulevez la porte pour la dégager de la charnière inférieure et mettez la porte de côté.

