---
permalink: platform-supplemental/42u-1280mm-power-on.html 
sidebar: sidebar 
keywords: connect, system, component, pdu, cable, ac, power, source, cabinet, power on the system cabinet 
summary: 'Vous devez connecter les composants du système aux PDU, acheminer les câbles de la PDU vers les sources d"alimentation CA, les connecter aux sources d"alimentation et mettre le système sous tension.' 
---
= Mettez l'armoire système sous tension
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connecter les composants du système aux PDU, acheminer les câbles de la PDU vers les sources d'alimentation CA, les connecter aux sources d'alimentation et mettre le système sous tension.


IMPORTANT: Pour éviter une panne du système en cas de défaillance d'une unité de distribution électrique, ne branchez pas les deux câbles d'alimentation d'un composant dans une unité de distribution électrique. Répartissez la charge sur le PDS qui sont branchés sur différents circuits, comme illustré.

Vous devez disposer de circuits d'alimentation séparés pour chaque PDU de votre armoire système.

. Connectez votre équipement aux PDU :
+
.. Connectez les alimentations du contrôleur à différentes PDU connectées à différentes sources d'alimentation.
.. Connectez les alimentations du tiroir disque à différentes PDU connectées à différentes sources d'alimentation.
.. Connectez toute alimentation de commutateur à différentes PDU connectées à différentes sources d'alimentation.
+
image::../media/cabinet_power_cabling_IEOPS-1320.svg[Câblage de l'alimentation de l'armoire IEOPS 1320]

+
Faites passer les câbles d'alimentation de la PDU par l'une des ouvertures suivantes dans l'armoire système :

+
*** Le haut de l'armoire système
*** Entre le bas de la porte arrière et le châssis de l'armoire du système
*** Par l'ouverture au sol et sous l'armoire du système




. Coupez les interrupteurs d'alimentation ou les disjoncteurs des unités de distribution d'alimentation.
. Branchez chaque câble d'alimentation de l'unité de distribution d'alimentation sur des sources d'alimentation CA individuelles situées sur des circuits CA distincts.
. Mettez les commutateurs d'alimentation ou les disjoncteurs sous tension aux PDU.
. Mettez vos composants sous tension, puis démarrez le système.
. Fermez et verrouillez les portes de l'armoire du système.

