---
permalink: platform-supplemental/42u-1280mm-features.html 
sidebar: sidebar 
keywords: system, cabinet, side, panel, front, rear, door, bolt-down, kit, optional, interconnect, pdu, equipment, integrate, cable, management, system, feature, system cabinet feature 
summary: 'L"armoire système se compose de panneaux latéraux, de portes avant et arrière, d"un kit de fixation en option, d"un kit d"interconnexion en option, d"unités de distribution d"alimentation pour votre équipement et d"un système de gestion des câbles intégré.' 
---
= Caractéristiques de l'armoire système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'armoire système se compose de panneaux latéraux, de portes avant et arrière, d'un kit de fixation en option, d'un kit d'interconnexion en option, d'unités de distribution d'alimentation pour votre équipement et d'un système de gestion des câbles intégré.

[cols="1,2"]
|===
| Fonction | Description 


 a| 
Panneaux latéraux
 a| 
Les armoires du système sont dotées de panneaux latéraux verrouillables, amovibles et interchangeables.



 a| 
Portes avant et arrière perforées
 a| 
Les armoires système sont équipées de portes avant et arrière amovibles avec mécanisme de déverrouillage rapide. La porte avant est réversible et les portes arrière sont divisées. Les deux portes sont perforées pour le refroidissement.



 a| 
Clé commune
 a| 
Cette clé déverrouille les portes avant, les portes arrière et les panneaux latéraux.



 a| 
Kit de pièces de rechange
 a| 
Ce kit se trouve à l'intérieur de l'armoire système, fixé à la porte de l'armoire. Il contient les composants suivants :

* Quatre vis pilotes Phillips 10-32 x 0.75 pouces
* Quatre écrous à cage de 10-32
* Un outil d'insertion d'écrou à cage
* Deux copies de clé principale




 a| 
Accès par câble
 a| 
Les passages de câbles sont intégrés en haut et en bas de l'armoire, ainsi qu'entre le bas de la porte arrière et le châssis.



 a| 
Gestion des câbles
 a| 
Le crochet de gestion des câbles et le cerclage de boucle sont fixés au cadre de l'armoire du système à intervalles égaux.



 a| 
Rails de support
 a| 
Le nombre de rails de support que vous recevez dépend de votre configuration. L'armoire système vide est livrée sans rails de support installés.

* Pour les armoires système configurées, un kit de rails fixes est livré avec l'armoire système afin de prendre en charge les supports de fixation arrière 80xx, FAS8200 et DS4486.
* Les armoires du système d'expédition rapide ne comprennent pas le kit de rails fixes supplémentaire.




 a| 
Panneaux d'obturation
 a| 
Le nombre et la taille des panneaux de masquage que vous recevez dépendent de votre configuration. L'armoire système vide est livrée sans panneaux d'obturation.



 a| 
Kit de boulon
 a| 
Ce kit en option vous permet de fixer l'armoire du système au sol du centre de données. Le kit n'est pas destiné à la stabilité sismique.

* Quatre supports boulonnés
* Quatre supports d'entretoise
* Six vis à tête hexagonale M8 x 20 mm et rondelles




 a| 
Kit d'interconnexion
 a| 
Ce kit facultatif vous permet de connecter plusieurs armoires système l'une à l'autre.

* Supports d'interconnexion
+
** Un jeu de quatre supports d'interconnexion pour connecter les armoires système avec les panneaux latéraux
** Un jeu de quatre supports d'interconnexion pour connecter les armoires système avec les panneaux latéraux


* Quatre vis Torx-30 M12x20 utilisées dans l'armoire du système avec les panneaux latéraux.
* Huit vis à tête fraisée Torx-30 M6x10 utilisées dans l'armoire du système avec les panneaux latéraux.




 a| 
Kit de rails de support
 a| 
Si vous avez commandé des rails de support supplémentaires avec votre armoire système, chaque kit contient un rail de support gauche et droit.


NOTE: Les rails et le kit de support sont conçus pour ne monter que l'armoire système 42U NetApp 1280 mm. N'utilisez pas les rails ou un kit de rails provenant d'autres armoires système car ils ne sont pas conçus pour être utilisés dans l'armoire système 42U de 1280 mm.

* Un rail de support gauche et droit
* Deux vis par rail pour fixer le rail au châssis de l'armoire système




 a| 
Clé à molette
 a| 
La clé en forme de croissant est utilisée pour déposer les supports de fixation sur la palette d'emballage, régler les pieds de mise à niveau de l'armoire du système et installer les supports de kit boulonnés, le cas échéant.

|===