---
permalink: platform-supplemental/42u-1280mm-power-on.html 
sidebar: sidebar 
keywords: connect, system, component, pdu, cable, ac, power, source, cabinet, power on the system cabinet 
summary: 'Vous devez connecter les composants du système aux PDU, acheminer les câbles de la PDU vers les sources d"alimentation CA, les connecter aux sources d"alimentation et mettre le système sous tension.' 
---
= Mettez l'armoire système sous tension
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connecter les composants du système aux PDU, acheminer les câbles de la PDU vers les sources d'alimentation CA, les connecter aux sources d'alimentation et mettre le système sous tension.

Vous devez disposer de circuits d'alimentation séparés pour chaque PDU de votre armoire système.

. Connectez votre équipement aux PDU, en vous assurant de connecter les alimentations de chaque composant à une PDU située de part et d'autre de l'armoire système.
. Faites passer les câbles d'alimentation de la PDU par une ouverture dans l'armoire système.
+
Utilisez l'une des ouvertures suivantes :

+
** Le haut de l'armoire système
** Entre le bas de la porte arrière et le châssis de l'armoire du système
** Par l'ouverture au sol et sous l'armoire du système


. Coupez les interrupteurs d'alimentation ou les disjoncteurs des unités de distribution d'alimentation.
. Branchez chaque câble d'alimentation de l'unité de distribution d'alimentation sur des sources d'alimentation CA individuelles situées sur des circuits CA distincts.
. Mettez les commutateurs d'alimentation ou les disjoncteurs sous tension aux PDU.
. Mettez vos composants sous tension, puis démarrez le système.
. Fermez et verrouillez les portes de l'armoire du système.

