---
permalink: platform-supplemental/sldiag-device-failure-diagnostics.html 
sidebar: sidebar 
keywords: run, diagnostic, help, access, device, intermittent, device, unavailable, storage, system, failure, run device failure diagnostic 
summary: 'L"exécution de diagnostics peut vous aider à déterminer pourquoi l"accès à un périphérique spécifique devient intermittent ou pourquoi le périphérique devient indisponible dans votre système de stockage.' 
---
= Exécutez les diagnostics d'échec du périphérique
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'exécution de diagnostics peut vous aider à déterminer pourquoi l'accès à un périphérique spécifique devient intermittent ou pourquoi le périphérique devient indisponible dans votre système de stockage.

. À l'invite du système de stockage, passez à l'invite DU CHARGEUR : `halt`
. Entrez la commande suivante à l'invite DU CHARGEUR : `boot_diags`
+

NOTE: Vous devez exécuter cette commande à partir de l'invite DU CHARGEUR pour que les diagnostics au niveau du système fonctionnent correctement. La commande boot_diags lance des pilotes spéciaux spécialement conçus pour les diagnostics au niveau du système.

. Exécutez les tests de diagnostic sur le périphérique, ce qui cause des problèmes en entrant la commande suivante : `sldiag device run [-dev devtype|mb|slotslotnum] [-name device]`
+
** -dev _devtype_ spécifie le type de périphérique à tester.
+
*** `ata` Est un périphérique Advanced Technology Attachment.
*** `bootmedia` est le périphérique de démarrage du système.
*** `cna` Est un adaptateur réseau convergé qui n'est pas connecté à un réseau ou à un périphérique de stockage.
*** `env` spécifications environnementales de la carte mère
*** `fcache` Est l'adaptateur Flash cache, également appelé module d'accélération des performances 2.
*** `fcal` Est un périphérique Fibre Channel-Arbitrated Loop non connecté à un périphérique de stockage ou à un réseau Fibre Channel.
*** `fcvi` Est l'interface virtuelle Fibre Channel non connectée à un réseau Fibre Channel.
*** `interconnect` ou `nvram-ib` est l'interface haute disponibilité.
*** `mem` mémoire système.
*** `nic` Est une carte d'interface réseau non connectée à un réseau.
*** `nvram` Est une mémoire RAM non volatile.
*** `nvmem` Est une solution hybride de NVRAM et de mémoire système.
*** `sas` Est un périphérique SCSI connecté en série non connecté à un tiroir disque.
*** `serviceproc` Est le processeur de service.
*** `storage` Est une interface ATA, FC-AL ou SAS dotée d'un tiroir disque connecté.
*** `toe` Est un moteur de déchargement TCP, un type de NIC.


** `mb` indique que tous les périphériques de la carte mère doivent être testés.
** `lot`_slotnum_ spécifie qu'un périphérique dans un numéro d'emplacement spécifique doit être testé.
** `-name _device_` spécifie une classe et un type de périphérique donnés.


. Afficher l'état du test en entrant la commande suivante : `sldiag device status`
+
Votre système de stockage fournit le résultat suivant pendant que les tests sont en cours d'exécution :

+
[listing]
----
There are still test(s) being processed.
----
+
Une fois tous les tests terminés, la réponse suivante apparaît par défaut :

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
. Identifiez les problèmes matériels en entrant la commande suivante : `sldiag device status [-dev devtype|mb|slotslotnum] [-name _device_] -long -state failed`
+
L'exemple suivant montre comment l'état complet des défaillances résultant du test de l'adaptateur FC-AL est affiché :

+
[listing]
----

*> **sldiag device status fcal -long -state failed**

TEST START ------------------------------------------
DEVTYPE: fcal
NAME: Fcal Loopback Test
START DATE: Sat Jan  3 23:10:56 GMT 2009

STATUS: Completed
Starting test on Fcal Adapter: 0b
Started gathering adapter info.
Adapter get adapter info OK
Adapter fc_data_link_rate: 1Gib
Adapter name: QLogic 2532
Adapter firmware rev: 4.5.2
Adapter hardware rev: 2

Started adapter get WWN string test.
Adapter get WWN string OK wwn_str: 5:00a:098300:035309

Started adapter interrupt test
Adapter interrupt test OK

Started adapter reset test.
Adapter reset OK

Started Adapter Get Connection State Test.
Connection State: 5
Loop on FC Adapter 0b is OPEN

Started adapter Retry LIP test
Adapter Retry LIP OK

ERROR: failed to init adaptor port for IOCTL call

ioctl_status.class_type = 0x1

ioctl_status.subclass = 0x3

ioctl_status.info = 0x0
 Started INTERNAL LOOPBACK:
INTERNAL LOOPBACK   OK
Error Count: 2  Run Time: 70 secs
>>>>> ERROR, please ensure the port has a shelf or plug.
END DATE: Sat Jan  3 23:12:07 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------
----
+
[cols="1,2"]
|===
| Si les tests de diagnostic au niveau du système... | Alors... 


 a| 
A entraîné des échecs de test
 a| 
Déterminer la cause du problème.

.. Quittez le mode maintenance en saisissant la commande suivante : `halt`
.. Procéder à un arrêt correct et débrancher les alimentations.
.. Vérifier que vous avez bien remarqué tous les facteurs à prendre en compte pour l'exécution des diagnostics au niveau du système, que les câbles sont correctement connectés et que les composants matériels sont correctement installés dans le système de stockage.
.. Rebranchez les blocs d'alimentation et mettez le système de stockage sous tension.
.. Répétez les étapes 1 à 5 de _exécution des diagnostics d'échec du périphérique_.




 a| 
Les mêmes échecs de test ont été obtenus
 a| 
Le support technique peut recommander de modifier les paramètres par défaut de certains tests pour vous aider à identifier le problème.

.. Modifiez l'état de sélection d'un périphérique ou d'un type de périphérique spécifique sur votre système de stockage en entrant la commande suivante : `sldiag device modify [-dev _devtype_|mb|slot_slotnum_] [-name device] [-selection _enable|disable|default|only_]`+-`selection _enable|disable|default|only_` permet d'activer, de désactiver, d'accepter la sélection par défaut d'un type de périphérique spécifié ou d'un périphérique nommé, ou d'activer uniquement le périphérique spécifié ou le périphérique nommé en désactivant d'abord tous les autres périphériques.
.. Vérifiez que les tests ont été modifiés en entrant la commande suivante : `sldiag option show`
.. Répétez les étapes 3 à 5 de _exécution des diagnostics d'échec du périphérique_.
.. Une fois que vous avez identifié et résolu le problème, réinitialisez les tests sur leur `default` etats en répétant les sous-étapes 1 et 2.
.. Répétez les étapes 1 à 5 de _exécution des diagnostics d'échec du périphérique_.




 a| 
Ont été achevés sans défaillance
 a| 
Il n'y a aucun problème matériel et votre système de stockage revient à l'invite.

.. Supprimez les journaux d'état en entrant la commande suivante : `sldiag device clearstatus [-dev _devtype_|mb|slot_slotnum_]`
.. Vérifiez que le journal est effacé en entrant la commande suivante : `sldiag device status [-dev _devtype_|mb|slot_slotnum_]`
+
La réponse par défaut suivante est affichée :

+
[listing]
----
SLDIAG: No log messages are present.
----
.. Quittez le mode maintenance en saisissant la commande suivante : `halt`
.. Saisissez la commande suivante à l'invite du chargeur pour démarrer le système de stockage : `boot_ontap`Vous avez terminé les diagnostics au niveau du système.


|===


Si les pannes persistent après avoir répété les étapes, vous devez remplacer le matériel.
