---
permalink: platform-supplemental/sldiag-use-cli-help.html 
sidebar: sidebar 
keywords: command-line, syntax, command, line, name, follow, question, mark, how to use online command-line help 
summary: 'Vous pouvez obtenir de l"aide sur la syntaxe de ligne de commande à partir de la ligne de commande en saisissant le nom de la commande suivie de l"aide ou du point d"interrogation \(?\).' 
---
= Comment utiliser l'aide en ligne de commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez obtenir de l'aide sur la syntaxe de ligne de commande à partir de la ligne de commande en saisissant le nom de la commande suivie de l'aide ou du point d'interrogation (?).

Les polices ou les symboles utilisés dans l'aide de syntaxe sont les suivants :

* *mot clé*
+
Spécifie le nom d'une commande ou d'une option qui doit être saisie comme indiqué.

* *< > (inférieur à, supérieur aux symboles)*
+
Spécifiez que vous devez remplacer la variable identifiée à l'intérieur des symboles par une valeur.

* *| (tuyau)*
+
Indique que vous devez choisir l'un des éléments de chaque côté du tuyau.

* *[ ] (parenthèses)*
+
Indiquer que l'élément à l'intérieur des supports est facultatif.

* *{ } (accolades)*
+
Indiquer que l'élément à l'intérieur des accolades est nécessaire.



Vous pouvez également saisir le point d'interrogation sur la ligne de commande pour obtenir la liste de toutes les commandes disponibles au niveau actuel de l'administration (administrative ou avancée).

L'exemple suivant montre le résultat de la saisie de la commande d'aide en environnement sur la ligne de commande du système de stockage. Le résultat de la commande affiche l'aide relative à la syntaxe des commandes d'environnement.

[listing]
----
toaster> environment help
Usage: environment status |
[status] [shelf [<adapter>]] |
[status] [shelf_log] |
[status] [shelf_stats] |
[status] [shelf_power_status] |
[status] [chassis [all | list-sensors | Fan | Power | Temp | Power Supply | RTC Battery | NVRAM4-temperature-7 | NVRAM4-battery-7]]
----