---
permalink: platform-supplemental/sldiag-system-installation-diagnostics.html 
sidebar: sidebar 
keywords: run, diagnostic, initial, system, installation, identify, version, system-level, diagnostic, support, device, storage, system, successful, hardware, function, properly, run system installation diagnostic 
summary: 'Après une installation initiale du système, vous exécutez des diagnostics pour identifier la version des diagnostics au niveau du système et des périphériques pris en charge sur votre système de stockage, et pour vérifier que l"installation est réussie et que tout le matériel fonctionne correctement.' 
---
= Exécutez les diagnostics d'installation du système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après une installation initiale du système, vous exécutez des diagnostics pour identifier la version des diagnostics au niveau du système et des périphériques pris en charge sur votre système de stockage, et pour vérifier que l'installation est réussie et que tout le matériel fonctionne correctement.

Votre système de stockage doit déjà exécuter Data ONTAP.

. À l'invite du système de stockage, passez à l'invite DU CHARGEUR : `halt`
. Entrez la commande suivante à l'invite DU CHARGEUR : `boot_diags`
+

NOTE: Vous devez exécuter cette commande à partir de l'invite DU CHARGEUR pour que les diagnostics au niveau du système fonctionnent correctement. La commande boot_diags lance des pilotes spéciaux spécialement conçus pour les diagnostics au niveau du système.

. Afficher la version des diagnostics au niveau du système présents sur votre système de stockage en entrant la commande suivante : `sldiag version show`
+
La version est affichée au format Diagnostics du niveau du système X.nn.nn. Le X est une référence alpha et le nn.nn sont des références numériques majeures et mineures, respectivement.

. Identifiez les types de périphériques de votre nouvelle installation système afin de connaître les composants à vérifier en entrant la commande suivante : `sldiag device types`
+
Votre système de stockage affiche certains ou tous les périphériques suivants :

+
** `ata` Est un périphérique Advanced Technology Attachment.
** `bootmedia` est le périphérique de démarrage du système.
** `cna` Est un adaptateur réseau convergé qui n'est pas connecté à un réseau ou à un périphérique de stockage.
** `env` spécifications environnementales de la carte mère
** `fcache` Est l'adaptateur Flash cache, également appelé module d'accélération des performances 2.
** `fcal` Est un périphérique Fibre Channel-Arbitrated Loop non connecté à un périphérique de stockage ou à un réseau Fibre Channel.
** `fcvi` Est l'interface virtuelle Fibre Channel non connectée à un réseau Fibre Channel.
** `interconnect` ou `nvram-ib` est l'interface haute disponibilité.
** mem est la mémoire système.
** `nic` Est une carte d'interface réseau non connectée à un réseau.
** `nvram` Est une mémoire RAM non volatile.
** `nvmem` Est une solution hybride de NVRAM et de mémoire système.
** `sas` Est un périphérique SCSI connecté en série non connecté à un tiroir disque.
** `serviceproc` Est le processeur de service.
** `storage` Est une interface ATA, FC-AL ou SAS dotée d'un tiroir disque connecté.
** `toe` Est un moteur de déchargement TCP, un type de NIC.


. Exécutez tous les tests de diagnostic par défaut sélectionnés sur votre système de stockage en entrant la commande suivante : `sldiag device run`
. Afficher l'état du test en entrant la commande suivante : `sldiag device status`
+
Votre système de stockage fournit le résultat suivant pendant que les tests sont en cours d'exécution :

+
[listing]
----
There are still test(s) being processed.
----
+
Une fois tous les tests terminés, la réponse suivante apparaît par défaut :

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
. Vérifiez qu'il n'y a aucun problème matériel sur votre nouveau système de stockage en entrant la commande suivante : `sldiag device status -long -state failed`
+
L'exemple suivant montre comment l'état complet des défaillances s'affiche dans un test exécuté sans le matériel approprié :

+
[listing]
----

*> **sldiag device status -long -state failed**

TEST START ------------------------------------------
DEVTYPE: nvram_ib
NAME: external  loopback test
START DATE: Sat Jan  3 23:10:55 GMT 2009

STATUS: Completed
ib3a: could not set loopback mode, test failed
END DATE: Sat Jan  3 23:11:04 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------

TEST START ------------------------------------------
DEVTYPE: fcal
NAME: Fcal Loopback Test
START DATE: Sat Jan  3 23:10:56 GMT 2009

STATUS: Completed
Starting test on Fcal Adapter: 0b
Started gathering adapter info.
Adapter get adapter info OK
Adapter fc_data_link_rate: 1Gib
Adapter name: QLogic 2532
Adapter firmware rev: 4.5.2
Adapter hardware rev: 2

Started adapter get WWN string test.
Adapter get WWN string OK wwn_str: 5:00a:098300:035309

Started adapter interrupt test
Adapter interrupt test OK

Started adapter reset test.
Adapter reset OK

Started Adapter Get Connection State Test.
Connection State: 5
Loop on FC Adapter 0b is OPEN

Started adapter Retry LIP test
Adapter Retry LIP OK

ERROR: failed to init adaptor port for IOCTL call

ioctl_status.class_type = 0x1

ioctl_status.subclass = 0x3

ioctl_status.info = 0x0
 Started INTERNAL LOOPBACK:
INTERNAL LOOPBACK   OK
Error Count: 2  Run Time: 70 secs
>>>>> ERROR, please ensure the port has a shelf or plug.
END DATE: Sat Jan  3 23:12:07 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------
----
+
[cols="1,2"]
|===
| Si les tests de diagnostic au niveau du système... | Alors... 


 a| 
Ont été achevés sans défaillance
 a| 
Il n'y a aucun problème matériel et votre système de stockage revient à l'invite.

.. Supprimez les journaux d'état en entrant la commande suivante : `sldiag device clearstatus`
.. Vérifiez que le journal est effacé en entrant la commande suivante : `sldiag device status`
+
La réponse par défaut suivante est affichée :

+
[listing]
----
SLDIAG: No log messages are present.
----
.. Quittez le mode maintenance en saisissant la commande suivante : `halt`
.. Saisissez la commande suivante à l'invite du chargeur pour démarrer le système de stockage : `boot_ontap`Vous avez terminé les diagnostics au niveau du système.




 a| 
A entraîné des échecs de test
 a| 
Déterminer la cause du problème.

.. Quittez le mode maintenance en saisissant la commande suivante : `halt`
.. Procéder à un arrêt correct et débrancher les alimentations.
.. Vérifier que vous avez bien remarqué tous les facteurs à prendre en compte pour l'exécution des diagnostics au niveau du système, que les câbles sont correctement connectés et que les composants matériels sont correctement installés dans le système de stockage.
.. Rebranchez les blocs d'alimentation et mettez le système de stockage sous tension.
.. Répétez les étapes 1 à 7 de _exécution des diagnostics d'installation du système_.


|===

