---
permalink: platform-supplemental/sldiag-introduction.html 
sidebar: sidebar 
keywords: system-level, diagnostic, command-line, interface, test, search, hardware, problem, storage, system, component, operating, identify, faulty, component, introduction, introduction to system-level diagnostic 
summary: 'Les diagnostics au niveau du système proposent une interface de ligne de commandes qui permet de rechercher et de déterminer des problèmes matériels sur les systèmes de stockage pris en charge. Les diagnostics au niveau du système permettent de vérifier qu"un composant spécifique fonctionne correctement ou de vous aider à identifier les composants défectueux.' 
---
= Introduction aux diagnostics au niveau du système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les diagnostics au niveau du système proposent une interface de ligne de commandes qui permet de rechercher et de déterminer des problèmes matériels sur les systèmes de stockage pris en charge. Les diagnostics au niveau du système permettent de vérifier qu'un composant spécifique fonctionne correctement ou de vous aider à identifier les composants défectueux.

Les diagnostics au niveau du système sont uniquement disponibles pour les systèmes de stockage pris en charge. La saisie des diagnostics au niveau du système au niveau de l'interface de ligne de commande de systèmes de stockage non pris en charge génère un message d'erreur.

Vous exécutez des diagnostics au niveau du système après l'une des situations de dépannage courantes suivantes :

* Installation initiale du système
* Ajout ou remplacement de composants matériels
* Incident sur le système causé par une défaillance matérielle non identifiée
* L'accès à un dispositif spécifique devient intermittent ou le dispositif devient indisponible
* Le temps de réponse du système est léthargique


Pour exécuter des diagnostics au niveau du système, vous devez déjà exécuter Data ONTAP car vous devez accéder à l'option *Maintenance mode boot* dans Data ONTAP. Il existe plusieurs approches pour obtenir cette option, mais il s'agit de l'approche recommandée dans les procédures décrites dans ce guide. Certains composants matériels de votre système peuvent nécessiter une approche spécifique, et cela sera documenté dans le dépliant sur les unités remplaçables sur site (FRU) applicable. Ce guide ne fournit pas de définitions détaillées des commandes, sous-commandes, tests ou conditions spécifiques.

Une fois la commande saisie, les tests exécutés en arrière-plan et le résultat réussi ou échoué des tests sont consignés dans le journal interne de la mémoire, dont la taille est fixe. Certains tests sont des utilitaires qui indiquent simplement terminé plutôt que réussi ou échoué. Après avoir exécuté les tests appropriés, les procédures décrites dans ce guide vous aident à générer un rapport d'état. Une fois que les résultats des tests ont réussi à réaliser les diagnostics au niveau du système, il est recommandé d'effacer le journal.

En cas d'échec des tests, les rapports d'état aideront le support technique à faire les recommandations appropriées. La défaillance peut être résolue en réinstallant la FRU, en vérifiant que les câbles sont connectés, ou en activant des tests spécifiques recommandés par le support technique, puis en réexécutant ces tests. Si la panne ne peut pas être résolue, il y a une défaillance matérielle et le matériel concerné doit être remplacé.

Aucun message d'erreur ne nécessite de définitions ou d'explications supplémentaires.
