---
permalink: a320/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, diagnostic, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, run diagnostics, complete the replacement process 
summary: 'Déplacez les ventilateurs, les disques durs et le module de contrôleur ou les modules du châssis défaillant vers le nouveau châssis, puis remplacez le châssis douteux par le rack d"équipement ou l"armoire système avec le nouveau châssis du même modèle que le châssis douteux.' 
---
= Remplacement du matériel : AFF A320
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Déplacez les ventilateurs, les disques durs et le module de contrôleur ou les modules du châssis défaillant vers le nouveau châssis, puis remplacez le châssis douteux par le rack d'équipement ou l'armoire système avec le nouveau châssis du même modèle que le châssis douteux.



== Étape 1 : retirez les modules de contrôleur

Pour remplacer le châssis, vous devez retirer les modules de contrôleur de l'ancien châssis.

. Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
. Libérez les dispositifs de retenue du câble d'alimentation, puis débranchez les câbles des blocs d'alimentation.
. Desserrez le crochet et la bride de boucle qui relient les câbles au périphérique de gestion des câbles, puis débranchez les câbles système et les SFP (si nécessaire) du module de contrôleur, en maintenant une trace de l'emplacement où les câbles ont été connectés.
+
Laissez les câbles dans le périphérique de gestion des câbles de sorte que lorsque vous réinstallez le périphérique de gestion des câbles, les câbles sont organisés.

. Retirez et mettez de côté les dispositifs de gestion des câbles des côtés gauche et droit du module de contrôleur.
. Retirer le module de contrôleur du châssis :
+
.. Insérez l'index dans le mécanisme de verrouillage de chaque côté du module de contrôleur.
.. Appuyez sur la languette orange située sur la partie supérieure du mécanisme de verrouillage jusqu'à ce qu'elle se dégage de la goupille de verrouillage du châssis.
+
Le crochet du mécanisme de verrouillage doit être presque vertical et doit être dégagé de l'axe du châssis.

.. Tirez doucement le module de contrôleur de quelques pouces vers vous pour pouvoir saisir les côtés du module de contrôleur.
.. A l'aide des deux mains, tirez doucement le module de contrôleur hors du châssis et posez-le sur une surface plane et stable.


. Répétez ces étapes pour l'autre module de contrôleur du châssis.




== Étape 2 : déplacer les ventilateurs

Pour déplacer les modules de ventilation vers le châssis de remplacement lors du remplacement du châssis, vous devez effectuer une séquence spécifique de tâches.

. Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
. Retirez le cadre (si nécessaire) à deux mains, en saisissant les ouvertures de chaque côté du cadre, puis en le tirant vers vous jusqu'à ce que le cadre se dégage des goujons à rotule du châssis.
. Appuyez sur le loquet de déverrouillage de la poignée de came du module de ventilateur, puis faites pivoter la poignée de came vers le bas.
+
Le module de ventilation se déplace un peu à l'écart du châssis.

. Tirez le module du ventilateur tout droit hors du châssis, en vous assurant de le soutenir avec votre main libre pour qu'il ne bascule pas hors du châssis.
+

CAUTION: Les modules de ventilation sont courts. Soutenez toujours la partie inférieure du module de ventilation avec votre main libre pour qu'il ne tombe pas brusquement du châssis et vous blesse.

. Mettez le module de ventilation de côté.
. Répétez les étapes précédentes pour les modules de ventilation restants.
. Insérez le module de ventilation dans le châssis de remplacement en l'alignant avec l'ouverture, puis faites-le glisser dans le châssis.
. Appuyez fermement sur la poignée de came du module de ventilateur pour qu'elle soit complètement insérée dans le châssis.
+
La poignée de came se soulève légèrement lorsque le module de ventilateur est complètement en place.

. Faites pivoter la poignée de came vers le haut jusqu'à sa position fermée, en vous assurant que le loquet de déverrouillage de la poignée de came s'enclenche dans la position verrouillée.
+
La LED du ventilateur doit être verte une fois que le ventilateur est assis et a été tournée jusqu'à la vitesse de fonctionnement.

. Répétez ces étapes pour les autres modules de ventilation.




== Étape 3 : remplacer un châssis depuis le rack d'équipement ou l'armoire système

Vous devez retirer le châssis existant du rack ou de l'armoire système de l'équipement avant de pouvoir installer le châssis de remplacement.

. Retirez les vis des points de montage du châssis.
. De deux personnes, faites glisser l'ancien châssis hors des rails du rack dans une armoire système ou un rack d'équipement, puis mettez-le de côté.
. Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
. Deux personnes utilisent pour installer le châssis de remplacement dans le rack ou l'armoire système en guidant le châssis sur les rails de rack d'une armoire système ou d'un rack d'équipement.
. Faites glisser le châssis complètement dans le rack de l'équipement ou l'armoire système.
. Fixez l'avant du châssis sur le rack ou l'armoire système de l'équipement à l'aide des vis que vous avez retirées de l'ancien châssis.
. Si ce n'est déjà fait, installez le cadre.




== Étape 4 : installer les modules de contrôleur

Après avoir installé les modules de contrôleur dans le nouveau châssis, vous devez le démarrer à un état où vous pouvez exécuter le test de diagnostic.

Pour les paires haute disponibilité avec deux modules de contrôleur dans le même châssis, l'ordre dans lequel vous installez le module de contrôleur est particulièrement important, car il tente de redémarrer dès que vous le placez entièrement dans le châssis.

. Alignez l'extrémité du module de contrôleur avec l'ouverture du châssis, puis poussez doucement le module de contrôleur à mi-course dans le système.
+

NOTE: N'insérez pas complètement le module de contrôleur dans le châssis tant qu'il n'y a pas été demandé.

. Recâblage de la console sur le module contrôleur, puis reconnexion du port de gestion.
. Branchez les câbles d'alimentation dans les blocs d'alimentation et réinstallez les dispositifs de retenue des câbles d'alimentation.
. Terminez la réinstallation du module de contrôleur :
+
.. S'assurer que les bras de verrouillage sont verrouillés en position étendue.
.. A l'aide des bras de verrouillage, poussez le module de contrôleur dans la baie du châssis jusqu'à ce qu'il s'arrête.
.. Appuyez sur les languettes orange du haut du mécanisme de verrouillage et maintenez-les enfoncées.
.. Poussez doucement le module contrôleur dans la baie du châssis jusqu'à ce qu'il affleure les bords du châssis.
+

NOTE: Les bras du mécanisme de verrouillage coulissent dans le châssis.

+
Le module de contrôleur commence à démarrer dès qu'il est complètement inséré dans le châssis.

.. Libérer les loquets pour verrouiller le module de contrôleur en place.
.. Recâblage du bloc d'alimentation.
.. Si ce n'est déjà fait, réinstallez le périphérique de gestion des câbles.
.. Interrompre le processus de démarrage normal en appuyant sur `Ctrl-C`.


. Répétez la procédure précédente pour installer le second contrôleur dans le nouveau châssis.

