---
permalink: fas500f/bootmedia-encryption-preshutdown-checks.html 
sidebar: sidebar 
keywords: fas500f, check onboard encryption keys as needed 
summary: 'Avant d"arrêter le contrôleur douteux et de vérifier le statut des clés de cryptage intégrées, vous devez vérifier le statut de ce contrôleur, désactiver le giveback automatique et vérifier quelle version de ONTAP le système fonctionne.' 
---
= Vérifier la prise en charge et l'état des clés de cryptage - FAS500f
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour assurer la sécurité des données sur votre système de stockage, vous devez vérifier la prise en charge et l'état de la clé de cryptage sur votre support de démarrage. Vérifiez si votre version de ONTAP prend en charge NetApp Volume Encryption (NVE) et avant d'arrêter le contrôleur, vérifiez si le gestionnaire de clés est actif.



== Étape 1 : Vérifiez la prise en charge NVE et téléchargez l’image ONTAP appropriée.

Déterminez si votre version ONTAP prend en charge le chiffrement de volume NetApp (NVE) afin de pouvoir télécharger l'image ONTAP appropriée pour le remplacement du support de démarrage.

.Étapes
. Vérifiez si votre version ONTAP prend en charge le chiffrement :
+
`version -v`

+
Si le résultat de cette commande indique `1Ono-DARE`, NVE n'est pas pris en charge par la version de votre cluster.

. Téléchargez l'image ONTAP appropriée en fonction de la prise en charge NVE :
+
** Si NVE est pris en charge : Téléchargez l’image ONTAP avec chiffrement de volume NetApp
** Si NVE n'est pas pris en charge : Téléchargez l'image ONTAP sans chiffrement de volume NetApp
+

NOTE: Téléchargez l'image ONTAP depuis le site de support NetApp vers votre serveur HTTP ou FTP ou vers un dossier local.  Vous aurez besoin de ce fichier image lors de la procédure de remplacement du support de démarrage.







== Étape 2 : Vérifier l’état du gestionnaire de clés et la configuration de sauvegarde

Avant de mettre hors service le contrôleur défectueux, vérifiez la configuration du gestionnaire de clés et sauvegardez les informations nécessaires.

.Étapes
. Déterminez le gestionnaire de clés activé sur votre système :
+
[cols="1a,2a"]
|===
| Version ONTAP | Exécutez cette commande 


 a| 
ONTAP 9.14.1 ou version ultérieure
 a| 
`security key-manager keystore show`

** Si EKM est activé, `EKM` est répertorié dans la sortie de la commande.
** Si OKM est activé, `OKM` est répertorié dans la sortie de la commande.
** Si aucun gestionnaire de clés n'est activé, `No key manager keystores configured` est répertorié dans la sortie de la commande.




 a| 
ONTAP 9.13.1 ou version antérieure
 a| 
`security key-manager show-key-store`

** Si EKM est activé, `external` est répertorié dans la sortie de la commande.
** Si OKM est activé, `onboard` est répertorié dans la sortie de la commande.
** Si aucun gestionnaire de clés n'est activé, `No key managers configured` est répertorié dans la sortie de la commande.


|===
. Selon que votre système dispose ou non d'un gestionnaire de clés, effectuez l'une des opérations suivantes :
+
*Si aucun gestionnaire de clés n'est configuré :*

+
Vous pouvez éteindre en toute sécurité le contrôleur défectueux et procéder à la procédure d'arrêt.

+
*Si un gestionnaire de clés est configuré (EKM ou OKM) :*

+
.. Saisissez la commande de requête suivante pour afficher l'état des clés d'authentification dans votre gestionnaire de clés :
+
`security key-manager key query`

.. Examinez le résultat et vérifiez la valeur dans le `Restored` colonne.  Cette colonne indique si les clés d'authentification de votre gestionnaire de clés (EKM ou OKM) ont été restaurées avec succès.


. Suivez la procédure appropriée en fonction de votre type de responsable clé :
+
[role="tabbed-block"]
====
.Gestionnaire de clés externe (EKM)
--
Suivez ces étapes en fonction de la valeur indiquée. `Restored` colonne.

*Si toutes les touches s'affichent `true` dans la colonne Restauré :*

Vous pouvez éteindre en toute sécurité le contrôleur défectueux et procéder à la procédure d'arrêt.

*Si des clés affichent une valeur autre que `true` dans la colonne Restauré :*

.. Restaurez les clés d'authentification de gestion des clés externes sur tous les nœuds du cluster :
+
`security key-manager external restore`

+
Si la commande échoue, contactez le support NetApp .

.. Vérifiez que toutes les clés d'authentification sont restaurées :
+
`security key-manager key query`

+
Confirmez que le `Restored` affichages en colonne `true` pour toutes les clés d'authentification.

.. Si toutes les clés sont restaurées, vous pouvez éteindre en toute sécurité le contrôleur défectueux et procéder à la procédure d'arrêt.


--
.Gestionnaire de clés intégré Onboard Key Manager (OKM)
--
Suivez ces étapes en fonction de la valeur indiquée. `Restored` colonne.

*Si toutes les touches s'affichent `true` dans la colonne Restauré :*

.. Sauvegardez les informations OKM :
+
... Passer en mode privilège avancé :
+
`set -priv advanced`

+
Entrer `y` lorsqu'on vous invite à continuer.

... Afficher les informations de sauvegarde de la gestion des clés :
+
`security key-manager onboard show-backup`

... Copiez les informations de sauvegarde dans un fichier séparé ou dans votre fichier journal.
+
Vous aurez besoin de ces informations de sauvegarde si vous devez récupérer manuellement OKM lors de la procédure de remplacement.

... Retour au mode administrateur :
+
`set -priv admin`



.. Vous pouvez éteindre en toute sécurité le contrôleur défectueux et procéder à la procédure d'arrêt.


*Si des clés affichent une valeur autre que `true` dans la colonne Restauré :*

.. Synchroniser le gestionnaire de clés intégré :
+
`security key-manager onboard sync`

+
Saisissez la phrase de passe alphanumérique de 32 caractères pour la gestion des clés intégrées lorsque vous y êtes invité.

+

NOTE: Il s'agit de la phrase secrète globale du cluster que vous avez créée lors de la configuration initiale du gestionnaire de clés intégré.  Si vous ne possédez pas cette phrase de passe, contactez l'assistance NetApp .

.. Vérifiez que toutes les clés d'authentification sont restaurées :
+
`security key-manager key query`

+
Confirmez que le `Restored` affichages en colonne `true` pour toutes les clés d'authentification et le `Key Manager` type affiche `onboard` .

.. Sauvegardez les informations OKM :
+
... Passer en mode privilège avancé :
+
`set -priv advanced`

+
Entrer `y` lorsqu'on vous invite à continuer.

... Afficher les informations de sauvegarde de la gestion des clés :
+
`security key-manager onboard show-backup`

... Copiez les informations de sauvegarde dans un fichier séparé ou dans votre fichier journal.
+
Vous aurez besoin de ces informations de sauvegarde si vous devez récupérer manuellement OKM lors de la procédure de remplacement.

... Retour au mode administrateur :
+
`set -priv admin`



.. Vous pouvez éteindre en toute sécurité le contrôleur défectueux et procéder à la procédure d'arrêt.


--
====


.Et la suite ?
Après avoir vérifié la prise en charge et l'état de la clé de cryptage sur le support de démarrage, vous devez link:bootmedia-shutdown.html["arrêter le contrôleur"].
