---
permalink: fas500f/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas500f, replace the chassis 
summary: Vous remplacez un châssis endommagé le nouveau châssis du même modèle que le châssis endommagé. 
---
= Présentation du remplacement de châssis - FAS500f
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour remplacer le châssis, vous devez déplacer le panneau, les modules de contrôleur et les disques NVMe du châssis endommagé vers le châssis de remplacement, puis retirer les châssis douteux du rack ou de l'armoire système et installer le châssis de remplacement à sa place.

Tous les autres composants du système doivent fonctionner correctement ; si ce n'est pas le cas, vous devez contacter le support technique.

* Cette procédure peut être utilisée avec toutes les versions de ONTAP prises en charge par votre système.
* Cette procédure est rédigée en supposant que vous déplacez le panneau, les disques NVMe et les modules de contrôleur sur le nouveau châssis, et que le châssis de remplacement est un nouveau composant de NetApp.
* Cette procédure est perturbatrice. Dans le cas d'un cluster à deux nœuds, la panne totale du service et une panne partielle dans un cluster multinœud sont associés.

