---
permalink: c400/install-videos.html 
sidebar: sidebar 
keywords: aff c400, aff, c400, video, rack, cable, system, manager, guide, setup, initial, configuration, hardware, installation, cabling, perform, end-to-end, software, configuration, hardware installation and cabling, perform end-to-end software configuration 
summary: 'Deux vidéos sont disponibles. L"une montre comment installer et connecter le système, l"autre montrant un exemple d"utilisation de la configuration assistée par System Manager pour effectuer la configuration initiale du système.' 
---
= Vidéos - AFF C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Deux vidéos sont disponibles. L'une montre comment installer et connecter le système, l'autre montrant un exemple d'utilisation de la configuration assistée par System Manager pour effectuer la configuration initiale du système.

Si vous disposez d'une configuration MetroCluster, utilisez le contenu d'installation de MetroCluster.

https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentation MetroCluster"^]



== Vidéo l'une des deux : installation du matériel et câblage

La vidéo suivante montre comment installer et raccorder votre nouveau système.

.Animation - instructions d'installation et de configuration du AFF C400
video::8e392453-beac-4db7-8088-aff1005e1f90[panopto]


== Vidéo deux sur deux : effectuez une configuration logicielle de bout en bout

La vidéo suivante présente une configuration logicielle de bout en bout pour les systèmes exécutant ONTAP 9.2 et versions ultérieures.

video::WAE0afWhj1c?[youtube]