---
permalink: a800/maintain-overview.html 
sidebar: sidebar 
keywords: aff A800 maintenance, maintenance, repairing A800, repairing aff A800, replace aff A800 components, replace aff A800 components 
summary: Maintenance du matériel AFF A800 
---
= Maintenance du matériel AFF A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Entretenez le matériel de votre système de stockage AFF A800 pour garantir une fiabilité à long terme et des performances optimales. Effectuez régulièrement des tâches de maintenance, comme le remplacement des composants défectueux, afin d'éviter les temps d'arrêt et les pertes de données.

Les procédures de maintenance supposent que le système de stockage AFF A800 a déjà été déployé en tant que nœud de stockage dans l'environnement ONTAP .



== Composants du système

Pour le système de stockage AFF A800, vous pouvez effectuer les procédures de maintenance sur les composants suivants.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Support de démarrage - récupération automatique"]
 a| 
Le support de démarrage stocke un ensemble principal et secondaire de fichiers image ONTAP que le système de stockage utilise pour démarrer.  Lors de la récupération automatisée, le système récupère l'image de démarrage à partir du nœud partenaire et exécute automatiquement l'option de menu de démarrage appropriée pour installer l'image sur votre support de démarrage de remplacement. La récupération automatique du support de démarrage est prise en charge uniquement dans ONTAP 9.17.1 et versions ultérieures. Si votre système de stockage exécute une version antérieure d' ONTAP, utilisez l'option link:bootmedia-replace-workflow.html["procédure de récupération de démarrage manuel"] .



 a| 
link:bootmedia-replace-workflow.html["Support de démarrage - récupération manuelle"]
 a| 
Le support de démarrage stocke un ensemble principal et secondaire de fichiers image ONTAP que le système de stockage utilise pour démarrer. Lors de la récupération manuelle, vous démarrez le système de stockage à partir d'une clé USB et restaurez manuellement l'image et la configuration du système de fichiers.  Si votre système de stockage exécute ONTAP 9.17.1 et versions ultérieures, utilisez lelink:bootmedia-replace-workflow-bmr.html["procédure de récupération de démarrage automatisée"] .



 a| 
link:chassis-replace-workflow.html["Châssis"]
 a| 
Le châssis correspond au boîtier physique qui contient tous les composants du contrôleur, tels que le contrôleur/l'unité centrale, l'alimentation et les E/S.



 a| 
link:controller-replace-workflow.html["Contrôleur"]
 a| 
Un contrôleur se compose d'une carte, d'un micrologiciel et d'un logiciel. Il contrôle les entraînements et met en œuvre les fonctions ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Vous devez remplacer un module DIMM (module de mémoire double en ligne) en cas de non-concordance de mémoire, ou si vous avez un module DIMM défectueux.



 a| 
link:drive-replace.html["Lecteur"]
 a| 
Un lecteur est un périphérique qui fournit le support de stockage physique pour les données.



 a| 
link:fan-replace.html["Ventilateur"]
 a| 
Le ventilateur refroidit le contrôleur.



 a| 
link:nvdimm-replace.html["NVDIMM"]
 a| 
Le NVDIMM (module de mémoire double en ligne non volatile) gère le transfert de données de la mémoire volatile vers le stockage non volatile et préserve l'intégrité des données en cas de coupure de courant ou d'arrêt du système.



 a| 
link:nvdimm-battery-replace.html["Batterie NVDIMM"]
 a| 
Une batterie NVDIMM est chargée de maintenir l'alimentation du module NVDIMM.



 a| 
link:pci-cards-and-risers-replace.html["Carte PCIe et risers"]
 a| 
Une carte PCIe (Peripheral Component Interconnect Express) est une carte d'extension qui se branche sur l'emplacement PCIe de la carte mère ou sur des risers branchés sur la carte mère.



 a| 
link:power-supply-replace.html["Alimentation électrique"]
 a| 
Une alimentation électrique fournit une source d'alimentation redondante dans un tiroir contrôleur.



 a| 
link:rtc-battery-replace.html["Pile de l'horloge en temps réel"]
 a| 
Une batterie d'horloge en temps réel conserve les informations relatives à la date et à l'heure du système si l'alimentation est coupée.

|===