---
permalink: a800/overview.html 
sidebar: sidebar 
summary: Spécifications clés du groupe de plateformes A800 
---
= Spécifications clés de AFF A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour le système de stockage AFF A800 dans une seule paire haute disponibilité.  Visitez NetApp Hardware Universe (HWU) pour obtenir les spécifications complètes de ce système de stockage.



== Spécifications clés de AFF A800

* Configuration de la plateforme : paire HA à châssis simple AFF A800
* Capacité brute maximale : 6,6096 Po
* Mémoire : 1280.0000 Go
* Facteur de forme : châssis 4U avec 2 contrôleurs HA et 48 emplacements pour disques
* Version ONTAP : ONTAP: 9.16.1P2
* Emplacements d'extension PCIe : 10
* Version minimale ONTAP : ONTAP 9.4RC1 == Maximums de mise à l'échelle
* Type : NAS ; Paires HA : 12 ; Capacité brute : 79,3 Po / 70,4 PiB ; Mémoire maximale : 15 360 Go
* Type : SAN ; paires HA : 6 ; capacité brute : 39,7 Po / 35,2 PiB ; mémoire maximale : 7 680 Go
* Type : Paire HA ; Capacité brute : 6,6 Po / 5,9 PiB ; Mémoire maximale : 1 280 000




== E/S



=== E/S embarquées

* Protocole : Ethernet 100 Gbps ; Ports : 4




=== E/S totales

* Protocole : Ethernet 100 Gbps ; Ports : 20
* Protocole : Ethernet 25 Gbit/s ; Ports : 16
* Protocole : Ethernet 10 Gbps ; Ports : 32
* Protocole : FC 32 Gbps ; Ports : 32
* Protocole : NVMe/FC 32 Gbit/s ; Ports : 32
* Ports : 0
* Ports : 0
* Protocole : SAS 12 Gbit/s ; Ports : 32




=== Ports de gestion

* Protocole : Ethernet 1 Gbps ; Ports : 4
* Protocole : RS-232 115 Kbps ; Ports : 4
* Protocole : USB 12 Mbps ; Ports : 4




== Prise en charge du réseau de stockage

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NFSv3/RDMA
* NFSv4/RDMA
* NVMe/FC
* NVMe/TCP
* S3
* S3 avec NAS
* PME 2.0
* PME 2.1
* SMB 2.x
* PME 3.0
* PME 3.1
* SMB 3.1.1 == Spécifications de l'environnement système
* Puissance typique : 6626 BTU/h
* Consommation d'énergie dans le pire des cas : 8 417 BTU/h
* Poids : 132,5 lb 60,1 kg
* Hauteur : 4U
* Largeur : 19 pouces conforme à la norme IEC (17,6 pouces 44,7 cm)
* Profondeur : 34,5 po (36,6 po avec support de gestion des câbles)
* Température/altitude/humidité de fonctionnement : 5 °C à 40 °C (41 °F à 104 °F) à une altitude de 3 048 m (10 000 pi) ; humidité relative de 8 % à 90 %, sans condensation
* Température/humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu'à 12 192 m (40 000 pi) 10 % à 95 % d'humidité relative, sans condensation, dans l'emballage d'origine
* Bruit acoustique : Puissance acoustique déclarée (LwAd) : 8,0 Pression acoustique (LpAm) (positions d'observation) : 62,8 dB




== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




== Haute disponibilité

* Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP
* Contrôleurs redondants remplaçables à chaud
* Alimentations redondantes remplaçables à chaud
* Gestion SAS en bande via des connexions SAS pour les étagères externes

