---
permalink: asa-c800/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: asa c800, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Pour restaurer le fonctionnement complet de votre système, vous devez restaurer la configuration NetApp Storage Encryption (si nécessaire), installer les licences pour le nouveau contrôleur et renvoyer la pièce défaillante à NetApp, comme indiqué dans les instructions RMA fournies avec le kit. Contactez l"assistance technique à l"adresse https://mysupport.netapp.com/site/global/dashboard["Support NetApp"], 888-463-8277 (Amérique du Nord), 00-800-44-638277 (Europe) ou +800-800-80-800 (Asie/Pacifique) si vous avez besoin du numéro RMA ou de l"aide supplémentaire pour la procédure de remplacement.' 
---
= Restauration complète du système - ASA C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour restaurer le fonctionnement complet de votre système, vous devez restaurer la configuration NetApp Storage Encryption (si nécessaire), installer les licences pour le nouveau contrôleur et renvoyer la pièce défaillante à NetApp, comme indiqué dans les instructions RMA fournies avec le kit.



== Étape 1 : installer les licences pour le contrôleur de remplacement dans ONTAP

Vous devez installer de nouvelles licences pour le _remplacement_ node si le nœud douteux utilisait des fonctions ONTAP qui requièrent une licence standard (nœud verrouillé). Pour les fonctionnalités avec licences standard, chaque nœud du cluster doit avoir sa propre clé pour cette fonctionnalité.

.Description de la tâche
Jusqu'à ce que vous installiez les clés de licence, les fonctions nécessitant des licences standard restent disponibles pour le _remplacement_ node. Cependant, si le nœud douteux était le seul nœud du cluster avec une licence pour la fonction, aucune modification de configuration de la fonction n'est autorisée. En outre, l'utilisation de fonctions sans licence sur le nœud peut vous mettre hors conformité avec votre contrat de licence. Vous devez donc installer la ou les clés de licence de remplacement sur le _remplacement_ noeud dès que possible.

.Avant de commencer
Les clés de licence doivent être au format à 28 caractères.

Vous disposez d'une période de grâce de 90 jours pour installer les clés de licence. Après la période de grâce, toutes les anciennes licences sont invalidés. Après l'installation d'une clé de licence valide, vous disposez de 24 heures pour installer toutes les clés avant la fin du délai de grâce.

.Étapes
. Si vous avez besoin de nouvelles clés de licence, vous pouvez obtenir ces clés sur le https://mysupport.netapp.com/site/global/dashboard["Site de support NetApp"] Dans la section My support (mon support), sous licences logicielles.
+

NOTE: Les nouvelles clés de licence dont vous avez besoin sont générées automatiquement et envoyées à l'adresse électronique du fichier. Si vous ne recevez pas l'e-mail contenant les clés de licence dans les 30 jours, contactez l'assistance technique.

. Installer chaque clé de licence : `+system license add -license-code license-key, license-key...+`
. Supprimez les anciennes licences, si nécessaire :
+
.. Vérifier si les licences ne sont pas utilisées : `license clean-up -unused -simulate`
.. Si la liste semble correcte, supprimez les licences inutilisées : `license clean-up -unused`






== Étape 2 : vérifier les LIF et enregistrer le numéro de série

Avant de renvoyer le _replace_ node au service, vérifiez que les LIF se trouvent sur leurs ports de rattachement, puis enregistrez le numéro de série du _replace_ node si AutoSupport est activé et réinitialisez le rétablissement automatique.

.Étapes
. Vérifiez que les interfaces logiques sont bien placées sur leur serveur domestique et leurs ports : `network interface show -is-home false`
+
Si des LIFs sont répertoriées comme faux, restaurez-les sur leurs ports de home port : `network interface revert -vserver * -lif *`

. Enregistrez le numéro de série du système auprès du support NetApp.
+
** Si AutoSupport est activé, envoyez un message AutoSupport pour enregistrer le numéro de série.
** Si AutoSupport n'est pas activé, appeler https://mysupport.netapp.com["Support NetApp"] pour enregistrer le numéro de série.


. Si une fenêtre de maintenance AutoSupport a été déclenchée, mettez-la fin à l'aide du `system node autosupport invoke -node * -type all -message MAINT=END` commande.
. Si le retour automatique a été désactivé, réactivez-le : `storage failover modify -node local -auto-giveback true`




== Étape 3 : renvoyer la pièce défaillante à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièces et remplacements"] page pour plus d'informations.
