---
permalink: asa-r2-c30/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa c30, replace the boot media 
summary: 'Avant de remplacer le support de démarrage de votre système de stockage ASA C30, assurez-vous de respecter les exigences et les points à considérer pour un remplacement réussi. Cela inclut la vérification du support de démarrage de remplacement approprié, le bon fonctionnement du port e0S (clé e0M) du contrôleur défectueux et l"activation du gestionnaire de clés intégré (OKM) ou du gestionnaire de clés externe (EKM).' 
---
= Configuration requise pour remplacer le support de démarrage - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système de stockage ASA C30, assurez-vous de respecter les exigences et les points à considérer pour un remplacement réussi. Cela inclut la vérification du support de démarrage de remplacement approprié, le bon fonctionnement du port e0S (clé e0M) du contrôleur défectueux et l'activation du gestionnaire de clés intégré (OKM) ou du gestionnaire de clés externe (EKM).

* Vous devez remplacer le composant défectueux par un composant FRU de remplacement de même capacité que celle reçue de NetApp.
* Vérifiez que le port e0M (clé) du contrôleur défectueux est connecté et n'est pas défectueux.
+
Le port e0M est utilisé pour communiquer entre les deux contrôleurs pendant le processus de récupération de démarrage automatisé.

* Pour OKM, vous avez besoin du contenu du fichier de phrase de passe OKM.
* Pour EKM, vous avez besoin de copies des fichiers suivants à partir du nœud partenaire :
+
** fichier /cfcard/kmip/servers.cfg.
** fichier /cfcard/kmip/certs/client.crt.
** fichier /cfcard/kmip/certs/client.key.
** Fichier /cfcard/kmip/certs/CA.pem.


* Il est essentiel d'appliquer les commandes au contrôleur approprié lorsque vous remplacez le support de démarrage défectueux :
+
** Le _contrôleur défaillant_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le _contrôleur sain_ est le partenaire HA du contrôleur altéré.




.Et la suite
Après avoir examiné la configuration requise pour le support de démarrage, vous link:bootmedia-shutdown-bmr.html["arrêter le contrôleur"].
