---
permalink: asa-r2-c30/io-module-overview.html 
sidebar: sidebar 
keywords: asa c30, replace io module, add io module, hotswap io module 
summary: 'Le système de stockage ASA C30 offre une flexibilité dans l"extension ou le remplacement des modules d"E/S pour améliorer la connectivité et les performances du réseau. L"ajout ou le remplacement d"un module d"E/S est essentiel lors de la mise à niveau des capacités réseau ou de l"adressage d"un module défaillant.' 
---
= Présentation de la maintenance des modules d'E/S - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système de stockage ASA C30 offre une grande flexibilité pour l'extension ou le remplacement des modules d'E/S afin d'améliorer la connectivité et les performances du réseau. L'ajout, le remplacement à chaud ou le remplacement d'un module d'E/S est essentiel pour mettre à niveau les capacités du réseau ou résoudre un problème de module défaillant.

Vous pouvez remplacer un module d'E/S défaillant de votre système de stockage par le même type de module ou par un autre. Vous pouvez échanger à chaud un cluster et un module d'E/S haute disponibilité lorsque votre système de stockage répond à des exigences spécifiques. Vous pouvez également ajouter un module d'E/S à un système de stockage disposant d'emplacements disponibles.

* link:io-module-add.html["Ajoutez un module d'E/S."]
+
L'ajout de modules d'E/S supplémentaires peut améliorer la redondance et garantir que le système de stockage reste opérationnel même en cas de défaillance d'un module d'E/S.

* link:io-module-hotswap.html["Remplacer à chaud un module d'E/S"]
+
Vous pouvez remplacer à chaud certains modules d'E/S par un module d'E/S équivalent afin de rétablir le système de stockage à son état de fonctionnement optimal. Le remplacement à chaud s'effectue sans avoir à effectuer une reprise manuelle.

+
Pour utiliser cette procédure, votre système de stockage doit exécuter ONTAP 9.17.1 ou une version ultérieure et répondre à des exigences système spécifiques.

* link:io-module-replace.html["Remplacez un module d'E/S."]
+
Le remplacement d'un module d'E/S défaillant permet de rétablir l'état de fonctionnement optimal du système de stockage.


