---
permalink: asa-r2-c30/io-module-overview.html 
sidebar: sidebar 
keywords: AFF c30, AFF c60, replace io module 
summary: 'Le système de stockage ASA C30 offre une flexibilité dans l"extension ou le remplacement des modules d"E/S pour améliorer la connectivité et les performances du réseau. L"ajout ou le remplacement d"un module d"E/S est essentiel lors de la mise à niveau des capacités réseau ou de l"adressage d"un module défaillant.' 
---
= Présentation de l'ajout et du remplacement d'un module d'E/S - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système de stockage ASA C30 offre une flexibilité dans l'extension ou le remplacement des modules d'E/S pour améliorer la connectivité et les performances du réseau. L'ajout ou le remplacement d'un module d'E/S est essentiel lors de la mise à niveau des capacités réseau ou de l'adressage d'un module défaillant.

* link:io-module-add.html["Ajoutez un module d'E/S."]
+
L'ajout de modules d'E/S supplémentaires peut améliorer la redondance et garantir que le système de stockage reste opérationnel même en cas de défaillance d'un module d'E/S.

* link:io-module-replace.html["Remplacez un module d'E/S."]
+
Le remplacement d'un module d'E/S défaillant permet de rétablir l'état de fonctionnement optimal du système de stockage.


