---
permalink: fas8200/bootmedia-2n-mcc-switchback.html 
sidebar: sidebar 
keywords: fas8200, switch back aggregate in a two-node metrocluster configuration, manual, manual boot recovery 
summary: 'Effectuez l"opération de basculement MetroCluster sur un système FAS8200 après avoir terminé le remplacement du support de démarrage dans une configuration MetroCluster à deux nœuds. Le système FAS8200 ne prend en charge que les procédures de récupération manuelle du support de démarrage. La récupération automatique du support de démarrage n"est pas prise en charge.' 
---
= Basculez des agrégats à l'arrière dans une configuration MetroCluster à deux nœuds - FAS8200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Effectuez l'opération de basculement MetroCluster sur un système FAS8200 après avoir terminé le remplacement du support de démarrage dans une configuration MetroCluster à deux nœuds. Cette procédure comprend la vérification de l'état des nœuds et des machines virtuelles de stockage (SVM), l'exécution de la commande de retour en arrière et la confirmation que la configuration revient à un état de fonctionnement normal avec des SVM de source synchronisée servant des données à partir de pools de disques locaux.

Le système FAS8200 ne prend en charge que les procédures de récupération manuelle du support de démarrage. La récupération automatique du support de démarrage n'est pas prise en charge.

Cette tâche s'applique uniquement aux configurations MetroCluster à deux nœuds.

.Étapes
. Vérifiez que tous les nœuds sont dans le `enabled` état : `metrocluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. Vérifier que la resynchronisation est terminée sur tous les SVM : `metrocluster vserver show`
. Vérifier que toutes les migrations LIF automatiques effectuées par les opérations de correction ont été effectuées correctement : `metrocluster check lif show`
. Effectuez le rétablissement en utilisant le `metrocluster switchback` utilisez une commande à partir d'un nœud du cluster survivant.
. Vérifiez que l'opération de rétablissement est terminée : `metrocluster show`
+
L'opération de rétablissement s'exécute toujours lorsqu'un cluster est dans `waiting-for-switchback` état :

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
Le rétablissement est terminé une fois les clusters dans `normal` état :

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
Si un rétablissement prend beaucoup de temps, vous pouvez vérifier l'état des lignes de base en cours en utilisant le `metrocluster config-replication resync-status show` commande.

. Rétablir toutes les configurations SnapMirror ou SnapVault.

