---
permalink: fas8200/controller-replace-overview.html 
sidebar: sidebar 
keywords: fas8200, prerequisite, replace the controller module 
summary: 'Vous devez passer en revue les conditions préalables à la procédure de remplacement et sélectionner la version appropriée de votre système d"exploitation ONTAP.' 
---
= Présentation du remplacement du module de contrôleur - FAS8200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez passer en revue les conditions préalables à la procédure de remplacement et sélectionner la version appropriée de votre système d'exploitation ONTAP.

* Tous les tiroirs disques doivent fonctionner correctement.
* Si votre système est un système FlexArray ou dispose d'une licence V_StorageAttach, vous devez vous reporter aux étapes supplémentaires requises avant d'effectuer cette procédure.
* Si votre système se trouve dans une paire haute disponibilité, le contrôleur en bon état doit pouvoir reprendre le contrôleur en cours de remplacement (appelé « contrôleur défectueux »).
* Si votre système est dans une configuration MetroCluster, vous devez passer en revue la section https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Choix de la procédure de récupération correcte"] pour déterminer si vous devez utiliser cette procédure.
+
Si c'est la procédure à suivre, notez que la procédure de remplacement du contrôleur d'un contrôleur dans une configuration MetroCluster à quatre ou huit contrôleurs est identique à celle d'une paire haute disponibilité. Aucune étape spécifique à MetroCluster n'est requise, car la défaillance est limitée à une paire haute disponibilité et les commandes de basculement du stockage peuvent être utilisées pour assurer une continuité de l'activité pendant le remplacement.

* Cette procédure comprend les étapes de réaffectation automatique ou manuelle des disques au contrôleur _replace_, en fonction de la configuration de votre système.
+
Vous devez effectuer la réaffectation du disque selon les instructions de la procédure.

* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.
* Vous devez remplacer un module de contrôleur par un module de contrôleur du même type de modèle. Vous ne pouvez pas mettre à niveau votre système en remplaçant simplement le module de contrôleur.
* Vous ne pouvez pas modifier de disques ou de tiroirs disques dans le cadre de cette procédure.
* Dans cette procédure, le périphérique d'amorçage est déplacé du contrôleur défaillant vers le contrôleur _remplacement_ de sorte que le _remplacement_ contrôleur démarre dans la même version de ONTAP que l'ancien module de contrôleur.
* Toutes les cartes PCIe déplacées de l'ancien module de contrôleur vers le nouveau module de contrôleur ou ajoutées depuis l'inventaire du site client existant doivent être prises en charge par le module de remplacement.
+
https://hwu.netapp.com["NetApp Hardware Universe"]

* Il est important d'appliquer les commandes au cours des étapes suivantes sur les systèmes appropriés :
+
** Le contrôleur _trouble_ est le contrôleur qui est en cours de remplacement.
** Le contrôleur _remplacement_ est le nouveau contrôleur qui remplace le contrôleur défaillant.
** Le contrôleur _Healthy_ est le contrôleur survivant.


* Vous devez toujours capturer la sortie de la console du contrôleur dans un fichier texte.
+
Vous disposez ainsi d'un enregistrement de la procédure afin de pouvoir résoudre tout problème que vous pourriez rencontrer pendant le processus de remplacement.


