---
permalink: afx-1k/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: afx 1k, replace the boot media 
summary: 'Avant de remplacer le support de démarrage de votre système de stockage AFX 1K, assurez-vous de répondre aux exigences nécessaires pour un remplacement réussi.  Cela inclut la vérification que vous disposez du support de démarrage de remplacement approprié, la confirmation qu"il n"y a pas de ports de cluster défectueux sur le contrôleur et la détermination si Onboard Key Manager (OKM) ou External Key Manager (EKM) est activé.' 
---
= Conditions requises pour remplacer le support de démarrage - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système de stockage AFX 1K, assurez-vous de répondre aux exigences nécessaires pour un remplacement réussi.  Cela inclut la vérification que vous disposez du support de démarrage de remplacement approprié, la confirmation qu'il n'y a pas de ports de cluster défectueux sur le contrôleur et la détermination si Onboard Key Manager (OKM) ou External Key Manager (EKM) est activé.

Avant de remplacer le support de démarrage, vérifiez les conditions suivantes.

* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.
* Il est important d'appliquer les commandes au cours de la procédure suivante sur le contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le contrôleur _Healthy_ est le partenaire HA du contrôleur déficient.


* Il ne doit y avoir aucun port de cluster défectueux sur le contrôleur défectueux.


.Et la suite ?
Après avoir examiné les exigences pour remplacer le support de démarrage, vous devezlink:bootmedia-shutdown.html["arrêter le contrôleur"] .
