---
permalink: afx-1k/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: afx 1k, replace the boot media 
summary: 'Avant de remplacer le support de démarrage de votre système de stockage AFX 1K, assurez-vous de respecter les conditions requises pour un remplacement réussi. Cela inclut la vérification que vous disposez du support de démarrage de remplacement adéquat, la confirmation qu"aucun port de cluster du contrôleur n"est défectueux, et la détermination de l"activation du Onboard Key Manager ou de l"External Key Manager.' 
---
= Conditions requises pour remplacer le support de démarrage - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système de stockage AFX 1K, assurez-vous de répondre aux exigences nécessaires pour un remplacement réussi.  Cela inclut la vérification que vous disposez du support de démarrage de remplacement approprié, la confirmation qu'il n'y a pas de ports de cluster défectueux sur le contrôleur et la détermination si Onboard Key Manager (OKM) ou External Key Manager (EKM) est activé.

Avant de remplacer le support de démarrage, vérifiez les conditions suivantes.

[NOTE]
====
NetApp recommande fortement d'activer la journalisation de la console sur les appareils que vous utilisez et de prendre les mesures suivantes lors de cette procédure :

* Laissez AutoSupport activé pendant votre maintenance. Cela permet au support NetApp de recevoir des informations de diagnostic en cas de problème.
* Activez la journalisation des sessions pour toutes les sessions CLI. Cela crée un enregistrement complet de toutes les commandes et des sorties système pendant l'opération de maintenance. Pour savoir comment activer la journalisation des sessions, consultez  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Comment configurer PuTTY pour une connectivité optimale aux systèmes ONTAP"^].


====
* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.
* Il est important d'appliquer les commandes au cours de la procédure suivante sur le contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le contrôleur _Healthy_ est le partenaire HA du contrôleur déficient.


* Il ne doit y avoir aucun port de cluster défectueux sur le contrôleur défectueux.


.Et la suite ?
Après avoir examiné les exigences pour remplacer le support de démarrage, vous devezlink:bootmedia-shutdown.html["arrêter le contrôleur"] .
