---
permalink: afx-1k/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: afx 1k, shutdown the controller 
summary: Arrêtez le contrôleur de votre système de stockage AFX 1K pour éviter la perte de données et garantir la stabilité du système lors du remplacement du châssis. 
---
= Arrêter le contrôleur pour remplacer le châssis - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arrêtez le contrôleur de votre système de stockage AFX 1K pour éviter la perte de données et garantir la stabilité du système lors du remplacement du châssis.

Pour arrêter le contrôleur endommagé, vous devez déterminer l'état du contrôleur et, si nécessaire, effectuer une reprise de basculement de stockage du contrôleur afin que le contrôleur sain continue de fournir les données du stockage du contrôleur endommagé.

.Description de la tâche
* Si vous avez un cluster avec plus de quatre nœuds, il doit être en quorum.  Pour afficher les informations de cluster sur vos nœuds, utilisez le `cluster show` commande.  Pour plus d'informations sur le `cluster show` commande, voirlink:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["Afficher les détails au niveau du nœud dans un cluster ONTAP"^] .
* Si le cluster n'est pas en quorum ou si l'état ou l'éligibilité d'un contrôleur (autre que le contrôleur altéré) s'affiche comme faux, vous devez corriger le problème avant d'arrêter le contrôleur altéré. Voir link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchroniser un nœud avec le cluster"^] .


.Étapes
. Si AutoSupport est activé, supprimez la création automatique de dossier en invoquant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
Le message AutoSupport suivant supprime la création automatique de dossiers pendant deux heures :

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Désactiver le retour automatique depuis la console du contrôleur défaillant :
+
`storage failover modify -node impaired-node -auto-giveback-of false`

+

NOTE: Lorsque vous voyez _Voulez-vous désactiver la restitution automatique ?_, entrez `y` .

+
.. Si vous exécutez la version 9.17.1 ONTAP et que le contrôleur endommagé ne peut pas être redémarré ou est déjà pris en charge, vous devez désactiver la liaison d'interconnexion HA du contrôleur sain avant de démarrer le contrôleur endommagé.  Cela empêche le contrôleur défaillant d'effectuer un retour automatique.
+
`system ha interconnect link off -node healthy-node -link 0`

+
`system ha interconnect link off -node healthy-node -link 1`



. Faites passer le contrôleur douteux à l'invite DU CHARGEUR :
+
[cols="1,2"]
|===
| Si le contrôleur en état de fonctionnement s'affiche... | Alors... 


 a| 
Invite DU CHARGEUR
 a| 
Passez à l'étape suivante.



 a| 
Invite système ou invite de mot de passe
 a| 
Prendre le relais ou arrêter le contrôleur altéré à partir du contrôleur sain :
`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

Le paramètre _-halt true_ amène le nœud altéré à l'invite LOADER.

|===


.Et la suite ?
Après avoir arrêté le contrôleur, vous devez link:chassis-replace-move-hardware.html["remplacez le châssis"].
