---
permalink: afx-1k/chassis-replace-prepare.html 
sidebar: sidebar 
keywords: afx 1k, replace the chassis 
summary: Préparez-vous à remplacer le châssis défectueux de votre système de stockage AFX 1K en identifiant le châssis défectueux, en vérifiant les composants de remplacement et en étiquetant les câbles et les modules de contrôleur. 
---
= Préparation au remplacement du châssis - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Préparez-vous à remplacer le châssis défectueux de votre système de stockage AFX 1K en identifiant le châssis défectueux, en vérifiant les composants de remplacement et en étiquetant les câbles et le module de contrôleur.



== Étape 1 : localisez et surveillez votre système

Vous devez ouvrir une session de console et enregistrer les journaux de sessions pour référence ultérieure, et activer également le voyant d'emplacement du système pour trouver le châssis défectueux.

.Étapes
. Connectez-vous au port série console pour établir une interface avec et surveiller le système.
. Localisez et allumez le voyant d'emplacement du contrôleur :
+
.. Utiliser `system controller location-led show` la commande pour afficher l'état actuel de la LED d'emplacement
.. Réglez l'état du voyant d'emplacement sur « on » :
+
`system controller location-led modify -node _node1_ -state on`

+
Le voyant d'emplacement reste allumé pendant 30 minutes.







== Étape 2 : vérifier les composants de remplacement

Vérifiez que vous avez reçu les composants nécessaires, retirez-les de leur emballage et conservez-les.

.Étapes
. Avant d'ouvrir l'emballage, vous devez regarder l'étiquette d'emballage et vérifier :
+
** Référence du composant.
** Description de la pièce.
** Quantité dans la boîte.


. Retirez le contenu de l'emballage et utilisez l'emballage pour renvoyer le composant défectueux à NetApp.




== Étape 3 : Étiqueter les câbles

Vous devez étiqueter les câbles avant de les retirer des modules d’E/S à l’arrière du système.

.Étapes
. Etiquetez tous les câbles associés au système de stockage. Cela facilite la réactivation plus loin dans cette procédure.
. Si vous n'êtes pas déjà correctement mis à la terre, mettez-vous à la terre.


.Et la suite ?
Une fois que vous êtes prêt à remplacer le matériel de votre châssis AFX 1K, vous devezlink:chassis-replace-shutdown.html["arrêter le contrôleur"] .
