---
permalink: afx-1k/io-module-overview.html 
sidebar: sidebar 
keywords: afx 1k, replace io module 
summary: 'Le système de stockage AFX 1K offre une flexibilité dans l"extension ou le remplacement des modules d"E/S pour améliorer la connectivité et les performances du réseau.  L"ajout ou le remplacement d"un module d"E/S est essentiel lors de la mise à niveau des capacités du réseau ou de la résolution d"un module défaillant.' 
---
= Présentation du module d'ajout et de remplacement d'E/S - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système de stockage AFX 1K offre une flexibilité dans l'extension ou le remplacement des modules d'E/S pour améliorer la connectivité et les performances du réseau.  L'ajout ou le remplacement d'un module d'E/S est essentiel lors de la mise à niveau des capacités du réseau ou de la résolution d'un module défaillant.

Vous pouvez remplacer un module d'E/S défectueux dans votre système de stockage AFX 1K par le même type de module d'E/S ou par un autre type de module d'E/S.  Vous pouvez également ajouter un module d’E/S dans un système avec des emplacements vides.

* link:io-module-add.html["Ajoutez un module d'E/S."]
+
L'ajout de modules supplémentaires peut améliorer la redondance, ce qui permet de garantir que le système reste opérationnel même en cas de défaillance d'un module.

* link:io-module-replace.html["Remplacez un module d'E/S."]
+
Le remplacement d'un module d'E/S défaillant permet de restaurer l'état de fonctionnement optimal du système.



.Numérotation des connecteurs d'E/S.
Les emplacements d'E/S du contrôleur AFX 1K sont numérotés de 1 à 11, comme indiqué dans l'illustration suivante.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numérotation des emplacements sur un contrôleur AFX 1K]
