---
permalink: asa150/install-videos.html 
sidebar: sidebar 
keywords: asa a150, a150, asa, asa a220, video, rack, cable, system, manager, guided, setup, configuration 
summary: 'Deux vidéos sont disponibles. L"une montre comment installer et connecter le système, l"autre montrant un exemple d"utilisation de la configuration assistée par System Manager pour effectuer la configuration initiale du système.' 
---
= Étapes vidéo - ASA A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez les vidéos suivantes pour apprendre à installer et à connecter les câbles du système et à effectuer la configuration initiale du système.

Si vous disposez d'une configuration MetroCluster, utilisez https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentation MetroCluster"^].

*Avertissement :* si votre système est installé avec ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 ou ONTAP 9.15.1 - 9.15.1P2 et que votre système contient au moins 10 lecteurs SSD internes, vous devez prendre des mesures supplémentaires pour préparer le système à l'installation. Voir problème  https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173["ONTAP-285173 - ADP ne laisse pas de partition racine de rechange sur un AFF A150 avec 10 disques internes ou plus"^].

Installation du matériel et câblage:: La vidéo suivante montre comment installer et câbler votre système.


.Animation - installation et configuration d'un AFF A150
video::561d941a-f387-4eb9-a10a-afb30029eb36[panopto]

NOTE: Le ASA A150 utilise la même procédure d'installation que le système AFF A150.
