---
permalink: asa150/install-quick-guide.html 
sidebar: sidebar 
keywords: asa a150, a150, asa, quick, guide, graphic, instructions, install, rack, cable 
summary: 'Ce guide fournit des instructions graphiques pour une installation type de votre système, du rack au câblage, jusqu"à l"introduction initiale du système.' 
---
= Guide rapide - ASA A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
*Avertissement :* si votre système est installé avec ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 ou ONTAP 9.15.1 - 9.15.1P2 et que votre système contient au moins 10 lecteurs SSD internes, vous devez prendre des mesures supplémentaires pour préparer le système à l'installation. Voir problème  https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173["ONTAP-285173 - ADP ne laisse pas de partition racine de rechange sur un AFF A150 avec 10 disques internes ou plus"^].

Les instructions d'installation et de configuration fournissent des instructions graphiques pour une installation standard de votre système, des racks au câblage, en passant par la présentation initiale du système. Utilisez ce guide si vous connaissez bien l'installation des systèmes NetApp.

Utilisez le lien : link:../media/PDF/Jan_2024_Rev2_AFFA150_ISI_IEOPS-1480.pdf["Instructions d'installation et de configuration du système AFF A150"^]


NOTE: Le ASA A150 utilise la même procédure d'installation que le système AFF A150.
