---
permalink: asa150/overview.html 
sidebar: sidebar 
keywords: ASA A150 specifications, ASA A150 specs, NetApp ASA A150, ASA A150 hardware 
summary: Spécifications clés du système de stockage ASA A150 
---
= Spécifications clés de ASA A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour l' ASA A150.  Visite https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) pour une liste complète des spécifications ASA A150 .  Cette page reflète une seule paire à haute disponibilité.



=== Spécifications clés de ASA A150

Configuration de la plateforme : ASA A150 UTA2, châssis simple, paire HA

Capacité brute maximale : 0,5472 Po

Mémoire : 64.0000 Go

Facteur de forme : châssis 2U avec 2 contrôleurs HA et 24 emplacements pour disques

Version ONTAP : b_startONTAP : 9.16.1P2b_end

Emplacements d'extension PCIe :

Version minimale ONTAP : ONTAP 9.13.1



=== Maximums de mise à l'échelle

|===


| Type | Paires HA | Capacité brute | Mémoire maximale 


| NAS |  |  |  


| SAN | 6 | 3,3 Po / 2,9 PiB | 384 Go 


| Paire haute disponibilité |  | 0,5 Po / 0,5 PiB | 64,0000 
|===


=== IO



==== E/S embarquées

|===


| Protocole | Ports 


| Ethernet 10 Gbit/s | 12 


| FC 16 Gbit/s | 8 


| SAS 12 Gbit/s | 4 
|===


==== E/S totales

|===


| Protocole | Ports 


| Ethernet 10 Gbit/s | 12 


| FC 16 Gbit/s | 8 


| SAS 12 Gbit/s | 4 
|===


==== Ports de gestion

|===


| Protocole | Ports 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 2 
|===


=== Réseau de stockage pris en charge

FC; iSCSI; NVMe/TCP;



=== Spécifications de l'environnement système

Aucune donnée environnementale disponible.



=== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




=== Haute disponibilité

Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP ; contrôleurs redondants remplaçables à chaud ; alimentations redondantes remplaçables à chaud ; gestion SAS en bande via des connexions SAS ; [//] 2025-10-15 ontap-systems-internal/issues/1357
