---
permalink: fas50/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: fas50, replace the boot media 
summary: 'Avant de remplacer le support de démarrage de votre système de stockage FAS50, assurez-vous de respecter les conditions requises pour un remplacement réussi. Il est notamment important de disposer d"une clé USB avec la capacité de stockage appropriée et de vérifier que vous disposez du périphérique de démarrage de remplacement approprié.' 
---
= Conditions requises pour la récupération manuelle du support de démarrage - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système de stockage FAS50, assurez-vous de respecter les conditions requises pour un remplacement réussi. Il est notamment important de disposer d'une clé USB avec la capacité de stockage appropriée et de vérifier que vous disposez du périphérique de démarrage de remplacement approprié.

[NOTE]
====
NetApp recommande fortement d'activer la journalisation de la console sur les appareils que vous utilisez et de prendre les mesures suivantes lors de cette procédure :

* Laissez AutoSupport activé pendant votre maintenance. Cela permet au support NetApp de recevoir des informations de diagnostic en cas de problème.
* Activez la journalisation des sessions pour toutes les sessions CLI. Cela crée un enregistrement complet de toutes les commandes et des sorties système pendant l'opération de maintenance. Pour savoir comment activer la journalisation des sessions, consultez  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Comment configurer PuTTY pour une connectivité optimale aux systèmes ONTAP"^].


====
.clé USB
* Assurez-vous d’avoir une clé USB formatée en FAT32.
* La clé USB doit avoir une capacité de stockage suffisante pour contenir le  `image_xxx.tgz` déposer.


.Préparation du dossier
Copiez le  `image_xxx.tgz` sur la clé USB. Ce fichier sera utilisé lors du transfert de l'image ONTAP via la clé USB.

À partir de l'image ONTAP extraite, copiez le  `EFI` dossier à la racine de la clé USB.

.Remplacement des composants
Remplacez le composant défectueux par le composant de remplacement fourni par NetApp.

.Identification du contrôleur
Il est essentiel d'appliquer les commandes au contrôleur approprié lorsque vous remplacez le support de démarrage défectueux :

* Le _contrôleur défaillant_ est le contrôleur sur lequel vous effectuez la maintenance.
* Le _contrôleur sain_ est le partenaire HA du contrôleur altéré.


.Et la suite ?
Après avoir examiné la configuration requise pour remplacer le support de démarrage, vous devez link:bootmedia-encryption-preshutdown-checks.html["vérifiez la prise en charge et l'état de la clé de cryptage sur le support de démarrage"].
