---
permalink: fas50/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: fas50, replace the boot media 
summary: 'Avant de remplacer le support de démarrage de votre système de stockage FAS50, assurez-vous de respecter les conditions requises pour un remplacement réussi. Cela inclut la vérification que vous disposez du support de démarrage de remplacement approprié, la confirmation que le port e0M (clé) du contrôleur défectueux fonctionne correctement et la détermination si Onboard Key Manager (OKM) ou External Key Manager (EKM) est activé.' 
---
= Exigences relatives à la récupération automatique du support de démarrage - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système de stockage FAS50, assurez-vous de respecter les conditions requises pour un remplacement réussi. Cela inclut la vérification que vous disposez du support de démarrage de remplacement approprié, la confirmation que le port e0M (clé) du contrôleur défectueux fonctionne correctement et la détermination si Onboard Key Manager (OKM) ou External Key Manager (EKM) est activé.

La récupération automatique du support de démarrage est prise en charge uniquement dans ONTAP 9.17.1 et versions ultérieures. Si votre système de stockage exécute une version antérieure d' ONTAP, utilisez l'option link:bootmedia-replace-workflow.html["procédure de récupération de démarrage manuel"] .

Passez en revue les exigences suivantes.

[NOTE]
====
NetApp recommande fortement d'activer la journalisation de la console sur les appareils que vous utilisez et de prendre les mesures suivantes lors de cette procédure :

* Laissez AutoSupport activé pendant votre maintenance. Cela permet au support NetApp de recevoir des informations de diagnostic en cas de problème.
* Activez la journalisation des sessions pour toutes les sessions CLI. Cela crée un enregistrement complet de toutes les commandes et des sorties système pendant l'opération de maintenance. Pour savoir comment activer la journalisation des sessions, consultez  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Comment configurer PuTTY pour une connectivité optimale aux systèmes ONTAP"^].


====
* Vous devez remplacer le composant défectueux par un composant FRU de remplacement de même capacité que celle reçue de NetApp.
* Vérifiez que l'interface e0S (port e0M wrench) du contrôleur défectueux n'est pas défectueuse.
+
Le port e0M est utilisé pour communiquer entre les deux contrôleurs pendant le processus de récupération de démarrage automatisé.

* Pour OKM, vous avez besoin de la phrase secrète à l'échelle du cluster ainsi que des données de sauvegarde.
* Pour EKM, vous avez besoin de copies des fichiers suivants à partir du nœud partenaire :
+
** fichier /cfcard/kmip/servers.cfg.
** fichier /cfcard/kmip/certs/client.crt.
** fichier /cfcard/kmip/certs/client.key.
** Fichier /cfcard/kmip/certs/CA.pem.


* Il est essentiel d'appliquer les commandes au contrôleur approprié lorsque vous remplacez le support de démarrage défectueux :
+
** Le _contrôleur défaillant_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le _contrôleur sain_ est le partenaire HA du contrôleur altéré.




.Et la suite
Après avoir examiné la configuration requise pour le support de démarrage, vous link:bootmedia-shutdown-bmr.html["arrêter le contrôleur"].
