---
permalink: fas50/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: fas50, how to reboot the system 
summary: Renvoyez le contrôle des ressources de stockage au contrôleur de remplacement afin que votre système FAS50 puisse reprendre son fonctionnement normal.  La procédure de restitution varie en fonction du type de cryptage utilisé par votre système, aucun cryptage, cryptage OKM Onboard Key Manager ou cryptage EKM External Key Manager. 
---
= Remettre le contrôleur - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Renvoyer le contrôle des ressources de stockage au contrôleur de remplacement afin que votre système FAS50 puisse reprendre son fonctionnement normal. La procédure de retour à zéro varie en fonction du type de chiffrement utilisé par votre système : pas de chiffrement, chiffrement OKM (Onboard Key Manager) ou chiffrement EKM (External Key Manager).

[role="tabbed-block"]
====
.Pas de cryptage
--
Remettez le contrôleur défectueux en mode de fonctionnement normal en laissant son espace de stockage.

.Étapes
. Dans l'invite Loader, entrez `boot_ontap`.
. Appuyez sur <enter> lorsque les messages de la console s'arrêtent.
+
** Si vous voyez l'invite _login_, passez à l'étape suivante à la fin de cette section.
** Si vous voyez _waiting for giveback_, appuyez sur la clé <enter>, connectez-vous au nœud partenaire, puis passez à l'étape suivante à la fin de cette section.


. Remettre le contrôleur défectueux en fonctionnement normal en réutilisant son espace de stockage : `storage failover giveback -ofnode _impaired_node_name_`
. Si le rétablissement automatique a été désactivé, le réactiver : `storage failover modify -node local -auto-giveback _true_`
. Si AutoSupport est activé, restaurer/annuler la suppression de la création automatique de cas : `system node autosupport invoke -node * -type all -message MAINT=END`


--
.Chiffrement intégré (OKM)
--
Réinitialise le chiffrement intégré et rétablit le fonctionnement normal du contrôleur.

.Étapes
. Dans l'invite Loader, entrez `boot_ontap maint`.
. Démarrez à partir du menu ONTAP à partir de l'invite Loader `boot_ontap menu` et sélectionnez l'option 10.
. Saisissez la phrase de passe OKM.
+

NOTE: Vous êtes invité à saisir deux fois la phrase de passe.

. Entrez les données de la clé de sauvegarde lorsque vous y êtes invité.
. Dans le menu de démarrage, entrez option `1` pour le démarrage normal.
. Appuyez sur <enter> lorsque _waiting for giveback_ s'affiche.
. Déplacez le câble de la console vers le nœud partenaire et connectez-vous en tant que `admin`.
. Ne donner que les agrégats CFO (l'agrégat racine) : `storage failover giveback -fromnode local -only-cfo-aggregates _true_`
+

NOTE: Si vous rencontrez des erreurs, contactez https://support.netapp.com["Support NetApp"].

. Attendez 5 minutes après la fin du rapport de rétablissement et vérifiez l'état du basculement et du rétablissement : `storage failover show` et `storage failover show-giveback`.
. Synchroniser et vérifier l'état des clés :
+
.. Replacer le câble de la console sur le contrôleur de remplacement.
.. Synchroniser les clés manquantes : `security key-manager onboard sync`
+

NOTE: Vous êtes invité à saisir la phrase de passe OKM au niveau du cluster.

.. Vérifier l'état des clés : `security key-manager key query -restored _false_`
+
La sortie ne doit pas afficher de résultats lorsqu'elle est correctement synchronisée.

+
Si le résultat affiche des résultats (les ID de clé des clés qui ne sont pas présents dans la table de clés internes du système), contactez https://support.netapp.com["Support NetApp"].



. Remettre le contrôleur défectueux en fonctionnement normal en réutilisant son espace de stockage : `storage failover giveback -ofnode _impaired_node_name_`
. Si le rétablissement automatique a été désactivé, le réactiver : `storage failover modify -node local -auto-giveback _true_`
. Si AutoSupport est activé, restaurer/annuler la suppression de la création automatique de cas : `system node autosupport invoke -node * -type all -message MAINT=END`


--
.Gestionnaire de clés externe (EKM)
--
Réinitialisez le cryptage et faites revenir le contrôleur en mode de fonctionnement normal.

.Étapes
. Si le volume racine est chiffré avec External Key Manager et que le câble de la console est connecté au nœud de remplacement, entrez `boot_ontap menu` et sélectionnez option `11`.
. Si ces questions apparaissent, répondez ou `n`, `y` le cas échéant :
+
Disposez-vous d'une copie du fichier /cfcard/kmip/certs/client.crt ? {y/n}

+
Possédez-vous une copie du fichier /cfcard/kmip/certs/client.key ? {y/n}

+
Possédez-vous une copie du fichier /cfcard/kmip/certs/CA.pem ? {y/n}

+
Possédez-vous une copie du fichier /cfcard/kmip/servers.cfg ? {y/n}

+
Connaissez-vous l'adresse du serveur KMIP ? {y/n}

+
Connaissez-vous le port KMIP ? {y/n}

+

NOTE: Contactez https://support.netapp.com["Support NetApp"] en cas de problème.

. Fournir les informations pour :
+
** Contenu du fichier de certificat client (client.crt)
** Le contenu du fichier de clé client (client.key)
** Contenu du fichier CA.pem (CA.pem) du serveur KMIP
** Adresse IP du serveur KMIP
** Port du serveur KMIP


. Une fois le processus terminé, le menu de démarrage s'affiche. Sélectionnez « 1 » pour un démarrage normal.
. Vérifier le statut du basculement : `storage failover show`
. Assurez-vous que tous les « core dumps » sur le nœud réparé sont enregistrés en mode avancé, puis `run local partner nosavecore` en `set -privilege advanced` .
. Remettre le contrôleur défectueux en fonctionnement normal en réutilisant son espace de stockage : `storage failover giveback -ofnode _impaired_node_name_`
. Si le rétablissement automatique a été désactivé, le réactiver : `storage failover modify -node local -auto-giveback _true_`
. Si AutoSupport est activé, restaurer/annuler la suppression de la création automatique de cas : `system node autosupport invoke -node * -type all -message MAINT=END`


--
====
.Et la suite ?
Une fois que vous avez transféré la propriété des ressources de stockage vers le contrôleur de remplacement, vous devez link:controller-replace-restore-system-rma.html["terminez le remplacement du contrôleur"]procéder.
