---
permalink: fas50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: fas50, prerequisite, replace the controller module 
summary: 'Avant de remplacer le contrôleur de votre système de stockage FAS50, veillez à respecter les exigences requises pour un remplacement réussi. Cela inclut la vérification du bon fonctionnement de tous les autres composants du système, la vérification du bon contrôleur de remplacement et l"enregistrement de la sortie de la console du contrôleur dans un fichier journal texte.' 
---
= Conditions requises pour remplacer le contrôleur - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le contrôleur de votre système de stockage FAS50, veillez à respecter les exigences requises pour un remplacement réussi. Cela inclut la vérification du bon fonctionnement de tous les autres composants du système, la vérification du bon contrôleur de remplacement et l'enregistrement de la sortie de la console du contrôleur dans un fichier journal texte.

Revoir les exigences et les considérations relatives à la procédure de remplacement du contrôleur.

[NOTE]
====
NetApp recommande fortement d'activer la journalisation de la console sur les appareils que vous utilisez et de prendre les mesures suivantes lors de cette procédure :

* Laissez AutoSupport activé pendant votre maintenance. Cela permet au support NetApp de recevoir des informations de diagnostic en cas de problème.
* Activez la journalisation des sessions pour toutes les sessions CLI. Cela crée un enregistrement complet de toutes les commandes et des sorties système pendant l'opération de maintenance. Pour savoir comment activer la journalisation des sessions, consultez  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Comment configurer PuTTY pour une connectivité optimale aux systèmes ONTAP"^].


====


== De formation

* Toutes les tablettes doivent fonctionner correctement.
* Le contrôleur sain doit pouvoir reprendre le contrôleur qui est remplacé (appelé « contrôleur défectueux » dans cette procédure).
* Si votre système est dans une configuration MetroCluster, vous devez passer en revue la section https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Choix de la procédure de récupération correcte"] pour déterminer si vous devez utiliser cette procédure.
* Vous devez remplacer un contrôleur par un contrôleur de même type. Vous ne pouvez pas mettre à niveau votre système en remplaçant simplement le contrôleur.
* Vous ne pouvez pas modifier de disques ou de tiroirs dans le cadre de cette procédure.




== Considérations

Il est important d'appliquer les commandes de cette procédure au contrôleur approprié :

* Le contrôleur _trouble_ est le contrôleur qui est en cours de remplacement.
* Le contrôleur _remplacement_ est le nouveau contrôleur qui remplace le contrôleur défaillant.
* Le contrôleur _Healthy_ est le contrôleur survivant.


.Et la suite ?
Après avoir passé en revue les conditions requises pour remplacer le contrôleur défectueux, vous devez link:controller-replace-shutdown.html["arrêtez le contrôleur défectueux"].
