---
permalink: fas50/install-hardware.html 
sidebar: sidebar 
keywords: fas50, install hardware, telco rack 
summary: 'Après avoir préparé l"installation du système de stockage FAS50, installez le matériel du système de stockage. Commencez par installer les kits de rails. Installez ensuite et sécurisez votre système de stockage dans une armoire ou un rack de télécommunications.' 
---
= Installer le matériel - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir préparé l'installation du système de stockage FAS50, installez le matériel du système de stockage. Commencez par installer les kits de rails. Installez ensuite et sécurisez votre système de stockage dans une armoire ou un rack de télécommunications.

Ignorez cette étape si votre système de stockage est livré dans une armoire.


CAUTION: Portez systématiquement un bracelet antistatique relié à une prise de terre vérifiée lors des opérations d'installation et de maintenance. Le non-respect des précautions ESD appropriées peut causer des dommages permanents aux nœuds de contrôleur, aux baies de stockage et aux commutateurs réseau.

.Avant de commencer
* Assurez-vous de disposer des instructions fournies avec le kit de rails.
* Soyez conscient des problèmes de sécurité associés au poids du système de stockage et de l'étagère.
* Assurez-vous que le flux d'air qui traverse le système de stockage pénètre par l'avant où le cadre ou les embouts sont installés et sort par l'arrière où se trouvent les ports.


.Étapes
. Installez les kits de rails pour votre système de stockage et les étagères selon les besoins, en suivant les instructions fournies avec les kits.
. Installez et sécurisez votre système de stockage dans l'armoire ou le rack de télécommunications :
+
.. Positionnez le système de stockage sur les rails au milieu de l'armoire ou du rack de télécommunications, puis soutenez le système de stockage par le bas et faites-le glisser pour le mettre en place.
.. Assurez-vous que les broches de guidage de l'armoire ou du rack de télécommunications sont bien en place dans les fentes du guide du châssis.
.. Fixez le système de stockage à l'armoire ou au rack de télécommunications à l'aide des vis de montage fournies.


. Fixez le panneau à l'avant du système de stockage.
. Installez et fixez la tablette selon les besoins.
+
.. Placez l'arrière de la tablette sur les rails, puis soutenez la tablette par le bas et faites-la glisser dans l'armoire ou le rack de télécommunications.
+
Si vous installez plusieurs tiroirs, placez le premier tiroir directement au-dessus des contrôleurs. Placez le second shelf directement sous les contrôleurs. Répétez cette procédure pour toutes les étagères supplémentaires.

.. Fixez l'étagère à l'armoire ou au rack de télécommunications à l'aide des vis de montage fournies.
+
.Et la suite ?
Après avoir installé le matériel de votre système de stockage, vous link:install-cable.html["câblez le matériel de fixation"].




