---
sidebar: sidebar 
permalink: fas50/install-requirements.html 
keywords: fas50, install, setup, cautions 
summary: 'Passez en revue l"équipement nécessaire et les précautions de levage pour votre plate-forme et vos étagères.' 
---
= Exigences d'installation - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Étude des exigences relatives à votre système de stockage FAS50



== Équipement nécessaire pour l'installation

Pour installer votre système de stockage, vous avez besoin de l'équipement et des outils suivants.

* Accès à un navigateur Web pour configurer votre système de stockage
* Sangle de décharge électrostatique (ESD)
* Lampe de poche
* Ordinateur portable ou console avec connexion USB/série
* Tournevis Phillips n°2




== Précautions de levage

Les systèmes de stockage et les tiroirs sont lourds. Faites preuve de prudence lorsque vous soulevez et déplacez ces éléments.



=== Poids du système de stockage

Prenez les précautions nécessaires lors du déplacement ou du levage de votre système de stockage.

Le système de stockage peut peser jusqu'à 24.4 kg (53.8 lb). Pour soulever le système de stockage, faire appel à deux personnes ou à un relevage hydraulique.

image::../media/drw_g_lifting_weight_ieops-1831.svg[Icône d'avertissement de poids FAS50]



=== Poids de la tablette

Prenez les précautions nécessaires lorsque vous déplacez ou soulevez votre tablette.

Une étagère DS460C peut peser jusqu'à 181.1 kg (260.4 lb). Pour soulever la tablette, il vous faudra peut-être jusqu'à cinq personnes ou un dispositif de levage hydraulique. Conservez tous les composants dans la tablette (à l'avant et à l'arrière) pour éviter de rééquilibrer le poids de la tablette.

image::../media/drw_ds460c_weight_warning_ieops-1932.svg[Avertissement de levage DS460C]

.Informations associées
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informations de sécurité et avis réglementaires"^]


.Et la suite ?
Après avoir pris en compte la configuration requise et les considérations relatives à votre système de stockage, vous link:install-prepare.html["avant l'installation"].
