---
permalink: fas50/io-module-overview.html 
sidebar: sidebar 
keywords: AFF A90, AFF A70, replace io module 
summary: 'Les systèmes FAS50 permettent d"étendre ou de remplacer les modules d"E/S de manière flexible afin d"améliorer la connectivité réseau et les performances. L"ajout ou le remplacement d"un module d"E/S est essentiel lors de la mise à niveau des capacités réseau ou de l"adressage d"un module défaillant.' 
---
= Présentation de l'ajout et du remplacement d'un module d'E/S - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes FAS50 permettent d'étendre ou de remplacer les modules d'E/S de manière flexible afin d'améliorer la connectivité réseau et les performances. L'ajout ou le remplacement d'un module d'E/S est essentiel lors de la mise à niveau des capacités réseau ou de l'adressage d'un module défaillant.

Vous pouvez remplacer un module d'E/S défaillant de votre système de stockage par le même type de module d'E/S ou par un autre type de module d'E/S. Vous pouvez également ajouter un module d'E/S à un système de stockage avec les emplacements disponibles.

* link:io-module-add.html["Ajoutez un module d'E/S."]
+
L'ajout de modules d'E/S supplémentaires peut améliorer la redondance et garantir que le système de stockage reste opérationnel même en cas de défaillance d'un module d'E/S.

* link:io-module-replace.html["Remplacez un module d'E/S."]
+
Le remplacement d'un module d'E/S défaillant permet de rétablir l'état de fonctionnement optimal du système de stockage.


