---
permalink: fas50/maintain-overview.html 
sidebar: sidebar 
keywords: aff a20 aff a30 aff a50 maintenance, maintenance, repairing a20 aff a30 aff a50, replace a20 aff a30 aff a50 components 
summary: 'Assurer la maintenance du matériel de vos systèmes de stockage FAS50 pour assurer une fiabilité à long terme et des performances optimales. Effectuez régulièrement des tâches de maintenance, telles que le remplacement de composants défectueux, afin d"éviter les temps d"indisponibilité et les pertes de données.' 
---
= Présentation de la maintenance matérielle - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Entretenez le matériel de votre système de stockage FAS50 pour garantir une fiabilité à long terme et des performances optimales. Effectuez régulièrement des tâches de maintenance, comme le remplacement des composants défectueux, afin d'éviter les temps d'arrêt et les pertes de données.

Les procédures de maintenance supposent que le système de stockage FAS50 a déjà été déployé en tant que nœud de stockage dans l'environnement ONTAP .



== Composants du système

Pour les systèmes de stockage FAS50, vous pouvez effectuer des procédures de maintenance sur les composants suivants.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Support de démarrage - récupération automatique"]
 a| 
Le support de démarrage stocke un ensemble primaire et secondaire de fichiers image ONTAP que le système de stockage utilise pour démarrer l'image depuis le nœud partenaire et exécuter automatiquement l'option de menu de démarrage appropriée pour installer l'image sur votre support de démarrage de remplacement. La récupération automatique du support de démarrage est prise en charge uniquement dans ONTAP 9.17.1 et versions ultérieures. Si votre système de stockage exécute une version antérieure d' ONTAP, utilisez l'option link:bootmedia-replace-workflow.html["procédure de récupération de démarrage manuel"] .



 a| 
link:bootmedia-replace-workflow.html["Support de démarrage - récupération manuelle"]
 a| 
Le support de démarrage stocke un ensemble principal et secondaire de fichiers image ONTAP que le système de stockage utilise pour démarrer l'image à partir d'une clé USB et restaurer la configuration à partir du nœud partenaire.



 a| 
link:caching-module-hot-swap.html["Module de cache"]
 a| 
Un module de cache (Flash cache) utilise des disques SSD haut débit pour stocker les données fréquemment utilisées afin d'accélérer leur récupération.



 a| 
link:chassis-replace-workflow.html["Châssis"]
 a| 
Le châssis correspond au boîtier physique qui contient tous les composants du contrôleur, tels que le contrôleur/l'unité centrale, l'alimentation et les E/S.



 a| 
link:controller-replace-workflow.html["Contrôleur"]
 a| 
Un contrôleur se compose d'une carte, d'un micrologiciel et d'un logiciel. Il contrôle les lecteurs et exécute le logiciel du système d'exploitation ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Un module de mémoire en ligne double (DIMM) est un type de mémoire d'ordinateur. Ils sont installés pour ajouter de la mémoire système à une carte mère du contrôleur.



 a| 
link:fan-replace.html["Ventilateur"]
 a| 
Un ventilateur refroidit le contrôleur et les entraînements.



 a| 
link:io-module-overview.html["Module d'E/S."]
 a| 
Le module d'E/S (module d'entrée/sortie) est un composant matériel qui sert d'intermédiaire entre le contrôleur et divers dispositifs ou systèmes qui doivent échanger des données avec le contrôleur.



 a| 
link:nvdimm-battery-replace.html["Batterie NV"]
 a| 
La batterie de la mémoire non volatile (NV) est chargée d'alimenter les composants NVMEM tandis que les données à la volée sont déchargées vers la mémoire Flash après une coupure de courant.



 a| 
link:power-supply-replace.html["Alimentation électrique"]
 a| 
Une alimentation fournit une source d'alimentation redondante dans un contrôleur.



 a| 
link:rtc-battery-replace.html["Pile de l'horloge en temps réel"]
 a| 
Une batterie d'horloge en temps réel conserve les informations relatives à la date et à l'heure du système si l'appareil est éteint.

|===