---
permalink: fas9500/controller_replace_recable_reassign_disks.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Recâble du système - FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Poursuivez la procédure de remplacement en réétiquetage des condications de stockage et de réseau.



== Étape 1 : recâblage du système

Après l'exécution des diagnostics, vous devez recâter les connexions réseau et stockage du module de contrôleur.

.Étapes
. Recâblage du système.
. Vérifiez que le câblage est correct à l'aide de https://["Active IQ Config Advisor"^].
+
.. Téléchargez et installez Config Advisor.
.. Entrez les informations du système cible, puis cliquez sur collecter les données.
.. Cliquez sur l'onglet câblage, puis examinez la sortie. Vérifiez que tous les tiroirs disques sont affichés et que tous les disques apparaissent dans le résultat, en corrigeant les problèmes de câblage que vous rencontrez.
.. Pour vérifier les autres câbles, cliquez sur l'onglet approprié, puis examinez les résultats de Config Advisor.





NOTE: Les informations d'ID système et d'affectation de disque résident dans le module NVRAM, qui se trouve dans un module séparé du module de contrôleur et ne sont pas affectées par le remplacement du module de contrôleur.



== Étape 2 : réaffectation de disques

Si le système de stockage est dans une paire HA, l'ID système du nouveau module de contrôleur est automatiquement attribué aux disques lors du rétablissement après la procédure. Vous devez confirmer la modification de l'ID système lors du démarrage du _replace_ node, puis vérifier que la modification a été implémentée.

Cette procédure s'applique uniquement aux systèmes qui exécutent ONTAP dans une paire HA.

. Si le _remplacement_ noeud est en mode Maintenance (affiche le `*>` Invite), quittez le mode maintenance et accédez à l'invite DU CHARGEUR : `halt`
. À partir de l'invite DU CHARGEUR sur le _replace_ node, démarrez le nœud, puis entrez `y` Si vous êtes invité à remplacer l'ID système en raison d'une discordance d'ID système.``boot_ontap``
. Attendre jusqu'à `Waiting for giveback...` Le message s'affiche sur la console _replace_ node, puis, à partir du nœud en bon état, vérifiez que le nouvel ID système partenaire a été automatiquement attribué : Storage failover show
+
Dans le résultat de la commande, un message indiquant l'ID du système a changé sur le nœud pour lequel l'ID a été modifié, et indiquant l'ancien et le nouveau ID corrects. Dans l'exemple suivant, le node2 a fait l'objet d'un remplacement et a un nouvel ID système de 151759706.

+
[listing]
----
node1> storage failover show
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. Depuis le nœud sain, vérifier que les « core dumps » sont enregistrés :
+
.. Changement au niveau de privilège avancé : `set -privilege advanced`
+
Vous pouvez répondre `Y` lorsque vous êtes invité à passer en mode avancé. L'invite du mode avancé s'affiche (*>).

.. Enregistrez les « coredumps » : `system node run -node _local-node-name_ partner savecore`
.. Attendez que la commande savecore soit terminée avant d'émettre le retour.
+
Vous pouvez saisir la commande suivante pour surveiller la progression de la commande savecore : `system node run -node _local-node-name_ partner savecore -s`

.. Retour au niveau de privilège admin : `set -privilege admin`


. Si le chiffrement du volume ou du stockage est configuré sur votre système de stockage, vous devez restaurer la fonctionnalité de chiffrement du stockage ou du volume en suivant l'une des procédures suivantes, selon que vous utilisez la gestion des clés intégrée ou externe :
+
** https://["Restaurez les clés de chiffrement intégrées de gestion des clés"^]
** https://["Restaurez les clés de chiffrement externes pour la gestion des clés"^]


. Remettre le nœud :
+
.. Depuis le nœud sain, remettre le stockage du nœud remplacé : `storage failover giveback -ofnode _replacement_node_name_`
+
Le _remplacement_ node reprend son stockage et termine son démarrage.

+
Si vous êtes invité à remplacer l'ID système en raison d'une discordance d'ID système, vous devez entrer `y`.

+

NOTE: Si le retour est vetoté, vous pouvez envisager d'ignorer les vetoes.

+
Pour plus d'informations, reportez-vous à la section https://["Commandes de rétablissement manuel"^] rubrique pour remplacer le droit de veto.

.. Une fois le retour arrière terminé, vérifiez que la paire haute disponibilité est saine et que le basculement est possible : Storage failover show
+
La sortie du `storage failover show` La commande ne doit pas inclure l'ID système modifié dans le message partenaire.



. Vérifier que les disques ont été correctement affectés : `storage disk show -ownership`
+
Les disques appartenant au _replace_ node doivent afficher le nouvel ID système. Dans l'exemple suivant, les disques appartenant au nœud1 affichent alors le nouvel ID système, 1873775277 :

+
[listing]
----
node1> storage disk show -ownership

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----
. Si le système est dans une configuration MetroCluster, surveillez l'état du nœud : `metrocluster node show`
+
La configuration MetroCluster prend quelques minutes après le remplacement pour revenir à un état normal. À ce moment, chaque nœud affiche un état configuré, avec la mise en miroir reprise sur incident activée et un mode de fonctionnement normal. Le `metrocluster node show -fields node-systemid` Le résultat de la commande affiche l'ancien ID système jusqu'à ce que la configuration MetroCluster revienne à un état normal.

. Si le nœud est dans une configuration MetroCluster, en fonction de l'état de la MetroCluster, vérifiez que le champ ID de domicile DR affiche le propriétaire d'origine du disque si le propriétaire d'origine est un nœud sur le site de secours.
+
Ceci est requis si les deux conditions suivantes sont vraies :

+
** La configuration MetroCluster est en état de basculement.
** Le _remplacement_ node est le propriétaire actuel des disques sur le site de secours.
+
Pour plus d'informations, voir https://["Modification de la propriété des disques lors du basculement haute disponibilité et du basculement du MetroCluster dans une configuration MetroCluster à quatre nœuds"^] sujet.



. Si votre système se trouve dans une configuration MetroCluster, vérifiez que chaque nœud est configuré : `metrocluster node show - fields configuration-state`
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Vérifiez que les volumes attendus sont présents pour chaque nœud : `vol show -node node-name`
. Si vous avez désactivé le basculement automatique au redémarrage, activez-le à partir du nœud sain : `storage failover modify -node replacement-node-name -onreboot true`

