---
permalink: fas2800/bootmedia-recovery-image-boot.html 
sidebar: sidebar 
keywords: fas2800, boot, recovery, image, restore, file, system, environmental, varible 
summary: 'Vous devez démarrer l"image ONTAP à partir du lecteur USB, restaurer le système de fichiers et vérifier les variables environnementales.' 
---
= Démarrez l'image de restauration - FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez démarrer l'image ONTAP à partir du lecteur USB, restaurer le système de fichiers et vérifier les variables environnementales.

.Étapes
. À partir de l'invite DU CHARGEUR, démarrez l'image de récupération à partir du lecteur flash USB : `boot_recovery`
+
L'image est téléchargée à partir de la clé USB.

. Lorsque vous y êtes invité, entrez le nom de l'image ou acceptez l'image par défaut affichée entre crochets sur votre écran.
. Restaurez le système de fichiers var :
+
[role="tabbed-block"]
====
.Option 1 : ONTAP 9.16.0 ou version antérieure
--
.. Sur le contrôleur défectueux, appuyez sur `Y` lorsque vous voyez `Do you want to restore the backup configuration now?`
.. Sur le contrôleur défectueux, appuyez sur `Y` lorsque vous êtes invité à remplacer _/etc/ssh/ssh_host_ecdsa_key_.
.. Sur le contrôleur sain, définissez le contrôleur défectueux sur le niveau de privilège avancé : `set -privilege advanced`.
.. Sur le contrôleur partenaire sain, exécutez la commande restore backup : `system node restore-backup -node local -target-address impaired_node_IP_address` .
+
*REMARQUE :* si vous voyez un message autre qu'une restauration réussie, contactez https://support.netapp.com["Support NetApp"].

.. Sur le contrôleur partenaire sain, remettez le contrôleur défectueux au niveau admin: `set -privilege admin`.
.. Sur le contrôleur défectueux, appuyez sur `Y` lorsque vous voyez `Was the restore backup procedure successful?`.
.. Sur le contrôleur défectueux, appuyez sur `Y` lorsque vous voyez `...would you like to use this restored copy now?`.
.. Sur le contrôleur défectueux, appuyez sur `Y` lorsque vous êtes invité à redémarrer le contrôleur défectueux et appuyez sur `ctrl-c` pour accéder au menu de démarrage.
.. Si le système n'utilise pas le chiffrement, sélectionnez _option 1 démarrage normal._, sinon, passez à link:bootmedia-encryption-restore.html["Restaurez le chiffrement"].


--
.Option 2 : ONTAP 9.16.1 ou version ultérieure
--
.. Sur le contrôleur défectueux, appuyez sur `Y` lorsque vous êtes invité à restaurer la configuration de sauvegarde.
+
Une fois la procédure de restauration réussie, ce message s'affiche sur la console - `syncflash_partner: Restore from partner complete`.

.. Sur le contrôleur défectueux, appuyez sur `Y` lorsque vous y êtes invité pour confirmer si la sauvegarde de restauration a réussi.
.. Sur le contrôleur défectueux, appuyez sur `Y` lorsque vous êtes invité à utiliser la configuration restaurée.
.. Sur le contrôleur défectueux, appuyez sur `Y` lorsque vous êtes invité à redémarrer le nœud.
.. Sur le contrôleur défectueux, appuyez sur `Y` lorsque vous êtes invité à redémarrer le contrôleur défectueux et appuyez sur `ctrl-c` pour accéder au menu de démarrage.
.. Si le système n'utilise pas le chiffrement, sélectionnez _option 1 démarrage normal._, sinon, passez à link:bootmedia-encryption-restore.html["Restaurez le chiffrement"].


--
====


. Branchez le câble de la console au contrôleur partenaire.
. Reaccordez le contrôleur à l'aide du `storage failover giveback -fromnode local` commande.
. Restaurez le retour automatique si vous le désactivez à l'aide de `storage failover modify -node local -auto-giveback true` commande.
. Si AutoSupport est activé, restaurez/annulez la création automatique de cas à l'aide de la `system node autosupport invoke -node * -type all -message MAINT=END` commande.
+
*REMARQUE :* si le processus échoue, contactez https://support.netapp.com["Support NetApp"].


