---
permalink: fas2800/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: fas2800, how to recable the system, how to reassign disks 
summary: Vous devez recomm le stockage et confirmer la réaffectation des disques. 
---
= Recâblage du système et réaffectation des disques - FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour effectuer la procédure de remplacement et restaurer entièrement le système en fonctionnement, vous devez récupérer le stockage, confirmer la réaffectation des disques, restaurer la configuration NetApp Storage Encryption (si nécessaire) et installer les licences du nouveau contrôleur. Vous devez effectuer une série de tâches avant de restaurer le système en mode de fonctionnement complet.



== Étape 1 : recâblage du système

Recâblage des connexions réseau et de stockage du module de contrôleur.

.Étapes
. Recâblage du système.
. Vérifiez que le câblage est correct à l'aide de https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].
+
.. Téléchargez et installez Config Advisor.
.. Entrez les informations du système cible, puis cliquez sur collecter les données.
.. Cliquez sur l'onglet câblage, puis examinez la sortie. Vérifiez que tous les tiroirs disques sont affichés et que tous les disques apparaissent dans le résultat, en corrigeant les problèmes de câblage que vous rencontrez.
.. Pour vérifier les autres câbles, cliquez sur l'onglet approprié, puis examinez les résultats de Config Advisor.






== Étape 2 : réaffectation de disques

Vous devez confirmer la modification de l'ID système au démarrage du contrôleur _replace_, puis vérifier que la modification a été implémentée.

. Si le _remplacement_ contrôleur est en mode Maintenance (affiche le `*>` Invite, quittez le mode maintenance et accédez à l'invite DU CHARGEUR : `halt`
. À partir de l'invite DU CHARGEUR sur le contrôleur _replace_, démarrez le contrôleur, puis entrez `y` Si vous êtes invité à remplacer l'ID système en raison d'une discordance d'ID système :``boot_ontap``
. Attendre jusqu'à `Waiting for giveback...` Le message s'affiche sur la console du contrôleur _replace_, puis, à partir du contrôleur sain, vérifiez que le nouvel ID système partenaire a été automatiquement attribué : `storage failover show`
+
Dans le résultat de la commande, un message indiquant l'ID système modifié sur le contrôleur associé est affiché, indiquant l'ancien et le nouveau ID corrects. Dans l'exemple suivant, le node2 a fait l'objet d'un remplacement et a un nouvel ID système de 151759706.

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. Depuis le contrôleur sain, vérifier que les « coredumps » sont enregistrés :
+
.. Changement au niveau de privilège avancé : `set -privilege advanced`
+
Vous pouvez répondre `Y` lorsque vous êtes invité à passer en mode avancé. L'invite du mode avancé s'affiche (*>).

.. Enregistrez les « coredumps » : `system node run -node _local-node-name_ partner savecore`
.. Attendez le `savecore` commande à compléter avant d'émettre le retour.
+
Vous pouvez saisir la commande suivante pour surveiller la progression de la commande savecore : `system node run -node _local-node-name_ partner savecore -s`

.. Retour au niveau de privilège admin : `set -privilege admin`


. Remettre le contrôleur :
+
.. Depuis le contrôleur sain, remettre le stockage du contrôleur remplacé : `storage failover giveback -ofnode _replacement_node_name_`
+
Le contrôleur _remplacement_ reprend son stockage et termine son démarrage.

+
Si vous êtes invité à remplacer l'ID système en raison d'une discordance d'ID système, vous devez entrer `y`.

+

IMPORTANT: Si le retour est refusé, résoudre le problème de veto. Si le droit de veto n'est pas critique à résoudre, vous pouvez annuler le droit de veto.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Recherchez le contenu Configuration haute disponibilité de votre version de ONTAP 9"]

.. Une fois le retour arrière terminé, vérifiez que la paire HA est saine et que le basculement est possible : `storage failover show`
+
La sortie du `storage failover show` La commande ne doit pas inclure l'ID système modifié dans le message partenaire.



. Vérifier que les disques ont été correctement affectés : `storage disk show -ownership`
+
Les disques appartenant au _replace_ Controller doivent afficher le nouvel ID système. Dans l'exemple suivant, les disques appartenant au nœud1 affichent alors le nouvel ID système, 1873775277 :

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----

