---
permalink: fas2800/dimm-replace.html 
sidebar: sidebar 
keywords: fas2800, replace, dimm, shut, down, impaired, controller, controller, metrocluster, replace, system, reinstall, diagnostics, module, filed, part, aggregates, 
summary: 'Vous devez remplacer un module DIMM dans le module de contrôleur lorsque votre système enregistre un nombre croissant de codes de correction d"erreurs (ECC) pouvant être corrigés ; dans le cas contraire, le système risque de se trouver en panne.' 
---
= Remplacez un module DIMM - FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez remplacer un module DIMM dans le module de contrôleur lorsque votre système enregistre un nombre croissant de codes de correction d'erreurs (ECC) pouvant être corrigés ; dans le cas contraire, le système risque de se trouver en panne.

Tous les autres composants du système doivent fonctionner correctement ; si ce n'est pas le cas, vous devez contacter le support technique.

Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.

.Animation - remplacer un module DIMM
video::6c035199-9b79-494b-9c65-af9a015ffaf0[panopto]


== Étape 1 : arrêtez le contrôleur défaillant

Pour arrêter le contrôleur défaillant, vous devez déterminer l'état du contrôleur et, si nécessaire, prendre le contrôle de façon à ce que le contrôleur en bonne santé continue de transmettre des données provenant du stockage défaillant du contrôleur.

Si vous avez un cluster avec plus de deux nœuds, il doit être dans le quorum. Si le cluster n'est pas au quorum ou si un contrôleur en bonne santé affiche la valeur false pour l'éligibilité et la santé, vous devez corriger le problème avant de désactiver le contrôleur défaillant ; voir link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchroniser un nœud avec le cluster"^].

.Étapes
. Si AutoSupport est activé, supprimez la création automatique de dossier en invoquant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=_number_of_hours_down_h`
+
Le message AutoSupport suivant supprime la création automatique de dossiers pendant deux heures : `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Si le contrôleur défectueux fait partie d'une paire HA, désactivez le rétablissement automatique à partir de la console du contrôleur en bon état : `storage failover modify -node local -auto-giveback false`
. Faites passer le contrôleur douteux à l'invite DU CHARGEUR :
+
[cols="1,2"]
|===
| Si le contrôleur en état de fonctionnement s'affiche... | Alors... 


 a| 
Invite DU CHARGEUR
 a| 
Passez à la section retrait du module de contrôleur.



 a| 
Attente du retour...
 a| 
Appuyez sur Ctrl-C, puis répondez `y`.



 a| 
Invite système ou invite de mot de passe (entrer le mot de passe système)
 a| 
Prendre le contrôle défectueux ou l'arrêter à partir du contrôleur en bon état : `storage failover takeover -ofnode _impaired_node_name_`

Lorsque le contrôleur douteux s'affiche en attente de rétablissement..., appuyez sur Ctrl-C et répondez `y`.

|===




== Étape 2 : retirer le module de contrôleur

Retirez le module de contrôleur du système, puis retirez le capot du module de contrôleur.

.Étapes
. Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
. Desserrez le crochet et la bride de boucle qui relient les câbles au périphérique de gestion des câbles, puis débranchez les câbles système et les SFP (si nécessaire) du module de contrôleur, en maintenant une trace de l'emplacement où les câbles ont été connectés.
+
Laissez les câbles dans le périphérique de gestion des câbles de sorte que lorsque vous réinstallez le périphérique de gestion des câbles, les câbles sont organisés.

. Retirez et mettez de côté les dispositifs de gestion des câbles des côtés gauche et droit du module de contrôleur.
. Appuyez sur le loquet de la poignée de came jusqu'à ce qu'il se libère, ouvrez complètement la poignée de came pour libérer le module de contrôleur du fond de panier central, puis, à l'aide de deux mains, retirez le module de contrôleur du châssis.
+
image::../media/drw_2240_x_opening_cam_latch.svg[drw 2240 x verrou de came d'ouverture]

. Retournez le module de contrôleur et placez-le sur une surface plane et stable.
. Ouvrez le capot en appuyant sur les boutons bleus situés sur les côtés du module de contrôleur pour libérer le capot, puis faites pivoter le capot vers le haut et hors du module de contrôleur.
+
image::../media/drw_2850_open_controller_module_cover_IEOPS-695.svg[couvercle du module de contrôleur ouvert drw 2850 IOPS 695]



[cols="1,3"]
|===


 a| 
image::../media/legend_icon_01.svg[icône de légende 01]
 a| 
Bouton de déverrouillage du capot du module de contrôleur

|===


== Étape 3 : remplacez les modules DIMM

Repérez le module DIMM à l'intérieur du contrôleur, retirez-le et remplacez-le.


NOTE: Avant de remplacer un module DIMM, vous devez débrancher la batterie NVMEM du module de contrôleur.

.Étapes
. Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
+
Vous devez effectuer un arrêt correct du système avant de remplacer les composants du système pour éviter de perdre des données non écrites dans la mémoire non volatile (NVMEM). La LED se trouve à l'arrière du module de contrôleur. Recherchez l'icône suivante :

+
image::../media/drw_hw_nvram_icon.svg[icône drw hw nvram]

. Si la LED NVMEM ne clignote pas, il n'y a pas de contenu dans la NVMEM ; vous pouvez passer aux étapes suivantes et passer à la tâche suivante de cette procédure.
. Si la LED NVMEM clignote, des données sont disponibles dans la NVMEM et vous devez la déconnecter pour effacer la mémoire :
+
.. Retirez la batterie du module de contrôleur en appuyant sur le bouton bleu situé sur le côté du module de contrôleur.
.. Faites glisser la batterie vers le haut jusqu'à ce qu'elle se dégage des supports de fixation, puis retirez la batterie du module de contrôleur.
.. Localisez le câble de batterie, appuyez sur le clip de la fiche mâle batterie pour libérer le clip de verrouillage de la prise, puis débranchez le câble de batterie de la prise.
.. Vérifiez que la LED NVMEM n'est plus allumée.
.. Rebranchez le connecteur de la batterie et vérifiez à nouveau le voyant à l'arrière du contrôleur.
.. Débranchez le câble de la batterie.


. Localisez les modules DIMM de votre module de contrôleur.
. Notez l'orientation et l'emplacement du module DIMM dans le support de manière à pouvoir insérer le module DIMM de remplacement dans le bon sens.
. Éjectez le module DIMM de son logement en écartant lentement les deux languettes de l'éjecteur de DIMM de chaque côté du module DIMM, puis en faisant glisser le module DIMM hors de son logement.
+
Le module DIMM pivote légèrement vers le haut.

. Faites pivoter le module DIMM aussi loin que possible, puis faites-le glisser hors du support.
+

NOTE: Tenez soigneusement le module DIMM par les bords pour éviter toute pression sur les composants de la carte de circuit DIMM.

+
image::../media/drw_2850_replace_dimms_IEOPS-699.svg[drw 2850 remplacez les modules dimm IOPS 699]

+
[cols="1,3"]
|===


 a| 
image::../media/legend_icon_01.svg[icône de légende 01]
 a| 
Bouton de déverrouillage de la batterie NVRAM



 a| 
image::../media/legend_icon_02.svg[icône de légende 02]
 a| 
Fiche de la batterie NVRAM



 a| 
image::../media/legend_icon_03.svg[icône de légende 03]
 a| 
Languettes d'éjection du module DIMM



 a| 
image::../media/legend_icon_04.svg[icône de légende 04]
 a| 
Modules DIMM

|===
. Retirez le module DIMM de remplacement du sac d'expédition antistatique, tenez le module DIMM par les coins et alignez-le sur le logement.
+
L'encoche entre les broches du DIMM doit être alignée avec la languette du support.

. Insérez le module DIMM directement dans le logement.
+
Le module DIMM s'insère bien dans le logement, mais devrait être facilement installé. Si ce n'est pas le cas, réalignez le module DIMM avec le logement et réinsérez-le.

+

NOTE: Inspectez visuellement le module DIMM pour vérifier qu'il est bien aligné et complètement inséré dans le logement.

. Poussez délicatement, mais fermement, sur le bord supérieur du module DIMM jusqu'à ce que les languettes de l'éjecteur s'enclenchent sur les encoches situées aux extrémités du module DIMM.
. Reconnectez la batterie NVMRM :
+
.. Branchez la batterie NVRAM.
+
Assurez-vous que la fiche se verrouille dans la prise d'alimentation de la batterie de la carte mère.

.. Alignez la batterie avec les supports de fixation de la paroi latérale en tôle.
.. Faites glisser la batterie vers le bas jusqu'à ce que le loquet de la batterie s'enclenche et s'enclenche dans l'ouverture de la paroi latérale.


. Réinstallez le capot du module de contrôleur.




== Étape 4 : réinstallez le module de contrôleur

Réinstallez le module de contrôleur dans le châssis.

.Étapes
. Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
. Si vous ne l'avez pas encore fait, remettez le capot sur le module de contrôleur.
. Retournez le module de contrôleur et alignez l'extrémité sur l'ouverture du châssis.
. Poussez doucement le module de contrôleur à mi-chemin dans le système.alignez l'extrémité du module de contrôleur avec l'ouverture du châssis, puis poussez doucement le module de contrôleur à mi-chemin dans le système.
+

NOTE: N'insérez pas complètement le module de contrôleur dans le châssis tant qu'il n'y a pas été demandé.

. Recâblage du système, selon les besoins.
+
Si vous avez retiré les convertisseurs de support (QSFP ou SFP), n'oubliez pas de les réinstaller si vous utilisez des câbles à fibre optique.

. Terminez la réinstallation du module de contrôleur :
+
.. Avec la poignée de came en position ouverte, poussez fermement le module de contrôleur jusqu'à ce qu'il rencontre le fond de panier et soit bien en place, puis fermez la poignée de came en position verrouillée.
+

NOTE: Ne forcez pas trop lorsque vous faites glisser le module de contrôleur dans le châssis pour éviter d'endommager les connecteurs.

+
Le contrôleur commence à démarrer dès qu'il est assis dans le châssis.

.. Si ce n'est déjà fait, réinstallez le périphérique de gestion des câbles.
.. Fixez les câbles au dispositif de gestion des câbles à l'aide du crochet et de la sangle de boucle.


. Redémarrez le module contrôleur.
+

NOTE: Au cours du processus de démarrage, les invites suivantes peuvent s'afficher :

+
** Un message d'avertissement indiquant une discordance d'ID système et demandant de remplacer l'ID système.
** Un avertissement s'affiche lorsque vous passez en mode maintenance dans une configuration HA, vous devez vous assurer que le contrôleur en bon état reste arrêté. Vous pouvez répondre en toute sécurité `y` à ces invites.






== Étape 5 : restaurez le rétablissement automatique et AutoSupport

Restaurez le rétablissement automatique et les AutoSupport s'ils ont été désactivés.

. Restaurez le rétablissement automatique à l'aide de `storage failover modify -node local -auto-giveback true` commande.
. Si une fenêtre de maintenance AutoSupport a été déclenchée, mettez-la fin à l'aide du `system node autosupport invoke -node * -type all -message MAINT=END` commande.




== Étape 6 : renvoyer la pièce défaillante à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièce et amp ; remplacements"] pour plus d'informations.
