---
permalink: fas2800/rtc-battery-replace.html 
sidebar: sidebar 
keywords: fas2800, replace, real, time, clock, battery, impaired, controller, shut, down, controller, system, rtc, date, time, controller, module, reinstall, replace, open 
summary: 'Vous remplacez la batterie de l"horloge temps réel (RTC) dans le module de contrôleur afin que les services et applications de votre système qui dépendent d"une synchronisation précise de l"heure continuent de fonctionner.' 
---
= Remplacez la batterie de l'horloge temps réel - FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous remplacez la batterie de l'horloge temps réel (RTC) dans le module de contrôleur afin que les services et applications de votre système qui dépendent d'une synchronisation précise de l'heure continuent de fonctionner.

* Cette procédure peut être utilisée avec toutes les versions de ONTAP prises en charge par votre système
* Tous les autres composants du système doivent fonctionner correctement ; si ce n'est pas le cas, vous devez contacter le support technique.




== Étape 1 : arrêtez le contrôleur défaillant

Pour arrêter le contrôleur défaillant, vous devez déterminer l'état du contrôleur et, si nécessaire, prendre le contrôle de façon à ce que le contrôleur en bonne santé continue de transmettre des données provenant du stockage défaillant du contrôleur.

.Description de la tâche
* Si vous disposez d'un système SAN, vous devez avoir vérifié les messages d'événement  `cluster kernel-service show`) pour le serveur lame SCSI du contrôleur défectueux.  `cluster kernel-service show`La commande (from priv mode Advanced) affiche le nom du nœud, son état de disponibilité et link:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["état du quorum"]son état de fonctionnement.
+
Chaque processus SCSI-Blade doit se trouver au quorum avec les autres nœuds du cluster. Tout problème doit être résolu avant de procéder au remplacement.

* Si vous avez un cluster avec plus de deux nœuds, il doit être dans le quorum. Si le cluster n'est pas au quorum ou si un contrôleur en bonne santé affiche la valeur false pour l'éligibilité et la santé, vous devez corriger le problème avant de désactiver le contrôleur défaillant ; voir link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchroniser un nœud avec le cluster"^].


.Étapes
. Si AutoSupport est activé, supprimez la création automatique de cas en appelant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
Le message AutoSupport suivant supprime la création automatique de dossiers pendant deux heures : `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Désactiver le rétablissement automatique depuis la console du contrôleur sain : `storage failover modify -node local -auto-giveback false`
+

NOTE: Lorsque vous voyez _voulez-vous désactiver l'auto-giveback?_, entrez `y`.

. Faites passer le contrôleur douteux à l'invite DU CHARGEUR :
+
[cols="1,2"]
|===
| Si le contrôleur en état de fonctionnement s'affiche... | Alors... 


 a| 
Invite DU CHARGEUR
 a| 
Passez à l'étape suivante.



 a| 
Attente du retour...
 a| 
Appuyez sur Ctrl-C, puis répondez `y` lorsque vous y êtes invité.



 a| 
Invite système ou invite de mot de passe
 a| 
Prendre le contrôle défectueux ou l'arrêter à partir du contrôleur en bon état : `storage failover takeover -ofnode _impaired_node_name_`

Lorsque le contrôleur douteux s'affiche en attente de rétablissement..., appuyez sur Ctrl-C et répondez `y`.

|===




== Étape 2 : retirer le module de contrôleur

Retirez le module de contrôleur du système, puis retirez le capot du module de contrôleur.

. Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
. Desserrez le crochet et la bride de boucle qui relient les câbles au périphérique de gestion des câbles, puis débranchez les câbles système et les SFP (si nécessaire) du module de contrôleur, en maintenant une trace de l'emplacement où les câbles ont été connectés.
+
Laissez les câbles dans le périphérique de gestion des câbles de sorte que lorsque vous réinstallez le périphérique de gestion des câbles, les câbles sont organisés.

. Retirez et mettez de côté les dispositifs de gestion des câbles des côtés gauche et droit du module de contrôleur.
. Appuyez sur le loquet de la poignée de came jusqu'à ce qu'il se libère, ouvrez complètement la poignée de came pour libérer le module de contrôleur du fond de panier central, puis, à l'aide de deux mains, retirez le module de contrôleur du châssis.
+
image::../media/drw_2850_pcm_remove_install_IEOPS-694.svg[drw 2850 pcm déposer l'installation IOPS 694]

. Retournez le module de contrôleur et placez-le sur une surface plane et stable.
. Ouvrez le capot en appuyant sur les boutons bleus situés sur les côtés du module de contrôleur pour libérer le capot, puis faites pivoter le capot vers le haut et hors du module de contrôleur.
+
image::../media/drw_2850_open_controller_module_cover_IEOPS-695.svg[couvercle du module de contrôleur ouvert drw 2850 IOPS 695]





== Étape 3 : remplacer la batterie RTC

Remplacez la batterie RTC en la plaçant à l'intérieur du contrôleur et suivez la séquence spécifique des étapes.

.Animation - remplacer la batterie RTC
video::7420d100-23b1-4213-a8da-af4701725622[panopto]
image::../media/drw_2850_replace_rtc_battery_IEOPS-701.svg[drw 2850 remplacer la batterie rtc IEOPS 701]

. Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
. Localisez la batterie RTC.
. Poussez doucement la batterie hors du support, faites-la pivoter pour l'éloigner du support, puis retirez-la du support.
+

NOTE: Notez la polarité de la batterie lorsque vous la retirez du support. La batterie est signalée par un signe plus et doit être correctement positionnée dans le support. Un signe plus près du support indique comment la batterie doit être positionnée.

. Retirez la batterie de rechange du sac d'expédition antistatique.
. Localisez le support de batterie vide dans le module de contrôleur.
. Notez la polarité de la batterie RTC, puis insérez-la dans le support en inclinant la batterie et en la poussant vers le bas.
. Inspectez visuellement la batterie pour vous assurer qu'elle est complètement installée dans le support et que la polarité est correcte.




== Étape 4 : réinstallez le module de contrôleur

Réinstallez le module du contrôleur et démarrez-le à l'invite DU CHARGEUR.

. Retournez le module de contrôleur et alignez l'extrémité sur l'ouverture du châssis.
. Poussez doucement le module de contrôleur à mi-chemin dans le système.alignez l'extrémité du module de contrôleur avec l'ouverture du châssis, puis poussez doucement le module de contrôleur à mi-chemin dans le système.
+
N'insérez pas complètement le module de contrôleur dans le châssis tant qu'il n'y a pas été demandé.

. Recâblage du système, selon les besoins.
+
Si vous avez retiré les convertisseurs de support (QSFP ou SFP), n'oubliez pas de les réinstaller si vous utilisez des câbles à fibre optique.

. Si les blocs d'alimentation ont été débranchés, rebranchez-les et réinstallez les dispositifs de retenue du câble d'alimentation.
. Terminez la réinstallation du module de contrôleur :


image::../media/drw_2850_pcm_remove_install_IEOPS-694.svg[drw 2850 pcm déposer l'installation IOPS 694]

. Avec la poignée de came en position ouverte, poussez fermement le module de contrôleur jusqu'à ce qu'il rencontre le fond de panier et soit bien en place, puis fermez la poignée de came en position verrouillée.
+

NOTE: Ne forcez pas trop lorsque vous faites glisser le module de contrôleur dans le châssis pour éviter d'endommager les connecteurs.

+
Le contrôleur commence à démarrer dès qu'il est assis dans le châssis.

. Si ce n'est déjà fait, réinstallez le périphérique de gestion des câbles.
. Fixez les câbles au dispositif de gestion des câbles à l'aide du crochet et de la sangle de boucle.
. Rebranchez les câbles d'alimentation aux blocs d'alimentation et aux sources d'alimentation, puis mettez le système sous tension pour démarrer le processus d'amorçage.
. Arrêtez le contrôleur à l'invite DU CHARGEUR.




== Étape 5 : réglez l'heure/la date après le remplacement de la batterie RTC

. Réinitialiser l'heure et la date sur le contrôleur :
+
.. Vérifiez la date et l'heure sur le contrôleur en bon état à l'aide du `show date` commande.
.. À l'invite DU CHARGEUR sur le contrôleur cible, vérifier l'heure et la date.
.. Si nécessaire, modifiez la date avec le `set date mm/dd/yyyy` commande.
.. Si nécessaire, réglez l'heure, en GMT, à l'aide du `set time hh:mm:ss` commande.
.. Confirmez la date et l'heure sur le contrôleur cible.


. À l'invite DU CHARGEUR, entrez `bye` Pour réinitialiser les cartes PCIe et d'autres composants et laisser le contrôleur redémarrer.
. Rétablir le fonctionnement normal du contrôleur en renvoie son espace de stockage : `storage failover giveback -ofnode _impaired_node_name_`
. Restaurez le rétablissement automatique à l'aide de `storage failover modify -node local -auto-giveback true` commande.
. Si une fenêtre de maintenance AutoSupport a été déclenchée, mettez-la fin à l'aide du `system node autosupport invoke -node * -type all -message MAINT=END` commande.




== Étape 6 : renvoyer la pièce défaillante à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièces et remplacements"] page pour plus d'informations.
