---
permalink: asa250/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa a250, replace the boot media 
summary: Avant de remplacer le support de démarrage de votre ASA A250, assurez-vous de respecter les conditions nécessaires à un remplacement réussi. 
---
= Exigences pour la récupération automatisée du support de démarrage - ASA A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre ASA A250, assurez-vous de respecter les conditions requises pour une opération réussie. Cela inclut la vérification que vous disposez du support de démarrage de remplacement adéquat, la confirmation que le port e0S (e0M wrench) du contrôleur défectueux n'est pas endommagé, et la détermination de l'activation de Onboard Key Manager (OKM) ou External Key Manager (EKM).

Le processus de récupération automatique du support de démarrage est pris en charge uniquement dans ONTAP 9.18.1 et versions ultérieures. Si votre système de stockage exécute une version antérieure d'ONTAP, utilisez le link:bootmedia-replace-workflow.html["procédure de récupération de démarrage manuel"].

* Vous devez remplacer le composant défectueux par un composant FRU de remplacement de même capacité que celle reçue de NetApp.
* Vérifiez que le port e0M (clé) du contrôleur défectueux est connecté et n'est pas défectueux.
+
Le port e0M est utilisé pour communiquer entre les deux contrôleurs pendant le processus de récupération de démarrage automatisé.

* Pour OKM, vous avez besoin de la phrase secrète à l'échelle du cluster ainsi que des données de sauvegarde.
* Pour EKM, vous avez besoin de copies des fichiers suivants à partir du nœud partenaire :
+
** fichier /cfcard/kmip/servers.cfg.
** fichier /cfcard/kmip/certs/client.crt.
** fichier /cfcard/kmip/certs/client.key.
** Fichier /cfcard/kmip/certs/CA.pem.


* Il est essentiel d'appliquer les commandes au contrôleur approprié lorsque vous remplacez le support de démarrage défectueux :
+
** Le _contrôleur défaillant_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le _contrôleur sain_ est le partenaire HA du contrôleur altéré.




.Et la suite
Après avoir examiné la configuration requise pour le support de démarrage, vous link:bootmedia-shutdown-bmr.html["arrêter le contrôleur"].
