---
permalink: asa250/overview.html 
sidebar: sidebar 
keywords: ASA A250 specifications, ASA A250 specs, NetApp ASA A250, ASA A250 hardware 
summary: Spécifications clés du système de stockage ASA A250 
---
= Spécifications clés de ASA A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour l' ASA A250.  Visite https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) pour une liste complète des spécifications ASA A250 .  Cette page reflète une seule paire à haute disponibilité.



=== Spécifications clés de ASA A250

Configuration de la plateforme : paire HA à châssis simple ASA A250 100 V

Capacité brute maximale : 0,7344 Po

Mémoire : 128.0000 Go

Facteur de forme : châssis 2U avec 2 contrôleurs HA et 24 emplacements pour disques

Version ONTAP : b_startONTAP : 9.16.1P2b_end

Emplacements d'extension PCIe : 4

Version minimale ONTAP : ONTAP 9.13.1



=== Maximums de mise à l'échelle

|===


| Type | Paires HA | Capacité brute | Mémoire maximale 


| NAS |  |  |  


| SAN | 6 | 4,4 Po / 3,9 PiB | 768 Go 


| Paire haute disponibilité |  | 0,7 Po / 0,7 PiB | 128,0000 
|===


=== IO



==== E/S embarquées

|===


| Protocole | Ports 


| Ethernet 25 Gbit/s | 4 


| Ethernet 10 Gbit/s | 4 
|===


==== E/S totales

|===


| Protocole | Ports 


| Ethernet 100 Gbit/s | 4 


| Ethernet 25 Gbit/s | 12 


| Ethernet 10 Gbit/s | 4 


| FC 32 Gbit/s | 8 


| NVMe/FC 32 Gbit/s | 8 


|  | 0 
|===


==== Ports de gestion

|===


| Protocole | Ports 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== Réseau de stockage pris en charge

FC ; iSCSI ; NVMe/FC ; NVMe/TCP ;



=== Spécifications de l'environnement système

Aucune donnée environnementale disponible.



=== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




=== Haute disponibilité

Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP ; contrôleurs redondants remplaçables à chaud ; alimentations redondantes remplaçables à chaud ; gestion SAS en bande via des connexions SAS pour les étagères externes ; [//] 2025-10-15 ontap-systems-internal/issues/1357
