---
permalink: c30-60/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff c30, aff c60, replace the boot media 
summary: Découvrez la configuration requise pour le remplacement du support de démarrage. 
---
= Exigences et considérations - AFF C30 et AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage, vérifiez les conditions et considérations suivantes.



== De formation

* Vous devez disposer d'une clé USB, formatée en FAT32, avec la quantité de stockage appropriée pour maintenir le `image_xxx.tgz`.
* Vous devez copier le `image_xxx.tgz` fichier sur la clé USB pour pouvoir l'utiliser ultérieurement dans cette procédure.
* Vous devez remplacer le composant défectueux par un composant FRU de remplacement de la même capacité que celle reçue de votre fournisseur.




== Considérations

* Il est important d'appliquer les commandes au cours de la procédure suivante sur le contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le contrôleur _Healthy_ est le partenaire HA du contrôleur déficient.


* Si nécessaire, vous pouvez allumer les voyants d'emplacement du châssis de la plate-forme (bleus) pour faciliter la localisation physique de la plate-forme concernée. Connectez-vous au BMC à l'aide de SSH et entrez `system location-led _on_` la commande.
+
Un châssis de plate-forme comporte trois voyants d'emplacement : un sur le panneau de commande et un sur chaque contrôleur. Les LED d'emplacement restent allumées pendant 30 minutes.

+
Vous pouvez les désactiver en entrant `system location-led _off_` la commande. Si vous n'êtes pas sûr que les LED soient allumées ou éteintes, vous pouvez vérifier leur état en entrant `system location-led show` la commande.


