---
permalink: c30-60/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: aff c30, aff c60, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: 'Vérifiez que la configuration haute disponibilité du contrôleur est active et qu"elle fonctionne correctement dans votre système de stockage AFF C30 ou AFF C60, puis vérifiez que les adaptateurs du système répertorient tous les chemins d"accès aux disques.' 
---
= Restaurez et vérifiez la configuration du système - AFF C30 et AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vérifiez que la configuration haute disponibilité du contrôleur est active et qu'elle fonctionne correctement dans votre système de stockage AFF C30 ou AFF C60, puis vérifiez que les adaptateurs du système répertorient tous les chemins d'accès aux disques.

Vérifiez la configuration système de bas niveau du contrôleur de remplacement et reconfigurez les paramètres système si nécessaire.



== Étape 1 : vérifiez les paramètres de configuration haute disponibilité

Vous devez vérifier `HA` l'état du contrôleur et, si nécessaire, mettre à jour l'état pour qu'il corresponde à la configuration de votre système de stockage.

. Démarrage en mode maintenance :
+
`boot_ontap maint`

+
.. Entrez `y` lorsque vous voyez _Continuer avec boot?_.
+
Si le message d'avertissement _ID système incorrect_ s'affiche, entrez `y`.



. Saisir `sysconfig -v` et capturer le contenu de l'affichage.
+

NOTE: Si vous voyez _INADÉQUATION DE PERSONNALITÉ_, contactez le service clientèle.

. A partir du `sysconfig -v` résultat, comparez les informations de la carte adaptateur avec les cartes et les emplacements dans le contrôleur de remplacement.
. Vérifier que tous les composants affichent le même `HA` état :
+
`ha-config show`

+
L'état de la HA doit être le même pour tous les composants.

. Si l'état système affiché du contrôleur ne correspond pas à la configuration de votre système de stockage, définissez l' `HA`état du contrôleur :
+
`ha-config modify controller ha-state`

+
La valeur de HA-State peut être l'une des suivantes :

+
** `ha`
** `non-ha` (non pris en charge)


. Vérifiez que le paramètre a changé :
+
`ha-config show`





== Étape 2 : vérifiez la liste des disques

. Vérifiez que l'adaptateur liste les chemins d'accès à tous les disques :
+
`storage show disk -p`

+
En cas de problème, vérifiez le câblage et réinstallez les câbles.

. Quitter le mode Maintenance :
+
`halt`



.Et la suite ?
Après avoir restauré et vérifié la configuration système de votre système AFF C30 ou AFF C60, vous devez link:controller-replace-recable-reassign-disks.html["remettez le contrôleur en place"].
