---
permalink: c30-60/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff c30, aff c60, prerequisite, replace the controller module 
summary: 'Avant de remplacer le contrôleur de votre système de stockage AFF C30 ou AFF C60, assurez-vous de répondre aux exigences nécessaires pour un remplacement réussi.  Cela comprend la vérification du bon fonctionnement de tous les autres composants du système, la vérification que vous disposez du contrôleur de remplacement approprié et l"enregistrement de la sortie de la console du contrôleur dans un fichier journal texte.' 
---
= Conditions requises pour remplacer le contrôleur - AFF C30 et AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le contrôleur de votre système de stockage AFF C30 ou AFF C60, assurez-vous de répondre aux exigences nécessaires pour un remplacement réussi.  Cela comprend la vérification du bon fonctionnement de tous les autres composants du système, la vérification que vous disposez du contrôleur de remplacement approprié et l'enregistrement de la sortie de la console du contrôleur dans un fichier journal texte.

Revoir les exigences et les considérations relatives à la procédure de remplacement du contrôleur.



== De formation

* Toutes les tablettes doivent fonctionner correctement.
* Le contrôleur sain doit pouvoir reprendre le contrôleur qui est remplacé (appelé « contrôleur défectueux » dans cette procédure).
* Si votre système est dans une configuration MetroCluster, vous devez passer en revue la section https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Choix de la procédure de récupération correcte"] pour déterminer si vous devez utiliser cette procédure.
* Vous devez remplacer un contrôleur par un contrôleur de même type. Vous ne pouvez pas mettre à niveau votre système en remplaçant simplement le contrôleur.
* Vous ne pouvez pas modifier de disques ou de tiroirs dans le cadre de cette procédure.
* Vous devez toujours capturer la sortie de la console du contrôleur dans un fichier journal texte.
+
Le résultat de la console vous fournit un enregistrement de la procédure que vous pouvez utiliser pour résoudre les problèmes que vous pourriez rencontrer pendant le processus de remplacement.





== Considérations

Il est important d'appliquer les commandes de cette procédure au contrôleur approprié :

* Le contrôleur _trouble_ est le contrôleur qui est en cours de remplacement.
* Le contrôleur _remplacement_ est le nouveau contrôleur qui remplace le contrôleur défaillant.
* Le contrôleur _Healthy_ est le contrôleur survivant.


.Et la suite ?
Après avoir passé en revue les conditions requises pour remplacer le contrôleur défectueux, vous devez link:controller-replace-shutdown.html["arrêtez le contrôleur défectueux"].
