---
permalink: c30-60/io-module-overview.html 
sidebar: sidebar 
keywords: AFF c30, AFF c60, replace io module 
summary: 'Les systèmes AAF C30 et AFF C60 offrent une grande flexibilité d"extension ou de remplacement des modules d"E/S pour améliorer la connectivité et les performances du réseau. L"ajout ou le remplacement d"un module d"E/S est essentiel lors de la mise à niveau des capacités réseau ou de l"adressage d"un module défaillant.' 
---
= Présentation de l'ajout et du remplacement du module d'E/S - AFF C30 et AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes AFF C30 et AFF C60 permettent d'étendre ou de remplacer des modules d'E/S de manière flexible afin d'améliorer la connectivité et les performances du réseau. L'ajout ou le remplacement d'un module d'E/S est essentiel lors de la mise à niveau des capacités réseau ou de l'adressage d'un module défaillant.

* link:io-module-add.html["Ajoutez un module d'E/S."]
+
L'ajout de modules d'E/S supplémentaires peut améliorer la redondance et garantir que le système de stockage reste opérationnel même en cas de défaillance d'un module d'E/S.

* link:io-module-replace.html["Remplacez un module d'E/S."]
+
Le remplacement d'un module d'E/S défaillant permet de rétablir l'état de fonctionnement optimal du système de stockage.


