---
permalink: c30-60/overview.html 
sidebar: sidebar 
keywords: AFF C30 C60 specifications, AFF C30 C60 specs, AFF C30 C60 capacity, AFF C30 C60 memory, AFF C30 C60 I/O, AFF C30 C60 compliance 
summary: Spécifications clés du groupe de plateformes C30-60 
---
= Spécifications clés du groupe de plateformes C30-60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour le groupe de plates-formes C30-60.  Visite https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) pour une liste complète des spécifications.  Cette page reflète une seule paire à haute disponibilité.



== AFF C60



=== Spécifications clés de AFF C60

Configuration de la plateforme : paire de châssis simple HA AFF C60

Capacité brute maximale : 7,3680 Po

Mémoire : 128.0000 Go

Facteur de forme : châssis 2U avec 2 contrôleurs HA et 24 emplacements pour disques

Version ONTAP : b_startONTAP : 9.16.1P2b_end

Emplacements d'extension PCIe : 8

Version minimale ONTAP : ONTAP 9.16.1RC1



=== Maximums de mise à l'échelle

|===


| Type | Paires HA | Capacité brute | Mémoire maximale 


| NAS | 4 | 29,5 Po / 26,2 PiB | 512 Go 


| SAN | 4 | 29,5 Po / 26,2 PiB | 512 Go 


| Paire haute disponibilité |  | 7,4 Po / 6,5 PiB | 128,0000 
|===


=== IO



==== E/S embarquées

Aucune donnée IO embarquée.



==== E/S totales

|===


| Protocole | Ports 


| Ethernet 100 Gbit/s | 16 


| Ethernet 25 Gbit/s | 24 


| Ethernet 10 Gbit/s | 24 


| FC 64 Gbit/s | 24 


| NVMe/FC 64 Gbit/s | 24 


|  | 0 
|===


==== Ports de gestion

|===


| Protocole | Ports 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2 
|===


=== Réseau de stockage pris en charge

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC ; NVMe/TCP; S3; S3 avec NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Spécifications de l'environnement système

* Puissance typique : 2892 BTU/h
* Puissance dans le pire des cas : 4 445 BTU/h
* Poids : 60,7 lb 27,5 kg
* Hauteur : 2U
* Largeur : conforme aux normes de rack IEC 19" (17,6" 44,7 cm)
* Profondeur:
* Température/Altitude/Humidité de fonctionnement : 10 °C à 35 °C (50 °F à 95 °F) jusqu’à 3 048 m (10 000 pi) d’altitude ; 8 % à 80 % d’humidité relative, sans condensation
* Température et humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu’à 12 192 m (40 000 pi), 10 % à 95 % d’humidité relative, sans condensation, dans son emballage d’origine.
* Niveau sonore : Puissance acoustique déclarée (LwAd) : 8,0 ; Pression acoustique (LpAm) (positions des passants) : 70,5 dB




=== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




=== Haute disponibilité

Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP ; Contrôleurs redondants remplaçables à chaud ; Alimentations redondantes remplaçables à chaud ;



== AFF C30



=== Spécifications clés de AFF C30

Configuration de la plateforme : paire HA à châssis simple AFF C30

Capacité brute maximale : 2,2104 Po

Mémoire : 128.0000 Go

Facteur de forme : châssis 2U avec 2 contrôleurs HA et 24 emplacements pour disques

Version ONTAP : b_startONTAP : 9.16.1P2b_end

Emplacements d'extension PCIe : 8

Version minimale ONTAP : ONTAP 9.16.1RC1



=== Maximums de mise à l'échelle

|===


| Type | Paires HA | Capacité brute | Mémoire maximale 


| NAS | 4 | 8,8 Po / 7,9 PiB | 512 Go 


| SAN | 4 | 8,8 Po / 7,9 PiB | 512 Go 


| Paire haute disponibilité |  | 2,2 Po / 2,0 PiB | 128,0000 
|===


=== IO



==== E/S embarquées

Aucune donnée IO embarquée.



==== E/S totales

|===


| Protocole | Ports 


| Ethernet 100 Gbit/s | 16 


| Ethernet 25 Gbit/s | 24 


| Ethernet 10 Gbit/s | 24 


| FC 64 Gbit/s | 24 


| NVMe/FC 64 Gbit/s | 24 


|  | 0 
|===


==== Ports de gestion

|===


| Protocole | Ports 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2 
|===


=== Réseau de stockage pris en charge

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC ; NVMe/TCP; S3; S3 avec NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Spécifications de l'environnement système

* Puissance typique : 2892 BTU/h
* Puissance dans le pire des cas : 4 445 BTU/h
* Poids : 60,7 lb 27,5 kg
* Hauteur : 2U
* Largeur : conforme aux normes de rack IEC 19" (17,6" 44,7 cm)
* Profondeur:
* Température/Altitude/Humidité de fonctionnement : 10 °C à 35 °C (50 °F à 95 °F) jusqu’à 3 048 m (10 000 pi) d’altitude ; 8 % à 80 % d’humidité relative, sans condensation
* Température et humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu’à 12 192 m (40 000 pi), 10 % à 95 % d’humidité relative, sans condensation, dans son emballage d’origine.
* Niveau sonore : Puissance acoustique déclarée (LwAd) : 8,0 ; Pression acoustique (LpAm) (positions des passants) : 70,5 dB




=== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




=== Haute disponibilité

Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP ; Contrôleurs redondants remplaçables à chaud ; Alimentations redondantes remplaçables à chaud ;
