---
permalink: a20-30-50/a30-key-specifications.html 
sidebar: sidebar 
keywords: AFF A30 specifications, AFF A30 specs, AFF A30 capacity, AFF A30 memory, AFF A30 I/O, AFF A30 compliance 
summary: Spécifications clés de AFF A30 
---
= Spécifications clés de AFF A30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour le système de stockage AFF A30 dans une seule paire haute disponibilité.  Visitez NetApp Hardware Universe (HWU) pour obtenir les spécifications complètes de ce système de stockage.



== Aperçu des spécifications de AFF A30

* Configuration de la plateforme : paire HA à châssis simple AFF A30
* Capacité brute maximale : 4,0392 Po
* Mémoire : 128.0000 Go
* Facteur de forme : châssis 2U avec 2 contrôleurs HA et 24 emplacements pour disques
* Version ONTAP : ONTAP: 9.16.1P2
* Emplacements d'extension PCIe : 8
* Version minimale ONTAP : ONTAP 9.16.1RC1




== Maximums de mise à l'échelle

* Type : NAS ; Paires HA : 4 ; Capacité brute : 16,2 Po / 14,3 PiB ; Mémoire maximale : 512 Go
* Type : SAN ; paires HA : 4 ; capacité brute : 16,2 Po / 14,3 PiB ; mémoire maximale : 512 Go
* Type : Paire HA ; Capacité brute : 4,0 Po / 3,6 PiB ; Mémoire maximale : 128 0000




== E/S



=== E/S embarquées

Aucune donnée d'E/S intégrée.



=== E/S totales

* Protocole : Ethernet 100 Gbps ; Ports : 16
* Protocole : Ethernet 25 Gbit/s ; Ports : 24
* Protocole : Ethernet 10 Gbit/s ; Ports : 24
* Protocole : FC 64 Gbps ; Ports : 24
* Protocole : NVMe/FC 64 Gbit/s ; Ports : 24
* Ports : 0
* Protocole : SAS 12 Gbit/s ; Ports : 16




=== Ports de gestion

* Protocole : Ethernet 1 Gbps ; Ports : 2
* Protocole : RS-232 115 Kbps ; Ports : 4
* Protocole : USB 600 Mbps ; Ports : 2




== Prise en charge du réseau de stockage

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NVMe/FC
* NVMe/TCP
* S3
* S3 avec NAS
* PME 2.0
* PME 2.1
* SMB 2.x
* PME 3.0
* PME 3.1
* SMB 3.1.1




== Spécifications de l'environnement système

* Puissance typique : 2892 BTU/h
* Puissance dans le pire des cas : 4 445 BTU/h
* Poids : 60,7 lb, 27,5 kg
* Hauteur : 2U
* Largeur : conforme aux normes de rack IEC 19" (17,6" 44,7 cm)
* Profondeur:
* Température/Altitude/Humidité de fonctionnement : 10 °C à 35 °C (50 °F à 95 °F) jusqu’à 3 048 m (10 000 pi) d’altitude ; 8 % à 80 % d’humidité relative, sans condensation
* Température et humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu’à 12 192 m (40 000 pi) ; humidité relative de 10 % à 95 %, sans condensation, dans son emballage d’origine.
* Niveau sonore : Puissance acoustique déclarée (LwAd) : 8,0 ; Pression acoustique (LpAm) (positions des passants) : 70,5 dB




== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




== Haute disponibilité

* Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP
* Contrôleurs redondants remplaçables à chaud
* Alimentations redondantes remplaçables à chaud
* Gestion SAS en bande via des connexions SAS pour les étagères externes

