---
permalink: a20-30-50/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, shut down the controller 
summary: Arrêtez le contrôleur défectueux de votre système de stockage AFF A20, AFF A30 ou AFF A50 pour éviter la perte de données et maintenir la stabilité du système pendant le processus de récupération du support de démarrage manuel. 
---
= Arrêtez le contrôleur pour la récupération manuelle du support de démarrage - AFF A20, AFF A30 et AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arrêtez le contrôleur défectueux de votre système de stockage AFF A20, AFF A30 ou AFF A50 pour éviter la perte de données et maintenir la stabilité du système pendant le processus de récupération du support de démarrage manuel.

[role="tabbed-block"]
====
.Option 1 : la plupart des systèmes
--
Pour arrêter le contrôleur défaillant, vous devez déterminer l'état du contrôleur et, si nécessaire, prendre le contrôle de façon à ce que le contrôleur en bonne santé continue de transmettre des données provenant du stockage défaillant du contrôleur.

.Description de la tâche
* Si vous disposez d'un système SAN, vous devez avoir vérifié les messages d'événement  `cluster kernel-service show`) pour le serveur lame SCSI du contrôleur défectueux.  `cluster kernel-service show`La commande (from priv mode Advanced) affiche le nom du nœud, son état de disponibilité et link:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["état du quorum"]son état de fonctionnement.
+
Chaque processus SCSI-Blade doit se trouver au quorum avec les autres nœuds du cluster. Tout problème doit être résolu avant de procéder au remplacement.

* Si vous avez un cluster avec plus de deux nœuds, il doit être dans le quorum. Si le cluster n'est pas au quorum ou si un contrôleur en bonne santé affiche la valeur false pour l'éligibilité et la santé, vous devez corriger le problème avant de désactiver le contrôleur défaillant ; voir link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchroniser un nœud avec le cluster"^].


.Étapes
. Si AutoSupport est activé, supprimez la création automatique de dossier en invoquant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
Le message AutoSupport suivant supprime la création automatique de dossiers pendant deux heures :

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Désactiver le retour automatique :
+
.. Entrez la commande suivante depuis la console du contrôleur sain :
+
`storage failover modify -node _impaired_node_name_ -auto-giveback false`

.. Entrer `y` lorsque vous voyez l'invite _Voulez-vous désactiver le retour automatique ?_


. Faites passer le contrôleur douteux à l'invite DU CHARGEUR :
+
[cols="1,2"]
|===
| Si le contrôleur en état de fonctionnement s'affiche... | Alors... 


 a| 
Invite DU CHARGEUR
 a| 
Passez à l'étape suivante.



 a| 
Attente du retour...
 a| 
Appuyez sur Ctrl-C, puis répondez `y` lorsque vous y êtes invité.



 a| 
Invite système ou invite de mot de passe
 a| 
Prendre le contrôle défectueux ou l'arrêter à partir du contrôleur en bon état :

`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

Le paramètre _-halt true_ vous amène à l'invite Loader.

|===


--
.Option 2 : le contrôleur est dans un MetroCluster
--
Pour arrêter le contrôleur défaillant, vous devez déterminer l'état du contrôleur et, si nécessaire, prendre le contrôle de façon à ce que le contrôleur en bonne santé continue de transmettre des données provenant du stockage défaillant du contrôleur.

* Si vous avez un cluster avec plus de deux nœuds, il doit être dans le quorum. Si le cluster n'est pas au quorum ou si un contrôleur en bonne santé affiche la valeur false pour l'éligibilité et la santé, vous devez corriger le problème avant de désactiver le contrôleur défaillant ; voir link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchroniser un nœud avec le cluster"^].
* Vous devez avoir confirmé que l'état de configuration MetroCluster est configuré et que les nœuds sont dans un état activé et normal :
+
`metrocluster node show`



.Étapes
. Si AutoSupport est activé, supprimez la création automatique de dossier en invoquant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`

+
Le message AutoSupport suivant supprime la création automatique de dossiers pendant deux heures :

+
`cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Désactiver le retour automatique :
+
.. Entrez la commande suivante depuis la console du contrôleur sain :
+
`storage failover modify -node local -auto-giveback false`

.. Entrer `y` lorsque vous voyez l'invite _Voulez-vous désactiver le retour automatique ?_


. Faites passer le contrôleur douteux à l'invite DU CHARGEUR :
+
[cols="1,2"]
|===
| Si le contrôleur en état de fonctionnement s'affiche... | Alors... 


 a| 
Invite DU CHARGEUR
 a| 
Passez à la section suivante.



 a| 
Attente du retour...
 a| 
Appuyez sur Ctrl-C, puis répondez `y` lorsque vous y êtes invité.



 a| 
Invite système ou invite de mot de passe (entrer le mot de passe système)
 a| 
Prendre le contrôle défectueux ou l'arrêter à partir du contrôleur en bon état :

`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

Le paramètre _-halt true_ vous amène à l'invite Loader.

|===


--
====
.Et la suite ?
Après l'arrêt du contrôleur, vous devez link:bootmedia-replace.html["remplacez le support de démarrage"].
