---
permalink: a20-30-50/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, replace the boot media 
summary: 'Avant de remplacer le support de démarrage de votre système de stockage AFF A20, AFF A30 et AFF A50, assurez-vous de répondre aux exigences nécessaires pour un remplacement réussi. Cela inclut la vérification que vous disposez du support de démarrage de remplacement approprié, la confirmation que le port e0S (clé e0M) du contrôleur défectueux fonctionne correctement et la détermination si le gestionnaire de clés intégré (OKM) ou le gestionnaire de clés externe (EKM) est activé.' 
---
= Exigences pour la récupération automatique du support de démarrage - AFF A20, AFF A30 et AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système de stockage AFF A20, AFF A30 et AFF A50, assurez-vous de respecter les conditions requises pour un remplacement réussi. Cela inclut la vérification du support de démarrage de remplacement approprié, le bon fonctionnement du port e0S (clé e0M) du contrôleur défectueux et l'activation du gestionnaire de clés intégré (OKM) ou du gestionnaire de clés externe (EKM).

La récupération automatique du support de démarrage est prise en charge uniquement dans ONTAP 9.17.1 et versions ultérieures. Si votre système de stockage exécute une version antérieure d' ONTAP, utilisez l'option link:bootmedia-replace-workflow.html["procédure de récupération de démarrage manuel"] .

Passez en revue les exigences suivantes.

* Vous devez remplacer le composant défectueux par un composant FRU de remplacement de même capacité que celle reçue de NetApp.
* Le port e0S (clé e0M) est utilisé pour la communication entre les deux contrôleurs lors du processus de récupération automatique au démarrage. Assurez-vous que le port e0S du contrôleur défectueux fonctionne correctement.
* Pour OKM, vous avez besoin du contenu du fichier de phrase de passe OKM.
* Pour EKM, vous avez besoin de copies des fichiers suivants à partir du nœud partenaire :
+
** fichier /cfcard/kmip/servers.cfg.
** fichier /cfcard/kmip/certs/client.crt.
** fichier /cfcard/kmip/certs/client.key.
** Fichier /cfcard/kmip/certs/CA.pem.


* Il est essentiel d'appliquer les commandes au contrôleur approprié lorsque vous remplacez le support de démarrage défectueux :
+
** Le _contrôleur défaillant_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le _contrôleur sain_ est le partenaire HA du contrôleur altéré.




.Et la suite
Après avoir examiné la configuration requise pour le support de démarrage, vous link:bootmedia-shutdown-bmr.html["arrêter le contrôleur"].
