---
permalink: a20-30-50/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, shutdown the controllers 
summary: Arrêtez les contrôleurs de votre système de stockage AFF A20, AFF A30 ou AFF A50 pour éviter toute perte de données et assurer la stabilité du système lors du remplacement du châssis. 
---
= Arrêter les contrôleurs pour remplacer le châssis - AFF A20, AFF A30 et AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arrêtez les contrôleurs de votre système de stockage AFF A20, AFF A30 ou AFF A50 pour éviter toute perte de données et assurer la stabilité du système lors du remplacement du châssis.

Cette procédure concerne les systèmes ayant des configurations à deux nœuds. Pour plus d'informations sur l'arrêt normal lors de la maintenance d'un cluster, reportez-vous à la section https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["Arrêtez et mettez sous tension votre système de stockage - Guide de résolution - base de connaissances NetApp"].

.Avant de commencer
* Vérifiez que vous disposez des autorisations et des informations d'identification nécessaires :
+
** Informations d'identification de l'administrateur local pour ONTAP.
** Accessibilité BMC pour chaque contrôleur.


* Assurez-vous de disposer des outils et de l'équipement nécessaires pour le remplacement.


.Étapes
. Connectez-vous au cluster via SSH ou connectez-vous à un nœud du cluster à l'aide d'un câble de console local et d'un ordinateur portable/d'une console.
. Empêchez tous les clients/hôtes d'accéder aux données sur le système NetApp.
. Suspendre les tâches de sauvegarde externes.
. Si AutoSupport est activé, supprimez la création de dossiers et indiquez combien de temps le système doit rester hors ligne :
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. Identifier l'adresse SP/BMC de tous les nœuds du cluster :
+
`system service-processor show -node * -fields address`

. Quitter le cluster shell :
+
`exit`

. Connectez-vous au SP/BMC de chaque contrôleur en utilisant l'adresse IP identifiée à l'étape précédente :
+
** Si vous vous connectez depuis le BMC via SSH, connectez-vous en utilisant l'adresse SP/BMC (par exemple, `ssh admin@<SP/BMC_address>`), puis entrez la commande `system console` et authentifiez-vous.
** Si vous utilisez une console locale ou un ordinateur portable connecté directement au contrôleur, connectez-vous en utilisant les mêmes identifiants d'administrateur du cluster.


. Arrêtez les deux nœuds situés dans le châssis défectueux :
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Pour les clusters qui utilisent SnapMirror en mode synchrone : `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Entrez *y* pour chaque contrôleur du cluster lorsque vous voyez :
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. Attendez que chaque contrôleur s'arrête et affichez l'invite DU CHARGEUR.


.Et la suite ?
Après avoir arrêté les contrôleurs, vous devez link:chassis-replace-move-hardware.html["remplacez le châssis"].
