---
permalink: a20-30-50/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Pour restaurer votre système à son fonctionnement complet, vous devez vérifier les LIF, vérifier l"état du cluster et renvoyer la pièce défaillante à NetApp.' 
---
= Remplacement complet du contrôleur - AFF A20, AFF A30 et AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour rétablir le fonctionnement complet de votre système de stockage, vous devez vérifier les LIF, vérifier l'état du cluster et renvoyer la pièce défaillante à NetApp.



== Étape 1 : vérifier la LIF et la santé du cluster

Avant de renvoyer le _replacement_ node à service, vérifiez que les LIFs se trouvent sur leurs ports home, vérifiez l'état du cluster et réinitialisez le rétablissement automatique.

.Étapes
. Vérifiez que les interfaces logiques sont bien placées sur leur serveur domestique et leurs ports : `network interface show -is-home false`
+
Si des LIFs sont répertoriées comme faux, restaurez-les sur leurs ports de home port : `network interface revert -vserver * -lif *`

. Vérifiez l'état de santé de votre cluster. Consultez https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Procédure de vérification de l'état du cluster à l'aide d'un script dans ONTAP"^] l'article de la base de connaissances pour plus d'informations.
. Si le retour automatique a été désactivé, réactivez-le : `storage failover modify -node local -auto-giveback true`




== Étape 2 : renvoyer la pièce défectueuse à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièces et remplacements"] page pour plus d'informations.
