---
sidebar: sidebar 
permalink: a20-30-50/install-requirements.html 
keywords: aff a20, aff a30, aff a50, install, setup, cautions 
summary: 'Passez en revue l"équipement nécessaire et les précautions de levage pour votre plate-forme et vos étagères.' 
---
= Exigences et considérations relatives à l'installation - AFF A20, AFF A30 et AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Consultez les conditions requises et les considérations relatives à votre système de stockage AFF A20, AFF A30 ou AFF A50.



== Équipement nécessaire pour l'installation

Pour installer votre système de stockage, vous avez besoin de l'équipement et des outils suivants.

* Accès à un navigateur Web pour configurer votre système de stockage
* Sangle de décharge électrostatique (ESD)
* Lampe de poche
* Ordinateur portable ou console avec connexion USB/série
* Trombone ou stylo à pointe sphérique à pointe étroite pour le réglage des ID de tablette de stockage NS224
* Tournevis Phillips n°2




== Précautions de levage

Les systèmes de stockage et les tiroirs sont lourds. Faites preuve de prudence lorsque vous soulevez et déplacez ces éléments.



=== Poids du système de stockage

Prenez les précautions nécessaires lors du déplacement ou du levage de votre système de stockage.

Un système de stockage A20, A30 ou A50 peut peser jusqu'à 27.9 kg (61.5 lb). Pour soulever le système de stockage, faire appel à deux personnes ou à un relevage hydraulique.

image::../media/drw_g_lifting_weight_ieops-1831.svg[AFF A20,A30,or an A50 weight caution icon]



=== Poids de la tablette

Prenez les précautions nécessaires lorsque vous déplacez ou soulevez votre tablette.

Une étagère NS224 avec modules NSM100B peut peser jusqu'à 25.8 kg (56.8 lb). Pour soulever la tablette, faites appel à deux personnes ou à un dispositif de levage hydraulique. Conservez tous les composants dans la tablette (à l'avant et à l'arrière) pour éviter de rééquilibrer le poids de la tablette.

image::../media/drw_ns224_nsm100b_lifting_weight_ieops-1832.svg[NS224 avec précaution de levage NSM100b]

.Informations associées
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informations de sécurité et avis réglementaires"^]


.Et la suite ?
Après avoir pris en compte la configuration requise et les considérations relatives à votre système de stockage, vous link:install-prepare.html["avant l'installation"].
