---
permalink: a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: aff a20, aff a30, and aff a50, replace io module, add io module, hotswap io module 
summary: 'Les systèmes de stockage AFF A20, AFF A30 et AFF A50 offrent une grande flexibilité pour l"extension ou le remplacement des modules d"E/S afin d"améliorer la connectivité et les performances du réseau. L"ajout, le remplacement à chaud ou le remplacement d"un module d"E/S est essentiel pour mettre à niveau les capacités réseau ou résoudre un problème de module défaillant.' 
---
= Présentation de la maintenance des modules d'E/S - AFF A20, AFF A30 et AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes de stockage AFF A20, AFF A30 et AFF A50 offrent une grande flexibilité pour l'extension ou le remplacement des modules d'E/S afin d'améliorer la connectivité et les performances du réseau. L'ajout, le remplacement à chaud ou le remplacement d'un module d'E/S est essentiel pour mettre à niveau les capacités réseau ou résoudre un problème de module défaillant.

* link:io-module-add.html["Ajoutez un module d'E/S."]
+
Vous pouvez ajouter des modules d'E/S pour améliorer la redondance, ce qui permet de garantir que le système de stockage reste opérationnel même si un module d'E/S tombe en panne. Vous pouvez ajouter des modules d'E/S lorsqu'il y a des emplacements disponibles ou lorsque tous les emplacements sont entièrement occupés.

* link:io-module-hotswap.html["Remplacer à chaud un module d'E/S"]
+
Vous pouvez remplacer à chaud certains modules d'E/S par un module d'E/S équivalent afin de rétablir le système de stockage à son état de fonctionnement optimal. Le remplacement à chaud s'effectue sans avoir à effectuer une reprise manuelle.

+
Pour utiliser cette procédure, votre système de stockage doit exécuter ONTAP 9.17.1 ou une version ultérieure et répondre aux exigences spécifiques de la version d'ONTAP que votre système exécute.

* link:io-module-replace.html["Remplacez un module d'E/S."]
+
Vous pouvez remplacer un module d'E/S défectueux pour rétablir le système de stockage à son état de fonctionnement optimal. Cette procédure nécessite une prise de contrôle manuelle du contrôleur avec le module d'E/S défectueux.


