---
permalink: a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: AFF A90, AFF A70, replace io module 
summary: 'Les systèmes AFF A20, AFF A30 et AFF A50 offrent une grande flexibilité d"extension ou de remplacement des modules d"E/S pour améliorer la connectivité et les performances du réseau. L"ajout ou le remplacement d"un module d"E/S est essentiel lors de la mise à niveau des capacités réseau ou de l"adressage d"un module défaillant.' 
---
= Vue d'ensemble de l'ajout et du remplacement du module d'E/S - AFF A20, AFF A30 et AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes AFF A20, AFF A30 et AFF A50 offrent une grande flexibilité d'extension ou de remplacement des modules d'E/S pour améliorer la connectivité et les performances du réseau. L'ajout ou le remplacement d'un module d'E/S est essentiel lors de la mise à niveau des capacités réseau ou de l'adressage d'un module défaillant.

Vous pouvez remplacer un module d'E/S défaillant de votre système de stockage par le même type de module d'E/S ou par un autre type de module d'E/S. Vous pouvez également ajouter un module d'E/S à un système de stockage avec les emplacements disponibles.

* link:io-module-add.html["Ajoutez un module d'E/S."]
+
L'ajout de modules d'E/S supplémentaires peut améliorer la redondance et garantir que le système de stockage reste opérationnel même en cas de défaillance d'un module d'E/S.

* link:io-module-replace.html["Remplacez un module d'E/S."]
+
Le remplacement d'un module d'E/S défaillant permet de rétablir l'état de fonctionnement optimal du système de stockage.


