---
permalink: c250/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff c250, prerequisite, replace the controller module 
summary: 'Vous devez passer en revue les conditions préalables à la procédure de remplacement et sélectionner la version appropriée de votre système d"exploitation ONTAP.' 
---
= Exigences pour le remplacement du contrôleur - AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le contrôleur de votre AFF C250, assurez-vous de respecter les conditions requises pour un remplacement réussi. Cela inclut de vérifier que tous les autres composants du système fonctionnent correctement, de vous assurer que vous disposez du contrôleur de remplacement adéquat et d'enregistrer la sortie de la console du contrôleur dans un fichier journal texte.

Vous devez passer en revue les conditions préalables à la procédure de remplacement et sélectionner la version appropriée de votre système d'exploitation ONTAP.

* Tous les tiroirs disques doivent fonctionner correctement.
* Si votre système est dans une configuration MetroCluster, vous devez passer en revue la section https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Choix de la procédure de récupération correcte"] pour déterminer si vous devez utiliser cette procédure.
* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.
* Vous devez remplacer un module de contrôleur par un module de contrôleur du même type de modèle. Vous ne pouvez pas mettre à niveau votre système en remplaçant simplement le module de contrôleur.
* Vous ne pouvez pas modifier de disques ou de tiroirs disques dans le cadre de cette procédure.
* Dans cette procédure, le périphérique d'amorçage est déplacé du contrôleur défaillant vers le contrôleur _remplacement_ de sorte que le _remplacement_ contrôleur démarre dans la même version de ONTAP que l'ancien module de contrôleur.
* Il est important d'appliquer les commandes au cours des étapes suivantes sur les systèmes appropriés :
+
** Le contrôleur _trouble_ est le contrôleur qui est en cours de remplacement.
** Le contrôleur _remplacement_ est le nouveau contrôleur qui remplace le contrôleur défaillant.
** Le contrôleur _Healthy_ est le contrôleur survivant.


* Vous devez toujours capturer la sortie de la console du contrôleur dans un fichier texte.
+
Vous disposez ainsi d'un enregistrement de la procédure afin de pouvoir résoudre tout problème que vous pourriez rencontrer pendant le processus de remplacement.



.Et la suite ?
Après avoir examiné les exigences relatives au remplacement du contrôleur défectueux, vous devez link:controller-replace-shutdown.html["arrêtez le contrôleur défectueux"].
