---
permalink: c250/maintain-overview.html 
sidebar: sidebar 
keywords: aff C250 maintenance, maintenance, repairing C250, repairing aff C250, replace aff C250 components, replace aff C250 components 
summary: Entretenir le matériel ASA C250 
---
= Entretenir le matériel AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour le système de stockage AFF C250, vous pouvez effectuer des procédures de maintenance sur les composants suivants.



== Support de démarrage

Le support de démarrage stocke un ensemble principal et secondaire de fichiers d'image de démarrage que le système utilise lorsqu'il démarre.



== Châssis

Le châssis correspond au boîtier physique qui contient tous les composants du contrôleur, tels que le contrôleur/l'unité centrale, l'alimentation et les E/S.



== Contrôleur

Un contrôleur se compose d'une carte, d'un micrologiciel et d'un logiciel. Il contrôle les entraînements et met en œuvre les fonctions ONTAP.



== DIMM

Vous devez remplacer un module DIMM (module de mémoire double en ligne) en cas de non-concordance de mémoire, ou si vous avez un module DIMM défectueux.



== Lecteur

Un lecteur est un périphérique qui fournit le support de stockage physique pour les données.



== Ventilateur

Le ventilateur refroidit le contrôleur.



== Carte mezzanine

Une carte mezzanine est une carte de circuit imprimé qui se branche directement sur une autre carte enfichable.



== Batterie NVMEM

Une batterie est fournie avec le contrôleur et conserve les données en cache en cas de panne de courant alternatif.



== Alimentation électrique

Une alimentation électrique fournit une source d'alimentation redondante dans un tiroir contrôleur.



== Batterie d'horloge en temps réel

Une batterie d'horloge en temps réel conserve les informations relatives à la date et à l'heure du système si l'alimentation est coupée.
