---
permalink: c250/overview.html 
sidebar: sidebar 
keywords: AFF C250 specifications, AFF C250 specs, NetApp AFF C250, AFF C250 hardware 
summary: Spécifications clés du système de stockage AFF C250 
---
= Spécifications clés de AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour l' AFF C250.  Visite https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) pour une liste complète des spécifications AFF C250 .  Cette page reflète une seule paire à haute disponibilité.



== Spécifications clés de AFF C250

Configuration de la plateforme : paire de châssis simple HA AFF C250

Capacité brute maximale : 1,4736 Po

Mémoire : 128.0000 Go

Facteur de forme : châssis 2U avec 2 contrôleurs HA et 24 emplacements pour disques

Version ONTAP : b_startONTAP : 9.16.1P2b_end

Emplacements d'extension PCIe : 4

Version minimale ONTAP : ONTAP 9.10.1P15



== Maximums de mise à l'échelle

|===


| Type | Paires HA | Capacité brute | Mémoire maximale 


| NAS | 12 | 17,7 Po / 15,7 PiB | 1536 Go 


| SAN | 6 | 8,8 Po / 7,9 PiB | 768 Go 


| Paire haute disponibilité |  | 1,5 Po / 1,3 PiB | 128,0000 
|===


== E/S



=== E/S embarquées

|===


| Protocole | Ports 


| Ethernet 25 Gbit/s | 4 


| Ethernet 10 Gbit/s | 4 
|===


=== E/S totales

|===


| Protocole | Ports 


| Ethernet 100 Gbit/s | 4 


| Ethernet 25 Gbit/s | 20 


| Ethernet 10 Gbit/s | 4 


| FC 32 Gbit/s | 16 


| NVMe/FC 32 Gbit/s | 16 


|  | 0 
|===


=== Ports de gestion

|===


| Protocole | Ports 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


== Réseau de stockage pris en charge

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC ; NVMe/TCP; S3; S3 avec NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



== Spécifications de l'environnement système

* Puissance typique : 2906 BTU/h
* Puissance dans le pire des cas : 3 750 BTU/h
* Poids : 54,3 lb 24,6 kg
* Hauteur : 2U
* Largeur : 19 pouces conforme à la norme IEC (17,6 pouces 44,7 cm)
* Profondeur:
* Température/Altitude/Humidité de fonctionnement : 10 °C à 35 °C (50 °F à 95 °F) jusqu’à 3 048 m (10 000 pi) d’altitude ; 8 % à 80 % d’humidité relative, sans condensation
* Température et humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu’à 12 192 m (40 000 pi), 10 % à 95 % d’humidité relative, sans condensation, dans son emballage d’origine.
* Bruit acoustique : Puissance acoustique déclarée (LwAd) : 7,2 ; Pression acoustique (LpAm) (positions des passants) : 69,1 dB




== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




== Haute disponibilité

Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP ; Contrôleurs redondants remplaçables à chaud ; Alimentations redondantes remplaçables à chaud ;
