---
permalink: asa-r2-a1k/bootmedia-overview.html 
sidebar: sidebar 
keywords: asa r2 a1k, overview, the boot media 
summary: Découvrez la méthode automatisée et la méthode manuelle de remplacement du support de démarrage. 
---
= Présentation du remplacement du support de démarrage - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez remplacer manuellement un support d'amorçage défectueux en utilisant le module USB pour l'image d'amorçage ou en utilisant l'option de remplacement automatique du support d'amorçage (BMR).

* link:bootmedia-replace-requirements-bmr.html["Remplacement automatique des supports de démarrage"]
+
Le remplacement automatique des supports de démarrage utilise l'image de démarrage à partir du nœud partné et exécute automatiquement l'option de menu de démarrage appropriée pour installer l'image de démarrage sur le support de démarrage de remplacement.

* link:bootmedia-replace-requirements.html["Remplacement manuel du support de démarrage"]
+
Le remplacement manuel des supports de démarrage utilise la méthode traditionnelle de téléchargement de l'image ONTAP à partir du site de support NetApp, de transfert de l'image vers un lecteur USB, de téléchargement vers le support de démarrage cible de remplacement et de navigation manuelle dans les options du menu de démarrage pour installer l'image ONTAP sur le support de démarrage de remplacement.


