---
permalink: asa-r2-a1k/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa r2 a1k, replace the boot media 
summary: Avant de remplacer le support de démarrage de votre système ASA A1K, assurez-vous de répondre aux exigences requises pour un remplacement réussi. 
---
= Conditions requises pour remplacer le support de démarrage - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système ASA A1K, assurez-vous de répondre aux exigences requises pour un remplacement réussi. Cela inclut la vérification que vous disposez du support de démarrage de remplacement approprié, la vérification qu'aucun port de cluster n'est défectueux sur le contrôleur et la détermination de l'activation du gestionnaire de clés intégré (OKM) ou du gestionnaire de clés externe (EKM).

Passez en revue les exigences suivantes.

* Vous devez remplacer le support de démarrage défectueux par un support de démarrage de remplacement que vous avez reçu de NetApp.
* Il ne doit y avoir aucun port de cluster défectueux sur le contrôleur défectueux.
* Déterminez si Onboard Key Manager (OKM) ou Eternal Key Manager (EKM) est configuré à l'aide de l'une des méthodes suivantes :
+
** Vous pouvez demander à l'administrateur système si OKM ou EKM sont activés.
** Pour vérifier si OKM est activé, vous pouvez utiliser le `security key-manager onboard show`.
** Pour vérifier si EKM est activé, vous pouvez utiliser le `security key-manager external show`.


* Pour OKM, vous avez besoin du contenu du fichier de phrase de passe OKM.
* Pour EKM, vous avez besoin de copies des fichiers suivants à partir du nœud partenaire :
+
** fichier /cfcard/kmip/servers.cfg.
** fichier /cfcard/kmip/certs/client.crt.
** fichier /cfcard/kmip/certs/client.key.
** Fichier /cfcard/kmip/certs/CA.pem.




.Et la suite
Après avoir examiné la configuration requise pour le support de démarrage, vous link:bootmedia-shutdown-bmr.html["arrêter le contrôleur"].
