---
permalink: asa-r2-a1k/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: asa r2 a1k, replace the boot media 
summary: Découvrez la configuration requise pour le remplacement du support de démarrage. 
---
= Exigences de remplacement du support de démarrage - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage, vérifiez les conditions suivantes.

* Vous devez disposer d'une clé USB, formatée en FAT32, avec la quantité de stockage appropriée pour maintenir le `image_xxx.tgz` fichier.
* Vous devez copier le `image_xxx.tgz` fichier sur la clé USB pour pouvoir l'utiliser ultérieurement dans cette procédure.
* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu NetApp.
* Il est important d'appliquer les commandes au cours de la procédure suivante sur le contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le contrôleur _Healthy_ est le partenaire HA du contrôleur déficient.



