---
permalink: asa-r2-a1k/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa r2 a1k, prerequisite, replace the controller module 
summary: 'Avant de remplacer le contrôleur de votre système ASA A1K, assurez-vous de répondre aux exigences requises pour un remplacement réussi. Cela inclut la vérification du bon fonctionnement de tous les autres composants du système, la vérification du bon contrôleur de remplacement et l"enregistrement de la sortie de la console du contrôleur dans un fichier journal texte.' 
---
= Conditions requises pour remplacer le contrôleur - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le contrôleur de votre système ASA A1K, assurez-vous de répondre aux exigences requises pour un remplacement réussi. Cela inclut la vérification du bon fonctionnement de tous les autres composants du système, la vérification du bon contrôleur de remplacement et l'enregistrement de la sortie de la console du contrôleur dans un fichier journal texte.

Passez en revue les exigences.

[NOTE]
====
NetApp recommande fortement d'activer la journalisation de la console sur les appareils que vous utilisez et de prendre les mesures suivantes lors de cette procédure :

* Laissez AutoSupport activé pendant votre maintenance. Cela permet au support NetApp de recevoir des informations de diagnostic en cas de problème.
* Activez la journalisation des sessions pour toutes les sessions CLI. Cela crée un enregistrement complet de toutes les commandes et des sorties système pendant l'opération de maintenance. Pour savoir comment activer la journalisation des sessions, consultez  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Comment configurer PuTTY pour une connectivité optimale aux systèmes ONTAP"^].


====
* Tous les tiroirs disques doivent fonctionner correctement.
* Le contrôleur sain doit pouvoir reprendre le contrôleur qui est remplacé (appelé « contrôleur défectueux » dans cette procédure).
* Vous devez remplacer le composant défectueux par un composant de remplacement que vous avez reçu de NetApp.
* N'utilisez pas cette procédure pour les mises à niveau du contrôleur ; reportez-vous plutôt au https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Choisissez la procédure de mise à niveau matérielle de votre contrôleur"] pour obtenir des conseils.
* Vous devez remplacer un module de contrôleur par un module de contrôleur du même type de modèle. Vous ne pouvez pas mettre à niveau votre système en remplaçant simplement le module de contrôleur.
* Vous ne pouvez pas modifier de disques ou de tiroirs disques dans le cadre de cette procédure.
* Comme le périphérique d'amorçage se trouve sur le module de gestion du système installé à l'arrière du système, vous n'avez pas besoin de déplacer le périphérique d'amorçage lors du remplacement d'un module de contrôleur.
* Il est important d'appliquer les commandes au cours des étapes suivantes sur les systèmes appropriés :
+
** Le contrôleur _trouble_ est le contrôleur qui est en cours de remplacement.
** Le contrôleur _remplacement_ est le nouveau contrôleur qui remplace le contrôleur défaillant.
** Le contrôleur _Healthy_ est le contrôleur survivant.




.Et la suite ?
Après avoir examiné les conditions requises pour remplacer votre contrôleur ASA A1K, vous devez link:controller-replace-shutdown-nomcc.html["arrêtez les contrôleurs"].
