---
permalink: asa-r2-a1k/io-module-overview.html 
sidebar: sidebar 
keywords: asa r2 a1k, replace io module 
summary: 'Le système ASA A1K offre une grande flexibilité d"extension ou de remplacement des modules d"E/S pour améliorer la connectivité et les performances du réseau. L"ajout ou le remplacement d"un module d"E/S est essentiel lors de la mise à niveau des capacités réseau ou de l"adressage d"un module défaillant' 
---
= Présentation de l'ajout et du remplacement du module d'E/S - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système ASA A1K offre une grande flexibilité d'extension ou de remplacement des modules d'E/S pour améliorer la connectivité et les performances du réseau. L'ajout ou le remplacement d'un module d'E/S est essentiel lors de la mise à niveau des capacités réseau ou de l'adressage d'un module défaillant.

Vous pouvez remplacer un module d'E/S défectueux dans votre système de stockage ASA A1K par le même type de module d'E/S ou par un autre type de module d'E/S. Vous pouvez également ajouter un module d'E/S dans un système doté de logements vides.

* link:io-module-add.html["Ajoutez un module d'E/S."]
+
L'ajout de modules supplémentaires peut améliorer la redondance, ce qui permet de garantir que le système reste opérationnel même en cas de défaillance d'un module.

* link:io-module-replace.html["Remplacez un module d'E/S."]
+
Le remplacement d'un module d'E/S défaillant permet de restaurer l'état de fonctionnement optimal du système.


