= Étape 1 : vérifier et définir l'état de haute disponibilité du châssis
:allow-uri-read: 


Vous devez vérifier l'état HA du châssis, renvoyer les agrégats et renvoyer la pièce défectueuse à NetApp, comme indiqué dans les instructions RMA fournies avec le kit.



== Étape 1 : vérifier et définir l'état de haute disponibilité du châssis

Vous devez vérifier l'état HA du châssis et, le cas échéant, mettre à jour l'état pour qu'il corresponde à la configuration de votre système.

. En mode Maintenance, depuis l'un ou l'autre module de contrôleur, afficher l'état HA du module de contrôleur local et du châssis : `ha-config show`
+
L'état de la HA doit être le même pour tous les composants.

. Si l'état du système affiché pour le châssis ne correspond pas à la configuration de votre système :
+
.. Définissez l'état haute disponibilité du châssis : `ha-config modify chassis _HA-state_`
+
La valeur de HA-State peut être l'une des suivantes :

+
*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mccip`
*** `non-ha`


.. Vérifiez que le paramètre a changé : `ha-config show`


. Si vous ne l'avez pas déjà fait, recâble le reste de votre système.
. Redémarrez le système.




== Étape 2 : basculement des agrégats dans une configuration MetroCluster à deux nœuds

Cette tâche s'applique uniquement aux configurations MetroCluster à deux nœuds.

.Étapes
. Vérifiez que tous les nœuds sont dans le `enabled` état : `metrocluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. Vérifier que la resynchronisation est terminée sur tous les SVM : `metrocluster vserver show`
. Vérifier que toutes les migrations LIF automatiques effectuées par les opérations de correction ont été effectuées correctement : `metrocluster check lif show`
. Effectuez le rétablissement en utilisant le `metrocluster switchback` utilisez une commande à partir d'un nœud du cluster survivant.
. Vérifiez que l'opération de rétablissement est terminée : `metrocluster show`
+
L'opération de rétablissement s'exécute toujours lorsqu'un cluster est dans `waiting-for-switchback` état :

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
Le rétablissement est terminé une fois les clusters dans `normal` état :

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
Si un rétablissement prend beaucoup de temps, vous pouvez vérifier l'état des lignes de base en cours en utilisant le `metrocluster config-replication resync-status show` commande.

. Rétablir toutes les configurations SnapMirror ou SnapVault.




== Étape 3 : renvoyer la pièce défaillante à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièces et remplacements"] page pour plus d'informations.
