= 
:allow-uri-read: 


Dans une configuration MetroCluster à deux nœuds exécutant ONTAP, vous devez réallouer manuellement des disques vers le nouvel ID système du contrôleur avant de rétablir le fonctionnement normal du système.

.Description de la tâche
Cette procédure s'applique uniquement aux systèmes d'une configuration MetroCluster à deux nœuds exécutant ONTAP.

Vous devez être sûr d'exécuter les commandes dans cette procédure sur le nœud approprié :

* Le noeud _trouble_ est le noeud sur lequel vous effectuez la maintenance.
* Le _remplacement_ node est le nouveau noeud qui a remplacé le noeud douteux dans le cadre de cette procédure.
* Le noeud _Healthy_ est le partenaire DR du noeud douteux.


.Étapes
. Si ce n'est déjà fait, redémarrez le _replace_ node, interrompez le processus d'amorçage en entrant `Ctrl-C`, Puis sélectionnez l'option pour démarrer en mode maintenance à partir du menu affiché.
+
Vous devez entrer `Y` Lorsque vous êtes invité à remplacer l'ID système en raison d'une discordance d'ID système.

. Afficher les anciens ID système du nœud sain : ``metrocluster node show -fields node-systemid`,dr-partenaire-systémid'
+
Dans cet exemple, le noeud_B_1 est l'ancien noeud, avec l'ancien ID système 118073209:

+
[listing]
----
dr-group-id cluster         node                 node-systemid dr-partner-systemid
 ----------- --------------------- -------------------- ------------- -------------------
 1           Cluster_A             Node_A_1             536872914     118073209
 1           Cluster_B             Node_B_1             118073209     536872914
 2 entries were displayed.
----
. Afficher le nouvel ID système à l'invite du mode maintenance sur le nœud pour personnes avec facultés affaiblies : `disk show`
+
Dans cet exemple, le nouvel ID système est 118065481 :

+
[listing]
----
Local System ID: 118065481
    ...
    ...
----
. Réassigner la propriété des disques (pour les systèmes FAS) ou la propriété LUN (pour les systèmes FlexArray), en utilisant les informations d'ID système obtenues via la commande disk show : `disk reassign -s old system ID`
+
Dans l'exemple précédent, la commande est : `disk reassign -s 118073209`

+
Vous pouvez répondre `Y` lorsque vous êtes invité à continuer.

. Vérifier que les disques (ou LUN FlexArray) ont été correctement affectés : `disk show -a`
+
Vérifiez que les disques appartenant au _replace_ node affichent le nouvel ID système pour le _replace_ node. Dans l'exemple suivant, les disques appartenant au système-1 affichent désormais le nouvel ID système, 118065481 :

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK     OWNER                 POOL   SERIAL NUMBER  HOME
-------    -------------         -----  -------------  -------------
disk_name   system-1  (118065481) Pool0  J8Y0TDZC       system-1  (118065481)
disk_name   system-1  (118065481) Pool0  J8Y09DXC       system-1  (118065481)
.
.
.
----
. Depuis le nœud sain, vérifier que les « core dumps » sont enregistrés :
+
.. Changement au niveau de privilège avancé : `set -privilege advanced`
+
Vous pouvez répondre `Y` lorsque vous êtes invité à passer en mode avancé. L'invite du mode avancé s'affiche (*>).

.. Vérifier que les « coredumps » sont enregistrés : `system node run -node _local-node-name_ partner savecore`
+
Si la sortie de la commande indique que savecore est en cours, attendez que savecore soit terminé avant d'émettre le retour. Vous pouvez surveiller la progression de la sauvegarde à l'aide du `system node run -node _local-node-name_ partner savecore -s command`.</info>.

.. Retour au niveau de privilège admin : `set -privilege admin`


. Si le _remplacement_ node est en mode Maintenance (affichage de l'invite *>), quittez le mode Maintenance et accédez à l'invite DU CHARGEUR : `halt`
. Démarrez le _remplacement_ node : `boot_ontap`
. Une fois que le _remplacement_ noeud a été complètement démarré, effectuez un rétablissement : `metrocluster switchback`
. Vérifiez la configuration MetroCluster : `metrocluster node show - fields configuration-state`
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Vérifier le fonctionnement de la configuration MetroCluster dans Data ONTAP :
+
.. Vérifier si des alertes d'intégrité sont disponibles sur les deux clusters : `system health alert show`
.. Vérifier que le MetroCluster est configuré et en mode normal : `metrocluster show`
.. Effectuer une vérification MetroCluster : `metrocluster check run`
.. Afficher les résultats de la vérification MetroCluster : `metrocluster check show`
.. Exécutez Config Advisor. Accédez à la page Config Advisor du site de support NetApp à l'adresse https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor/["support.netapp.com/NOW/download/tools/config_advisor/"].
+
Une fois Config Advisor exécuté, vérifiez les résultats de l'outil et suivez les recommandations fournies dans la sortie pour résoudre tous les problèmes détectés.



. Simuler une opération de basculement :
+
.. Depuis l'invite de n'importe quel nœud, passez au niveau de privilège avancé : `set -privilege advanced`
+
Vous devez répondre avec `y` lorsque vous êtes invité à passer en mode avancé et à afficher l'invite du mode avancé (*>).

.. Effectuez l'opération de rétablissement avec le paramètre -Simulate : `metrocluster switchover -simulate`
.. Retour au niveau de privilège admin : `set -privilege admin`



