= 
:allow-uri-read: 


Vérifiez les conditions requises pour le remplacement du contrôleur.

[NOTE]
====
NetApp recommande fortement d'activer la journalisation de la console sur les appareils que vous utilisez et de prendre les mesures suivantes lors de cette procédure :

* Laissez AutoSupport activé pendant votre maintenance. Cela permet au support NetApp de recevoir des informations de diagnostic en cas de problème.
* Activez la journalisation des sessions pour toutes les sessions CLI. Cela crée un enregistrement complet de toutes les commandes et des sorties système pendant l'opération de maintenance. Pour savoir comment activer la journalisation des sessions, consultez  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Comment configurer PuTTY pour une connectivité optimale aux systèmes ONTAP"^].


====
* Tous les tiroirs disques doivent fonctionner correctement.
* Le contrôleur sain doit pouvoir reprendre le contrôleur qui est remplacé (appelé « contrôleur défectueux » dans cette procédure).
* N'utilisez pas cette procédure pour les mises à niveau du contrôleur ; reportez-vous plutôt au https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Choisissez la procédure de mise à niveau matérielle de votre contrôleur"] pour obtenir des conseils.
* Si votre système est dans une configuration MetroCluster, vous devez consulter la section https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Choix de la procédure de récupération correcte"] pour déterminer si vous devez utiliser cette procédure de remplacement de contrôleur.
* Vous devez remplacer le composant défectueux par l'unité remplaçable sur site (FRU) que vous avez reçue de NetApp.
* Vous devez remplacer un module de contrôleur par un module de contrôleur du même type de modèle. Vous ne pouvez pas mettre à niveau votre système en remplaçant simplement le module de contrôleur.
* Vous ne pouvez pas modifier de disques ou de tiroirs disques dans le cadre de cette procédure.
* Comme le périphérique d'amorçage se trouve sur le module de gestion du système installé à l'arrière du système, vous n'avez pas besoin de déplacer le périphérique d'amorçage lors du remplacement d'un module de contrôleur.
* Il est important d'appliquer les commandes au cours des étapes suivantes sur les systèmes appropriés :
+
** Le contrôleur _trouble_ est le contrôleur qui est en cours de remplacement.
** Le contrôleur _remplacement_ est le nouveau contrôleur qui remplace le contrôleur défaillant.
** Le contrôleur _Healthy_ est le contrôleur survivant.



