= Étape 1 : arrêtez le contrôleur défaillant
:allow-uri-read: 


Vous devez remplacer un module DIMM dans le module de contrôleur lorsque votre système enregistre un nombre croissant de codes de correction d'erreurs (ECC) pouvant être corrigés ; dans le cas contraire, le système risque de se trouver en panne.

.Avant de commencer
Tous les autres composants du système doivent fonctionner correctement ; si ce n'est pas le cas, vous devez contacter le support technique.

Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.



== Étape 1 : arrêtez le contrôleur défaillant

Arrêtez ou prenez le contrôle du contrôleur défectueux.

Pour arrêter le contrôleur défaillant, vous devez déterminer l'état du contrôleur et, si nécessaire, prendre le contrôle de façon à ce que le contrôleur en bonne santé continue de transmettre des données provenant du stockage défaillant du contrôleur.

.Description de la tâche
* Si vous disposez d'un système SAN, vous devez avoir vérifié les messages d'événement  `cluster kernel-service show`) pour le serveur lame SCSI du contrôleur défectueux.  `cluster kernel-service show`La commande (depuis la commande priv en mode avancé) affiche le nom du nœud, l'état de quorum de ce nœud, l'état de disponibilité de ce nœud ainsi que l'état opérationnel de ce nœud.
+
Chaque processus SCSI-Blade doit se trouver au quorum avec les autres nœuds du cluster. Tout problème doit être résolu avant de procéder au remplacement.

* Si vous avez un cluster avec plus de deux nœuds, il doit être dans le quorum. Si le cluster n'est pas au quorum ou si un contrôleur en bonne santé affiche la valeur false pour l'éligibilité et la santé, vous devez corriger le problème avant de désactiver le contrôleur défaillant ; voir link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchroniser un nœud avec le cluster"^].


.Étapes
. Si AutoSupport est activé, supprimez la création automatique de cas en appelant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
Le message AutoSupport suivant supprime la création automatique de dossiers pendant deux heures : `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Désactiver le rétablissement automatique depuis la console du contrôleur sain : `storage failover modify –node local -auto-giveback false`
+

NOTE: Lorsque vous voyez _voulez-vous désactiver l'auto-giveback?_, entrez `y`.

. Faites passer le contrôleur douteux à l'invite DU CHARGEUR :
+
[cols="1,2"]
|===
| Si le contrôleur en état de fonctionnement s'affiche... | Alors... 


 a| 
Invite DU CHARGEUR
 a| 
Passez à l'étape suivante.



 a| 
Attente du retour...
 a| 
Appuyez sur Ctrl-C, puis répondez `y` lorsque vous y êtes invité.



 a| 
Invite système ou invite de mot de passe
 a| 
Prendre le contrôle défectueux ou l'arrêter à partir du contrôleur en bon état : `storage failover takeover -ofnode _impaired_node_name_`

Lorsque le contrôleur douteux s'affiche en attente de rétablissement..., appuyez sur Ctrl-C et répondez `y`.

|===




== Étape 2 : retirer le module de contrôleur

Vous devez retirer le module de contrôleur du boîtier lorsque vous remplacez le module de contrôleur ou un composant à l'intérieur du module de contrôleur.

. Vérifiez le voyant d'état de la mémoire NVRAM situé dans le logement 4/5 du système. Une LED NVRAM est également présente sur le panneau avant du module contrôleur. Recherchez l'icône NV :
+
image::../media/drw_a1K-70-90_nvram-led_ieops-1463.svg[Emplacement graphique de la LED d'avertissement et d'état de la NVRAM]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Légende numéro 1, largeur = 30 px"]
 a| 
LED d'état NVRAM



 a| 
image:../media/legend_icon_02.svg["Légende numéro 1, largeur = 30 px"]
 a| 
LED d'avertissement NVRAM

|===
+

NOTE: Si la LED d'état de la mémoire NVRAM clignote, cela peut signifier que le module de contrôleur n'a pas été repris ou arrêté correctement (données non validées). Si le module de contrôleur défectueux n'a pas été repris avec succès par le module de contrôleur partenaire, contactez https://mysupport.netapp.com/site/global/dashboard["Support NetApp"] avant de poursuivre cette procédure.

+
Le comportement général de la LED d'état NVRAM sur le module de contrôleur défectueux est le suivant :

+
** La LED d'état de la NVRAM clignote lorsque le module de contrôleur est mis hors tension et que le module de contrôleur est dans l'état « en attente de rétablissement » ou que le module de contrôleur n'est pas repris ou arrêté correctement (données non validées).
** Le voyant d'état NVRAM clignote lorsque le module de contrôleur est retiré du boîtier et peut signifier que le module de contrôleur n'est pas pris en charge ou arrêté correctement (données non validées). Vérifiez que le module de contrôleur a été correctement pris en charge par le module de contrôleur partenaire ou que le module de contrôleur défectueux affiche `waiting for giveback`. Le voyant clignotant peut alors être ignoré (et le contrôleur peut être retiré du boîtier).


. Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
. À l'avant de l'unité, accrochez vos doigts dans les trous des cames de verrouillage, appuyez sur les languettes des leviers de came et faites doucement, mais fermement pivoter les deux loquets vers vous en même temps.
+
Le module de contrôleur se déplace légèrement hors du boîtier.

+
image::../media/drw_a1k_pcm_remove_replace_ieops-1375.svg[Supprimer le graphique du contrôleur]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Légende numéro 1, largeur = 30 px"]
| Une came de verrouillage s'enclenche 
|===
. Faites glisser le module de contrôleur hors du boîtier et placez-le sur une surface plane et stable.
+
Assurez-vous de soutenir le bas du module de contrôleur lorsque vous le faites glisser hors du boîtier.





== Étape 3 : remplacez un module DIMM

Vous devez remplacer un module DIMM lorsque le système signale une défaillance permanente pour ce module DIMM.

. Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
. Ouvrir le conduit d'air du contrôleur sur le dessus du contrôleur.
+
.. Insérez vos doigts dans les encoches situées à l'extrémité du conduit d'air.
.. Soulevez le conduit d'air et faites-le pivoter vers le haut aussi loin que possible.


. Repérez les modules DIMM sur votre module de contrôleur et identifiez-les pour les remplacer.
. Éjectez le module DIMM de son logement en écartant lentement les deux languettes de l'éjecteur de DIMM de chaque côté du module DIMM, puis en faisant glisser le module DIMM hors de son logement.
+

IMPORTANT: Tenez soigneusement le module DIMM par les bords pour éviter toute pression sur les composants de la carte de circuit DIMM.

+
image::../media/drw_a1k_dimms_ieops-1512.svg[DIMM remplacez]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Légende numéro 1, largeur = 30 px"]
 a| 
Languettes d'éjection du module DIMM et du module DIMM

|===
. Retirez le module DIMM de remplacement du sac d'expédition antistatique, tenez le module DIMM par les coins et alignez-le sur le logement.
+
L'encoche entre les broches du DIMM doit être alignée avec la languette du support.

. Assurez-vous que les languettes de l'éjecteur de DIMM sur le connecteur sont en position ouverte, puis insérez le module DIMM directement dans le logement.
+
Le module DIMM s'insère bien dans le logement, mais devrait être facilement installé. Si ce n'est pas le cas, réalignez le module DIMM avec le logement et réinsérez-le.

+

IMPORTANT: Inspectez visuellement le module DIMM pour vérifier qu'il est bien aligné et complètement inséré dans le logement.

. Poussez délicatement, mais fermement, sur le bord supérieur du module DIMM jusqu'à ce que les languettes de l'éjecteur s'enclenchent sur les encoches situées aux extrémités du module DIMM.
. Fermer le conduit d'air du contrôleur.




== Étape 4 : installer le contrôleur

Réinstallez le module de contrôleur et démarrez-le.

. Si ce n'est déjà fait, fermer le conduit d'air.
. Alignez l'extrémité du module de contrôleur avec l'ouverture du boîtier, puis faites glisser le module de contrôleur dans le châssis, les leviers tournés vers l'avant du système.
. Une fois que le module de contrôleur vous empêche de le faire glisser plus loin, faites pivoter les poignées de came vers l'intérieur jusqu'à ce qu'elles se reverrouillent sous les ventilateurs
+

NOTE: N'appliquez pas une force excessive lorsque vous faites glisser le module de contrôleur dans le boîtier pour éviter d'endommager les connecteurs.

+
Le module de contrôleur commence à démarrer dès qu'il est complètement inséré dans le boîtier.

. Restaurez le retour automatique si vous le désactivez à l'aide de `storage failover modify -node local -auto-giveback true` commande.
. Si AutoSupport est activé, restaurez/annulez la création automatique de cas à l'aide de la `system node autosupport invoke -node * -type all -message MAINT=END` commande.




== Étape 5 : renvoyer la pièce défaillante à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièces et remplacements"] page pour plus d'informations.
