= Étape 1 : arrêtez le contrôleur défaillant
:allow-uri-read: 


Utilisez cette procédure pour remplacer un module d'E/S défectueux.

* Vous pouvez utiliser cette procédure avec toutes les versions de ONTAP prises en charge par votre système de stockage.
* Tous les autres composants du système de stockage doivent fonctionner correctement. Si ce n'est pas le cas, vous devez contacter le support technique.




== Étape 1 : arrêtez le contrôleur défaillant

Arrêtez ou prenez le contrôleur pour facultés affaiblies en utilisant l'une des options suivantes.

[role="tabbed-block"]
====
.Option 1 : la plupart des systèmes
--
Pour arrêter le contrôleur défaillant, vous devez déterminer l'état du contrôleur et, si nécessaire, prendre le contrôle de façon à ce que le contrôleur en bonne santé continue de transmettre des données provenant du stockage défaillant du contrôleur.

.Description de la tâche
* Si vous disposez d'un système SAN, vous devez avoir vérifié les messages d'événement  `cluster kernel-service show`) pour le serveur lame SCSI du contrôleur défectueux.  `cluster kernel-service show`La commande (depuis la commande priv en mode avancé) affiche le nom du nœud, l'état de quorum de ce nœud, l'état de disponibilité de ce nœud ainsi que l'état opérationnel de ce nœud.
+
Chaque processus SCSI-Blade doit se trouver au quorum avec les autres nœuds du cluster. Tout problème doit être résolu avant de procéder au remplacement.

* Si vous avez un cluster avec plus de deux nœuds, il doit être dans le quorum. Si le cluster n'est pas au quorum ou si un contrôleur en bonne santé affiche la valeur false pour l'éligibilité et la santé, vous devez corriger le problème avant de désactiver le contrôleur défaillant ; voir link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchroniser un nœud avec le cluster"^].


.Étapes
. Si AutoSupport est activé, supprimez la création automatique de cas en appelant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
Le message AutoSupport suivant supprime la création automatique de dossiers pendant deux heures : `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Désactiver le rétablissement automatique depuis la console du contrôleur sain : `storage failover modify –node local -auto-giveback false`
+

NOTE: Lorsque vous voyez _voulez-vous désactiver l'auto-giveback?_, entrez `y`.

. Faites passer le contrôleur douteux à l'invite DU CHARGEUR :
+
[cols="1,2"]
|===
| Si le contrôleur en état de fonctionnement s'affiche... | Alors... 


 a| 
Invite DU CHARGEUR
 a| 
Passez à l'étape suivante.



 a| 
Attente du retour...
 a| 
Appuyez sur Ctrl-C, puis répondez `y` lorsque vous y êtes invité.



 a| 
Invite système ou invite de mot de passe
 a| 
Prendre le contrôle défectueux ou l'arrêter à partir du contrôleur en bon état : `storage failover takeover -ofnode _impaired_node_name_`

Lorsque le contrôleur douteux s'affiche en attente de rétablissement..., appuyez sur Ctrl-C et répondez `y`.

|===


--
.Option 2 : le contrôleur est dans un MetroCluster
--
Pour arrêter le contrôleur défaillant, vous devez déterminer l'état du contrôleur et, si nécessaire, prendre le contrôle de façon à ce que le contrôleur en bonne santé continue de transmettre des données provenant du stockage défaillant du contrôleur.

* Si vous avez un cluster avec plus de deux nœuds, il doit être dans le quorum. Si le cluster n'est pas au quorum ou si un contrôleur en bonne santé affiche la valeur false pour l'éligibilité et la santé, vous devez corriger le problème avant de désactiver le contrôleur défaillant ; voir link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchroniser un nœud avec le cluster"^].
* Si vous disposez d'une configuration MetroCluster, vous devez avoir confirmé que l'état de configuration MetroCluster est configuré et que les nœuds sont dans un état activé et normal (`metrocluster node show`).


.Étapes
. Si AutoSupport est activé, supprimez la création automatique de dossier en invoquant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
Le message AutoSupport suivant supprime la création automatique de dossiers pendant deux heures : `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Désactiver le rétablissement automatique depuis la console du contrôleur sain : `storage failover modify –node local -auto-giveback false`
. Faites passer le contrôleur douteux à l'invite DU CHARGEUR :
+
[cols="1,2"]
|===
| Si le contrôleur en état de fonctionnement s'affiche... | Alors... 


 a| 
Invite DU CHARGEUR
 a| 
Passez à l'étape suivante.



 a| 
Attente du retour...
 a| 
Appuyez sur Ctrl-C, puis répondez `y` lorsque vous y êtes invité.



 a| 
Invite système ou invite de mot de passe (entrer le mot de passe système)
 a| 
Prendre le contrôle défectueux ou l'arrêter à partir du contrôleur en bon état : `storage failover takeover -ofnode _impaired_node_name_`

Lorsque le contrôleur douteux s'affiche en attente de rétablissement..., appuyez sur Ctrl-C et répondez `y`.

|===


--
====


== Étape 2 : remplacez un module d'E/S défectueux

Pour remplacer un module d'E/S, localisez-le dans le module de contrôleur et suivez la séquence spécifique des étapes.

. À l'avant du châssis, enfoncez fermement chaque disque jusqu'à ce que vous sentiez un arrêt positif. Cela permet de s'assurer que les disques sont fermement installés contre le fond de panier central du châssis.
+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[Entraînement drw a800 assis IEOPS 960]

. Aller à l'arrière du châssis. Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
. Débranchez l'alimentation en retirant le module de contrôleur d'environ trois pouces :
+

NOTE: Si votre système de stockage est équipé d'unités d'alimentation CC, déconnectez le bloc du câble d'alimentation des unités d'alimentation.

+
.. Appuyez sur les deux loquets de verrouillage, puis faites pivoter les deux loquets vers le bas en même temps.
.. Retirez le module de contrôleur d'environ 3 pouces du châssis pour le mettre hors tension.


. Débranchez tout câblage du module d'E/S cible.
+
Assurez-vous d'étiqueter les câbles de manière à connaître leur origine.

. Faites pivoter le chemin de câbles vers le bas en tirant sur les boutons situés à l'intérieur du chemin de câbles et en le faisant pivoter vers le bas.
. Retirez le module d'E/S du module de contrôleur :
+

NOTE: L'illustration suivante illustre le retrait d'un module d'E/S horizontal et vertical. En général, vous ne retirez qu'un seul module d'E/S.

+
image::../media/drw_a70_90_io_remove_replace_ieops-1532.svg[Retirez le module d'E/S.]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Légende numéro 1,largeur=30px"]
 a| 
Bouton de verrouillage de came

|===
+
.. Appuyer sur le bouton de verrouillage de came.
+
Le loquet de came s'éloigne du module de contrôleur.

.. Faites pivoter le loquet de came le plus loin possible. Pour les modules horizontaux, faites pivoter la came à l'écart du module aussi loin que possible.
.. Retirez le module du module de contrôleur en accrochant votre doigt dans l'ouverture du levier de came et en tirant le module hors du module de contrôleur.
+
Assurez-vous de garder une trace de l'emplacement dans lequel se trouvait le module d'E/S.



. Mettez le module d'E/S de côté.
. Installez le module d'E/S de remplacement dans le logement cible :
+
.. Alignez le module d'E/S sur les bords du logement.
.. Faites glisser doucement le module dans le logement jusqu'au fond du module de contrôleur, puis faites pivoter le loquet de came complètement vers le haut pour verrouiller le module en place.


. Branchez le câble du module d'E/S.
. Répéter les étapes de dépose et de pose pour remplacer les modules supplémentaires du contrôleur.
. Réinstallez le module de contrôleur dans le châssis.
+

NOTE: Si vous disposez d'une alimentation CC, reconnectez les blocs de câbles aux blocs d'alimentation.

. Faites pivoter le chemin de câbles en position verrouillée.




== Étape 3 : redémarrer le contrôleur

Après avoir remplacé un module d'E/S, vous devez redémarrer le module de contrôleur.


NOTE: Si le nouveau module d'E/S n'est pas le même modèle que le module défaillant, vous devez d'abord redémarrer le contrôleur BMC.

.Étapes
. Redémarrez le contrôleur BMC si le module de remplacement n'est pas du même modèle que l'ancien module :
+
.. À partir de l'invite du CHARGEUR, passez en mode de privilège avancé : _set Privilege Advanced_
.. Redémarrez le contrôleur BMC : _sp reboot_


. À partir de l'invite du CHARGEUR, redémarrez le nœud : _bye_
+

NOTE: Ceci réinitialise les cartes d'E/S et les autres composants et redémarre le nœud.

+

NOTE: Assurez-vous de quitter le mode Maintenance après avoir terminé la conversion.

. Retournez le nœud en mode de fonctionnement normal : _Storage failover giveback -ofnode albridred_node_name_
. Si le rétablissement automatique a été désactivé, réactivez-le : _Storage failover modify -node local -auto-giveback true_




== Étape 4 : renvoyer la pièce défaillante à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièce et amp ; remplacements"] pour plus d'informations.
