= 
:allow-uri-read: 


Vous pouvez restaurer l'image ONTAP (récupération du support de démarrage) à partir du nœud partenaire à l'aide `boot_recovery -partner` de la commande sur les plateformes ASA r2 exécutant ONTAP 9.16.0 et versions ultérieures.

.Avant de commencer
Lorsque vous démarrez un nœud et que le support de démarrage sur ce nœud est corrompu, vous verrez les messages suivants et le processus de démarrage avec STOP à l'invite Loader :

[listing]
----

Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014


Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel:Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0,fat)


ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0,fat)


Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>

----
Si ce message s'affiche, vous devez restaurer l'image ONTAP

.Étapes
. À partir de l'invite Loader, entrez la commande _boot_Recovery -Partner_.
+
L'écran affiche le message `Starting boot media recovery (BMR) process press Ctrl-C to abort...` et commence les vérifications initiales.

. Surveillez le processus pendant que Loader configure les ports de cluster locaux et exécute netboot via `\http://<remote-partner-IP>:65530/recoverydisk/image.tgz`.
+
Une fois netboot en cours d'exécution, `Starting BMR ...` s'affiche à l'écran et le processus termine l'installation.

+
.. Si le gestionnaire de clés n'est pas configuré, le message suivant s'affiche :
+
....
key manager is not configured. Exiting.
....
.. Si le message suivant s'affiche, le gestionnaire de clés intégré (OKM) est configuré :
+
....

key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):

....
+
Passez à la section pour terminer le processus de récupération.

.. Si le message suivant s'affiche, le gestionnaire de clés externe (EKM) est configuré. Allez à la rubrique EKM et terminez le processus de restauration :
+
....
Error when fetching key manager config from partner 169.254.139.209: 28
Has key manager been configured on this system? {y|n}

....


. Surveillez le processus BMR lors de l'exécution de la restauration de la configuration de sauvegarde, du fichier env, de la base de données mdb et du rdb à partir du partenaire.
. Le nœud redémarre et le BMR est terminé lorsque vous voyez les éléments suivants :


....

varfs_backup_restore: update checksum for varfs.tgz
varfs_backup_restore: restore using /cfcard/x86_64/freebsd/oldvarfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: Rebooting to load the new varfs
.
Terminated
varfs_backup_restore: bootarg.abandon_varfs is set! Skipping /var backup.

....