= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Aucun chiffrement ni External Key Manager (EKM)
--
Remettez le contrôleur défectueux en mode de fonctionnement normal en laissant son espace de stockage.

.Étapes
. Dans l'invite Loader, entrez `boot_ontap`.
. Appuyez sur <enter> lorsque les messages de la console s'arrêtent.
+
** Si vous voyez l'invite _login_, passez à l'étape suivante à la fin de cette section.
** Si vous voyez _waiting for giveback_, appuyez sur la clé <enter>, connectez-vous au nœud partenaire, puis passez à l'étape suivante à la fin de cette section.


. Remettre le contrôleur défectueux en fonctionnement normal en réutilisant son espace de stockage : `storage failover giveback -ofnode _impaired_node_name_`
. Si le rétablissement automatique a été désactivé, le réactiver : `storage failover modify -node local -auto-giveback _true_`
. Si AutoSupport est activé, restaurer/annuler la suppression de la création automatique de cas : `system node autosupport invoke -node * -type all -message MAINT=END`


--
.Chiffrement intégré (OKM)
--
Restaurez et rescelliez les clés de chiffrement embarquées pour OKM et remettez le contrôleur en fonctionnement normal.

.Avant de commencer
Avant de commencer, consultez  https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-show-backup.html["security key-manager onboard show-backup"] ou contactez NetApp Support.

.Étapes
. Démarrez à partir du menu ONTAP à partir de l'invite Loader `boot_ontap menu` et sélectionnez l'option 10.
. Récupérez et vérifiez la phrase secrète globale du cluster auprès du contrôleur sain.
+
.. Exécutez la commande suivante pour récupérer la phrase secrète du cluster :
+
`security key-manager onboard show-backup`

.. Vérifiez la phrase secrète globale du cluster à l'aide de la commande suivante :
+
`security key-manager onboard verify-backup`



. Saisissez la phrase de passe OKM.
+

NOTE: Vous êtes invité à saisir deux fois la phrase de passe.

. Entrez les données de la clé de sauvegarde lorsque vous y êtes invité.
. Dans le menu de démarrage, entrez option `1` pour le démarrage normal.
. Appuyez sur <enter> lorsque _waiting for giveback_ s'affiche.
. Déplacez le câble de la console vers le nœud partenaire et connectez-vous en tant que `admin`.
. Ne donner que les agrégats CFO (l'agrégat racine) : `storage failover giveback -fromnode local -only-cfo-aggregates _true_`
+
** Si vous rencontrez des erreurs, contactez https://support.netapp.com["Support NetApp"].


. Attendez 5 minutes après la fin du rapport de rétablissement et vérifiez l'état du basculement et du rétablissement : `storage failover show` et `storage failover show-giveback`.
. Synchroniser et vérifier l'état des clés :
+
.. Replacer le câble de la console sur le contrôleur de remplacement.
.. Synchroniser les clés manquantes : `security key-manager onboard sync`
+

NOTE: Vous êtes invité à saisir la phrase de passe OKM au niveau du cluster.

.. Vérifier l'état des clés : `security key-manager key query -restored false`
+
La sortie ne devrait afficher aucun résultat lorsque la synchronisation est correcte.

+
Si le résultat affiche des résultats (les ID de clé des clés qui ne sont pas présents dans la table de clés internes du système), contactez https://support.netapp.com["Support NetApp"].



. Remettre le contrôleur défectueux en fonctionnement normal en réutilisant son espace de stockage : `storage failover giveback -ofnode _impaired_node_name_`
. Si le rétablissement automatique a été désactivé, le réactiver : `storage failover modify -node local -auto-giveback _true_`
+

NOTE: Ne passez pas outre le droit de veto sur le retour pour les clés manquantes. Contactez le support NetApp.

. Si AutoSupport est activé, restaurer/annuler la suppression de la création automatique de cas : `system node autosupport invoke -node * -type all -message MAINT=END`


--
====