= Vérifiez la configuration NVE
:allow-uri-read: 


Avant d'arrêter le contrôleur défaillant, vérifiez si NetApp Volume Encryption (NVE) ou NetApp Storage Encryption (NSE) sont activés sur le système. Si c'est le cas, vous devez vérifier la configuration.

.Étapes
. Connectez le câble de la console au contrôleur pour facultés affaiblies.
. Vérifier si NVE est configuré pour n'importe quel volume du cluster : `volume show -is-encrypted true`
+
Si des volumes sont répertoriés dans le résultat, NVE est configuré et vous devez vérifier la configuration NVE. Si aucun volume n'est indiqué, vérifiez si NSE est configuré ou non.

. Vérifier si NSE est configuré : `storage encryption disk show`
+
** Si le résultat de la commande affiche les détails du disque avec les informations relatives au mode et à l'ID de clé, NSE est configuré et vous devez vérifier la configuration NSE.
** Si NVE et NSE ne sont pas configurés, vous pouvez arrêter le contrôleur défaillant.






== Vérifiez la configuration NVE

.Étapes
. Afficher les ID de clé des clés d'authentification stockées sur les serveurs de gestion des clés : `security key-manager query`
+
** Si le `Restored` s'affiche `yes` et tous les gestionnaires de clés s'affichent `available`, il est sûr d'arrêter le contrôleur défaillant.
** Si le `Restored` colonne affiche tout autre élément que `yes`, ou si un gestionnaire de clés s'affiche `unavailable`, vous devez effectuer quelques étapes supplémentaires.
** Si le message cette commande n'est pas prise en charge lorsque la gestion intégrée des clés est activée, vous devez effectuer d'autres étapes supplémentaires.


. Si le `Restored` colonne affichée autre que `yes`, ou si un gestionnaire de clés s'affiche `unavailable`:
+
.. Récupérez et restaurez toutes les clés d'authentification et les ID de clé associés : `security key-manager restore -address *`
+
Si la commande échoue, contactez le support NetApp.

+
http://mysupport.netapp.com/["mysupport.netapp.com"]

.. Vérifiez que le `Restored` s'affiche `yes` affichage de toutes les clés d'authentification et de tous les gestionnaires de clés `available`: `security key-manager query`
.. Arrêtez le contrôleur défaillant.


. Si vous avez vu le message, cette commande n'est pas prise en charge lorsque la gestion intégrée des clés est activée, affichez les clés stockées dans le gestionnaire de clés intégré : `security key-manager key show -detail`
+
.. Si le `Restored` s'affiche `yes` sauvegardez manuellement les informations de gestion intégrée des clés :
+
*** Accédez au mode de privilège avancé et entrez `y` lorsque vous êtes invité à continuer : `set -priv advanced`
*** Entrez la commande pour afficher les informations de sauvegarde OKM : `security key-manager backup show`
*** Copiez le contenu des informations de sauvegarde dans un fichier distinct ou dans votre fichier journal. Dans les scénarios d'incident, vous devrez peut-être restaurer manuellement le gestionnaire de clés intégré OKM.
*** Revenir en mode admin: `set -priv admin`
*** Arrêtez le contrôleur défaillant.


.. Si le `Restored` colonne affiche tout autre élément que `yes`:
+
*** Exécutez l'assistant d'installation du gestionnaire de clés : `security key-manager setup -node target/impaired node name`
+

NOTE: Entrez la phrase secrète de gestion de clés intégrée du client à l'invite. Si la phrase de passe ne peut pas être fournie, contactez http://mysupport.netapp.com/["mysupport.netapp.com"]

*** Vérifiez que le `Restored` s'affiche `yes` pour toutes les clés d'authentification : `security key-manager key show -detail`
*** Accédez au mode de privilège avancé et entrez `y` lorsque vous êtes invité à continuer : `set -priv advanced`
*** Entrez la commande pour afficher les informations de sauvegarde OKM : `security key-manager backup show`
*** Copiez le contenu des informations de sauvegarde dans un fichier distinct ou dans votre fichier journal. Dans les scénarios d'incident, vous devrez peut-être restaurer manuellement le gestionnaire de clés intégré OKM.
*** Revenir en mode admin: `set -priv admin`
*** Vous pouvez arrêter le contrôleur en toute sécurité.








== Vérifiez la configuration NSE

.Étapes
. Afficher les ID de clé des clés d'authentification stockées sur les serveurs de gestion des clés : `security key-manager query`
+
** Si le `Restored` s'affiche `yes` et tous les gestionnaires de clés s'affichent `available`, il est sûr d'arrêter le contrôleur défaillant.
** Si le `Restored` colonne affiche tout autre élément que `yes`, ou si un gestionnaire de clés s'affiche `unavailable`, vous devez effectuer quelques étapes supplémentaires.
** Si le message cette commande n'est pas prise en charge lorsque la gestion intégrée des clés est activée, vous devez effectuer d'autres étapes supplémentaires


. Si le `Restored` colonne affichée autre que `yes`, ou si un gestionnaire de clés s'affiche `unavailable`:
+
.. Récupérez et restaurez toutes les clés d'authentification et les ID de clé associés : `security key-manager restore -address *`
+
Si la commande échoue, contactez le support NetApp.

+
http://mysupport.netapp.com/["mysupport.netapp.com"]

.. Vérifiez que le `Restored` s'affiche `yes` affichage de toutes les clés d'authentification et de tous les gestionnaires de clés `available`: `security key-manager query`
.. Arrêtez le contrôleur défaillant.


. Si vous avez vu le message, cette commande n'est pas prise en charge lorsque la gestion intégrée des clés est activée, affichez les clés stockées dans le gestionnaire de clés intégré : `security key-manager key show -detail`
+
.. Si le `Restored` s'affiche `yes`, sauvegardez manuellement les informations de gestion des clés intégrées :
+
*** Accédez au mode de privilège avancé et entrez `y` lorsque vous êtes invité à continuer : `set -priv advanced`
*** Entrez la commande pour afficher les informations de sauvegarde OKM :  `security key-manager backup show`
*** Copiez le contenu des informations de sauvegarde dans un fichier distinct ou dans votre fichier journal. Dans les scénarios d'incident, vous devrez peut-être restaurer manuellement le gestionnaire de clés intégré OKM.
*** Revenir en mode admin: `set -priv admin`
*** Arrêtez le contrôleur défaillant.


.. Si le `Restored` colonne affiche tout autre élément que `yes`:
+
*** Exécutez l'assistant d'installation du gestionnaire de clés : `security key-manager setup -node target/impaired node name`
+

NOTE: Entrez la phrase de passe OKM du client à l'invite. Si la phrase de passe ne peut pas être fournie, contactez http://mysupport.netapp.com/["mysupport.netapp.com"]

*** Vérifiez que le `Restored` affiche la colonne `yes` pour toutes les clés d'authentification : `security key-manager key show -detail`
*** Accédez au mode de privilège avancé et entrez `y` lorsque vous êtes invité à continuer : `set -priv advanced`
*** Entrez la commande pour sauvegarder les informations OKM : ``security key-manager backup show``
+

NOTE: Assurez-vous que les informations OKM sont enregistrées dans votre fichier journal. Ces informations seront nécessaires dans les scénarios d'incident pour lesquels OKM peut avoir besoin d'être restauré manuellement.

*** Copiez le contenu des informations de sauvegarde dans un fichier distinct ou dans votre journal. Dans les scénarios d'incident, vous devrez peut-être restaurer manuellement le gestionnaire de clés intégré OKM.
*** Revenir en mode admin: `set -priv admin`
*** Vous pouvez arrêter le contrôleur en toute sécurité.





