= De formation
:allow-uri-read: 


Passez en revue les exigences et considérations suivantes.



== De formation

* Le châssis de remplacement doit être du même modèle que le châssis défectueux. Cette procédure est destinée à un remplacement similaire, et non à une mise à niveau.
* Tous les autres composants du système de stockage doivent fonctionner correctement ; dans le cas contraire, contactez https://mysupport.netapp.com/site/global/dashboard["Support NetApp"] avant de poursuivre cette procédure.




== Considérations

* La procédure de remplacement du châssis est disruptive. Dans le cas d'un cluster à deux nœuds, la panne totale du service et une panne partielle dans un cluster multinœud sont associés.
* Vous pouvez suivre la procédure de remplacement du châssis avec toutes les versions de ONTAP prises en charge par votre système de stockage.
* La procédure de remplacement du châssis suppose que vous déplacez le panneau, les disques, les caches de disques et les contrôleurs vers le nouveau châssis.

