= De formation
:allow-uri-read: 


Vous devez revoir les conditions requises et les considérations relatives à la procédure de remplacement du contrôleur.



== De formation

* Toutes les tablettes doivent fonctionner correctement.
* Le contrôleur sain doit pouvoir reprendre le contrôleur qui est remplacé (appelé « contrôleur défectueux » dans cette procédure).
* Vous devez remplacer un contrôleur par un contrôleur de même type. Vous ne pouvez pas mettre à niveau votre système en remplaçant simplement le contrôleur.
* Vous ne pouvez pas modifier de disques ou de tiroirs dans le cadre de cette procédure.
* Vous devez toujours capturer la sortie de la console du contrôleur dans un fichier journal texte.
+
Le résultat de la console vous fournit un enregistrement de la procédure que vous pouvez utiliser pour résoudre les problèmes que vous pourriez rencontrer pendant le processus de remplacement.





== Considérations

* Il est important d'appliquer les commandes de cette procédure au contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur qui est en cours de remplacement.
** Le contrôleur _remplacement_ est le nouveau contrôleur qui remplace le contrôleur défaillant.
** Le contrôleur _Healthy_ est le contrôleur survivant.



