= 
:allow-uri-read: 


Préparez le système de stockage et l'emplacement du module d'E/S afin qu'il soit sûr de retirer le module d'E/S défectueux :

.Étapes
. Mettez-vous à la terre.
. Débranchez les câbles du module d'E/S défectueux.
+
Veillez à étiqueter les câbles afin de pouvoir les reconnecter aux mêmes ports plus tard dans cette procédure.

+
[NOTE]
====
Le module d'E/S devrait être défaillant (les ports devraient être en état de liaison désactivée) ; cependant, si les liaisons sont toujours actives et qu'elles contiennent le dernier port de cluster fonctionnel, le débranchement des câbles déclenche un basculement automatique.

Attendez cinq minutes après avoir débranché les câbles pour vous assurer que tous les basculements automatiques ou les basculements LIF sont terminés avant de poursuivre cette procédure.

====
. Si AutoSupport est activé, supprimez la création automatique de dossier en invoquant un message AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`

+
Par exemple, le message AutoSupport suivant supprime la création automatique de cas pendant deux heures :

+
`node2::> system node autosupport invoke -node * -type all -message MAINT=2h`

. En fonction de la version d'ONTAP exécutée par votre système de stockage et de l'état des contrôleurs, désactivez la restitution automatique :
+
[cols="1,2,3"]
|===
| Version ONTAP | Si... | Alors... 


 a| 
9.17.1 ou 9.18.1RC
 a| 
Si le contrôleur défaillant a pris automatiquement le relais du contrôleur sain
 a| 
Désactiver le retour automatique :

.. Saisissez la commande suivante depuis la console du contrôleur défectueux
+
`storage failover modify -node local -auto-giveback false`

.. Entrer `y` lorsque vous voyez l'invite _Voulez-vous désactiver le retour automatique ?_




 a| 
9.18.1GA ou version ultérieure
 a| 
Si l'un des contrôleurs a pris le contrôle de son partenaire automatiquement
 a| 
Désactiver le retour automatique :

.. Saisissez la commande suivante depuis la console du contrôleur qui a pris le contrôle de son partenaire :
+
`storage failover modify -node local -auto-giveback false`

.. Entrer `y` lorsque vous voyez l'invite _Voulez-vous désactiver le retour automatique ?_




 a| 
9.18.1GA ou version ultérieure
 a| 
Les deux contrôleurs sont opérationnels et traitent des E/S (fournissent des données)
 a| 
Passez à l'étape suivante.

|===
. Préparez le module d'E/S défectueux en vue de son retrait en le mettant hors service et en le coupant de l'alimentation :
+
.. Entrez la commande suivante :
+
`system controller slot module remove -node _impaired_node_name_ -slot _slot_number_`

.. Entrer `y` lorsque vous voyez l'invite _Voulez-vous continuer ?_
+
Par exemple, la commande suivante prépare le module défaillant dans l'emplacement 4 sur le nœud 2 (le contrôleur défectueux) pour le retrait, et affiche un message indiquant qu'il est sûr de le retirer :

+
[listing]
----
node2::> system controller slot module remove -node node2 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node2 will be powered off for removal.

Do you want to continue? {y|n}: y

The module has been successfully removed from service and powered off. It can now be safely removed.
----


. Vérifiez que le module d'E/S défectueux est hors tension :
+
`system controller slot module show`

+
Le résultat doit afficher  `_powered-off_` dans la  `_status_` colonne pour le module défaillant et son numéro d'emplacement.


