= Équipement nécessaire pour l'installation
:allow-uri-read: 




== Équipement nécessaire pour l'installation

Pour installer votre système de stockage, vous avez besoin de l'équipement et des outils suivants.

* Accès à un navigateur Web pour configurer votre système de stockage
* Sangle de décharge électrostatique (ESD)
* Lampe de poche
* Ordinateur portable ou console avec connexion USB/série
* Trombone ou stylo à pointe sphérique à pointe étroite pour le réglage des ID de tablette de stockage NS224
* Tournevis Phillips n°2




== Précautions de levage

Les systèmes de stockage et les tiroirs sont lourds. Faites preuve de prudence lorsque vous soulevez et déplacez ces éléments.



=== Poids du système de stockage

Prenez les précautions nécessaires lors du déplacement ou du levage de votre système de stockage.



=== Poids de la tablette

Prenez les précautions nécessaires lorsque vous déplacez ou soulevez votre tablette.

.Informations associées
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informations de sécurité et avis réglementaires"^]

