= Équipement nécessaire pour l'installation
:allow-uri-read: 




== Équipement nécessaire pour l'installation

Pour installer votre système de stockage, vous avez besoin de l'équipement et des outils suivants.

* Accès à un navigateur Web pour configurer votre système de stockage
* Sangle de décharge électrostatique (ESD)
* Lampe de poche
* Ordinateur portable ou console avec connexion USB/série
* Trombone ou stylo à pointe sphérique à pointe étroite pour le réglage des ID de tablette de stockage NS224
* Tournevis Phillips n°2




== Précautions de levage

Les systèmes de stockage et les tiroirs de stockage sont lourds. Faites preuve de prudence lorsque vous soulevez et déplacez ces éléments.



=== Poids du système de stockage

Prenez les précautions nécessaires lors du déplacement ou du levage de votre système de stockage.

[role="tabbed-block"]
====
.A1K
--
Un système de stockage A1K peut peser jusqu'à 28.5 kg (62.83 lb). Pour soulever le système, faire appel à deux personnes ou à un relevage hydraulique.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1K icône d'avertissement de levage]

--
.A70 et A90
--
Un système de stockage A70 ou A90 peut peser jusqu'à 68.8 kg (151.68 lb). Pour lever le système, faire appel à quatre personnes ou à un relevage hydraulique.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[Icône d'avertissement de poids AFF A90 et AFF A70]

--
====


=== Poids des étagères de stockage

Une étagère de stockage NS224 peut peser jusqu'à 30.29 kg (66.78 lb). Pour soulever la tablette de rangement, faites appel à deux personnes ou à un dispositif de levage hydraulique. Conservez tous les composants dans la tablette de stockage (avant et arrière) pour éviter de débalourer le poids de la tablette.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[Avertissement de levage NS224]

.Informations associées
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informations de sécurité et avis réglementaires"^]

