= 
:allow-uri-read: 


[cols="2*"]
|===
| Plateformes (avec liens vers les fiches techniques) | Disponible au début 


 a| 
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A1K"]
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A70"]
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A90"]

 a| 
ONTAP 9.15.1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C250"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C400"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C800"]
 a| 
ONTAP 9.13.P11



 a| 
https://hwu.netapp.com/ProductSpecs/Index["FAS2820"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A150"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A250"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A400"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A900"]
 a| 
ONTAP 9.13.1



 a| 
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C250"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C400"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C800"]

 a| 
ONTAP 9.12.1P1

ONTAP 9.13.1 GA et versions ultérieures ONTAP

[NOTE]
====
Ces plateformes ne sont pas prises en charge avec ONTAP 9.13.1 RC1.

====


 a| 
https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A150"]

[NOTE]
====
N'essayez pas d'installer ou de démarrer votre système de stockage AFF A150 avec une version non prise en charge de ONTAP. Si vous tentez d'installer ou de démarrer votre système avec une version non prise en charge de ONTAP, ONTAP l'autorisera (ONTAP ne bloquera pas la tentative). Par conséquent, votre système de stockage AFF A150 apparaît comme un système de stockage FAS2750.

==== a| 
ONTAP 9.13.1 et versions ultérieures de ONTAP

ONTAP 9.12.1P1

ONTAP 9.11.1P8

ONTAP 9.10.1P12



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS9500"]
 a| 
ONTAP 9.11.1

ONTAP 9.10.1P3



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A900"]
 a| 
ONTAP 9.10.1



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A250/AFF ASA A250"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS500f"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A800"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8300"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A400"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AVEC AFF ASA A220"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7623-ds-3989.pdf["AFF C190"^]
 a| 
ONTAP 9.6



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF A320"]
 a| 
ONTAP 9.6

|===