= 
:allow-uri-read: 


Vous devez restaurer les informations de configuration du volume racine vers les périphériques de démarrage.

.Description de la tâche
Vous devez effectuer ces étapes sur les nœuds 3 et 4, en effectuant chaque étape sur un nœud, puis sur l'autre avant de passer à l'étape suivante.

.Étapes
. Accéder au menu de démarrage à partir de l'invite DU CHARGEUR : `boot_ontap menu`
. Dans le menu de démarrage, sélectionnez (6) mettre à jour la mémoire flash dans la configuration de sauvegarde et entrez``y`` lorsque vous êtes invité à continuer.
+
[listing]
----
Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 6

This will replace all flash-based configuration with the last backup to
disks. Are you sure you want to continue?: y
----
+
Le processus de mise à jour flash s'exécute pendant plusieurs minutes, puis le système redémarre.

. Lorsque vous êtes invité à confirmer que l'ID système ne correspond pas, entrez `y`.
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id? {y|n} [n] y
----
+
La séquence de démarrage se poursuit normalement.


