---
permalink: c190/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: AFF c190, nondisruptive, disruptive, replace the boot media, manual, manual boot recovery 
summary: 'Découvrez comment remplacer le support de démarrage sur un système AFF C190 et comprenez les différentes méthodes de remplacement. Le système AFF C190 ne prend en charge que les procédures de récupération manuelles du support de démarrage. La récupération automatique du support de démarrage n"est pas prise en charge.' 
---
= Présentation du remplacement du support de démarrage - AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez comment remplacer le support de démarrage sur un système AFF C190 et comprenez les différentes méthodes de remplacement. Le support de démarrage stocke les fichiers image de démarrage primaire et secondaire utilisés par le système au démarrage. Selon la configuration de votre réseau, vous pouvez effectuer soit un remplacement non perturbateur (paire HA connectée au réseau), soit un remplacement perturbateur (nécessite deux redémarrages).

Le système AFF C190 ne prend en charge que les procédures de récupération manuelles du support de démarrage. La récupération automatique du support de démarrage n'est pas prise en charge.

Vous devez disposer d'une clé USB, formatée en FAT32, avec la quantité de stockage appropriée pour maintenir le `image_xxx.tgz` fichier.

* Les méthodes de remplacement d'un support de démarrage sans interruption et entraînant des perturbations nécessitent toutes deux la restauration du système de fichiers var :
+
** Pour un remplacement sans interruption, la paire HA doit être connectée à un réseau afin de restaurer le système de fichiers var.
** Pour le remplacement perturbateur, vous n'avez pas besoin d'une connexion réseau pour restaurer le système de fichiers var, mais le processus nécessite deux redémarrages.


* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.
* Il est important d'appliquer les commandes au cours de la procédure suivante sur le contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le contrôleur _Healthy_ est le partenaire HA du contrôleur déficient.



