---
permalink: c190/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: AFF c190, nondisruptive, disruptive, replace the boot media, manual, manual boot recovery 
summary: 'Découvrez comment remplacer le support de démarrage sur un système AFF C190 et comprenez les différentes méthodes de remplacement. Le système AFF C190 ne prend en charge que les procédures de récupération manuelles du support de démarrage. La récupération automatique du support de démarrage n"est pas prise en charge.' 
---
= Présentation du remplacement du support de démarrage - AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez comment remplacer le support de démarrage sur un système AFF C190 et comprenez les différentes méthodes de remplacement. Le support de démarrage stocke les fichiers image de démarrage primaire et secondaire utilisés par le système au démarrage. Selon la configuration de votre réseau, vous pouvez effectuer soit un remplacement non perturbateur (paire HA connectée au réseau), soit un remplacement perturbateur (nécessite deux redémarrages).

[NOTE]
====
NetApp recommande fortement d'activer la journalisation de la console sur les appareils que vous utilisez et de prendre les mesures suivantes lors de cette procédure :

* Laissez AutoSupport activé pendant votre maintenance. Cela permet au support NetApp de recevoir des informations de diagnostic en cas de problème.
* Activez la journalisation des sessions pour toutes les sessions CLI. Cela crée un enregistrement complet de toutes les commandes et des sorties système pendant l'opération de maintenance. Pour savoir comment activer la journalisation des sessions, consultez  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Comment configurer PuTTY pour une connectivité optimale aux systèmes ONTAP"^].


====
Le système AFF C190 ne prend en charge que les procédures de récupération manuelles du support de démarrage. La récupération automatique du support de démarrage n'est pas prise en charge.

Vous devez disposer d'une clé USB, formatée en FAT32, avec la quantité de stockage appropriée pour maintenir le `image_xxx.tgz` fichier.

* Les méthodes de remplacement d'un support de démarrage sans interruption et entraînant des perturbations nécessitent toutes deux la restauration du système de fichiers var :
+
** Pour un remplacement sans interruption, la paire HA doit être connectée à un réseau afin de restaurer le système de fichiers var.
** Pour le remplacement perturbateur, vous n'avez pas besoin d'une connexion réseau pour restaurer le système de fichiers var, mais le processus nécessite deux redémarrages.


* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.
* Il est important d'appliquer les commandes au cours de la procédure suivante sur le contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le contrôleur _Healthy_ est le partenaire HA du contrôleur déficient.



