---
permalink: c190/chassis-replace-complete-rma.html 
sidebar: sidebar 
keywords: aff c190, verify and set HA state 
summary: 'Vous devez vérifier l"état de haute disponibilité du châssis.' 
---
= Restaurez et vérifiez la configuration - AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez vérifier l'état de haute disponibilité du châssis.



== Étape 1 : vérification et paramétrage de l'état HA du châssis

Vous devez vérifier l'état HA du châssis et, le cas échéant, mettre à jour l'état pour qu'il corresponde à la configuration de votre système.

. En mode Maintenance, depuis l'un ou l'autre module de contrôleur, afficher l'état HA du module de contrôleur local et du châssis :
+
`*ha-config show*`

+
L'état de la HA doit être le même pour tous les composants.

. Si l'état du système affiché pour le châssis ne correspond pas à la configuration de votre système :
+
.. Définissez l'état haute disponibilité du châssis :
+
`*ha-config modify chassis _HA-state_*`

+
La valeur pour `_HA-state_` peut être l'une des suivantes :

+
*** `ha`
*** `non-ha`


.. Vérifiez que le paramètre a changé :
+
`*ha-config show*`



. Si vous ne l'avez pas déjà fait, recâble le reste de votre système.
. Redémarrez le système.




== Étape 2 : renvoyer la pièce défectueuse à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièces et remplacements"] page pour plus d'informations.
