---
permalink: a700/maintain-overview.html 
sidebar: sidebar 
keywords: aff A700 maintenance, maintenance, repairing A700, repairing aff A700, replace aff A700 components, replace aff A700 components 
summary: Conservez le matériel ASA A700 
---
= Maintenance du matériel AFF A700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour le système de stockage AFF A700, vous pouvez effectuer les procédures de maintenance sur les composants suivants.



== Support de démarrage

Le support de démarrage stocke un ensemble principal et secondaire de fichiers d'image de démarrage que le système utilise lorsqu'il démarre.



== Module de cache

Vous devez remplacer le module de cache du contrôleur lorsque votre système enregistre un seul message AutoSupport (ASUP) indiquant que le module est hors ligne.



== Châssis

Le châssis correspond au boîtier physique qui contient tous les composants du contrôleur, tels que le contrôleur/l'unité centrale, l'alimentation et les E/S.



== Contrôleur

Un contrôleur se compose d'une carte, d'un micrologiciel et d'un logiciel. Il contrôle les entraînements et met en œuvre les fonctions ONTAP.



== DCPM

Le DCPM (module d'alimentation du contrôleur de déchargement) contient la batterie NVRAM11.



== DIMM

Vous devez remplacer un module DIMM (module de mémoire double en ligne) en cas de non-concordance de mémoire, ou si vous avez un module DIMM défectueux.



== Ventilateur

Le ventilateur refroidit le contrôleur.



== Module d'E/S.

Le module d'E/S (module d'entrée/sortie) est un composant matériel qui sert d'intermédiaire entre le contrôleur et divers dispositifs ou systèmes qui doivent échanger des données avec le contrôleur.



== VOYANT USB

Le module USB à LED fournit la connectivité aux ports de console et à l'état du système.



== NVRAM

Le module NVRAM (mémoire vive non volatile) permet au contrôleur de conserver les données lors des mises hors/sous tension ou des redémarrages du système.



== Alimentation électrique

Une alimentation électrique fournit une source d'alimentation redondante dans un tiroir contrôleur.



== Pile de l'horloge en temps réel

Une batterie d'horloge en temps réel conserve les informations relatives à la date et à l'heure du système si l'alimentation est coupée.



== Module X91148A

Le module X91148A est un module d'E/S qui sert d'intermédiaire entre le contrôleur et divers dispositifs ou systèmes qui doivent échanger des données avec le contrôleur.
