---
permalink: fas-70-90/bootmedia-encryption-restore.html 
sidebar: sidebar 
keywords: fas70, fas90, post boot media replacement steps for okm, nse, and nve 
summary: 'Une fois les variables d"environnement vérifiées, vous devez effectuer une procédure spécifique aux systèmes sur lesquels Onboard Key Manager \(OKM\), NetApp Storage Encryption \(NSE\) ou NetApp Volume Encryption \(NVE\) est activé.' 
---
= Restaurez le chiffrement - FAS70 et FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Restaurez le chiffrement sur le support de démarrage de remplacement.



== Étape 1 : restaurez le gestionnaire de clés

Vous devez effectuer les étapes spécifiques aux systèmes pour lesquels le gestionnaire de clés intégré (OKM), le chiffrement de stockage NetApp (NSE) ou le chiffrement de volume NetApp (NVE) sont activés à l'aide des paramètres que vous avez capturés au début de cette procédure.


NOTE: Si NSE ou NVE sont activés et que le gestionnaire de clés intégré ou externe est activé, vous devez restaurer les paramètres que vous avez capturés au début de cette procédure.

.Étapes
. Branchez le câble de la console au contrôleur cible.
. Sélectionnez l'une des options suivantes pour restaurer la configuration du gestionnaire de clés intégré à partir du menu d'amorçage ONAT.


[role="tabbed-block"]
====
.Option 1 : systèmes avec configuration de serveur de gestionnaire de clés intégrée
--
Restaurez la configuration du gestionnaire de clés intégré (OKM) à partir du menu de démarrage ONTAP.

.Avant de commencer
* Assurez-vous de disposer des informations suivantes lors de la restauration de la configuration de OKM :
+
** Phrase de passe à l'échelle du cluster entrée https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html["tout en activant la gestion intégrée des clés"].
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/backup-key-management-information-manual-task.html["Informations de sauvegarde pour le gestionnaire de clés intégré"].


* Effectuer la https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_verify_onboard_key_management_backup_and_cluster-wide_passphrase["Comment vérifier la sauvegarde de gestion intégrée des clés et la phrase secrète au niveau du cluster"] procédure avant de continuer.


.Étapes
. Branchez le câble de la console au contrôleur cible.
. Dans le menu de démarrage ONTAP, sélectionnez l'option appropriée :
+
[cols="1a,2a"]
|===
| Version ONTAP | Sélectionnez cette option 


 a| 
ONTAP 9.8 ou version ultérieure
 a| 
Sélectionnez l'option 10.

|===


--
====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 10

....
[]
====
A| ONTAP 9.7 et versions antérieures a| sélectionnez l'option cachée `recover_onboard_keymanager`

====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
Selection (1-19)? recover_onboard_keymanager

....
[]
====
|===


| + . Confirmez que vous souhaitez poursuivre le processus de restauration. + .Afficher l'exemple d'invite [%pliable] 
|===
====
`This option must be used only in disaster recovery procedures. Are you sure? (y or n):`

[]
====
. Saisissez deux fois la phrase de passe au niveau du cluster.
+
Lorsque vous saisissez la phrase de passe, la console n'affiche aucune entrée.



====
`Enter the passphrase for onboard key management:`

`Enter the passphrase again to confirm:`

[]
====
+

. Entrez les informations de sauvegarde.
+
.. Collez l'intégralité du contenu de la ligne de DÉBUT DE SAUVEGARDE à travers la ligne de FIN DE SAUVEGARDE.




====
....
Enter the backup data:

--------------------------BEGIN BACKUP--------------------------
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
3456789012345678901234567890123456789012345678901234567890123456
4567890123456789012345678901234567890123456789012345678901234567
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

---------------------------END BACKUP---------------------------

....
[]
====
. Appuyez deux fois sur la touche entrée à la fin de l'entrée.
+
Le processus de récupération est terminé.



====
....

Enter the backup data:

Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.

***********************************************************************************
* Select option "(1) Normal Boot." to complete recovery process.
*
* Run the "security key-manager onboard sync" command to synchronize the key database after the node reboots.
***********************************************************************************

....
[]
====
+ ATTENTION : ne pas continuer si la sortie affichée est autre que `Successfully recovered keymanager secrets`. Effectuez le dépannage pour corriger l'erreur.

. Sélectionnez l'option 1 dans le menu de démarrage pour poursuivre le démarrage dans ONTAP.


====
....

***********************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***********************************************************************************


(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
[]
====
. Vérifier que la console du contrôleur affiche les éléments suivants :
+
`Waiting for giveback...(Press Ctrl-C to abort wait)`

. Depuis le nœud partenaire, rendre le contrôleur partenaire :
+
`storage failover giveback -fromnode local -only-cfo-aggregates true`.

. Après le démarrage avec un agrégat CFO uniquement, exécutez la commande suivante :
+
`security key-manager onboard sync` commande.

. Saisissez la phrase secrète pour l'ensemble du cluster pour le gestionnaire de clés intégré.


====
....

Enter the cluster-wide passphrase for the Onboard Key Manager:

All offline encrypted volumes will be brought online and the corresponding volume encryption keys (VEKs) will be restored automatically within 10 minutes. If any offline encrypted volumes are not brought online automatically, they can be brought online manually using the "volume online -vserver <vserver> -volume <volume_name>" command.

....
[]
====
+ REMARQUE : si la synchronisation réussit, l'invite du cluster est renvoyée sans message supplémentaire. Si la synchronisation échoue, un message d'erreur s'affiche avant de revenir à l'invite du cluster. Ne continuez pas tant que l'erreur n'a pas été corrigée et que la synchronisation a réussi.

. Assurez-vous que toutes les clés sont synchronisées :
+
`security key-manager key query -restored false`.

+
`There are no entries matching your query.`

+

NOTE: Aucun résultat ne doit apparaître lors du filtrage de FALSE dans le paramètre restauré.

. Giveback le nœud du partenaire :
+
`storage failover giveback -fromnode local`

. Si vous l'avez désactivée, restaurez le rétablissement automatique en saisissant la commande suivante :
+
`storage failover modify -node local -auto-giveback true`

. Si AutoSupport est activé, restaurez la création automatique de dossiers en saisissant la commande suivante :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--

--
Restaurez la configuration du gestionnaire de clés externe à partir du menu de démarrage ONAT.

.Avant de commencer
Vous avez besoin des informations suivantes pour restaurer la configuration du gestionnaire de clés externe (EKM) :

* Copie du fichier /cfcard/kmip/servers.cfg à partir d'un autre nœud de cluster ou des informations suivantes :
+
** Adresse du serveur KMIP.
** Port KMIP.
** Copie du fichier /cfcard/kmip/certs/client.crt d'un autre nœud de cluster ou du certificat client.
** Copie du fichier /cfcard/kmip/certs/client.key à partir d'un autre nœud de cluster ou de la clé client.
** Copie du fichier /cfcard/kmip/certs/CA.pem d'un autre nœud de cluster ou de l'autorité de certification du serveur KMIP.




.Étapes
. Branchez le câble de la console au contrôleur cible.
. Sélectionnez l'option 11 dans le menu de démarrage ONTAP.


====
....

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 11
....
[]
====
+

. Lorsque vous y êtes invité, vérifiez que vous avez recueilli les informations requises.


====
....
Do you have a copy of the /cfcard/kmip/certs/client.crt file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/client.key file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/CA.pem file? {y/n}
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
....
[]
====
+

====
....
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
Do you know the KMIP server address? {y/n}
Do you know the KMIP Port? {y/n}
....
[]
====
+

. Lorsque vous y êtes invité, entrez les informations sur le client et le serveur.


====
....
Enter the client certificate (client.crt) file contents:
Enter the client key (client.key) file contents:
Enter the KMIP server CA(s) (CA.pem) file contents:
Enter the server configuration (servers.cfg) file contents:
....
[]
====
+ .montrer l'exemple

====
....
Enter the client certificate (client.crt) file contents:
-----BEGIN CERTIFICATE-----
MIIDvjCCAqagAwIBAgICN3gwDQYJKoZIhvcNAQELBQAwgY8xCzAJBgNVBAYTAlVT
MRMwEQYDVQQIEwpDYWxpZm9ybmlhMQwwCgYDVQQHEwNTVkwxDzANBgNVBAoTBk5l
MSUbQusvzAFs8G3P54GG32iIRvaCFnj2gQpCxciLJ0qB2foiBGx5XVQ/Mtk+rlap
Pk4ECW/wqSOUXDYtJs1+RB+w0+SHx8mzxpbz3mXF/X/1PC3YOzVNCq5eieek62si
Fp8=
-----END CERTIFICATE-----

Enter the client key (client.key) file contents:
-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAoU1eajEG6QC2h2Zih0jEaGVtQUexNeoCFwKPoMSePmjDNtrU
MSB1SlX3VgCuElHk57XPdq6xSbYlbkIb4bAgLztHEmUDOkGmXYAkblQ=
-----END RSA PRIVATE KEY-----

Enter the KMIP server CA(s) (CA.pem) file contents:
-----BEGIN CERTIFICATE-----
MIIEizCCA3OgAwIBAgIBADANBgkqhkiG9w0BAQsFADCBjzELMAkGA1UEBhMCVVMx
7yaumMQETNrpMfP+nQMd34y4AmseWYGM6qG0z37BRnYU0Wf2qDL61cQ3/jkm7Y94
EQBKG1NY8dVyjphmYZv+
-----END CERTIFICATE-----

Enter the IP address for the KMIP server: 10.10.10.10
Enter the port for the KMIP server [5696]:

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
kmip_init: configuring ports
Running command '/sbin/ifconfig e0M'
..
..
kmip_init: cmd: ReleaseExtraBSDPort e0M
​​​​....


====

. The recovery process completes.


+
.Show example prompt
[%collapsible]
====
....
Le système est prêt à utiliser un ou plusieurs gestionnaires de clés externes. Tentative de récupération des clés à partir des serveurs clés [Aoû 29 21:06:28]: 0x808806100: 0: DEBUG: Kmip2::main: [InitOpenssl]:460: L'initialisation d'OpenSSL a réussi à récupérer les secrets keymanager.

....



. Select option 1 from the boot menu to continue booting into ONTAP.

+
....
****
* Sélectionnez l'option « (1) démarrage normal » pour terminer le processus de récupération. *


****
(1) démarrage normal. (2) démarrez sans /etc/rc. (3) Modifier le mot de passe. (4) nettoyer la configuration et initialiser tous les disques. (5) démarrage en mode Maintenance. (6) mettre à jour la mémoire flash à partir de la configuration de sauvegarde. (7) installez d'abord le nouveau logiciel. (8) redémarrez le nœud. (9) configurez le partitionnement de disque avancé. (10) mettez en place les secrets de récupération du gestionnaire de clés intégré. (11) configurez le nœud pour la gestion externe des clés. Sélection (1-11) ? 1

....
====
+


. Restore automatic giveback, if you disabled it, by entering the following command:
+
`storage failover modify -node local -auto-giveback true` command.

. If AutoSupport is enabled, restore automatic case creation by entering  the following command:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


--

====

== Step 2: Complete the boot media replacement

Complete the boot media replacement process after the normal boot by completing final checks and giving back storage.

. Check the console output:
+
[%header,cols="1,3"]
|===
| If the console displays...| Then...
a|
The login prompt
a|
Go to Step 6.
a|
Waiting for giveback...
a|

 .. Log into the partner controller.
 .. Confirm the target controller is ready for giveback with the _storage failover show_ command.

|===

. Move the console cable to the partner controller and give back the target controller storage using the _storage failover giveback -fromnode local -only-cfo-aggregates true_ command.

 ** If the command fails because of a failed disk, physically disengage the failed disk, but leave the disk in the slot until a replacement is received.

 ** If the command fails because the partner is "not ready", wait 5 minutes for the HA subsystem to synchronize between the partners.
 ** If the command fails because of an NDMP, SnapMirror, or SnapVault process, disable the process. See the appropriate Documentation Center for more information.
. Wait 3 minutes and check the failover status with the _storage failover show_ command.
. At the clustershell prompt, enter the _network interface show -is-home false_ command to list the logical interfaces that are not on their home controller and port.
+
If any interfaces are listed as `false`, revert those interfaces back to their home port using the _net int revert -vserver Cluster -lif _nodename_ command.

. Move the console cable to the target controller and run the _version -v_ command to check the ONTAP versions.

. Use the `storage encryption disk show` to review the output.
. Use the _security key-manager key query_ command to display the key IDs of the authentication keys that are stored on the key management servers.
 ** If the `Restored` column = `yes/true`, you are done and can proceed to complete the replacement process.
 ** If the `Key Manager type` = `external` and the `Restored` column = anything other than `yes/true`, use the _security key-manager external restore_ command to restore the key IDs of the authentication keys.
+
NOTE: If the command fails, contact Customer Support.

 ** If the `Key Manager type` = `onboard` and the `Restored` column = anything other than `yes/true`, use the _security key-manager onboard sync_ command to synchronize the missing onboard keys on the repaired node.
+
Use the _security key-manager key query_ command to verify that the `Restored` column = `yes/true` for all authentication keys.

. Connect the console cable to the partner controller.
. Give back the controller using the `storage failover giveback -fromnode local` command.
. Restore automatic giveback if you disabled it by using the _storage failover modify -node local -auto-giveback true_ command.
. If AutoSupport is enabled, restore/unsuppress automatic case creation by using the _system node autosupport invoke -node * -type all -message MAINT=END_ command.

....