---
permalink: fas-70-90/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: fas70, fas90, replace the chassis 
summary: 'Avant de remplacer le châssis de votre système FAS70 ou FAS90, assurez-vous de répondre aux exigences nécessaires pour un remplacement réussi.  Cela inclut la vérification du bon fonctionnement de tous les autres composants du système, la vérification que vous disposez des informations d"identification d"administrateur local pour ONTAP, du châssis de remplacement approprié et des outils nécessaires.' 
---
= Exigences pour remplacer le châssis - FAS70 et FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le châssis de votre système FAS70 ou FAS90, assurez-vous de répondre aux exigences nécessaires pour un remplacement réussi.  Cela inclut la vérification du bon fonctionnement de tous les autres composants du système, la vérification que vous disposez des informations d'identification d'administrateur local pour ONTAP, du châssis de remplacement approprié et des outils nécessaires.

Le châssis est le châssis physique abritant tous les composants du système tels que les ventilateurs, l'unité contrôleur/CPU, la NVRAM12, le module de gestion du système, les cartes d'E/S et les modules d'obturation, ainsi que les blocs d'alimentation.

Passez en revue les exigences suivantes.

* Assurez-vous que tous les autres composants du système fonctionnent correctement ; si ce n'est pas le cas, contactez http://mysupport.netapp.com/["Support NetApp"^] pour obtenir de l'aide.
* Obtenez les informations d'identification de l'administrateur local pour ONTAP si vous ne les avez pas.
* Assurez-vous de disposer des outils et de l'équipement nécessaires pour le remplacement.
* Vous pouvez utiliser la procédure de remplacement du châssis avec toutes les versions de ONTAP prises en charge par votre système.
* La procédure de remplacement du châssis est écrite en supposant que vous déplacez le cadre, les ventilateurs, le module de contrôleur, la NVRAM12, le module de gestion du système, les cartes d'E/S et les modules d'obturation, ainsi que les blocs d'alimentation vers le nouveau châssis, et que le châssis de remplacement est un nouveau composant de NetApp.


.Et la suite ?
Après avoir examiné la configuration requise pour remplacer le châssis, vous devez link:chassis-replace-prepare.html["préparez le remplacement du châssis"].
