---
permalink: fas-70-90/fan-replace.html 
sidebar: sidebar 
keywords: fas70, fas90, replace a fan 
summary: Vous devez retirer le module de contrôleur du châssis lorsque vous remplacez un module de ventilation défectueux et le remplacer par un nouveau module de ventilation. 
---
= Remplacer un ventilateur - FAS70 et FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour remplacer un module de ventilation sans interrompre le service, vous devez effectuer une séquence spécifique de tâches.

.Étapes
. Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
. Retirez le cadre (si nécessaire) à deux mains, en saisissant les ouvertures de chaque côté du cadre, puis en le tirant vers vous jusqu'à ce que le cadre se dégage des goujons à rotule du châssis.
. Identifiez le module de ventilation que vous devez remplacer en vérifiant les messages d'erreur de la console et en regardant le voyant d'avertissement de chaque module de ventilation.
+
Face au module de contrôleur, les modules de ventilation sont numérotés de 1 à 5, de gauche à droite.

+

NOTE: Chaque ventilateur est doté d'une seule LED. Il est vert lorsque le ventilateur fonctionne correctement et orange lorsque ce n'est pas le cas.

. Appuyez sur le bouton noir du module de ventilation et tirez le module de ventilation hors du châssis, en vous assurant de le soutenir avec votre main libre.
+

IMPORTANT: Les modules de ventilation sont courts. Soutenez toujours la partie inférieure du module de ventilation avec votre main libre pour qu'il ne tombe pas brusquement du châssis et vous blesse.

+
image::../media/drw_a1k_fan_remove_replace_ieops-1376.svg[Remplacement du ventilateur]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Légende numéro 1, largeur = 30 px"]
 a| 
Bouton de déverrouillage noir

|===
. Mettez le module de ventilation de côté.
. Alignez les bords du module de ventilateur de remplacement avec l'ouverture du châssis, puis faites-le glisser dans le châssis jusqu'à ce qu'il s'enclenche.
+
Lorsqu'il est inséré dans un système sous tension, le voyant d'avertissement orange s'éteint une fois que le ventilateur est reconnu par ce système.

. Alignez le cadre avec les goujons à rotule, puis poussez doucement le cadre sur les goujons à rotule.
. Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièces et remplacements"^] page pour plus d'informations.

