---
permalink: fas-70-90/fas70-key-specifications.html 
sidebar: sidebar 
keywords: FAS70 specifications, FAS70 specs, FAS70 capacity, FAS70 memory, FAS70 I/O, FAS70 compliance 
summary: Spécifications clés du FAS70 
---
= Spécifications clés du FAS70
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour le système de stockage FAS70 dans une seule paire haute disponibilité.  Visitez NetApp Hardware Universe (HWU) pour obtenir les spécifications complètes de ce système de stockage.



== Aperçu des spécifications du FAS70

* Configuration de la plateforme : paire HA à double châssis FAS70
* Capacité brute maximale : 15 0000 Po
* Mémoire : 256.0000 Go
* Facteur de forme : châssis 2U avec 1 contrôleur HA
* Version ONTAP : ONTAP: 9.16.1P2
* Emplacements d'extension PCIe : 18
* Version minimale ONTAP : ONTAP 9.15.1 == Maximums de scale-out
* Type : NAS ; Paires HA : 12 ; Capacité brute : 180,0 Po / 159,9 PiB ; Mémoire maximale : 3 072 Go
* Type : SAN ; paires HA : 6 ; capacité brute : 90,0 Po / 79,9 PiB ; mémoire maximale : 1 536 Go
* Type : Paire HA ; Capacité brute : 15,0 Po / 13,3 PiB ; Mémoire maximale : 256,0000




== E/S



=== E/S embarquées

Aucune donnée d'E/S intégrée.



=== E/S totales

* Protocole : Ethernet 200 Gbps ; Ports : 20
* Protocole : Ethernet 100 Gbps ; Ports : 32
* Protocole : Ethernet 25 Gbit/s ; Ports : 48
* Protocole : Ethernet 10 Gbit/s ; Ports : 48
* Protocole : FC 64 Gbps ; Ports : 48
* Protocole : NVMe/FC 64 Gbit/s ; Ports : 48
* Ports : 0
* Protocole : SAS 12 Gbit/s ; Ports : 48




=== Ports de gestion

* Protocole : Ethernet 1 Gbps ; Ports : 2
* Protocole : RS-232 115 Kbps ; Ports : 4
* Protocole : USB 600 Mbps ; Ports : 2




== Prise en charge du réseau de stockage

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NVMe/FC
* NVMe/TCP
* S3
* S3 avec NAS
* PME 2.0
* PME 2.1
* SMB 2.x
* PME 3.0
* PME 3.1
* SMB 3.1.1 == Spécifications de l'environnement système
* Puissance typique : 2653 BTU/h
* Puissance dans le pire des cas : 3 050 BTU/h
* Poids : 59,5 lb 27,0 kg
* Hauteur : 2U
* Largeur : 19 pouces conforme à la norme IEC (17,7 pouces 44,9 cm)
* Profondeur : 30,0 po (35,2 po avec support de gestion des câbles)
* Température/altitude/humidité de fonctionnement : 10 °C à 35 °C (50 °F à 95 °F) à une altitude de 3 048 m (10 000 pi) ; humidité relative de 8 % à 80 %, sans condensation
* Température/humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu'à 12 192 m (40 000 pi) 10 % à 95 % d'humidité relative, sans condensation, dans l'emballage d'origine
* Bruit acoustique : Puissance acoustique déclarée (LwAd) : 8,5 Pression acoustique (LpAm) (positions d'observation) : 67,7 dB




== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




== Haute disponibilité

* Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP
* Contrôleurs redondants remplaçables à chaud
* Alimentations redondantes remplaçables à chaud
* Gestion SAS en bande via des connexions SAS pour les étagères externes

