---
sidebar: sidebar 
permalink: fas-70-90/install-requirements.html 
keywords: fas70, fas90, install, setup, cautions 
summary: 'Passez en revue l"équipement nécessaire et les précautions de levage pour votre plate-forme et vos étagères.' 
---
= Conditions requises pour l'installation - FAS70 et FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vérifiez l'équipement nécessaire et les précautions de levage pour votre système de stockage FAS70 ou FAS90 et vos tiroirs de stockage.



== Équipement nécessaire pour l'installation

Pour installer votre système de stockage, vous avez besoin de l'équipement et des outils suivants.

* Accès à un navigateur Web pour configurer votre système de stockage
* Sangle de décharge électrostatique (ESD)
* Lampe de poche
* Ordinateur portable ou console avec connexion USB/série
* Tournevis Phillips n°2




== Précautions de levage

Les systèmes de stockage et les tiroirs sont lourds. Faites preuve de prudence lorsque vous soulevez et déplacez ces éléments.



=== Poids du système de stockage

Prenez les précautions nécessaires lors du déplacement ou du levage de votre système de stockage.

Un système de stockage FAS70 ou FAS90 peut peser jusqu'à 28.5 kg (62.83 lbs). Pour soulever le système, faire appel à deux personnes ou à un relevage hydraulique.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[Icône d'avertissement de levage FAS70 et FAS90]



=== Poids de la tablette

Prenez les précautions nécessaires lorsque vous déplacez ou soulevez votre tablette.

Une étagère NS224 peut peser jusqu'à 30.29 kg (66.78 lb). Pour soulever la tablette, faites appel à deux personnes ou à un dispositif de levage hydraulique. Conservez tous les composants dans la tablette (à l'avant et à l'arrière) pour éviter de rééquilibrer le poids de la tablette.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 attention de levage]

Une étagère DS460C peut peser jusqu'à 181.1 kg (260.4 lb). Pour soulever l'étagère de stockage, il peut être nécessaire de compter jusqu'à cinq personnes ou un dispositif de levage hydraulique. Conservez tous les composants dans la tablette de stockage (avant et arrière) pour éviter de débalourer le poids de la tablette.

image::../media/drw_ds460c_weight_warning_ieops-1932.svg[Avertissement de levage DS460C]

.Informations associées
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informations de sécurité et avis réglementaires"^]


.Et la suite ?
Après avoir examiné la configuration matérielle requise, vous link:install-prepare.html["Préparez l'installation de votre système de stockage FAS70 ou FAS90"].
