---
permalink: asa900/controller_replace_overview.html 
sidebar: sidebar 
keywords: ASA A900 
summary: 'Vous devez passer en revue les conditions préalables à la procédure de remplacement et sélectionner la version appropriée de votre système d"exploitation ONTAP.' 
---
= Remplacer le module de contrôleur - ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour remplacer le module de contrôleur défaillant, vous devez arrêter le contrôleur défaillant, déplacer les composants internes vers le module de contrôleur de remplacement, installer le module de contrôleur de remplacement et redémarrer le contrôleur de remplacement.

.Avant de commencer
Vous devez passer en revue les conditions préalables à la procédure de remplacement et sélectionner la version appropriée de votre système d'exploitation ONTAP.

[NOTE]
====
NetApp recommande fortement d'activer la journalisation de la console sur les appareils que vous utilisez et de prendre les mesures suivantes lors de cette procédure :

* Laissez AutoSupport activé pendant votre maintenance. Cela permet au support NetApp de recevoir des informations de diagnostic en cas de problème.
* Activez la journalisation des sessions pour toutes les sessions CLI. Cela crée un enregistrement complet de toutes les commandes et des sorties système pendant l'opération de maintenance. Pour savoir comment activer la journalisation des sessions, consultez  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Comment configurer PuTTY pour une connectivité optimale aux systèmes ONTAP"^].


====
* Tous les tiroirs disques doivent fonctionner correctement.
* Si votre système dispose d'une licence V_StorageAttach, vous devez vous reporter aux étapes supplémentaires requises avant d'effectuer cette procédure.
* Si votre système se trouve dans une paire haute disponibilité, le contrôleur en bon état doit pouvoir reprendre le contrôleur en cours de remplacement (appelé « contrôleur défectueux »).
* Si votre système est dans une configuration MetroCluster, vous devez passer en revue la section https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Choix de la procédure de récupération correcte"] pour déterminer si vous devez utiliser cette procédure.
+
Si c'est cette procédure, notez que la procédure de remplacement du contrôleur d'un contrôleur dans une configuration MetroCluster à quatre ou huit nœuds est identique à celle d'une paire HA. Aucune étape spécifique à MetroCluster n'est requise, car la défaillance est limitée à une paire haute disponibilité et les commandes de basculement du stockage peuvent être utilisées pour assurer une continuité de l'activité pendant le remplacement.

* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.
* Vous devez remplacer un module de contrôleur par un module de contrôleur du même type de modèle. Vous ne pouvez pas mettre à niveau votre système en remplaçant simplement le module de contrôleur.
* Vous ne pouvez pas modifier de disques ou de tiroirs disques dans le cadre de cette procédure.
* Au cours de cette procédure, le périphérique de démarrage est déplacé du contrôleur défaillant vers le contrôleur de remplacement de sorte que le contrôleur de remplacement démarre dans la même version de ONTAP que l'ancien module de contrôleur.
* Il est important d'appliquer les commandes au cours des étapes suivantes sur les systèmes appropriés :
+
** Le contrôleur défectueux est le contrôleur en cours de remplacement.
** Le remplacement du contrôleur est le nouveau contrôleur qui remplace le contrôleur défaillant.
** Le contrôleur sain est le contrôleur survivant.



