---
permalink: asa900/overview.html 
sidebar: sidebar 
keywords: ASA A900 specifications, ASA A900 specs, NetApp ASA A900, ASA A900 hardware 
summary: Spécifications clés du système de stockage ASA A900 
---
= Spécifications clés de ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour l' ASA A900.  Visite https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) pour une liste complète des spécifications ASA A900 .  Cette page reflète une seule paire à haute disponibilité.



=== Spécifications clés de ASA A900

Configuration de la plateforme : paire HA à châssis unique ASA A900

Capacité brute maximale : 14,6880 Po

Mémoire : 2048.0000 Go

Facteur de forme : châssis 8U avec 2 contrôleurs HA

Version ONTAP : b_startONTAP : 9.16.1P2b_end

Emplacements d'extension PCIe : 20

Version minimale ONTAP : ONTAP 9.13.1



=== Maximums de mise à l'échelle

|===


| Type | Paires HA | Capacité brute | Mémoire maximale 


| NAS |  |  |  


| SAN | 6 | 88,1 Po / 78,3 PiB | 12288 Go 


| Paire haute disponibilité |  | 14,7 Po / 13,0 PiB | 2048,0000 
|===


=== IO



==== E/S embarquées

Aucune donnée IO embarquée.



==== E/S totales

|===


| Protocole | Ports 


| Ethernet 100 Gbit/s | 32 


| Ethernet 25 Gbit/s | 64 


| Ethernet 10 Gbit/s | 64 


| FC 32 Gbit/s | 64 


| NVMe/FC 32 Gbit/s | 64 


|  | 0 


| SAS 12 Gbit/s | 64 
|===


==== Ports de gestion

|===


| Protocole | Ports 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 6 


| USB 12 Mbps | 2 
|===


=== Réseau de stockage pris en charge

FC ; iSCSI ; NVMe/FC ; NVMe/TCP ;



=== Spécifications de l'environnement système

* Puissance typique : 8004 BTU/h
* Consommation d'énergie dans le pire des cas : 9 937 BTU/h
* Poids : 220,5 lb/100,0 kg
* Hauteur : 8U
* Largeur : 19" conforme à la norme IEC (17,7" 45,0 cm)
* Profondeur : 28,8 po (36,8 po avec support de gestion des câbles)
* Température/altitude/humidité de fonctionnement : 10 °C à 35 °C (50 °F à 95 °F) à une altitude de 3 048 m (10 000 pi) ; 8 % à 80 % (humidité relative, sans condensation)
* Température/humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu'à 12 192 m (40 000 pi)<br/>10 % à 95 % d'humidité relative, sans condensation, dans l'emballage d'origine
* Bruit acoustique : Puissance acoustique déclarée (LwAd) : 7,4 ; br/Pression acoustique (LpAm) (positions d'observation) : 65,0 dB




=== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




=== Haute disponibilité

Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP ; contrôleurs redondants remplaçables à chaud ; alimentations redondantes remplaçables à chaud ; gestion SAS en bande via des connexions SAS ; [//] 2025-10-15 ontap-systems-internal/issues/1357
