---
permalink: a150/overview.html 
sidebar: sidebar 
keywords: AFF A150 specifications, AFF A150 specs, NetApp AFF A150, AFF A150 hardware 
summary: Spécifications clés du système de stockage AFF A150 
---
= Spécifications clés de AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour l' AFF A150.  Visite https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) pour une liste complète des spécifications AFF A150 .  Cette page reflète une seule paire à haute disponibilité.



=== Spécifications clés de AFF A150

Configuration de la plateforme : AFF A150 UTA2, châssis simple, paire HA

Capacité brute maximale : 0,5472 Po

Mémoire : 64.0000 Go

Facteur de forme : châssis 2U avec 2 contrôleurs HA et 24 emplacements pour disques

Version ONTAP : b_startONTAP : 9.16.1P2b_end

Emplacements d'extension PCIe :

Version minimale ONTAP : ONTAP 9.10.1P12



=== Maximums de mise à l'échelle

|===


| Type | Paires HA | Capacité brute | Mémoire maximale 


| NAS | 12 | 6,6 Po / 5,8 PiB | 768 Go 


| SAN | 6 | 3,3 Po / 2,9 PiB | 384 Go 


| Paire haute disponibilité |  | 0,5 Po / 0,5 PiB | 64,0000 
|===


=== IO



==== E/S embarquées

|===


| Protocole | Ports 


| Ethernet 10 Gbit/s | 12 


| FC 16 Gbit/s | 8 


| SAS 12 Gbit/s | 4 
|===


==== E/S totales

|===


| Protocole | Ports 


| Ethernet 10 Gbit/s | 12 


| FC 16 Gbit/s | 8 


| SAS 12 Gbit/s | 4 
|===


==== Ports de gestion

|===


| Protocole | Ports 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 2 
|===


=== Réseau de stockage pris en charge

CIFS; FC; FCoE; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/TCP; S3; S3 avec NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Spécifications de l'environnement système

* Puissance typique : 1209 BTU/h
* Consommation d'énergie dans le pire des cas : 1 676 BTU/h
* Poids : 60,8 lb<br/>27,6 kg
* Hauteur : 2U
* Largeur : 19 pouces conforme à la norme IEC (17,6 pouces 44,7 cm)
* Profondeur : 19,0 po (24,1 po avec support de gestion des câbles)
* Température/altitude/humidité de fonctionnement : 5 °C à 45 °C (41 °F à 113 °F) à une altitude de 3 048 m (10 000 pi) ; 8 % à 90 % d’humidité relative, sans condensation
* Température/humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu'à 12 192 m (40 000 pi)<br/>10 % à 95 % d'humidité relative, sans condensation, dans l'emballage d'origine
* Bruit acoustique : Puissance acoustique déclarée (LwAd) : 6,9 ;<br/>Pression acoustique (LpAm) (positions d'observation) : 51,0 dB




=== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




=== Haute disponibilité

Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP ; Contrôleurs redondants remplaçables à chaud ; Alimentations redondantes remplaçables à chaud ; Gestion SAS en bande via des connexions SAS ;
