---
permalink: a150/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: 'Vous devez vérifier l"état haute disponibilité du châssis et exécuter des diagnostics au niveau du système, des agrégats de recul et renvoyer la pièce défectueuse à NetApp, comme décrit dans les instructions RMA livrées avec le kit.' 
---
= Restaurez et vérifiez la configuration - AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez vérifier l'état haute disponibilité du châssis et exécuter des diagnostics au niveau du système, des agrégats de recul et renvoyer la pièce défectueuse à NetApp, comme décrit dans les instructions RMA livrées avec le kit.



== Étape 1 : vérifier et définir l'état de haute disponibilité du châssis

Vous devez vérifier l'état HA du châssis et, le cas échéant, mettre à jour l'état pour qu'il corresponde à la configuration de votre système.

. En mode Maintenance, depuis l'un ou l'autre module de contrôleur, afficher l'état HA du module de contrôleur local et du châssis : `ha-config show`
+
L'état de la HA doit être le même pour tous les composants.

. Si l'état du système affiché pour le châssis ne correspond pas à la configuration de votre système :
+
.. Définissez l'état haute disponibilité du châssis : `ha-config modify chassis _HA-state_`
+
La valeur de HA-State peut être l'une des suivantes :

+
*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mccip`
*** `non-ha`


.. Vérifiez que le paramètre a changé : `ha-config show`


. Si vous ne l'avez pas déjà fait, recâble le reste de votre système.
. L'étape suivante dépend de la configuration de votre système.
+
[cols="1,2"]
|===
| Si votre système est en... | Alors... 


 a| 
Une configuration autonome
 a| 
.. Quitter le mode Maintenance : `halt`
.. Accédez à link:chassis_replace.html["« Fin du processus de remplacement"].




 a| 
Une paire haute disponibilité avec un second module de contrôleur
 a| 
Quitter le mode Maintenance : `halt` L'invite DU CHARGEUR s'affiche.

|===




== Étape 2 : exécutez les diagnostics au niveau du système

Après avoir installé un nouveau châssis, exécutez les diagnostics d'interconnexion.

Votre système doit être à l'invite DU CHARGEUR pour démarrer System Level Diagnostics.

Toutes les commandes des procédures de diagnostic sont émises par le contrôleur où le composant est remplacé.

. Si le contrôleur à réparer n'est pas à l'invite DU CHARGEUR, effectuez la procédure suivante :
+
.. Sélectionnez l'option mode Maintenance dans le menu affiché.
.. Une fois le contrôleur démarré en mode maintenance, arrêtez le contrôleur : `halt`
+
Une fois que vous avez terminé d'exécuter la commande, vous devez attendre que le système s'arrête à l'invite DU CHARGEUR.

+

NOTE: Au cours du processus de démarrage, vous pouvez répondre en toute sécurité `y` pour demander :



. Répétez l'étape précédente sur le second contrôleur si vous êtes dans une configuration haute disponibilité.
+

NOTE: Les deux contrôleurs doivent être en mode maintenance pour exécuter le test d'interconnexion.

. À l'invite DU CHARGEUR, accédez aux pilotes spéciaux spécialement conçus pour les diagnostics au niveau du système afin de fonctionner correctement : `boot_diags`
+
Au cours du processus de démarrage, vous pouvez répondre en toute sécurité `y` Aux invites jusqu'à ce que l'invite du mode Maintenance (*>) s'affiche.

. Activez les tests de diagnostic d'interconnexion à partir de l'invite du mode maintenance : `sldiag device modify -dev interconnect -sel enable`
+
Les tests d'interconnexion sont désactivés par défaut et doivent être activés séparément.

. Exécutez le test de diagnostic d'interconnexion à partir de l'invite du mode maintenance : `sldiag device run -dev interconnect`
+
Vous ne devez exécuter le test d'interconnexion qu'à partir d'un seul contrôleur.

. Vérifiez qu'aucun problème matériel ne provient du remplacement du châssis : `sldiag device status -dev interconnect -long -state failed`
+
Les diagnostics au niveau du système vous renvoie à l'invite s'il n'y a pas d'échec de test ou répertorie l'état complet des échecs résultant du test du composant.

. Procéder selon le résultat de l'étape précédente.
+
[cols="1,2"]
|===
| Si les tests de diagnostic au niveau du système... | Alors... 


 a| 
Ont été achevés sans défaillance
 a| 
.. Effacez les journaux d'état : `sldiag device clearstatus`
.. Vérifiez que le journal a été effacé : `sldiag device status`
+
La réponse par défaut suivante est affichée :

+
[listing]
----
SLDIAG: No log messages are present.
----
.. Quitter le mode maintenance sur les deux contrôleurs : `halt`
+
Le système affiche l'invite DU CHARGEUR.

+

NOTE: Vous devez quitter le mode de maintenance sur les deux contrôleurs avant de poursuivre l'opération.

.. Entrez la commande suivante sur les deux contrôleurs à l'invite DU CHARGEUR : `bye`
.. Faire revenir le contrôleur en mode de fonctionnement normal :


|===
+
[cols="1,2"]
|===
| Si votre système exécute ONTAP... | Alors... 


 a| 
Avec deux nœuds dans le cluster
 a| 
Exécutez les commandes suivantes : `node::> cluster ha modify -configured true``node::> storage failover modify -node node0 -enabled true`



 a| 
Avec plus de deux nœuds dans le cluster
 a| 
Exécutez cette commande :``node::> storage failover modify -node node0 -enabled true``



 a| 
Dans une configuration MetroCluster à deux nœuds
 a| 
Passez à l'étape suivante. La procédure de rétablissement MetroCluster est effectuée lors de la prochaine tâche du processus de remplacement.



 a| 
Dans une configuration autonome
 a| 
Vous n'avez pas d'autres étapes dans cette tâche particulière.

Vous avez terminé les diagnostics au niveau du système.



 a| 
A entraîné des échecs de test
 a| 
Déterminer la cause du problème.

.. Quitter le mode Maintenance : `halt`
.. Procéder à un arrêt correct, puis débrancher les alimentations.
.. Vérifier que vous avez bien remarqué tous les facteurs à prendre en compte pour l'exécution des diagnostics au niveau du système, que les câbles sont correctement connectés et que les composants matériels sont correctement installés dans le système de stockage.
.. Rebranchez les blocs d'alimentation, puis mettez le système de stockage sous tension.
.. Exécutez à nouveau le test de diagnostic au niveau du système.


|===




== Étape 3 : retournez les agrégats via une configuration MetroCluster à deux nœuds

Après avoir terminé le remplacement des unités remplaçables sur site dans une configuration MetroCluster à deux nœuds, vous pouvez exécuter l'opération de rétablissement MetroCluster. Cette configuration renvoie la configuration à son état de fonctionnement normal, avec les SVM (Storage Virtual machines) source et sur le site précédemment douteux actifs et peuvent accéder aux données des pools de disques locaux.

Cette tâche s'applique uniquement aux configurations MetroCluster à deux nœuds.

.Étapes
. Vérifiez que tous les nœuds sont dans le `enabled` état : `metrocluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. Vérifier que la resynchronisation est terminée sur tous les SVM : `metrocluster vserver show`
. Vérifier que toutes les migrations LIF automatiques effectuées par les opérations de correction ont été effectuées correctement : `metrocluster check lif show`
. Effectuez le rétablissement en utilisant le `metrocluster switchback` utilisez une commande à partir d'un nœud du cluster survivant.
. Vérifiez que l'opération de rétablissement est terminée : `metrocluster show`
+
L'opération de rétablissement s'exécute toujours lorsqu'un cluster est dans `waiting-for-switchback` état :

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
Le rétablissement est terminé une fois les clusters dans `normal` état :

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
Si un rétablissement prend beaucoup de temps, vous pouvez vérifier l'état des lignes de base en cours en utilisant le `metrocluster config-replication resync-status show` commande.

. Rétablir toutes les configurations SnapMirror ou SnapVault.




== Étape 4 : renvoyer la pièce défaillante à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièce et amp ; remplacements"] pour plus d'informations.
