---
permalink: a150/install-videos.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, aff a220, video, rack, cable, system, manager, guided, setup, configuration 
summary: 'Deux vidéos sont disponibles. L"une montre comment installer et connecter le système, l"autre montrant un exemple d"utilisation de la configuration assistée par System Manager pour effectuer la configuration initiale du système.' 
---
= Vidéos - AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Deux vidéos sont disponibles : l'une montrant comment installer et connecter le système, l'autre montrant un exemple d'utilisation de la configuration assistée par System Manager pour effectuer la configuration initiale du système.

Si vous disposez d'une configuration MetroCluster, utilisez le contenu d'installation de MetroCluster.

https://["Documentation MetroCluster"^]



== Vidéo l'une des deux : installation du matériel et câblage

La vidéo suivante montre comment installer et raccorder votre nouveau système.

.Animation - installation et configuration d'un AFF A150
video::561d941a-f387-4eb9-a10a-afb30029eb36[panopto]


== Vidéo deux sur deux : configuration logicielle de bout en bout

La vidéo suivante présente une configuration logicielle de bout en bout pour les systèmes exécutant ONTAP 9.2 et versions ultérieures.

video::WAE0afWhj1c?[youtube]