---
permalink: a150/install-setup.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, install, setup, initial configuration 
summary: Installez et configurez votre système. 
---
= Commencez ici : choisissez votre installation et configuration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour la plupart des configurations, vous avez le choix entre différents formats de contenu.

* link:../a150/install-quick-guide.html["Pas de temps"]
+
Un PDF imprimable contenant des instructions détaillées avec des liens en direct vers du contenu supplémentaire.

* link:../a150/install-videos.html["Étapes vidéo"]
+
Instructions étape par étape de la vidéo.

* link:../a150/install-detailed-guide.html["Étapes détaillées"]
+
Instructions en ligne détaillées avec liens en direct vers du contenu supplémentaire.



Si votre système est dans une configuration MetroCluster IP, reportez-vous à la section https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Installez la configuration IP de MetroCluster"] instructions.

*Avertissement :* si votre système est installé avec ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 ou ONTAP 9.15.1 - 9.15.1P2 et que votre système contient au moins 10 lecteurs SSD internes, vous devez prendre des mesures supplémentaires pour préparer le système à l'installation. Voir problème  https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173["ONTAP-285173 - ADP ne laisse pas de partition racine de rechange sur un AFF A150 avec 10 disques internes ou plus"^].
