---
permalink: asa-c400/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: asa-c400, replace the boot media 
summary: 'Avant de remplacer le support de démarrage de votre système ASA C400, assurez-vous de respecter les conditions requises pour un remplacement réussi. Il est notamment important de disposer d"une clé USB avec la capacité de stockage appropriée et de vérifier que vous disposez du périphérique de démarrage de remplacement approprié.' 
---
= Conditions requises pour la récupération manuelle du support de démarrage - ASA C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système ASA C400, assurez-vous de respecter les conditions requises pour un remplacement réussi. Il est notamment important de disposer d'une clé USB avec la capacité de stockage appropriée et de vérifier que vous disposez du périphérique de démarrage de remplacement approprié.

Si votre système de stockage exécute ONTAP 9.17.1 ou une version ultérieure, utilisez lelink:bootmedia-replace-workflow-bmr.html["procédure de récupération de démarrage automatisée"] .  Si votre système exécute une version antérieure d’ ONTAP, vous devez utiliser le processus de récupération de démarrage manuel.

.Et la suite ?
Après avoir examiné la configuration requise pour remplacer le support de démarrage, vous devez link:bootmedia-encryption-preshutdown-checks.html["vérifiez la prise en charge et l'état de la clé de cryptage sur le support de démarrage"].
