---
permalink: asa-r2-70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, replace the boot media 
summary: Avant de remplacer le support de démarrage de votre système ASA A70 ou A90, assurez-vous de répondre aux exigences requises pour un remplacement réussi. 
---
= Nécessité de remplacer le support de démarrage - ASA A70 et ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système ASA A70 ou ASA A90, assurez-vous de répondre aux exigences requises pour un remplacement réussi. Cela inclut la vérification que vous disposez du support de démarrage de remplacement approprié, la vérification qu'aucun port de cluster n'est défectueux sur le contrôleur et la détermination de l'activation du gestionnaire de clés intégré (OKM) ou du gestionnaire de clés externe (EKM).

Passez en revue les exigences suivantes.

* Vous devez remplacer le support de démarrage défectueux par un support de démarrage de remplacement que vous avez reçu de NetApp.
* Il ne doit y avoir aucun port de cluster défectueux sur le contrôleur défectueux.
* Pour OKM, vous avez besoin du contenu du fichier de phrase de passe OKM.
* Pour EKM, vous avez besoin de copies des fichiers suivants à partir du nœud partenaire :
+
** fichier /cfcard/kmip/servers.cfg.
** fichier /cfcard/kmip/certs/client.crt.
** fichier /cfcard/kmip/certs/client.key.
** Fichier /cfcard/kmip/certs/CA.pem.




.Et la suite
Après avoir examiné la configuration requise pour le support de démarrage, vous link:bootmedia-shutdown-bmr.html["arrêter le contrôleur"].
