---
permalink: asa-r2-70-90/bootmedia-overview-bmr.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, overview, the boot media 
summary: Découvrez la méthode automatisée de remplacement du support de démarrage. 
---
= Présentation de la récupération du support de démarrage - ASA A70 et ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La restauration du support de démarrage utilise l'image de démarrage du nœud partenaire et exécute automatiquement l'option de menu de démarrage appropriée pour installer l'image de démarrage sur le support de démarrage de remplacement.

Lorsque des messages d'erreur de démarrage similaires à ceux illustrés ci-dessous s'affichent, vous devez remplacer le support de démarrage et restaurer l'image ONTAP à partir du nœud partenaire.

....
Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014

Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat)
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat)

Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....