---
permalink: asa-r2-70-90/bootmedia-overview.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, overview, the boot media 
summary: Découvrez la méthode automatisée et la méthode manuelle de remplacement du support de démarrage. 
---
= Présentation du remplacement du support de démarrage - ASA A70 et ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez remplacer manuellement un support d'amorçage défaillant en utilisant le module USB pour l'image d'amorçage ou en utilisant l'option de récupération automatique du support d'amorçage (BMR).

* link:bootmedia-replace-requirements-bmr.html["Restauration automatisée des supports de démarrage"]
+
La restauration automatique du support de démarrage utilise l'image de démarrage du nœud partné et exécute automatiquement l'option de menu de démarrage appropriée pour installer l'image de démarrage sur le support de démarrage de remplacement.

* link:bootmedia-replace-requirements.html["Remplacement manuel du support de démarrage"]
+
Le remplacement manuel des supports de démarrage utilise la méthode traditionnelle de téléchargement de l'image ONTAP à partir du site de support NetApp, de transfert de l'image vers un lecteur USB, de téléchargement vers le support de démarrage cible de remplacement et de navigation manuelle dans les options du menu de démarrage pour installer l'image ONTAP sur le support de démarrage de remplacement.


