---
permalink: asa-r2-70-90/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Pour restaurer votre système à son fonctionnement complet, vous devez vérifier les LIF, vérifier l"état du cluster et renvoyer la pièce défaillante à NetApp. Contactez le support technique au https://mysupport.netapp.com/site/global/dashboard["Support NetApp"], 888-463-8277 (Amérique du Nord), 00-800-44-638277 (Europe) ou au +800-800-80-800 (Asie/Pacifique) si vous avez besoin du numéro RMA ou d"une aide supplémentaire pour la procédure de remplacement.' 
---
= Remplacement complet du contrôleur - ASA A70 et ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour terminer le remplacement du contrôleur de votre système ASA A70 ou ASA A90, restaurez d'abord la configuration du chiffrement du stockage NetApp (si nécessaire). Ensuite, vérifiez que les interfaces logiques (LIF) signalent leurs ports de repos et effectuez une vérification de l'état du cluster. Enfin, retournez la pièce défectueuse à NetApp.



== Étape 1 : vérifier la LIF et la santé du cluster

Avant de renvoyer le nœud de remplacement à la maintenance, vérifiez que les interfaces logiques se trouvent sur leurs ports home, vérifiez l'état du cluster et réinitialisez le rétablissement automatique.

.Étapes
. Vérifiez que les interfaces logiques sont bien placées sur leur serveur domestique et leurs ports : `network interface show -is-home false`
+
Si des interfaces logiques sont répertoriées sous la forme false, restaurez-les sur leurs ports home : `network interface revert -vserver * -lif *`

. Vérifiez l'état de santé de votre cluster. Consultez https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Procédure de vérification de l'état du cluster à l'aide d'un script dans ONTAP"^] l'article de la base de connaissances pour plus d'informations.
. Si le retour automatique a été désactivé, réactivez-le : `storage failover modify -node local -auto-giveback true`




== Étape 2 : renvoyer la pièce défectueuse à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièces et remplacements"] page pour plus d'informations.
