---
permalink: asa-r2-70-90/io-module-overview.html 
sidebar: sidebar 
keywords: ASA A90,  ASA A70, replace io module 
summary: 'Les systèmes ASA A70 et ASA A90 permettent d"étendre ou de remplacer des modules d"E/S de manière flexible afin d"améliorer la connectivité et les performances du réseau. L"ajout ou le remplacement d"un module d"E/S est essentiel lors de la mise à niveau des capacités réseau ou de l"adressage d"un module défaillant.' 
---
= Présentation de l'ajout et du remplacement du module d'E/S - ASA A70 et ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes ASA A70 et ASA A90 permettent d'étendre ou de remplacer des modules d'E/S de manière flexible afin d'améliorer la connectivité et les performances du réseau. L'ajout ou le remplacement d'un module d'E/S est essentiel lors de la mise à niveau des capacités réseau ou de l'adressage d'un module défaillant.

Vous pouvez remplacer un module d'E/S défaillant de votre système de stockage ASA A70 ou ASA A90 par un module d'E/S du même type ou par un autre type de module d'E/S. Vous pouvez également ajouter un module d'E/S dans un système doté de logements vides.

* link:io-module-add.html["Ajoutez un module d'E/S."]
+
L'ajout de modules supplémentaires peut améliorer la redondance, ce qui permet de garantir que le système reste opérationnel même en cas de défaillance d'un module.

* link:io-module-replace.html["Remplacez un module d'E/S."]
+
Le remplacement d'un module d'E/S défaillant permet de restaurer l'état de fonctionnement optimal du système.



.Numérotation des connecteurs d'E/S.
Les connecteurs d'E/S des contrôleurs ASA A70 et ASA A90 sont numérotés de 1 à 11, comme illustré ci-dessous.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numérotation des emplacements sur les contrôleurs ASA A70 et AFF A90]
