---
permalink: c800/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff c800, verify and set HA state, complete the replacement process 
summary: 'Vous devez vérifier l"état HA du châssis et renvoyer la pièce défectueuse à NetApp, comme indiqué dans les instructions RMA fournies avec le kit.' 
---
= Terminez le processus de restauration et de remplacement - AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Redémarrez les contrôleurs, vérifiez l'état du système et renvoyez la pièce défectueuse à NetApp pour terminer la dernière étape de la procédure de remplacement du châssis AFF C800 .



== Étape 1 : vérifier et définir l'état de haute disponibilité du châssis

.Étapes
. En mode Maintenance, depuis l'un ou l'autre module de contrôleur, afficher l'état HA du module de contrôleur local et du châssis : `ha-config show`
+
L'état de la HA doit être le même pour tous les composants.

. Si l'état du système affiché pour le châssis ne correspond pas à la configuration de votre système :
+
.. Définissez l'état haute disponibilité du châssis : `ha-config modify chassis _HA-state_`
+
La valeur de HA-State peut être l'une des suivantes :

+
*** `ha`
*** `mcc`
*** `mccip`
*** `non-ha`


.. Vérifiez que le paramètre a changé : `ha-config show`


. Si vous ne l'avez pas déjà fait, recâble le reste de votre système.
. Réinstallez le cadre à l'avant du système.




== Étape 2 : vérifiez l'état du système de stockage

Une fois la restitution du contrôleur terminée, vérifiez l'état du système à l'aide de https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] .  Corrigez tout problème constaté.



== Étape 3 : renvoyer la pièce défaillante à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièces et remplacements"] page pour plus d'informations.
