---
permalink: c800/overview.html 
sidebar: sidebar 
keywords: AFF C800 specifications, AFF C800 specs, NetApp AFF C800, AFF C800 hardware 
summary: Spécifications clés du système de stockage AFF C800 
---
= Spécifications clés de AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour l' AFF C800.  Visite https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) pour une liste complète des spécifications AFF C800 .  Cette page reflète une seule paire à haute disponibilité.



=== Spécifications clés de AFF C800

Configuration de la plateforme : paire de châssis simple HA AFF C800

Capacité brute maximale : 7,3680 Po

Mémoire : 1280.0000 Go

Facteur de forme : châssis 4U avec 2 contrôleurs HA et 48 emplacements pour disques

Version ONTAP : b_startONTAP : 9.16.1P2b_end

Emplacements d'extension PCIe : 10

Version minimale ONTAP : ONTAP 9.10.1P15



=== Maximums de mise à l'échelle

|===


| Type | Paires HA | Capacité brute | Mémoire maximale 


| NAS | 12 | 88,4 Po / 78,5 PiB | 15360 Go 


| SAN | 6 | 44,2 Po / 39,3 PiB | 7680 Go 


| Paire haute disponibilité |  | 7,4 Po / 6,5 PiB | 1280,0000 
|===


=== IO



==== E/S embarquées

|===


| Protocole | Ports 


| Ethernet 100 Gbit/s | 4 
|===


==== E/S totales

|===


| Protocole | Ports 


| Ethernet 100 Gbit/s | 20 


| Ethernet 25 Gbit/s | 16 


| Ethernet 10 Gbit/s | 32 


| FC 32 Gbit/s | 32 


| NVMe/FC 32 Gbit/s | 32 


|  | 0 


|  | 0 
|===


==== Ports de gestion

|===


| Protocole | Ports 


| Ethernet 1 Gbit/s | 4 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== Réseau de stockage pris en charge

CIFS ; FC ; iSCSI ; NFS v3 ; NFS v4.0 ; NFS v4.1 ; NFS v4.2 ; NFSv3/RDMA ; NFSv4/RDMA ; NVMe/FC ; NVMe/TCP ; S3 ; S3 avec NAS ; SMB 2.0 ; SMB 2.1 ; SMB 2.x ; SMB 3.0 ; SMB 3.1 ; SMB 3.1.1 ;



=== Spécifications de l'environnement système

* Puissance typique : 6626 BTU/h
* Consommation d'énergie dans le pire des cas : 8 417 BTU/h
* Poids : 132,5 lb/60,1 kg
* Hauteur : 4U
* Largeur : 19 pouces conforme à la norme IEC (17,6 pouces 44,7 cm)
* Profondeur : 34,5 po (36,6 po avec support de gestion des câbles)
* Température/altitude/humidité de fonctionnement : 5 °C à 40 °C (41 °F à 104 °F) à une altitude de 3 048 m (10 000 pi) ; 8 % à 90 % (humidité relative, sans condensation)
* Température/humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu'à 12 192 m (40 000 pi)<br/>10 % à 95 % d'humidité relative, sans condensation, dans l'emballage d'origine
* Bruit acoustique : Puissance acoustique déclarée (LwAd) : 8,0 ; br/Pression acoustique (LpAm) (positions d'observation) : 62,8 dB




=== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




=== Haute disponibilité

Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP ; Contrôleurs redondants remplaçables à chaud ; Alimentations redondantes remplaçables à chaud ;

 [//] 2025-10-15 ontap-systems-internal/issues/1357