---
permalink: fas9000/bootmedia-recovery-image-boot-options.html 
sidebar: sidebar 
keywords: aff a700, fas9000, boot, recovery, image, two, node, metrocluster, configuration 
summary: 'La procédure de démarrage du nœud douteux à partir de l"image de récupération dépend de si le système se trouve dans une configuration MetroCluster à deux nœuds.' 
---
= Démarrez l'image de restauration - FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La procédure de démarrage du nœud douteux à partir de l'image de récupération dépend de si le système se trouve dans une configuration MetroCluster à deux nœuds.



== Option 1 : démarrez l'image de récupération dans la plupart des systèmes

Vous devez démarrer l'image ONTAP à partir du lecteur USB, restaurer le système de fichiers et vérifier les variables environnementales.

Cette procédure s'applique aux systèmes qui ne se trouvent pas dans une configuration MetroCluster à deux nœuds.

.Étapes
. À partir de l'invite DU CHARGEUR, démarrez l'image de récupération à partir du lecteur flash USB : `boot_recovery`
+
L'image est téléchargée à partir de la clé USB.

. Lorsque vous y êtes invité, entrez le nom de l'image ou acceptez l'image par défaut affichée entre crochets sur votre écran.
. Restaurez le `var` système de fichiers :
+
[cols="1,2"]
|===
| Si votre système dispose de... | Alors... 


 a| 
Une connexion réseau
 a| 
.. Appuyez sur `y` lorsque vous êtes invité à restaurer la configuration de sauvegarde.
.. Définissez le nœud sain sur le niveau de privilège avancé : `set -privilege advanced`
.. Exécutez la commande restore backup : `system node restore-backup -node local -target-address _impaired_node_IP_address_`
.. Renvoyer le nœud au niveau admin : `set -privilege admin`
.. Appuyez sur `y` lorsque vous êtes invité à utiliser la configuration restaurée.
.. Appuyez sur `y` lorsque vous êtes invité à redémarrer le nœud.




 a| 
Aucune connexion réseau
 a| 
.. Appuyez sur `n` lorsque vous êtes invité à restaurer la configuration de sauvegarde.
.. Redémarrez le système à l'invite du système.
.. Sélectionnez l'option *mettre à jour Flash dans Backup config* (Sync flash) dans le menu affiché.
+
Si vous êtes invité à poursuivre la mise à jour, appuyez sur `y`.





 a| 
Aucune connexion réseau et se trouve dans une configuration IP de MetroCluster
 a| 
.. Appuyez sur `n` lorsque vous êtes invité à restaurer la configuration de sauvegarde.
.. Redémarrez le système à l'invite du système.
.. Attendez que les connexions de stockage iSCSI se connectent.
+
Vous pouvez continuer après avoir afficher les messages suivants :

+
[listing]
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
.. Sélectionnez l'option *mettre à jour Flash dans Backup config* (Sync flash) dans le menu affiché.
+
Si vous êtes invité à poursuivre la mise à jour, appuyez sur `y`.



|===
. Assurez-vous que les variables environnementales sont définies comme prévu :
+
.. Prenez le nœud vers l'invite DU CHARGEUR.
.. Vérifiez les paramètres de la variable d'environnement à l'aide de l' `printenv` commande.
.. Si une variable d'environnement n'est pas définie comme prévu, modifiez-la avec le `setenv __environment-variable-name__ __changed-value__` commande.
.. Enregistrez vos modifications à l'aide du `savenv` commande.


. Le suivant dépend de la configuration de votre système :
+
** Si keymanager, NSE ou NVE intégré est configuré sur votre système, rendez-vous sur xref:bootmedia-encryption-restore.adoc[OKM, NSE et NVE si besoin]
** Si keymanager, NSE ou NVE intégré ne sont pas configurés sur votre système, effectuez les étapes de cette section.


. Dans l'invite DU CHARGEUR, entrez le `boot_ontap` commande.
+
[cols="1,2"]
|===
| *Si vous voyez... | Puis...* 


 a| 
Invite de connexion
 a| 
Passer à l'étape suivante.



 a| 
Attente du retour...
 a| 
.. Connectez-vous au nœud partenaire.
.. Vérifiez que le nœud cible est prêt pour un rétablissement à l'aide du `storage failover show` commande.


|===
. Connectez le câble de la console au nœud partenaire.
. Renvoyer le nœud à l'aide du `storage failover giveback -fromnode local` commande.
. À l'invite du cluster, vérifiez les interfaces logiques avec le `net int -is-home false` commande.
+
Si l'une des interfaces est indiquée comme « FALSE », restaurez ces interfaces à son port d'origine à l'aide de l' `net int revert` commande.

. Déplacez le câble de la console vers le nœud réparé et exécutez la `version -v` Commande pour vérifier les versions de ONTAP.
. Restaurez le retour automatique si vous le désactivez à l'aide de `storage failover modify -node local -auto-giveback true` commande.




== Option 2 : démarrez l'image de restauration dans une configuration MetroCluster à deux nœuds

Vous devez démarrer l'image ONTAP à partir du lecteur USB et vérifier les variables environnementales.

Cette procédure s'applique aux systèmes dotés d'une configuration MetroCluster à deux nœuds.

.Étapes
. À partir de l'invite DU CHARGEUR, démarrez l'image de récupération à partir du lecteur flash USB : `boot_recovery`
+
L'image est téléchargée à partir de la clé USB.

. Lorsque vous y êtes invité, entrez le nom de l'image ou acceptez l'image par défaut affichée entre crochets sur votre écran.
. Une fois l'image installée, démarrez le processus de restauration :
+
.. Appuyez sur `n` lorsque vous êtes invité à restaurer la configuration de sauvegarde.
.. Appuyez sur `y` lorsque vous êtes invité à redémarrer le système pour commencer à utiliser le nouveau logiciel installé.
+
Vous devez être prêt à interrompre le processus d'amorçage lorsque vous y êtes invité.



. Lorsque le système démarre, appuyez sur `Ctrl-C` après que vous ayez vu le `Press Ctrl-C for Boot Menu` Message. Et lorsque le menu de démarrage est affiché, sélectionnez l'option 6.
. Vérifiez que les variables d'environnement sont définies comme prévu.
+
.. Prenez le nœud vers l'invite DU CHARGEUR.
.. Vérifiez les paramètres de la variable d'environnement à l'aide de l' `printenv` commande.
.. Si une variable d'environnement n'est pas définie comme prévu, modifiez-la avec le `setenv __environment-variable-name__ __changed-value__` commande.
.. Enregistrez vos modifications à l'aide du `savenv` commande.
.. Redémarrez le nœud.



