---
permalink: fas9000/x91148a-module-install-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, add, x91148a, storage, module, NIC, no open, slots, open slots, system 
summary: 'Vous pouvez ajouter un module d"E/S à votre système en remplaçant une carte réseau ou une carte de stockage par une nouvelle carte dans un système entièrement rempli, ou en ajoutant une nouvelle carte réseau ou un adaptateur de stockage dans un logement de châssis vide du système.' 
---
= Présentation de l'ajout d'un module X91148A - AFF A9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter un module d'E/S à votre système en remplaçant une carte réseau ou une carte de stockage par une nouvelle carte dans un système entièrement rempli, ou en ajoutant une nouvelle carte réseau ou un adaptateur de stockage dans un logement de châssis vide du système.

.Avant de commencer
* Vérifier le https://hwu.netapp.com/["NetApp Hardware Universe"] Pour vérifier que le nouveau module d'E/S est compatible avec votre système et la version de ONTAP que vous utilisez.
* Si plusieurs emplacements sont disponibles, vérifiez les priorités des emplacements dans https://hwu.netapp.com/["NetApp Hardware Universe"] Et utiliser la meilleure solution disponible pour votre module d'E/S.
* Pour ajouter un module d'E/S sans interruption, vous devez prendre le contrôle cible, retirer l'obturateur de slot dans le slot cible ou retirer un module d'E/S existant, ajouter un nouveau module d'E/S ou un module de remplacement, puis renvoyer le contrôleur cible.
* S'assurer que tous les autres composants fonctionnent correctement.

