---
permalink: asa-r2-a20-30-50/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, replace the boot media 
summary: 'Avant de remplacer le support de démarrage de votre système de stockage ASA A20, ASA A30 ou ASA A50, assurez-vous de respecter les exigences et les points à considérer pour un remplacement réussi. Cela inclut la vérification que vous disposez du support de démarrage de remplacement approprié, la confirmation que le port e0M (clé) du contrôleur défectueux fonctionne correctement et la détermination si Onboard Key Manager (OKM) ou External Key Manager (EKM) est activé.' 
---
= Conditions requises pour remplacer le support de démarrage - ASA A20, ASA A30 et ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le support de démarrage de votre système de stockage ASA A20, ASA A30 ou ASA A50, assurez-vous de respecter les exigences et les points à considérer pour un remplacement réussi. Cela inclut la vérification que vous disposez du support de démarrage de remplacement approprié, la confirmation que le port e0M (clé) du contrôleur défectueux fonctionne correctement et la détermination si Onboard Key Manager (OKM) ou External Key Manager (EKM) est activé.

Passez en revue les exigences suivantes.

* Vous devez remplacer le composant défectueux par un composant FRU de remplacement de même capacité que celle reçue de NetApp.
* Vérifiez que le port e0M (clé) du contrôleur défectueux est connecté et n'est pas défectueux.
+
Le port e0M est utilisé pour communiquer entre les deux contrôleurs pendant le processus de récupération de démarrage automatisé.

* Pour OKM, vous avez besoin de la phrase secrète à l'échelle du cluster ainsi que des données de sauvegarde.
* Pour EKM, vous avez besoin de copies des fichiers suivants à partir du nœud partenaire :
+
** fichier /cfcard/kmip/servers.cfg.
** fichier /cfcard/kmip/certs/client.crt.
** fichier /cfcard/kmip/certs/client.key.
** Fichier /cfcard/kmip/certs/CA.pem.


* Il est essentiel d'appliquer les commandes au contrôleur approprié lorsque vous remplacez le support de démarrage défectueux :
+
** Le _contrôleur défaillant_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le _contrôleur sain_ est le partenaire HA du contrôleur altéré.




.Et la suite
Après avoir examiné la configuration requise pour le support de démarrage, vous link:bootmedia-shutdown-bmr.html["arrêtez le contrôleur défectueux"].
