---
permalink: asa-r2-a20-30-50/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, verify and set HA state, complete the replacement process 
summary: 'Vérifier l"état HA du châssis, puis renvoyer la pièce défectueuse à NetApp pour terminer l"étape finale de la procédure de remplacement du châssis ASA A20, ASA A30 et ASA A50.' 
---
= Remplacement complet du châssis - ASA A20, ASA A30 et ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vérifier l'état HA du châssis, puis renvoyer la pièce défectueuse à NetApp pour terminer l'étape finale de la procédure de remplacement du châssis ASA A20, ASA A30 et ASA A50.



== Étape 1 : vérifier et définir l'état de haute disponibilité du châssis

Vous devez vérifier l'état HA du châssis et, si nécessaire, mettre à jour l'état pour qu'il corresponde à la configuration de votre système de stockage.

. En mode Maintenance, depuis l'un ou l'autre contrôleur, afficher l'état HA du contrôleur local et du châssis :
+
`ha-config show`

+
L'état de la HA doit être le même pour tous les composants.

. Si l'état système affiché pour le châssis ne correspond pas à la configuration de votre système de stockage :
+
.. Définissez l'état haute disponibilité du châssis :
+
`ha-config modify chassis _HA-state_`

+
La valeur de l'état HA doit être _ha_.

.. Vérifiez que le paramètre a changé :
+
`ha-config show`



. Si ce n'est pas déjà fait, recâblage du reste de votre système de stockage.




== Étape 2 : renvoyer la pièce défectueuse à NetApp

Retournez la pièce défectueuse à NetApp, tel que décrit dans les instructions RMA (retour de matériel) fournies avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièces et remplacements"] page pour plus d'informations.
