---
permalink: asa-r2-a20-30-50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, prerequisite, replace the controller module 
summary: 'Avant de remplacer le contrôleur de votre système de stockage ASA A20, ASA A30 ou ASA A50, assurez-vous de répondre aux exigences nécessaires pour un remplacement réussi.  Cela comprend la vérification du bon fonctionnement de tous les autres composants du système, la vérification que vous disposez du contrôleur de remplacement approprié et l"enregistrement de la sortie de la console du contrôleur dans un fichier journal texte.' 
---
= Conditions requises pour remplacer le contrôleur - ASA A20, ASA A30 et ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de remplacer le contrôleur de votre système de stockage ASA A20, ASA A30 ou ASA A50, assurez-vous de répondre aux exigences nécessaires pour un remplacement réussi.  Cela comprend la vérification du bon fonctionnement de tous les autres composants du système, la vérification que vous disposez du contrôleur de remplacement approprié et l'enregistrement de la sortie de la console du contrôleur dans un fichier journal texte.

Vous devez revoir les conditions requises et les considérations relatives à la procédure de remplacement du contrôleur.



== De formation

* Toutes les tablettes doivent fonctionner correctement.
* Le contrôleur sain doit pouvoir reprendre le contrôleur qui est remplacé (appelé « contrôleur défectueux » dans cette procédure).
* Vous devez remplacer un contrôleur par un contrôleur de même type. Vous ne pouvez pas mettre à niveau votre système en remplaçant simplement le contrôleur.
* Vous ne pouvez pas modifier de disques ou de tiroirs dans le cadre de cette procédure.
* Vous devez toujours capturer la sortie de la console du contrôleur dans un fichier journal texte.
+
Le résultat de la console vous fournit un enregistrement de la procédure que vous pouvez utiliser pour résoudre les problèmes que vous pourriez rencontrer pendant le processus de remplacement.





== Considérations

* Il est important d'appliquer les commandes de cette procédure au contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur qui est en cours de remplacement.
** Le contrôleur _remplacement_ est le nouveau contrôleur qui remplace le contrôleur défaillant.
** Le contrôleur _Healthy_ est le contrôleur survivant.




.Et la suite ?
Après avoir passé en revue les conditions requises pour remplacer le contrôleur défectueux, vous devez link:controller-replace-shutdown.html["arrêtez le contrôleur défectueux"].
