---
permalink: asa-r2-key-specifications/asa-a50-key-specifications.html 
sidebar: sidebar 
keywords: ASA A50 specifications, ASA A50 specs, ASA A50 capacity, ASA A50 memory, ASA A50 I/O, ASA A50 compliance 
summary: Spécifications clés de ASA A50 
---
= Spécifications clés de ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour le système de stockage ASA A50 dans une seule paire haute disponibilité.  Visitez NetApp Hardware Universe (HWU) pour obtenir les spécifications complètes de ce système de stockage.



== Spécifications de la capacité clé, de la mémoire, du facteur de forme et de la version ONTAP

* Configuration de la plateforme : paire HA à châssis unique ASA A50
* Capacité brute maximale : 1,8360 Po
* Mémoire : 256.0000 Go
* Facteur de forme : châssis 2U avec 2 contrôleurs HA et 24 emplacements pour disques
* Version ONTAP : ONTAP: 9.16.1P2
* Emplacements d'extension PCIe : 8
* Version minimale ONTAP : ONTAP 9.16.1




== Maximums de mise à l'échelle

* Type : NAS
* Type : SAN ; paires HA : 6 ; capacité brute : 11,0 Po / 9,8 PiB ; mémoire maximale : 1 536 Go
* Type : Paire HA ; Capacité brute : 1,8 Po / 1,6 PiB ; Mémoire maximale : 256 0000




== E/S



=== E/S embarquées

Aucune donnée d'E/S intégrée.



=== E/S totales

* Protocole : Ethernet 100 Gbps ; Ports : 16
* Protocole : Ethernet 25 Gbit/s ; Ports : 24
* Protocole : Ethernet 10 Gbit/s ; Ports : 24
* Protocole : FC 64 Gbps ; Ports : 24
* Protocole : NVMe/FC 64 Gbit/s ; Ports : 24
* Ports : 0




=== Ports de gestion

* Protocole : Ethernet 1 Gbps ; Ports : 2
* Protocole : RS-232 115 Kbps ; Ports : 4
* Protocole : USB 600 Mbps ; Ports : 2




== Prise en charge du réseau de stockage

* FC
* iSCSI
* NVMe/FC
* NVMe/TCP




== Spécifications de l'environnement système

* Puissance typique : 3076 BTU/h
* Puissance dans le pire des cas : 4 860 BTU/h
* Poids : 60,7 lb 27,5 kg
* Hauteur : 2U
* Largeur : 19 pouces conforme à la norme IEC (17,6 pouces 44,7 cm)
* Profondeur:
* Température/Altitude/Humidité de fonctionnement : 10 °C à 35 °C (50 °F à 95 °F) jusqu’à 3 048 m (10 000 pi) d’altitude ; 8 % à 80 % d’humidité relative, sans condensation
* Température et humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu’à 12 192 m (40 000 pi), 10 % à 95 % d’humidité relative, sans condensation, dans son emballage d’origine.
* Bruit acoustique : Puissance acoustique déclarée (LwAd) : 8,0 Pression acoustique (LpAm) (positions d'observation) : 70,5 dB




== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




== Haute disponibilité

* Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP
* Contrôleurs redondants remplaçables à chaud
* Alimentations redondantes remplaçables à chaud
* Gestion SAS en bande via des connexions SAS pour les étagères externes

