---
permalink: asa-r2-key-specifications/asa-a90-key-specifications.html 
sidebar: sidebar 
summary: Spécifications clés de ASA A90 
---
= Spécifications clés de ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Voici quelques spécifications sélectionnées pour le système de stockage ASA A90 dans une seule paire haute disponibilité.  Visitez NetApp Hardware Universe (HWU) pour obtenir les spécifications complètes de ce système de stockage.



== Spécifications de la capacité clé, de la mémoire, du facteur de forme et de la version ONTAP

* Configuration de la plateforme : paire HA à châssis unique ASA A90
* Capacité brute maximale : 2,6622 Po
* Mémoire : 2048.0000 Go
* Facteur de forme : châssis 4U avec 2 contrôleurs HA et 48 emplacements pour disques
* Version ONTAP : ONTAP: 9.16.1P2
* Emplacements d'extension PCIe : 18
* Version minimale ONTAP : ONTAP 9.16.0 == Maximums de scale-out
* Type : NAS
* Type : SAN ; paires HA : 6 ; capacité brute : 16,0 Po / 14,2 PiB ; mémoire maximale : 12 288 Go
* Type : Paire HA ; Capacité brute : 2,7 Po / 2,4 PiB ; Mémoire maximale : 2 048 0000




== E/S



=== E/S embarquées

Aucune donnée d'E/S intégrée.



=== E/S totales

* Protocole : Ethernet 200 Gbps ; Ports : 24
* Protocole : Ethernet 100 Gbps ; Ports : 36
* Protocole : Ethernet 25 Gbit/s ; Ports : 56
* Protocole : Ethernet 10 Gbit/s ; Ports : 56
* Protocole : FC 64 Gbps ; Ports : 56
* Protocole : NVMe/FC 64 Gbit/s ; Ports : 56
* Ports : 0




=== Ports de gestion

* Protocole : Ethernet 1 Gbps ; Ports : 2
* Protocole : RS-232 115 Kbps ; Ports : 4
* Protocole : USB 600 Mbps ; Ports : 2




== Prise en charge du réseau de stockage

* FC
* iSCSI
* NVMe/FC
* NVMe/TCP == Spécifications de l'environnement système
* Puissance typique : 8304 BTU/h
* Puissance dans le pire des cas : 10 948 BTU/h
* Poids : 170,4 lb 77,3 kg
* Hauteur : 4U
* Largeur : 19 pouces conforme à la norme IEC (17,6 pouces 44,7 cm)
* Profondeur : 34,5 po (36,6 po avec support de gestion des câbles)
* Température/altitude/humidité de fonctionnement : 10 °C à 35 °C (50 °F à 95 °F) à une altitude de 3 048 m (10 000 pi) ; humidité relative de 8 % à 80 %, sans condensation
* Température/humidité hors fonctionnement : -40 °C à 70 °C (-40 °F à 158 °F) jusqu'à 12 192 m (40 000 pi) 10 % à 95 % d'humidité relative, sans condensation, dans l'emballage d'origine
* Bruit acoustique : Puissance acoustique déclarée (LwAd) : 8,6 Pression acoustique (LpAm) (positions d'observation) : 71,6 dB




== Conformité

* Certifications EMC/EMI : AMCA, FCC, ICES, KC, Maroc, VCCI
* Certifications sécurité : BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certifications Sécurité/CEM/EMI : EAC, UKRSEPRO
* Certifications Sécurité/EMC/EMI/RoHS : BSMI, CE DoC, UKCA DoC
* Normes CEM/EMI : BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Partie 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normes de sécurité : ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (partie 1)




== Haute disponibilité

* Contrôleur de gestion de carte mère (BMC) basé sur Ethernet et interface de gestion ONTAP
* Contrôleurs redondants remplaçables à chaud
* Alimentations redondantes remplaçables à chaud
* Gestion SAS en bande via des connexions SAS pour les étagères externes

