---
permalink: afx/afx-install-setup.html 
sidebar: sidebar 
keywords: afx, afx 1k, install, setup, initial configuration 
summary: Installez et configurez votre système. 
---
= Installez et configurez votre système de stockage AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aller à la https://docs.netapp.com/us-en/ontap-afx/index.html["Documentation AFX"^] pour apprendre à installer, utiliser et gérer votre système AFX.

Le https://docs.netapp.com/us-en/ontap-afx/index.html["Documentation AFX"^] comprend des informations telles que :

* Instructions d'installation et de configuration
* Instructions d'administration pour la configuration de votre système, telles que l'approvisionnement du stockage NAS, le clonage des données et le redimensionnement du stockage local.
* Instructions pour la gestion de votre système, y compris la gestion de l'accès client, la sécurisation de vos données et la protection de vos données.
* Des instructions de surveillance et de dépannage, y compris des informations sur les alertes, les événements de cluster et les journaux du système.


Des procédures de maintenance spécifiques pour chaque type de système AFX sont disponibles dans lelink:../afx-landing-maintain/index.html["Section de maintenance du système AFX"] .
