---
permalink: asa-c250/bootmedia-recovery-image-boot-non-2n-mcc.html 
sidebar: sidebar 
keywords: asa c250, boot the recovery image 
summary: 'Vous devez démarrer l"image ONTAP à partir du lecteur USB, restaurer le système de fichiers et vérifier les variables environnementales.' 
---
= Démarrez l'image de récupération - ASA C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez démarrer l'image ONTAP à partir du lecteur USB, restaurer le système de fichiers et vérifier les variables environnementales.

. À partir de l'invite DU CHARGEUR, démarrez l'image de récupération à partir du lecteur flash USB : `boot_recovery`
+
L'image est téléchargée à partir de la clé USB.

. Lorsque vous y êtes invité, entrez le nom de l'image ou acceptez l'image par défaut affichée entre crochets sur votre écran.
. Restaurez le `var` système de fichiers :
+
[cols="1,2"]
|===
| Si votre système dispose de... | Alors... 


 a| 
Une connexion réseau
 a| 
.. Appuyez sur `y` lorsque vous êtes invité à restaurer la configuration de sauvegarde.
.. Définissez le contrôleur sain sur le niveau de privilège avancé : `set -privilege advanced`
.. Exécutez la commande restore backup : `system node restore-backup -node local -target-address _impaired_node_IP_address_`
.. Renvoyer le contrôleur au niveau admin : `set -privilege admin`
.. Appuyez sur `y` lorsque vous êtes invité à utiliser la configuration restaurée.
.. Appuyez sur `y` lorsque vous êtes invité à redémarrer le contrôleur.




 a| 
Aucune connexion réseau
 a| 
.. Appuyez sur `n` lorsque vous êtes invité à restaurer la configuration de sauvegarde.
.. Redémarrez le système à l'invite du système.
.. Sélectionnez l'option *mettre à jour Flash dans Backup config* (Sync flash) dans le menu affiché.
+
Si vous êtes invité à poursuivre la mise à jour, appuyez sur `y`.





 a| 
Aucune connexion réseau et se trouve dans une configuration IP de MetroCluster
 a| 
.. Appuyez sur `n` lorsque vous êtes invité à restaurer la configuration de sauvegarde.
.. Redémarrez le système à l'invite du système.
.. Attendez que les connexions de stockage iSCSI se connectent.
+
Vous pouvez continuer après avoir afficher les messages suivants :

+
[listing]
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
.. Sélectionnez l'option *mettre à jour Flash dans Backup config* (Sync flash) dans le menu affiché.
+
Si vous êtes invité à poursuivre la mise à jour, appuyez sur `y`.



|===
. Assurez-vous que les variables environnementales sont définies comme prévu :
+
.. Prenez le contrôleur vers l'invite DU CHARGEUR.
.. Vérifiez les paramètres de la variable d'environnement à l'aide de l' `printenv` commande.
.. Si une variable d'environnement n'est pas définie comme prévu, modifiez-la avec le `setenvenvironment_variable_name changed_value` commande.
.. Enregistrez vos modifications à l'aide du `saveenv` commande.


. Le suivant dépend de la configuration de votre système :
+
** Si keymanager, NSE ou NVE intégré est configuré sur votre système, rendez-vous sur xref:bootmedia-encryption-restore.adoc[OKM, NSE et NVE si besoin]
** Si keymanager, NSE ou NVE intégré ne sont pas configurés sur votre système, effectuez les étapes de cette section.


. Dans l'invite DU CHARGEUR, entrez le `boot_ontap` commande.
+
[cols="1,2"]
|===
| Si vous voyez... | Alors... 


 a| 
Invite de connexion
 a| 
Passer à l'étape suivante.



 a| 
Attente du retour...
 a| 
.. Connectez-vous au contrôleur partenaire.
.. Vérifiez que le contrôleur cible est prêt pour le rétablissement à l'aide du `storage failover show` commande.


|===
. Branchez le câble de la console au contrôleur partenaire.
. Reaccordez le contrôleur à l'aide du `storage failover giveback -fromnode local` commande.
. À l'invite du cluster, vérifiez les interfaces logiques avec le `net int -is-home false` commande.
+
Si l'une des interfaces est indiquée comme « FALSE », restaurez ces interfaces à son port d'origine à l'aide de l' `net int revert` commande.

. Déplacez le câble de la console vers le contrôleur réparé et exécutez le `version -v` Commande pour vérifier les versions de ONTAP.
. Restaurez le retour automatique si vous le désactivez à l'aide de `storage failover modify -node local -auto-giveback true` commande.


[]
====
Vous devez démarrer l'image ONTAP à partir du lecteur USB, restaurer le système de fichiers et vérifier les variables environnementales.

. À partir de l'invite DU CHARGEUR, démarrez l'image de récupération à partir du lecteur flash USB : `boot_recovery`
+
L'image est téléchargée à partir de la clé USB.

. Lorsque vous y êtes invité, entrez le nom de l'image ou acceptez l'image par défaut affichée entre crochets sur votre écran.
. Restaurez le `var` système de fichiers :
+
[cols="1,2"]
|===
| Si votre système dispose de... | Alors... 


 a| 
Une connexion réseau
 a| 
.. Appuyez sur `y` lorsque vous êtes invité à restaurer la configuration de sauvegarde.
.. Définissez le contrôleur sain sur le niveau de privilège avancé : `set -privilege advanced`
.. Exécutez la commande restore backup : `system node restore-backup -node local -target-address _impaired_node_IP_address_`
.. Renvoyer le contrôleur au niveau admin : `set -privilege admin`
.. Appuyez sur `y` lorsque vous êtes invité à utiliser la configuration restaurée.
.. Appuyez sur `y` lorsque vous êtes invité à redémarrer le contrôleur.




 a| 
Aucune connexion réseau
 a| 
.. Appuyez sur `n` lorsque vous êtes invité à restaurer la configuration de sauvegarde.
.. Redémarrez le système à l'invite du système.
.. Sélectionnez l'option *mettre à jour Flash dans Backup config* (Sync flash) dans le menu affiché.
+
Si vous êtes invité à poursuivre la mise à jour, appuyez sur `y`.





 a| 
Aucune connexion réseau et se trouve dans une configuration IP de MetroCluster
 a| 
.. Appuyez sur `n` lorsque vous êtes invité à restaurer la configuration de sauvegarde.
.. Redémarrez le système à l'invite du système.
.. Attendez que les connexions de stockage iSCSI se connectent.
+
Vous pouvez continuer après avoir afficher les messages suivants :

+
[listing]
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
.. Sélectionnez l'option *mettre à jour Flash dans Backup config* (Sync flash) dans le menu affiché.
+
Si vous êtes invité à poursuivre la mise à jour, appuyez sur `y`.



|===
. Assurez-vous que les variables environnementales sont définies comme prévu :
+
.. Prenez le contrôleur vers l'invite DU CHARGEUR.
.. Vérifiez les paramètres de la variable d'environnement à l'aide de l' `printenv` commande.
.. Si une variable d'environnement n'est pas définie comme prévu, modifiez-la avec le `setenvenvironment_variable_name changed_value` commande.
.. Enregistrez vos modifications à l'aide du `saveenv` commande.


. Le suivant dépend de la configuration de votre système :
+
** Si keymanager, NSE ou NVE intégré est configuré sur votre système, rendez-vous sur xref:bootmedia-encryption-restore.adoc[OKM, NSE et NVE si besoin]
** Si keymanager, NSE ou NVE intégré ne sont pas configurés sur votre système, effectuez les étapes de cette section.


. Dans l'invite DU CHARGEUR, entrez le `boot_ontap` commande.
+
[cols="1,2"]
|===
| Si vous voyez... | Alors... 


 a| 
Invite de connexion
 a| 
Passer à l'étape suivante.



 a| 
Attente du retour...
 a| 
.. Connectez-vous au contrôleur partenaire.
.. Vérifiez que le contrôleur cible est prêt pour le rétablissement à l'aide du `storage failover show` commande.


|===
. Branchez le câble de la console au contrôleur partenaire.
. Reaccordez le contrôleur à l'aide du `storage failover giveback -fromnode local` commande.
. À l'invite du cluster, vérifiez les interfaces logiques avec le `net int -is-home false` commande.
+
Si l'une des interfaces est indiquée comme « FALSE », restaurez ces interfaces à son port d'origine à l'aide de l' `net int revert` commande.

. Déplacez le câble de la console vers le contrôleur réparé et exécutez le `version -v` Commande pour vérifier les versions de ONTAP.
. Restaurez le retour automatique si vous le désactivez à l'aide de `storage failover modify -node local -auto-giveback true` commande.


====