---
permalink: asa-c250/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: asa c250, shutdown the controllers 
summary: Pour remplacer le châssis, vous devez arrêter les contrôleurs. 
---
= Arrêtez les contrôleurs - ASA C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arrêtez les contrôleurs afin d'effectuer des opérations de maintenance sur le châssis.

Cette procédure concerne les systèmes ayant des configurations à deux nœuds. Si votre système comporte plus de deux nœuds, reportez-vous à la section https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_perform_a_graceful_shutdown_and_power_up_of_one_HA_pair_in_a_4__node_cluster["Comment effectuer un arrêt normal et mettre sous tension une paire haute disponibilité dans un cluster à quatre nœuds"^].

.Avant de commencer
* Empêchez tous les clients/hôtes d'accéder aux données sur le système NetApp.
* Suspendre les tâches de sauvegarde externes.
* Vérifiez que vous disposez des autorisations et des informations d'identification nécessaires :
+
** Informations d'identification de l'administrateur local pour ONTAP.
** Phrase secrète pour la gestion des clés intégrée NetApp à l'échelle du cluster en cas d'utilisation du chiffrement du stockage ou de NVE/NAE.
** Accès BMC pour chaque contrôleur.


* Assurez-vous de disposer des outils et de l'équipement nécessaires pour le remplacement.
* Avant de procéder à l'arrêt, vous devez :
+
** Effectuer des opérations supplémentaires https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["vérifications de l'état du système"].
** Mettez à niveau ONTAP vers une version recommandée pour le système.
** Résoudre tout https://activeiq.netapp.com/["Alertes et risques liés au bien-être Active IQ"]. Notez toutes les anomalies présentes sur le système, telles que les voyants des composants du système.




.Étapes
. Connectez-vous au cluster via SSH ou connectez-vous à un nœud du cluster à l'aide d'un câble de console local et d'un ordinateur portable/d'une console.
. Désactivez AutoSupport et indiquez la durée de mise hors ligne du système :
+
`system node autosupport invoke -node * -type all -message "MAINT=8h Power Maintenance"`

. Identifiez l'adresse SP/BMC de tous les nœuds :
+
`system service-processor show -node * -fields address`

. Quitter le cluster shell : `exit`
. Connectez-vous au processeur de service/contrôleur BMC via SSH en utilisant l'adresse IP de l'un des nœuds répertoriés dans le résultat de l'étape précédente.
+
Si vous utilisez une console ou un ordinateur portable, connectez-vous au contrôleur à l'aide des mêmes informations d'identification d'administrateur de cluster.

+

NOTE: Ouvrez une session SSH sur chaque connexion SP/BMC afin de pouvoir surveiller la progression.

. Arrêtez les deux nœuds situés dans le châssis défectueux :
+
`system node halt -node <node>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Pour les clusters qui utilisent SnapMirror en mode synchrone : `system node halt -node <node>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Entrez *y* pour chaque contrôleur du cluster lorsque vous voyez `_Warning: Are you sure you want to halt node "cluster <node-name> number"?
{y|n}:_`
. Attendez que chaque contrôleur s'arrête et affichez l'invite DU CHARGEUR.

