---
permalink: asa-c250/maintain-overview.html 
sidebar: sidebar 
keywords: asa C250 maintenance, maintenance, repairing C250, repairing asa C250, replace asa C250 components, replace asa C250 components 
summary: Entretenir le matériel ASA C250 
---
= Entretenir le matériel ASA C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Assurez la maintenance du matériel de votre système de stockage ASA C250 pour garantir sa fiabilité à long terme et des performances optimales. Effectuez des tâches de maintenance régulières, comme le remplacement des composants défectueux, afin de prévenir l'interruption et la perte de données.

Les procédures de maintenance supposent que le système de stockage ASA C250 a déjà été déployé en tant que nœud de stockage dans l'environnement ONTAP.



== Composants du système

Pour le système de stockage ASA C250, vous pouvez effectuer des procédures de maintenance sur les composants suivants.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Support de démarrage - récupération automatique"]
 a| 
Le support de démarrage stocke un ensemble principal et un ensemble secondaire de fichiers image ONTAP que le système de stockage utilise pour démarrer. Lors d'une récupération automatisée, le système récupère l'image de démarrage depuis le nœud partenaire et exécute automatiquement l'option appropriée du menu de démarrage pour installer l'image sur votre support de démarrage de remplacement. Le processus automatisé de récupération du support de démarrage est pris en charge uniquement dans ONTAP 9.18.1 et versions ultérieures. Si votre système de stockage exécute une version antérieure d'ONTAP, utilisez le link:bootmedia-replace-workflow.html["procédure de récupération de démarrage manuel"].



 a| 
link:bootmedia-replace-workflow.html["Support de démarrage - récupération manuelle"]
 a| 
Le support de démarrage contient un ensemble principal et un ensemble secondaire de fichiers image ONTAP que le système de stockage utilise pour démarrer. Lors d'une récupération manuelle, vous démarrez le système de stockage à partir d'une clé USB et restaurez manuellement l'image du système de fichiers et la configuration. Si votre système de stockage exécute ONTAP 9.18.1 ou une version ultérieure, utilisez le link:bootmedia-replace-workflow-bmr.html["procédure de récupération de démarrage automatisée"].



 a| 
link:chassis-replace-workflow.html["Châssis"]
 a| 
Le châssis correspond au boîtier physique qui contient tous les composants du contrôleur, tels que le contrôleur/l'unité centrale, l'alimentation et les E/S.



 a| 
link:controller-replace-workflow.html["Contrôleur"]
 a| 
Un contrôleur se compose d'une carte, d'un micrologiciel et d'un logiciel. Il contrôle les entraînements et met en œuvre les fonctions ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Vous devez remplacer un module DIMM (module de mémoire double en ligne) en cas de non-concordance de mémoire, ou si vous avez un module DIMM défectueux.



 a| 
link:drive-replace.html["Lecteur"]
 a| 
Un lecteur est un périphérique qui fournit le support de stockage physique pour les données.



 a| 
link:fan-replace.html["Ventilateur"]
 a| 
Le ventilateur refroidit le contrôleur.



 a| 
link:mezzanine-replace.html["Carte mezzanine"]
 a| 
La carte mezzanine est un circuit imprimé qui se branche directement sur une autre carte enfichable.



 a| 
link:nvmem-nvram-battery-replace.html["Batterie NVMEM"]
 a| 
La batterie NVMEM est chargée de préserver les données mises en cache si l'alimentation secteur tombe en panne.



 a| 
link:power-supply-replace.html["Alimentation électrique"]
 a| 
Une alimentation électrique fournit une source d'alimentation redondante dans un tiroir contrôleur.



 a| 
link:rtc-battery-replace.html["Pile de l'horloge en temps réel"]
 a| 
Une batterie d'horloge en temps réel conserve les informations relatives à la date et à l'heure du système si l'alimentation est coupée.

|===