---
permalink: a300/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a300, replace the chassis 
summary: Vous remplacez un châssis endommagé le nouveau châssis du même modèle que le châssis endommagé. 
---
= Présentation du remplacement de châssis - AFF A300
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour remplacer le châssis, vous devez déplacer les blocs d'alimentation, les ventilateurs et les modules de contrôleur du châssis pour lequel le châssis est endommagé vers le nouveau châssis, et permuter les châssis pour lequel le châssis est endommagé du rack d'équipement ou de l'armoire système avec le nouveau châssis du même modèle que le châssis endommagé.

Tous les autres composants du système doivent fonctionner correctement ; si ce n'est pas le cas, vous devez contacter le support technique.

* Cette procédure peut être utilisée avec toutes les versions de ONTAP prises en charge par votre système.
* Cette procédure est rédigée en supposant que vous déplaiez le ou les modules de contrôleur vers le nouveau châssis, et que le châssis est un nouveau composant de NetApp.
* Cette procédure est perturbatrice. Dans le cas d'un cluster à deux nœuds, la panne totale du service et une panne partielle dans un cluster multinœud sont associés.

