---
permalink: ns224/cable-as-switch-attached.html 
sidebar: sidebar 
keywords: ns224 nvme drive shelf cabling guide, ns224 drive shelf cabling guide, ns224 shelf cabling guide, ns224 cabling guide, switch-attach, switch-attached, switch-attached storage, cable ns224 drive shelves as switch-attached storage 
summary: 'Si vous disposez d"un système dans lequel les tiroirs disques NS224 doivent être câblés comme stockage à connexion par commutateur \(pas de stockage à connexion directe\), utilisez les informations fournies.' 
---
= Reliez les étagères en tant que stockage relié à un commutateur - étagères NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous disposez d'un système dans lequel les tiroirs disques NS224 doivent être câblés en tant que stockage à connexion par commutateur (pas de stockage à connexion directe), utilisez les informations fournies.

* Pour connecter les tiroirs disques NS224 via les commutateurs de stockage, reportez-vous au https://hwu.netapp.com["NetApp Hardware Universe"^] pour plus d'informations. Pour les anciens modèles de matériel, vous trouverez également des informations sur le câblage des commutateurs dans le https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580["Guide de câblage de tiroirs disques NVMe NS224"^].
* Pour installer vos commutateurs de stockage, reportez-vous au https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Documentation sur les commutateurs AFF et FAS"^].
* Pour vérifier le matériel pris en charge par votre modèle de plate-forme, tel que les commutateurs de stockage et les câbles, reportez-vous au https://hwu.netapp.com["NetApp Hardware Universe"^] .

