---
permalink: ns224/hot-add-asa-cable-a250.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, asa a250, cable 
summary: Câblez votre étagère NS224 à votre ASA A250 afin que chaque étagère dispose de deux connexions à chaque contrôleur de la paire haute disponibilité. 
---
= Connectez un châssis NS224 à votre système ASA A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Câblez votre étagère NS224 à votre ASA A250 afin que chaque étagère dispose de deux connexions à chaque contrôleur de la paire haute disponibilité.

.Description de la tâche
Vu de l'arrière du châssis de la plateforme, le port de la carte compatible RoCE sur la gauche est le port « a » (e1a) et le port de droite est le port « b » (e1b).

.Étapes
. Connectez les câbles du tiroir :
+
.. Reliez le port E0a du NSM A du tiroir du contrôleur à l'emplacement 1 du port a (e1a).
.. Reliez le port e0b du tiroir NSM A au port 1 b du contrôleur B (e1b).
.. Reliez le port e0a du NSM B du tiroir du contrôleur B au port a (e1a) du connecteur 1 du contrôleur.
.. Reliez le port e0b du tiroir NSM B au port b (e1b) du contrôleur A. + l'illustration suivante montre le câblage du tiroir une fois l'opération terminée.
+
image::../media/drw_ns224_a250_c250_f500f_1shelf_ieops-1824.svg[Câblage d'un AFF/ASA A250 C250 ou d'un FAS500f avec un tiroir NS224 et un jeu de ports de carte PCIe]



. Vérifiez que le tiroir ajouté à chaud est correctement câblé à l'aide de https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^].
+
Si des erreurs de câblage sont générées, suivez les actions correctives fournies.



.Et la suite
Si vous avez désactivé l'attribution automatique des lecteurs lors de la préparation de cette procédure, vous devez attribuer manuellement la propriété du lecteur, puis réactiver l'attribution automatique si nécessaire. Accédez à link:hot-add-asa-complete.html["Terminez l'ajout à chaud"].

Sinon, vous effectuez l'ajout à chaud d'un tiroir.
