---
permalink: ns224/hot-add-eoa-complete.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, eoa systems, end-of-availability, complete, drive 
summary: 'Si vous avez désactivé l"attribution automatique des lecteurs, attribuez manuellement la propriété des lecteurs et réactivez l"attribution automatique des lecteurs pour votre système en fin de disponibilité.' 
---
= Complétez l'ajout à chaud du NS224 pour votre système en fin de disponibilité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez désactivé l'affectation automatique des disques dans le cadre de la préparation du tiroir NS224 à chaud, vous devez attribuer manuellement la propriété des disques, puis réactiver l'affectation automatique des disques, si nécessaire.

.Avant de commencer
Vous devez déjà avoir câblé votre étagère comme indiqué pour votre paire haute disponibilité.

.Étapes
. Afficher tous les disques non propriétaires : `storage disk show -container-type unassigned`
+
Vous pouvez saisir la commande sur l'un ou l'autre contrôleur.

. Affectez chaque disque : `storage disk assign -disk _disk_name_ -owner _owner_name_`
+
Vous pouvez saisir la commande sur l'un ou l'autre contrôleur.

+
Vous pouvez utiliser le caractère générique pour attribuer plusieurs lecteurs à la fois.

. Réactivez l'affectation automatique des disques si nécessaire : `storage disk option modify -node _node_name_ -autoassign on`
+
Vous devez réactiver l'affectation automatique des disques sur les deux contrôleurs.


