---
permalink: ns224/hot-add-asa-prepare-a1k.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, asa systems, preparation, roce, asa a1k 
summary: 'Préparez votre système ASA A1K à ajouter à chaud un châssis NS224 en installant des modules d"E/S compatibles RoCE, en configurant les ports, en recâblant les châssis existants et en désactivant l"attribution automatique des disques.' 
---
= Préparez votre système ASA A1K pour l'ajout à chaud d'un châssis NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Préparez votre système ASA A1K à l'ajout à chaud d'une baie NS224 en vous assurant qu'il y a suffisamment de ports de stockage compatibles RoCE, en les configurant pour une utilisation de stockage, en recâblant les baies existantes pour une connectivité optimale et en désactivant l'attribution automatique des disques.



== Installer des modules d'E/S compatibles RoCE

Si votre système prend en charge l'utilisation de cartes PCIe ou de modules d'E/S compatibles RoCE, votre paire haute disponibilité doit disposer de suffisamment de ports Ethernet compatibles RoCE disponibles pour prendre en charge le nombre de shelves que vous ajoutez à chaud.

.Étapes
. Pour chaque tiroir que vous ajoutez à chaud, vérifiez qu'il existe deux ports compatibles RoCE sur chaque contrôleur.
+
Ces ports peuvent se trouver sur les contrôleurs, sur des cartes PCIe compatibles RoCE, une combinaison des deux, ou sur des modules d'E/S compatibles RoCE, selon la compatibilité de votre système.

. Si votre paire haute disponibilité ne dispose pas de suffisamment de ports compatibles RoCE, installez les cartes PCIe ou les modules d'E/S supplémentaires dans les emplacements de contrôleur appropriés, comme pris en charge par votre système.
+
.. Identifiez les emplacements de contrôleur appropriés pour votre système. Voir https://hwu.netapp.com["NetApp Hardware Universe"^].
.. Consultez la documentation de votre système pour obtenir les instructions d'installation de la carte PCIe ou du module d'E/S.






== Configurez les ports compatibles RoCE pour l'utilisation du stockage

Sur certains systèmes, les ports compatibles RoCE sont automatiquement configurés pour une utilisation de stockage lorsqu'une carte PCIe ou un module d'E/S compatible RoCE est installé dans un emplacement de contrôleur pris en charge. Cependant, vous devez suivre cette procédure pour vérifier que les ports sont correctement configurés pour une utilisation de stockage.

La configuration des ports RoCE non dédiés pour le stockage est une procédure non perturbatrice. Il n'est pas nécessaire de redémarrer les contrôleurs, sauf si l'un ou les deux sont en mode maintenance. Cette procédure suppose qu'aucun contrôleur n'est en mode maintenance.

Si vous devez à l'avenir modifier l'utilisation des ports pour le stockage en vue de leur utilisation réseau, utilisez la commande `storage port modify -node _node_name_ -port _port_name_ -mode network`.

.Étapes
. Vérifiez que vous avez installé toutes les cartes PCIe ou modules d'E/S compatibles RoCE supplémentaires dans chaque contrôleur.
. Connectez-vous au cluster à l'aide d'une connexion SSH ou du port série console.
. Vérifiez que les ports non dédiés de la paire haute disponibilité sont configurés pour le stockage en saisissant la commande `storage port show`.
+
Le résultat de la commande varie en fonction de votre version d'ONTAP :

+
** **ONTAP 9.8 ou version ultérieure :** Les ports non dédiés configurés pour le stockage affichent  `storage` dans la  `Mode` colonne. Les ports non configurés pour le stockage affichent  `network` dans la  `Mode` colonne.
** **ONTAP 9.7 :** Les ports non dédiés configurés pour le stockage affichent  `false` dans la colonne  `Is Dedicated?` et  `enabled` dans la colonne  `State`. Les ports non configurés pour le stockage affichent  `false` dans la colonne  `Is Dedicated?` et  `disabled` dans la colonne  `State`.


. Si les ports non dédiés sont configurés pour le stockage, cette procédure est terminée. Sinon, suivez les étapes suivantes pour configurer les ports.
. Configurez les ports non dédiés pour le stockage sur l'un des contrôleurs. Vous devez répéter la commande correspondante pour chaque port que vous configurez.
+
[cols="1,3"]
|===
| Si votre paire haute disponibilité est en cours d'exécution... | Utilisez cette commande... 


 a| 
ONTAP 9.8 ou version ultérieure
 a| 
`storage port modify -node _node_name_ -port _port_name_ -mode storage`



 a| 
ONTAP 9.7
 a| 
`storage port enable -node _node_name_ -port _port_name_`

|===
. Répétez l'étape précédente pour la deuxième manette.
. Vérifiez que les ports non dédiés des deux contrôleurs sont configurés pour le stockage en saisissant la commande `storage port show`.
+
Le résultat de la commande varie en fonction de votre version d'ONTAP :

+
** **ONTAP 9.8 ou version ultérieure :** Les ports non dédiés configurés pour l'utilisation du stockage affichent  `storage` dans la  `Mode` colonne.
** **ONTAP 9.7 :** Les ports non dédiés configurés pour l'utilisation du stockage affichent  `false` dans la  `Is Dedicated?` colonne et  `enabled` dans la  `State` colonne.






== Recâblage des étagères existantes

Lorsque vous ajoutez à chaud des étagères à une paire haute disponibilité A1K, vous devez recâbler les étagères existantes pour équilibrer la connectivité entre plusieurs modules d'E/S compatibles RoCE.

* Si vous ajoutez à chaud un deuxième châssis, le premier châssis doit être recâblé entre les emplacements 11 et 10. Pour un deuxième châssis, la procédure suppose que le châssis existant est câblé à un module d'E/S compatible RoCE dans l'emplacement 11 de chaque contrôleur.
* Si vous ajoutez à chaud une quatrième étagère, la troisième étagère doit être recâblée entre les emplacements 9 et 8. Pour une quatrième étagère, la procédure suppose que la troisième étagère est câblée à l'emplacement 9 de chaque contrôleur.
* Si vous ajoutez à chaud un troisième châssis et installez un troisième ou un quatrième module d'E/S compatible RoCE dans chaque contrôleur, le troisième châssis est câblé uniquement au troisième ou aux troisième et quatrième modules d'E/S. Il n'est pas nécessaire de recâbler les châssis existants, vous pouvez donc ignorer cette procédure.


.Étapes
. Procédez de l'une des manières suivantes si vous ajoutez un deuxième ou un quatrième tiroir à chaud.
+
** Si vous ajoutez un second tiroir à chaud, recentrez le premier tiroir sur les modules d'E/S compatibles RoCE dans le slot 11 et le slot 10 de chaque contrôleur.
+
... Sur le contrôleur A, déplacez le câble du slot 11 port b (e11b) vers le slot 10 port b (e10b).
... Répétez le même déplacement de câble sur le contrôleur B.


** Si vous ajoutez un quatrième tiroir à chaud, recentrez le troisième tiroir sur les modules d'E/S compatibles RoCE dans le slot 9 et le slot 8 de chaque contrôleur.
+
... Sur le contrôleur A, déplacez le câble du slot 9 port b (e9b) vers le slot 8 port b (e8b).
... Répétez le même déplacement de câble sur le contrôleur B.




. Vérifiez que le shelf recabled est correctement câblé à l'aide de https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^].
+
Si des erreurs de câblage sont générées, suivez les actions correctives fournies.





== Désactiver l'affectation automatique de l'entraînement

Si vous ne savez pas si vous devez attribuer manuellement la propriété des disques ou si vous souhaitez comprendre l'affectation automatique des règles de propriété des disques pour votre système de stockage, rendez-vous sur https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html["À propos de l'assignation automatique de Disk Ownership"^].

.Étapes
. Vérifiez si l'affectation automatique des disques est activée : `storage disk option show`
+
Vous pouvez saisir la commande sur l'un ou l'autre nœud.

+
Si l'attribution automatique des lecteurs est activée, la sortie affiche  `on` dans la colonne  `Auto Assign` pour chaque nœud.

. Si l'affectation automatique des disques est activée, désactivez-la : `storage disk option modify -node _node_name_ -autoassign off`
+
Vous devez désactiver l'affectation automatique des disques sur les deux nœuds.



.Et la suite
Accédez à link:hot-add-asa-install.html["installer l'étagère"].
