---
permalink: ns224/service-replace-dimm.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, nondisruptive, dimm, i/o, replace a dimm 
summary: Vous pouvez remplacer un module DIMM défectueux sans interruption dans un tiroir de disque NS224 sous tension, puis pendant que les E/S sont en cours. 
---
= Remplacez un module DIMM - les tiroirs NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez remplacer un module DIMM défectueux sans interruption dans un tiroir de disque NS224 sous tension, puis pendant que les E/S sont en cours.

.Avant de commencer
* Le module NSM partenaire du tiroir doit être opérationnel et correctement câblé afin que votre tiroir conserve la connectivité lorsque vous retirez le module NSM avec le FRU défectueux (module NSM cible).
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Téléchargement NetApp : Config Advisor"^]

* Tous les autres composants du système, y compris les trois autres modules DIMM, doivent fonctionner correctement.


.Description de la tâche
* Laissez un délai d'au moins 70 secondes entre le retrait et l'installation du module de tiroir NVMe (NSM).
+
Cela laisse suffisamment de temps à ONTAP pour traiter l'événement de suppression NSM.

* *Meilleure pratique :* la meilleure pratique consiste à installer sur votre système les versions les plus récentes du firmware du module de tiroir NVMe (NSM) et du firmware du lecteur avant de remplacer les composants FRU.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Téléchargements NetApp : firmware des tiroirs disques"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Téléchargements NetApp : firmware de disque"^]

+
[NOTE]
====
Ne rétablissez pas le firmware en tant que version qui ne prend pas en charge votre tiroir et ses composants.

====
* Si nécessaire, vous pouvez allumer les LED situées à l'emplacement des tiroirs (bleues) pour faciliter l'emplacement physique des tiroirs concernés : `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Si vous ne connaissez pas le `_shelf_name_` sur la tablette concernée, exécutez la `storage shelf show` commande.

+
Une étagère comporte trois LED d'emplacement : une sur le panneau d'affichage de l'opérateur et une sur chaque module NSM. Les LED d'emplacement restent allumées pendant 30 minutes. Vous pouvez les désactiver en entrant la même commande, mais en utilisant le `off` option.

* Lorsque vous déballez le module DIMM de remplacement, conservez tous les matériaux d'emballage pour l'utiliser lorsque vous renvoyez le module DIMM défectueux.
+
Si vous avez besoin du numéro d'autorisation de renvoi de matériel ou d'une aide supplémentaire pour effectuer la procédure de remplacement, contactez le support technique à l'adresse https://mysupport.netapp.com/site/global/dashboard["Support NetApp"^], 888-463-8277 (Amérique du Nord), 00-800-44-638277 (Europe) ou +800-800-80-800 (Asie/Pacifique).

* Vous pouvez utiliser la vidéo suivante ou les étapes écrites pour remplacer un module DIMM.
+
.Animation : remplacez un module DIMM dans un tiroir de lecteur NS224
video::eef28b10-ed93-4aa7-bfce-aa86002f20a2[panopto]


.Étapes
. Mettez-vous à la terre.
. Déconnectez le câblage du module NSM contenant le FRU que vous remplacez :
+
.. Débrancher le cordon d'alimentation de l'alimentation en ouvrant la retenue du cordon d'alimentation, puis débrancher le cordon d'alimentation de l'alimentation.
+
Les blocs d'alimentation n'ont pas de commutateur d'alimentation.

.. Déconnectez le câblage de stockage des ports du module NSM.
+
Notez les ports du module NSM auxquels chaque câble est connecté. Vous reconnectez les câbles aux mêmes ports lorsque vous réinsérez le module NSM, plus loin dans cette procédure.



. Retirez le module NSM du shelf :
+
.. Faites passer vos doigts dans les trous des doigts des mécanismes de verrouillage de chaque côté du module NSM.
+

NOTE: Si vous retirez le module NSM inférieur et que le rail inférieur empêche l'accès aux mécanismes de verrouillage, placez vos doigts dans les trous des doigts de l'intérieur (en croisant les bras).

.. À l'aide de vos pouces, appuyez sur les languettes orange et maintenez-les enfoncées au-dessus des mécanismes de verrouillage.
+
Les mécanismes de verrouillage se relèvent, en libérant les goupilles de verrouillage de la tablette.

.. Tirez doucement jusqu'à ce que le module NSM se trouve à environ un tiers de la sortie de la tablette, saisissez les côtés du module NSM avec les deux mains pour soutenir son poids, puis placez-le sur une surface plane et stable.
+
Lorsque vous commencez à tirer, les bras du mécanisme de verrouillage s'étendent du module NSM et se verrouillent en position complètement sortie.



. Desserrez la vis du couvercle du module NSM et ouvrez le couvercle.
+
L'étiquette FRU du capot du module NSM indique l'emplacement des quatre modules DIMM, deux de chaque côté du dissipateur de chaleur, au centre du module NSM.

. Identifiez physiquement le module DIMM défectueux.
+
Lorsqu'un module DIMM est défectueux, le système consigne un message d'avertissement à la console du système indiquant quel module DIMM est défectueux.

. Remplacez le module DIMM défectueux :
+
.. Notez l'orientation du module DIMM dans le logement afin que vous puissiez insérer le module DIMM de remplacement dans la même orientation.
.. Éjectez le module DIMM de son logement en écartant lentement les languettes de l'éjecteur aux deux extrémités de l'emplacement DIMM, puis soulevez le module DIMM pour le sortir de son logement.
+

NOTE: Tenez soigneusement le module DIMM par les coins ou les bords pour éviter toute pression sur les composants de la carte de circuit DIMM.

+
Les languettes de l'éjecteur restent en position ouverte.

.. Retirez le module DIMM de remplacement de son sac d'expédition antistatique.
.. Tenez le DIMM par les coins, puis insérez-le à l'équerre dans un logement.
+
L'encoche située au bas du DIMM, entre les broches, doit être alignée avec la languette dans le logement.

+
Lorsqu'il est correctement inséré, le module DIMM doit être inséré facilement, mais bien inséré dans le logement. Si ce n'est pas le cas, réinsérez le module DIMM.

.. Poussez doucement, mais fermement, sur le bord supérieur du DIMM jusqu'à ce que les languettes de l'éjecteur s'enclenchent sur les encoches aux deux extrémités du DIMM.


. Fermez le couvercle du module NSM, puis serrez la vis à serrage à main.
. Réinsérez le module NSM dans le shelf :
+
.. S'assurer que les bras du mécanisme de verrouillage sont verrouillés en position complètement sortie.
.. A l'aide des deux mains, faites glisser doucement le module NSM dans l'étagère jusqu'à ce que le poids du module NSM soit entièrement supporté par l'étagère.
.. Poussez le module NSM dans la tablette jusqu'à ce qu'il s'arrête (environ un demi-pouce de l'arrière de l'étagère).
+
Vous pouvez placer vos pouces sur les languettes orange à l'avant de chaque boucle de doigt (des bras du mécanisme de verrouillage) pour enfoncer le module NSM.

.. Faites passer vos doigts dans les trous des doigts des mécanismes de verrouillage de chaque côté du module NSM.
+

NOTE: Si vous insérez le module NSM inférieur et que le rail inférieur empêche l'accès aux mécanismes de verrouillage, placez vos doigts dans les trous des doigts de l'intérieur (en croisant les bras).

.. À l'aide de vos pouces, appuyez sur les languettes orange et maintenez-les enfoncées au-dessus des mécanismes de verrouillage.
.. Poussez doucement vers l'avant pour placer les loquets au-dessus de la butée.
.. Libérez vos pouces des haut des mécanismes de verrouillage, puis continuez à pousser jusqu'à ce que les mécanismes de verrouillage s'enclenchent.
+
Le module NSM doit être complètement inséré dans la tablette et au ras des bords de la tablette.



. Reconnectez le câblage au module NSM :
+
.. Reconnectez le câblage de stockage aux deux mêmes ports de module NSM.
+
Les câbles sont insérés avec la languette de retrait du connecteur orientée vers le haut. Lorsqu'un câble est inséré correctement, il s'enclenche.

.. Rebranchez le cordon d'alimentation à l'alimentation, puis fixez le cordon d'alimentation à l'aide de la pièce de retenue du cordon d'alimentation.
+
Lorsqu'elle fonctionne correctement, la LED bicolore d'un bloc d'alimentation s'allume en vert.

+
De plus, les deux LED LNK (vertes) du port du module NSM s'allument. Si un voyant LNK ne s'allume pas, réinstallez le câble.



. Vérifiez que les voyants d'avertissement (orange) du module NSM contenant le module DIMM défectueux et le panneau d'affichage de l'opérateur de la tablette ne sont plus allumés.
+
Les voyants d'avertissement du module NSM s'éteignent après le redémarrage du module NSM et ne détectent plus un problème de module DIMM. Cela peut prendre trois à cinq minutes.

. Vérifiez que le module NSM est correctement câblé en exécutant Active IQ Config Advisor.
+
Si des erreurs de câblage sont générées, suivez les actions correctives fournies.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Téléchargement NetApp : Config Advisor"^]


