---
permalink: ns224/service-replace-boot-media.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, boot, media, run, ontap, nvme, module, nsm, firmware, version, nondisruptive, i/o 
summary: 'Lorsque le support de démarrage tombe en panne sur un tiroir de disque NS224 dans une paire haute disponibilité exécutant ONTAP 9.7 ou version ultérieure ou que le tiroir exécute le firmware du module de tiroir NVMe \(NSM\) version 1.1x ou ultérieure, vous pouvez remplacer le support de démarrage. Le remplacement du support de démarrage peut s"effectuer sans interruption, alors que le tiroir disque est sous tension et que les E/S sont en cours.' 
---
= Remplacez le support de démarrage - étagères NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque le support de démarrage tombe en panne sur un tiroir de disque NS224 dans une paire HA exécutant ONTAP 9.7 ou version ultérieure ou si le tiroir exécute la version 0111 ou ultérieure du firmware du module de tiroir NVMe (NSM), vous pouvez remplacer le support de démarrage. Le remplacement du support de démarrage peut s'effectuer sans interruption, alors que le tiroir disque est sous tension et que les E/S sont en cours.

.Avant de commencer
* Votre paire HA doit déjà exécuter ONTAP 9.7 ou une version ultérieure, qui dispose de la version minimale prise en charge du micrologiciel NSM, ou votre paire HA doit déjà exécuter une version de ONTAP 9.6 avec une version 0111 ou ultérieure du micrologiciel NSM.
+
Vous pouvez entrer le `storage shelf show -module` Contrôlez la version du firmware NSM sur votre tiroir au niveau de la console de l'un ou l'autre contrôleur.

+
[NOTE]
====
Si votre tiroir n'exécute pas la version 0111 ou ultérieure du micrologiciel NSM, vous ne pouvez pas remplacer le support d'amorçage, vous devez remplacer le module NSM.

link:service-replace-nsm100.html["Remplacez un module NSM - étagères NS224"^]

====
* Vous avez besoin d'un tournevis cruciforme n° 1.
+
La vis utilisée pour fixer le support de démarrage à la carte nécessite un tournevis cruciforme n° 1 ; l'utilisation d'un autre type de tournevis pourrait dénuder la vis.

* Le module NSM partenaire du tiroir doit être opérationnel et correctement câblé afin que votre tiroir conserve la connectivité lorsque vous retirez le module NSM avec le FRU défectueux (module NSM cible).
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Téléchargement NetApp : Config Advisor"^]

* Tous les autres composants du système doivent fonctionner correctement.


.Description de la tâche
* Une fois le support de démarrage remplacé, l'image de démarrage du module NSM partenaire du tiroir est automatiquement copiée sur le support de démarrage de remplacement.
+
Cette opération peut prendre jusqu'à cinq minutes.

* Laissez un délai d'au moins 70 secondes entre le retrait et l'installation du module de tiroir NVMe (NSM).
+
Cela laisse suffisamment de temps à ONTAP pour traiter l'événement de suppression NSM.

* Si nécessaire, vous pouvez allumer les LED situées à l'emplacement des tiroirs (bleues) pour faciliter l'emplacement physique des tiroirs concernés : `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Si vous ne connaissez pas le `_shelf_name_` sur la tablette concernée, exécutez la `storage shelf show` commande.

+
Une étagère comporte trois LED d'emplacement : une sur le panneau d'affichage de l'opérateur et une sur chaque module NSM. Les LED d'emplacement restent allumées pendant 30 minutes. Vous pouvez les désactiver en entrant la même commande, mais en utilisant le `off` option.

* Après le remplacement du support de démarrage, vous pouvez renvoyer la pièce défectueuse à NetApp, comme décrit dans les instructions RMA (retour de matériel) fournies avec le kit.
+
Si vous avez besoin du numéro d'autorisation de renvoi de matériel ou d'une aide supplémentaire pour effectuer la procédure de remplacement, contactez le support technique à l'adresse https://mysupport.netapp.com/site/global/dashboard["Support NetApp"^], 888-463-8277 (Amérique du Nord), 00-800-44-638277 (Europe) ou +800-800-80-800 (Asie/Pacifique).

* Vous pouvez utiliser l'animation suivante ou les étapes écrites pour remplacer le support de démarrage.
+
.Animation : remplacez le support de démarrage dans un tiroir de lecteur NS224
video::20ed85f9-1f80-4e0e-9219-ab4600070d8a[panopto]


.Étapes
. Assurez-vous que les deux modules NSM du tiroir exécutent la même version du micrologiciel : version 0200 ou ultérieure.
. Mettez-vous à la terre.
. Déconnectez le câblage du module NSM contenant le FRU que vous remplacez :
+
.. Déconnectez le cordon d'alimentation du bloc d'alimentation en ouvrant le dispositif de retenue du cordon d'alimentation s'il s'agit d'une alimentation CA, ou en dévissant les deux vis à serrage manuel s'il s'agit d'une alimentation CC, puis débranchez le cordon d'alimentation du bloc d'alimentation.
+
Les blocs d'alimentation n'ont pas de commutateur d'alimentation.

.. Déconnectez le câblage de stockage des ports du module NSM.
+
Notez les ports du module NSM auxquels chaque câble est connecté. Vous reconnectez les câbles aux mêmes ports lorsque vous réinsérez le module NSM, plus loin dans cette procédure.



. Retirez le module NSM du shelf :
+
.. Faites passer vos doigts dans les trous des doigts des mécanismes de verrouillage de chaque côté du module NSM.
+

NOTE: Si vous retirez le module NSM inférieur et que le rail inférieur empêche l'accès aux mécanismes de verrouillage, placez vos doigts dans les trous des doigts de l'intérieur (en croisant les bras).

.. À l'aide de vos pouces, appuyez sur les languettes orange et maintenez-les enfoncées au-dessus des mécanismes de verrouillage.
+
Les mécanismes de verrouillage se relèvent, en libérant les goupilles de verrouillage de la tablette.

.. Tirez doucement jusqu'à ce que le module NSM se trouve à environ un tiers de la sortie de la tablette, saisissez les côtés du module NSM avec les deux mains pour soutenir son poids, puis placez-le sur une surface plane et stable.
+
Lorsque vous commencez à tirer, les bras du mécanisme de verrouillage s'étendent du module NSM et se verrouillent en position complètement sortie.



. Desserrez la vis du couvercle du module NSM et ouvrez le couvercle.
. Localisez physiquement le support de démarrage défectueux.
+
Le support de démarrage est situé le long de la paroi du châssis de la tablette, à l'opposé du bloc d'alimentation.

. Remplacez le support de démarrage :
+
.. À l'aide du tournevis cruciforme n° 1, retirez avec précaution la vis fixant l'extrémité inférieure (à encoche) du support de démarrage à la carte.
.. Retirez le support de démarrage en tournant légèrement l'extrémité crantée vers le haut, puis en le tirant doucement vers vous jusqu'à ce qu'il se dégage du support.
+
Vous pouvez maintenir le support de chaussure en plaçant le pouce et l'index sur les bords latéraux, à l'extrémité crantée

.. Déballez le support de démarrage du sac antistatique.
.. Insérez le support de démarrage de remplacement en le poussant doucement dans la prise jusqu'à ce qu'il soit correctement inséré dans la prise.
+
Vous pouvez maintenir le support de chaussure en plaçant le pouce et l'index sur les bords latéraux, à l'extrémité crantée Assurez-vous que le côté avec le dissipateur de chaleur est orienté vers le haut.

+
Lorsqu'il est correctement positionné et que vous le laissez aller du support de démarrage, l'extrémité crantée du support de démarrage est inclinée vers le haut, à l'écart de la carte, car elle n'est pas encore fixée à l'aide de la vis.

.. Maintenez délicatement l'extrémité crantée du support de démarrage pendant que vous insérez et serrez la vis avec le tournevis pour fixer le support de démarrage en place.
+

NOTE: Serrez la vis juste assez pour maintenir le support de démarrage bien en place, mais ne serrez pas trop.



. Fermez le couvercle du module NSM, puis serrez la vis à serrage à main.
. Réinsérez le module NSM dans le shelf :
+
.. S'assurer que les bras du mécanisme de verrouillage sont verrouillés en position complètement sortie.
.. A l'aide des deux mains, faites glisser doucement le module NSM dans l'étagère jusqu'à ce que le poids du module NSM soit entièrement supporté par l'étagère.
.. Poussez le module NSM dans la tablette jusqu'à ce qu'il s'arrête (environ un demi-pouce de l'arrière de l'étagère).
+
Vous pouvez placer vos pouces sur les languettes orange à l'avant de chaque boucle de doigt (des bras du mécanisme de verrouillage) pour enfoncer le module NSM.

.. Faites passer vos doigts dans les trous des doigts des mécanismes de verrouillage de chaque côté du module NSM.
+

NOTE: Si vous insérez le module NSM inférieur et que le rail inférieur empêche l'accès aux mécanismes de verrouillage, placez vos doigts dans les trous des doigts de l'intérieur (en croisant les bras).

.. À l'aide de vos pouces, appuyez sur les languettes orange et maintenez-les enfoncées au-dessus des mécanismes de verrouillage.
.. Poussez doucement vers l'avant pour placer les loquets au-dessus de la butée.
.. Libérez vos pouces des haut des mécanismes de verrouillage, puis continuez à pousser jusqu'à ce que les mécanismes de verrouillage s'enclenchent.
+
Le module NSM doit être complètement inséré dans la tablette et au ras des bords de la tablette.



. Reconnectez le câblage au module NSM :
+
.. Reconnectez le câblage de stockage aux deux mêmes ports de module NSM.
+
Les câbles sont insérés avec la languette de retrait du connecteur orientée vers le haut. Lorsqu'un câble est inséré correctement, il s'enclenche.

.. Rebranchez le cordon d'alimentation sur le bloc d'alimentation, puis fixez-le à l'aide du dispositif de retenue du cordon d'alimentation s'il s'agit d'un bloc d'alimentation CA, ou serrez les deux vis à molette s'il s'agit d'un bloc d'alimentation CC.
+
Lorsqu'elle fonctionne correctement, la LED bicolore d'un bloc d'alimentation s'allume en vert.

+
De plus, les deux LED LNK (vertes) du port du module NSM s'allument. Si un voyant LNK ne s'allume pas, réinstallez le câble.



. Vérifiez que les voyants d'avertissement (orange) du module NSM contenant le support de démarrage défectueux et le panneau de commande de l'étagère ne sont plus allumés.
+
La mise hors tension des LED d'avertissement peut prendre entre 5 et 10 minutes. Il s'agit du temps nécessaire au redémarrage du module NSM et à la copie de l'image du support de démarrage.

+
Si les voyants de panne restent allumés, le support de démarrage peut ne pas être correctement installé ou un autre problème peut se présenter et vous devez contacter le support technique pour obtenir de l'aide.

. Vérifiez que le module NSM est correctement câblé en exécutant Active IQ Config Advisor.
+
Si des erreurs de câblage sont générées, suivez les actions correctives fournies.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Téléchargement NetApp : Config Advisor"^]


