---
permalink: ns224/service-replace-drive.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, fail, replace, drive, nondisruptive, i/o, hot-swap, hot-swap a drive 
summary: 'Vous pouvez remplacer un disque défectueux dans un tiroir disque NS224 sous tension, puis en cours d"E/S.' 
---
= Remplacement à chaud d'un disque - tiroirs NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez remplacer un disque défectueux dans un tiroir disque NS224 sous tension, puis en cours d'E/S.

.Avant de commencer
* Le lecteur que vous installez doit être pris en charge par le tiroir NS224.
+
https://["NetApp Hardware Universe"^]

* Si l'authentification SED est activée, vous devez utiliser les instructions de remplacement SED dans la documentation ONTAP.
+
Les instructions de la documentation ONTAP décrivent les étapes supplémentaires que vous devez effectuer avant et après le remplacement d'un SED.

+
https://["Présentation du chiffrement NetApp avec l'interface de ligne de commandes"^]

* Tous les autres composants du système doivent fonctionner correctement ; si ce n'est pas le cas, contactez le support technique.
* Vérifiez que le lecteur que vous retirez a échoué.
+
Vous pouvez vérifier que le lecteur est défectueux en exécutant le `storage disk show -broken` commande. Le lecteur défectueux apparaît dans la liste des disques défectueux. Si ce n'est pas le cas, attendez, puis exécutez de nouveau la commande.

+

NOTE: Selon le type et la capacité du disque, il peut prendre jusqu'à plusieurs heures pour que le lecteur apparaisse dans la liste des disques défaillants.



.Description de la tâche
* *Meilleure pratique :* la meilleure pratique consiste à installer la version actuelle du Disk qualification Package (DQP) avant le remplacement à chaud d'un disque.
+
Une fois la version actuelle du DQP installée, votre système peut reconnaître et utiliser de nouveaux lecteurs qualifiés. Cela permet d'éviter que les messages d'événement du système ne soient pas à jour sur les disques et évite le partitionnement de disque car les disques ne sont pas reconnus. Le DQP vous informe également de la non-mise à jour du firmware du disque.

+
https://["Téléchargements NetApp : pack de qualification des disques"^]

* *Meilleure pratique :* la meilleure pratique consiste à installer sur votre système les versions les plus récentes du firmware du module de tiroir NVMe (NSM) et du firmware du lecteur avant de remplacer les composants FRU.
+
https://["Téléchargements NetApp : firmware des tiroirs disques"^]

+
https://["Téléchargements NetApp : firmware de disque"^]

+
[NOTE]
====
Ne rétablissez pas le firmware en tant que version qui ne prend pas en charge votre tiroir et ses composants.

====
* Le firmware des disques est automatiquement mis à jour (sans interruption) sur les nouveaux disques dont les versions de micrologiciel ne sont pas à jour.
+

NOTE: Le firmware des disques est vérifié toutes les deux minutes.

* Si nécessaire, vous pouvez allumer les LED situées à l'emplacement des tiroirs (bleues) pour faciliter l'emplacement physique des tiroirs concernés : `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Si vous ne connaissez pas le `_shelf_name_` sur la tablette concernée, exécutez la `storage shelf show` commande.

+
Une étagère comporte trois LED d'emplacement : une sur le panneau d'affichage de l'opérateur et une sur chaque module NSM. Les LED d'emplacement restent allumées pendant 30 minutes. Vous pouvez les désactiver en entrant la même commande, mais en utilisant le `off` option.

* Lorsque vous déballez le lecteur de remplacement, conservez tous les matériaux d'emballage pour l'utiliser lorsque vous renvoyez le lecteur défectueux.
+
Si vous avez besoin du numéro d'autorisation de renvoi de matériel ou d'une aide supplémentaire pour effectuer la procédure de remplacement, contactez le support technique à l'adresse https://["Support NetApp"^], 888-463-8277 (Amérique du Nord), 00-800-44-638277 (Europe) ou +800-800-80-800 (Asie/Pacifique).

* L'animation suivante présente les parties de retrait et d'insertion physiques de la procédure de remplacement à chaud du disque.
+
.Animation - permutation à chaud d'un disque dans un tiroir de disque NS224
video::733011a7-e03a-41b0-8723-aa840133bf25[panopto]
+
.Étapes
.. Si vous souhaitez attribuer manuellement la propriété du disque de remplacement, vous devez désactiver l'affectation automatique des disques s'il est activé.
+

NOTE: Vous devez attribuer manuellement la propriété des disques si les disques du tiroir sont détenus par les deux modules de contrôleur dans la paire haute disponibilité.

+

NOTE: Vous attribuez manuellement la propriété des disques, puis réactivez l'affectation automatique des disques plus tard dans cette procédure.

+
... Vérifiez si l'affectation automatique des disques est activée : `storage disk option show`
+
Vous pouvez saisir la commande sur un ou deux modules de contrôleur.

+
Si l'affectation automatique de l'entraînement est activée, la sortie affiche `on` dans le `Auto Assign` colonne (pour chaque module de contrôleur).

... Si l'affectation automatique des disques est activée, désactivez-la : `storage disk option modify -node node_name -autoassign off`
+
Vous devez désactiver l'affectation automatique des disques sur les deux modules de contrôleur.



.. Mettez-vous à la terre.
.. Identifiez physiquement le disque défectueux.
+
Lorsqu'un disque tombe en panne, le système consigne un message d'avertissement à la console du système pour indiquer quel disque est en panne. En outre, la LED d'avertissement (orange) s'allume sur le panneau d'affichage de l'opérateur du tiroir disque et le disque défectueux.

+

NOTE: Le voyant d'activité (vert) d'un disque défectueux peut être allumé (en continu), ce qui indique que le lecteur est sous tension, mais ne doit pas clignoter, ce qui indique une activité d'E/S. Un disque défectueux n'a aucune activité d'E/S.

.. Retirez le disque défectueux :
+
... Appuyez sur le bouton de dégagement situé sur la face d'entraînement pour ouvrir la poignée de came.
... Faites glisser l'entraînement hors de la tablette à l'aide de la poignée de came et en soutenant l'entraînement avec l'autre main.


.. Attendre au moins 70 secondes avant d'insérer le lecteur de remplacement.
+
Ceci permet au système de reconnaître qu'un lecteur a été retiré.

.. Insérer le lecteur de remplacement :
+
... Avec la poignée de came en position ouverte, insérer l'entraînement de remplacement à l'aide des deux mains.
... Poussez jusqu'à ce que l'entraînement s'arrête.
... Fermez la poignée de came de façon à ce que le lecteur soit bien en place dans le plan médian et que la poignée s'enclenche.
+
Assurez-vous de fermer lentement la poignée de came de manière à ce qu'elle s'aligne correctement sur la face de l'entraînement.



.. Vérifiez que le voyant d'activité (vert) du lecteur est allumé.
+
Lorsque le voyant d'activité du lecteur est allumé, cela signifie que le lecteur est alimenté. Lorsque le voyant d'activité du lecteur clignote, cela signifie que le lecteur est alimenté et que les E/S sont en cours. Si le micrologiciel du lecteur est mis à jour automatiquement, le voyant clignote.

.. Si vous remplacez un autre lecteur, répétez les étapes 3 à 7.
.. Si vous avez désactivé l'affectation automatique de disques à l'étape 1, affectez manuellement la propriété des disques, puis réactivez l'affectation automatique de disques si nécessaire :
+
... Afficher tous les disques non propriétaires : `storage disk show -container-type unassigned`
+
Vous pouvez saisir la commande sur un ou deux modules de contrôleur.

... Affectez chaque disque : `storage disk assign -disk disk_name -owner owner_name`
+
Vous pouvez saisir la commande sur un ou deux modules de contrôleur.

+
Vous pouvez utiliser le caractère générique pour attribuer plusieurs lecteurs à la fois.

... Réactivez l'affectation automatique des disques si nécessaire : `storage disk option modify -node node_name -autoassign on`
+
Vous devez réactiver l'affectation automatique des disques sur les deux modules de contrôleur.






