---
permalink: a700s/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a700s, aff, a700s, primary, boot, media, store, ontap, image, system, restore, primary, media, secondary, usb, flash, drive, replace, replace the boot media, manual, manual boot recovery 
summary: 'Découvrez comment remplacer le support de démarrage sur un système AFF A700s et comprenez les méthodes de récupération. Le système AFF A700s ne prend en charge que les procédures de récupération manuelles du support de démarrage. La récupération automatique du support de démarrage n"est pas prise en charge.' 
---
= Présentation du remplacement du support de démarrage - AFF A700s
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez comment remplacer le support de démarrage sur un système AFF A700s et comprenez les méthodes de récupération. Le support de démarrage principal stocke l'image de démarrage ONTAP que le système utilise au démarrage. Vous pouvez restaurer l'image du support de démarrage principal à l'aide de l'image ONTAP provenant du support de démarrage secondaire ou, si nécessaire, d'une clé USB formatée en FAT32.

Le système AFF A700s ne prend en charge que les procédures de récupération manuelles du support de démarrage. La récupération automatique du support de démarrage n'est pas prise en charge.

Si le support d'amorçage secondaire a échoué ou s'il n'a pas le fichier image.tgz, vous devez restaurer le support d'amorçage principal à l'aide d'un lecteur flash USB. Le lecteur doit être formaté en FAT32 et avoir la quantité de stockage appropriée pour contenir le fichier image_xxx.tgz.

* Le processus de remplacement restaure le système de fichiers var du support de démarrage secondaire ou du lecteur flash USB vers le support de démarrage principal.
* Vous devez remplacer le composant défectueux par un composant FRU de remplacement que vous avez reçu de votre fournisseur.
* Il est important d'appliquer les commandes au cours de la procédure suivante sur le contrôleur approprié :
+
** Le contrôleur _trouble_ est le contrôleur sur lequel vous effectuez la maintenance.
** Le contrôleur _Healthy_ est le partenaire HA du contrôleur déficient.




Si vous devez remplacer le support de démarrage secondaire alors que le support de démarrage principal est installé et en bon état, contactez le support NetApp et mentionnez l'article de la https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_replace_the_secondary_boot_device_of_an_a700s["Comment remplacer le périphérique de démarrage secondaire d'un système AFF A700s"^] base de connaissances.
