---
permalink: a700s/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a700s, replace the chassis 
summary: Vous remplacez un châssis endommagé le nouveau châssis du même modèle que le châssis endommagé. 
---
= Présentation du remplacement de châssis - AFF A700s
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour remplacer le châssis, vous devez déplacer les modules de contrôleur et les disques SSD du châssis endommagé vers le châssis de remplacement, puis retirer le châssis endommagé du rack ou de l'armoire système et installer le châssis de remplacement à sa place.

Tous les autres composants du système doivent fonctionner correctement ; si ce n'est pas le cas, vous devez contacter le support technique.

* Cette procédure peut être utilisée avec toutes les versions de ONTAP prises en charge par votre système.
* Cette procédure est écrite en supposant que vous déplaiez les SSD et les modules de contrôleurs vers le nouveau châssis, et que le châssis de remplacement est un nouveau composant de NetApp.
* Cette procédure est perturbatrice. Dans le cas d'un cluster à deux nœuds, la panne totale du service et une panne partielle dans un cluster multinœud sont associés.

