---
permalink: asa-r2/asa-r2-install-setup.html 
sidebar: sidebar 
keywords: asa r2 a1k, a70, a90, install, setup, initial configuration 
summary: Installez et configurez votre système. 
---
= Installez et configurez vos systèmes ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Consultez le https://docs.netapp.com/us-en/asa-r2/index.html["Documentation des systèmes ASA r2"^] pour savoir comment installer, utiliser et gérer votre système ASA r2.

Le https://docs.netapp.com/us-en/asa-r2/index.html["Documentation des systèmes ASA r2"^] comprend des informations telles que :

* Instructions d'installation et de configuration
* Instructions d'administration pour la configuration de votre système, telles que le provisionnement du stockage SAN, le clonage de données et le redimensionnement du stockage local.
* Instructions pour la gestion de votre système, y compris la gestion de l'accès client, la sécurisation de vos données et la protection de vos données.
* Des instructions de surveillance et de dépannage, y compris des informations sur les alertes, les événements de cluster et les journaux du système.


Les procédures de maintenance spécifiques pour chaque type de système ASA r2 se trouvent dans le link:../asa-r2-landing-maintain/index.html["Section sur la maintenance des systèmes ASA r2"].
